/**
 * data_days_146_150.js - Day 146~150 단어 데이터
 * data_days_141_145.js 이후에 로드해야 합니다
 */
Object.assign(VOCA_DATA, {
  146: {
    theme: "공학·제조 어휘",
    words: [
      { word: "prototype", pron: "/ˈprəʊtətaɪp/", pos: "n.", meanings: ["프로토타입", "시제품"], example: "Engineers built a prototype to test the design's structural integrity before committing to mass production.", exampleKr: "엔지니어들은 대량 생산에 착수하기 전에 설계의 구조적 무결성을 테스트하기 위해 프로토타입을 제작했다." },
      { word: "tensile strength", pron: "/ˈtensaɪl streŋθ/", pos: "n.", meanings: ["인장 강도", "항장력"], example: "Carbon fibre composites have an exceptional tensile strength-to-weight ratio compared with traditional steel.", exampleKr: "탄소 섬유 복합재는 전통적인 강철에 비해 탁월한 인장 강도 대 중량 비율을 가진다." },
      { word: "tolerance", pron: "/ˈtɒlərəns/", pos: "n.", meanings: ["공차", "허용 오차"], example: "Precision engineering requires components to be machined within extremely tight dimensional tolerances.", exampleKr: "정밀 공학은 부품이 극히 좁은 치수 공차 범위 내에서 가공될 것을 요구한다." },
      { word: "injection moulding", pron: "/ɪnˈdʒekʃən ˈməʊldɪŋ/", pos: "n.", meanings: ["사출 성형"], example: "Injection moulding is used to manufacture millions of identical plastic parts quickly and cost-effectively.", exampleKr: "사출 성형은 수백만 개의 동일한 플라스틱 부품을 빠르고 비용 효율적으로 제조하는 데 사용된다." },
      { word: "CAD", pron: "/kæd/", pos: "n.", meanings: ["컴퓨터 지원 설계", "CAD"], example: "CAD software enables engineers to design, simulate, and modify complex three-dimensional structures digitally.", exampleKr: "CAD 소프트웨어는 엔지니어가 복잡한 3차원 구조를 디지털로 설계, 시뮬레이션, 수정할 수 있게 한다." },
      { word: "yield strength", pron: "/jiːld streŋθ/", pos: "n.", meanings: ["항복 강도", "내력"], example: "A material's yield strength determines the maximum stress it can endure without permanent deformation.", exampleKr: "재료의 항복 강도는 영구적인 변형 없이 견딜 수 있는 최대 응력을 결정한다." },
      { word: "thermal conductivity", pron: "/ˈθɜːrməl ˌkɒndʌkˈtɪvɪti/", pos: "n.", meanings: ["열전도율"], example: "Metals with high thermal conductivity are used in heat exchangers to efficiently transfer heat away from components.", exampleKr: "열전도율이 높은 금속은 부품에서 열을 효율적으로 전달하기 위해 열교환기에 사용된다." },
      { word: "composite material", pron: "/ˈkɒmpəzɪt məˈtɪəriəl/", pos: "n.", meanings: ["복합 재료"], example: "Composite materials like fibreglass combine two substances to achieve properties superior to either alone.", exampleKr: "유리 섬유와 같은 복합 재료는 두 물질을 결합하여 각각 단독으로는 달성할 수 없는 우수한 특성을 얻는다." },
      { word: "lean manufacturing", pron: "/liːn ˌmænjʊˈfæktʃərɪŋ/", pos: "n.", meanings: ["린 제조", "린 생산"], example: "Lean manufacturing eliminates waste at every stage of production by focusing on continuous process improvement.", exampleKr: "린 제조는 지속적인 프로세스 개선에 집중함으로써 생산의 모든 단계에서 낭비를 제거한다." },
      { word: "Six Sigma", pron: "/sɪks ˈsɪɡmə/", pos: "n.", meanings: ["6시그마", "품질 관리 방법론"], example: "The factory implemented Six Sigma methodology to reduce defective products to fewer than 3.4 per million.", exampleKr: "공장은 불량품을 백만 개당 3.4개 미만으로 줄이기 위해 6시그마 방법론을 도입했다." },
      { word: "quality control", pron: "/ˈkwɒlɪti kənˈtrəʊl/", pos: "n.", meanings: ["품질 관리", "품질 통제"], example: "Rigorous quality control procedures ensure that finished products meet all specified safety and performance standards.", exampleKr: "엄격한 품질 관리 절차는 완성된 제품이 지정된 모든 안전 및 성능 기준을 충족하도록 보장한다." },
      { word: "automation", pron: "/ˌɔːtəˈmeɪʃən/", pos: "n.", meanings: ["자동화"], example: "Factory automation using robotic arms has dramatically increased production speed while reducing labour costs.", exampleKr: "로봇 팔을 사용한 공장 자동화는 노동 비용을 줄이면서 생산 속도를 크게 증가시켰다." },
      { word: "torque", pron: "/tɔːrk/", pos: "n.", meanings: ["토크", "회전력"], example: "The engine produces maximum torque at low revolutions, providing strong acceleration from a standstill.", exampleKr: "엔진은 낮은 회전수에서 최대 토크를 발생시켜 정차 상태에서 강한 가속을 제공한다." },
      { word: "calibration", pron: "/ˌkælɪˈbreɪʃən/", pos: "n.", meanings: ["교정", "검정"], example: "Regular calibration of measurement instruments ensures that all readings remain accurate and reliable over time.", exampleKr: "측정 기기의 정기적인 교정은 모든 측정값이 시간이 지나도 정확하고 신뢰할 수 있도록 보장한다." },
      { word: "fatigue", pron: "/fəˈtiːɡ/", pos: "n.", meanings: ["피로 파괴", "재료 피로"], example: "Metal fatigue caused by repeated stress cycles can lead to catastrophic structural failure without visible warning.", exampleKr: "반복된 응력 사이클에 의한 금속 피로는 눈에 보이는 경고 없이 치명적인 구조 파괴로 이어질 수 있다." },
      { word: "supply chain", pron: "/səˈplaɪ tʃeɪn/", pos: "n.", meanings: ["공급망", "공급 사슬"], example: "Disruptions to the global supply chain exposed how dependent manufacturers are on just-in-time delivery.", exampleKr: "글로벌 공급망 혼란은 제조업체들이 적시 납품에 얼마나 의존하는지를 드러냈다." },
      { word: "batch production", pron: "/bætʃ prəˈdʌkʃən/", pos: "n.", meanings: ["배치 생산", "뱃치 생산"], example: "Batch production allows manufacturers to switch between different products without major reconfiguration of equipment.", exampleKr: "배치 생산은 제조업체가 장비의 주요 재구성 없이 다른 제품 간에 전환할 수 있게 한다." },
      { word: "modular design", pron: "/ˈmɒdjʊlər dɪˈzaɪn/", pos: "n.", meanings: ["모듈식 설계", "모듈 디자인"], example: "Modular design allows components to be replaced or upgraded individually without replacing the entire system.", exampleKr: "모듈식 설계는 전체 시스템을 교체하지 않고도 구성 요소를 개별적으로 교체하거나 업그레이드할 수 있게 한다." },
      { word: "stress test", pron: "/stres test/", pos: "n.", meanings: ["응력 시험", "내구성 테스트"], example: "Bridges undergo extensive stress tests to verify they can safely bear loads far exceeding normal traffic conditions.", exampleKr: "교량은 정상적인 교통 조건을 훨씬 초과하는 하중을 안전하게 견딜 수 있는지 검증하기 위해 광범위한 응력 시험을 받는다." },
      { word: "machining", pron: "/məˈʃiːnɪŋ/", pos: "n.", meanings: ["기계 가공", "절삭 가공"], example: "CNC machining removes excess material from metal blocks to create precise components for aerospace applications.", exampleKr: "CNC 기계 가공은 항공우주 용도의 정밀 부품을 만들기 위해 금속 블록에서 과잉 재료를 제거한다." }
    ]
  },
  147: {
    theme: "글로벌 이슈 어휘",
    words: [
      { word: "multilateralism", pron: "/ˌmʌltiˈlætərəlɪzəm/", pos: "n.", meanings: ["다자주의", "다자간 협력"], example: "Multilateralism involves cooperation among many nations to address challenges that no single country can solve alone.", exampleKr: "다자주의는 어떤 단일 국가도 혼자서는 해결할 수 없는 문제를 해결하기 위해 여러 나라 간의 협력을 포함한다." },
      { word: "sovereignty", pron: "/ˈsɒvrənti/", pos: "n.", meanings: ["주권", "자주권"], example: "The principle of sovereignty holds that each state has the right to govern itself without external interference.", exampleKr: "주권 원칙은 각 국가가 외부 간섭 없이 스스로를 통치할 권리가 있다고 규정한다." },
      { word: "diaspora", pron: "/daɪˈæspərə/", pos: "n.", meanings: ["디아스포라", "해외 이산 공동체"], example: "The Indian diaspora spans over 170 countries and sends substantial remittances back to support families at home.", exampleKr: "인도의 디아스포라는 170개 이상의 국가에 걸쳐 있으며 고국의 가족을 부양하기 위해 상당한 송금을 보낸다." },
      { word: "geopolitics", pron: "/ˌdʒiːəʊˈpɒlɪtɪks/", pos: "n.", meanings: ["지정학"], example: "Geopolitics examines how geography, resources, and strategic location influence a nation's power and foreign policy.", exampleKr: "지정학은 지리, 자원, 전략적 위치가 국가의 힘과 외교 정책에 어떻게 영향을 미치는지 연구한다." },
      { word: "human trafficking", pron: "/ˈhjuːmən ˈtræfɪkɪŋ/", pos: "n.", meanings: ["인신매매"], example: "Human trafficking is one of the most serious global crimes, exploiting millions of victims for forced labour.", exampleKr: "인신매매는 강제 노동을 위해 수백만 명의 피해자를 착취하는 가장 심각한 글로벌 범죄 중 하나이다." },
      { word: "food insecurity", pron: "/fuːd ɪnˈsɪkjʊrɪti/", pos: "n.", meanings: ["식량 불안정", "식량 부족"], example: "Climate change is worsening food insecurity in sub-Saharan Africa as extreme weather threatens harvests.", exampleKr: "기후 변화는 극단적인 날씨가 수확을 위협함에 따라 사하라 이남 아프리카의 식량 불안정을 악화시키고 있다." },
      { word: "pandemic", pron: "/pænˈdemɪk/", pos: "n.", meanings: ["팬데믹", "세계적 유행병"], example: "The COVID-19 pandemic demonstrated how quickly an infectious disease can spread across interconnected global networks.", exampleKr: "COVID-19 팬데믹은 전염병이 상호 연결된 글로벌 네트워크를 통해 얼마나 빠르게 확산할 수 있는지 보여주었다." },
      { word: "remittance", pron: "/rɪˈmɪtəns/", pos: "n.", meanings: ["송금", "이민자 본국 송금"], example: "Remittances sent by migrant workers represent a major source of income for many developing countries.", exampleKr: "이민 노동자들이 보내는 송금은 많은 개발도상국에 주요한 수입원을 나타낸다." },
      { word: "stateless", pron: "/ˈsteɪtlɪs/", pos: "adj.", meanings: ["무국적의", "국가 없는"], example: "Stateless individuals lack legal protection and face barriers in accessing education, healthcare, and employment.", exampleKr: "무국적자들은 법적 보호를 받지 못하며 교육, 의료, 고용 접근에 장벽을 직면한다." },
      { word: "peacekeeping", pron: "/ˈpiːskiːpɪŋ/", pos: "n.", meanings: ["평화유지", "평화 유지 활동"], example: "UN peacekeeping missions deploy troops to conflict zones to monitor ceasefires and protect civilian populations.", exampleKr: "유엔 평화유지 임무는 휴전을 감시하고 민간인을 보호하기 위해 분쟁 지역에 군대를 파견한다." },
      { word: "sanctions", pron: "/ˈsæŋkʃənz/", pos: "n.", meanings: ["제재", "국제 제재"], example: "Economic sanctions were imposed on the country to pressure it into complying with international law.", exampleKr: "국제법 준수를 압박하기 위해 그 나라에 경제 제재가 부과되었다." },
      { word: "digital divide", pron: "/ˈdɪdʒɪtəl dɪˈvaɪd/", pos: "n.", meanings: ["디지털 격차"], example: "The digital divide between wealthy and poor nations widens as technology becomes ever more central to economic opportunity.", exampleKr: "기술이 경제적 기회의 핵심이 됨에 따라 부유한 나라와 가난한 나라 사이의 디지털 격차가 벌어지고 있다." },
      { word: "climate justice", pron: "/ˈklaɪmɪt ˈdʒʌstɪs/", pos: "n.", meanings: ["기후 정의"], example: "Climate justice demands that nations most responsible for emissions bear the greatest burden of addressing climate change.", exampleKr: "기후 정의는 배출에 가장 책임이 있는 국가들이 기후 변화 대응의 가장 큰 부담을 져야 한다고 요구한다." },
      { word: "urbanisation", pron: "/ˌɜːrbənaɪˈzeɪʃən/", pos: "n.", meanings: ["도시화"], example: "Rapid urbanisation in Asia has created megacities where infrastructure struggles to keep pace with population growth.", exampleKr: "아시아의 급속한 도시화는 인프라가 인구 증가를 따라가기 힘든 거대도시를 만들어냈다." },
      { word: "demographic dividend", pron: "/ˌdeməˈɡræfɪk ˈdɪvɪdend/", pos: "n.", meanings: ["인구 배당효과"], example: "Countries with a large young workforce can enjoy a demographic dividend if they invest adequately in education.", exampleKr: "젊은 노동력이 많은 나라들은 교육에 충분히 투자하면 인구 배당효과를 누릴 수 있다." },
      { word: "child labour", pron: "/tʃaɪld ˈleɪbər/", pos: "n.", meanings: ["아동 노동"], example: "International organisations work to eliminate child labour by promoting access to education and improving family incomes.", exampleKr: "국제 기구들은 교육 접근을 촉진하고 가족 소득을 향상시킴으로써 아동 노동을 근절하기 위해 노력한다." },
      { word: "refugee crisis", pron: "/ˈrefjʊdʒiː ˈkraɪsɪs/", pos: "n.", meanings: ["난민 위기"], example: "The ongoing refugee crisis has tested the capacity and political will of receiving nations to offer asylum.", exampleKr: "지속되는 난민 위기는 망명을 제공하려는 수용 국가들의 역량과 정치적 의지를 시험해왔다." },
      { word: "aid dependency", pron: "/eɪd dɪˈpendənsi/", pos: "n.", meanings: ["원조 의존성"], example: "Critics argue that long-term aid dependency can undermine local industries and institutions in developing nations.", exampleKr: "비평가들은 장기적인 원조 의존성이 개발도상국의 지역 산업과 기관을 약화시킬 수 있다고 주장한다." },
      { word: "tariff", pron: "/ˈtærɪf/", pos: "n.", meanings: ["관세", "세율"], example: "High tariffs on imported steel were imposed to protect domestic manufacturers from cheaper foreign competition.", exampleKr: "더 저렴한 외국 경쟁으로부터 국내 제조업체를 보호하기 위해 수입 철강에 높은 관세가 부과되었다." },
      { word: "illiteracy", pron: "/ɪˈlɪtərəsi/", pos: "n.", meanings: ["문맹", "비식자율"], example: "Illiteracy perpetuates poverty by limiting people's ability to access information, employment, and civic participation.", exampleKr: "문맹은 정보, 고용, 시민 참여에 접근하는 사람들의 능력을 제한함으로써 빈곤을 영속시킨다." }
    ]
  },
  148: {
    theme: "인류학·고고학 어휘",
    words: [
      { word: "ethnography", pron: "/eθˈnɒɡrəfi/", pos: "n.", meanings: ["민족지학", "문화 기술지"], example: "The anthropologist spent two years conducting ethnography, living within the community she was studying.", exampleKr: "그 인류학자는 자신이 연구하는 공동체 안에서 생활하며 2년간 민족지학 조사를 수행했다." },
      { word: "kinship", pron: "/ˈkɪnʃɪp/", pos: "n.", meanings: ["혈연 관계", "친족"], example: "Kinship systems define social relationships and obligations between individuals based on descent and marriage.", exampleKr: "친족 제도는 혈통과 결혼을 기반으로 개인 간의 사회적 관계와 의무를 정의한다." },
      { word: "ritual", pron: "/ˈrɪtʃʊəl/", pos: "n./adj.", meanings: ["의식", "의례적인"], example: "Coming-of-age rituals in many cultures mark the transition from childhood to adult responsibilities and privileges.", exampleKr: "많은 문화에서 성인식은 어린 시절에서 성인의 책임과 특권으로의 전환을 표시한다." },
      { word: "artefact", pron: "/ˈɑːrtɪfækt/", pos: "n.", meanings: ["유물", "인공 유물"], example: "The artefacts recovered from the burial site provided insight into the daily life of the ancient civilisation.", exampleKr: "매장지에서 발굴된 유물들은 고대 문명의 일상생활에 대한 통찰을 제공했다." },
      { word: "excavation", pron: "/ˌekskəˈveɪʃən/", pos: "n.", meanings: ["발굴", "발굴 조사"], example: "The excavation of Pompeii revealed a city frozen in time by the volcanic eruption of Mount Vesuvius.", exampleKr: "폼페이 발굴은 베수비오 화산 폭발로 시간이 멈춘 도시를 드러냈다." },
      { word: "stratigraphy", pron: "/strəˈtɪɡrəfi/", pos: "n.", meanings: ["층위학", "지층학"], example: "Archaeologists use stratigraphy to date finds by analysing the order of the soil layers in which they occur.", exampleKr: "고고학자들은 발견물이 있는 토양층의 순서를 분석하여 유물의 연대를 측정하기 위해 층위학을 사용한다." },
      { word: "carbon dating", pron: "/ˈkɑːrbən ˈdeɪtɪŋ/", pos: "n.", meanings: ["방사성 탄소 연대 측정"], example: "Carbon dating of the bone fragments placed the human remains at approximately twelve thousand years old.", exampleKr: "뼈 파편의 방사성 탄소 연대 측정은 인간 유해를 약 1만 2천 년 전으로 추정했다." },
      { word: "oral tradition", pron: "/ˈɔːrəl trəˈdɪʃən/", pos: "n.", meanings: ["구전 전통", "구전 문화"], example: "Many indigenous communities preserve their history and cultural values through oral traditions passed down across generations.", exampleKr: "많은 원주민 공동체는 세대를 거쳐 전해지는 구전 전통을 통해 역사와 문화적 가치를 보존한다." },
      { word: "totem", pron: "/ˈtəʊtəm/", pos: "n.", meanings: ["토템", "부족 상징"], example: "A totem is a natural object or animal that serves as a symbol of a clan or family within indigenous societies.", exampleKr: "토템은 원주민 사회에서 씨족이나 가족의 상징으로 기능하는 자연물이나 동물이다." },
      { word: "taboo", pron: "/təˈbuː/", pos: "n./adj.", meanings: ["금기", "터부"], example: "Certain foods are taboo in many cultures due to religious, spiritual, or deeply rooted historical beliefs.", exampleKr: "특정 음식은 종교적, 영적 또는 깊이 뿌리박힌 역사적 믿음 때문에 많은 문화에서 금기시된다." },
      { word: "cultural diffusion", pron: "/ˈkʌltʃərəl dɪˈfjuːʒən/", pos: "n.", meanings: ["문화 전파", "문화 확산"], example: "The Silk Road facilitated cultural diffusion between East and West through the exchange of goods and ideas.", exampleKr: "실크로드는 상품과 아이디어의 교환을 통해 동서 간의 문화 전파를 촉진했다." },
      { word: "acculturation", pron: "/əˌkʌltʃəˈreɪʃən/", pos: "n.", meanings: ["문화 변용", "문화 동화"], example: "Acculturation occurs when a group adopts elements of another culture after prolonged contact with it.", exampleKr: "문화 변용은 집단이 다른 문화와 오랜 접촉 후 그 요소를 채택할 때 발생한다." },
      { word: "hominid", pron: "/ˈhɒmɪnɪd/", pos: "n.", meanings: ["호미니드", "사람과 동물"], example: "The discovery of ancient hominid fossils in East Africa transformed our understanding of human evolutionary history.", exampleKr: "동아프리카에서 고대 호미니드 화석의 발견은 인간 진화 역사에 대한 우리의 이해를 변화시켰다." },
      { word: "cultural relativism", pron: "/ˈkʌltʃərəl ˈrelətɪvɪzəm/", pos: "n.", meanings: ["문화 상대주의"], example: "Cultural relativism holds that practices should be understood within the context of their own culture, not judged by another's standards.", exampleKr: "문화 상대주의는 관행이 다른 문화의 기준으로 판단되는 것이 아니라 자신의 문화 맥락 안에서 이해되어야 한다고 주장한다." },
      { word: "endogamy", pron: "/enˈdɒɡəmi/", pos: "n.", meanings: ["내혼", "집단 내 결혼"], example: "Endogamy, the practice of marrying within one's social group, serves to maintain cultural identity and concentrate wealth.", exampleKr: "자신의 사회 집단 내에서 결혼하는 관행인 내혼은 문화적 정체성을 유지하고 부를 집중시키는 기능을 한다." },
      { word: "shamanism", pron: "/ˈʃeɪmənɪzəm/", pos: "n.", meanings: ["샤머니즘", "무속 신앙"], example: "Shamanism involves spiritual practitioners who enter altered states to communicate with spirits on behalf of their community.", exampleKr: "샤머니즘은 공동체를 대신하여 영과 소통하기 위해 변성 의식 상태에 들어가는 영적 실천자를 포함한다." },
      { word: "prehistoric", pron: "/ˌpriːhɪˈstɒrɪk/", pos: "adj.", meanings: ["선사 시대의"], example: "Prehistoric cave paintings in Lascaux, France, date back more than seventeen thousand years.", exampleKr: "프랑스 라스코의 선사 시대 동굴 벽화는 1만 7천 년 이상 전으로 거슬러 올라간다." },
      { word: "lithic", pron: "/ˈlɪθɪk/", pos: "adj.", meanings: ["석기의", "돌의"], example: "Lithic analysis examines ancient tools made of stone to understand the technology of early human societies.", exampleKr: "석기 분석은 초기 인간 사회의 기술을 이해하기 위해 돌로 만든 고대 도구를 조사한다." },
      { word: "burial site", pron: "/ˈberiəl saɪt/", pos: "n.", meanings: ["매장지", "고분"], example: "The discovery of a Neolithic burial site containing grave goods revealed complex beliefs about life after death.", exampleKr: "부장품이 들어있는 신석기 시대 매장지의 발견은 사후 세계에 대한 복잡한 믿음을 드러냈다." },
      { word: "anthropomorphism", pron: "/ˌænθrəpəˈmɔːfɪzəm/", pos: "n.", meanings: ["의인화", "인간화"], example: "Anthropomorphism attributes human characteristics to animals or deities, common in ancient mythology and religion.", exampleKr: "의인화는 동물이나 신에게 인간의 특성을 부여하는 것으로, 고대 신화와 종교에서 흔하다." }
    ]
  },
  149: {
    theme: "수사·범죄학 어휘",
    words: [
      { word: "forensic", pron: "/fəˈrensɪk/", pos: "adj.", meanings: ["법과학의", "법의학의"], example: "Forensic evidence collected at the crime scene, including DNA samples, proved decisive in securing the conviction.", exampleKr: "DNA 샘플을 포함한 범죄 현장에서 수집된 법과학적 증거는 유죄 판결을 확보하는 데 결정적이었다." },
      { word: "alibi", pron: "/ˈælɪbaɪ/", pos: "n.", meanings: ["알리바이", "부재 증명"], example: "The suspect provided a solid alibi, confirmed by security footage showing him elsewhere during the crime.", exampleKr: "용의자는 범행 당시 다른 곳에 있었음을 보여주는 보안 영상으로 확인된 확실한 알리바이를 제시했다." },
      { word: "perpetrator", pron: "/ˈpɜːrpɪtreɪtər/", pos: "n.", meanings: ["범인", "가해자"], example: "Investigators worked for months to identify the perpetrator before making a breakthrough based on digital evidence.", exampleKr: "수사관들은 디지털 증거를 바탕으로 돌파구를 찾기 전까지 몇 달 동안 범인을 식별하기 위해 노력했다." },
      { word: "recidivism", pron: "/rɪˈsɪdɪvɪzəm/", pos: "n.", meanings: ["재범", "상습 범행"], example: "High recidivism rates suggest that prison alone is ineffective at rehabilitating offenders and preventing reoffending.", exampleKr: "높은 재범률은 감옥만으로는 범죄자를 재활하고 재범을 방지하는 데 효과적이지 않다는 것을 시사한다." },
      { word: "deterrence", pron: "/dɪˈterəns/", pos: "n.", meanings: ["억지력", "범죄 억제"], example: "Severe penalties are intended to serve as a deterrence, discouraging others from committing similar offences.", exampleKr: "엄중한 처벌은 다른 사람들이 유사한 범죄를 저지르는 것을 막기 위한 억지력으로 작용하도록 의도된다." },
      { word: "subpoena", pron: "/səˈpiːnə/", pos: "n./v.", meanings: ["소환장", "소환하다"], example: "The court issued a subpoena requiring the executive to testify and hand over all relevant financial documents.", exampleKr: "법원은 임원이 증언하고 모든 관련 재무 서류를 제출하도록 요구하는 소환장을 발부했다." },
      { word: "interrogation", pron: "/ɪnˌterəˈɡeɪʃən/", pos: "n.", meanings: ["심문", "조사"], example: "Detectives use structured interrogation techniques to gather information while ensuring suspects' legal rights are respected.", exampleKr: "형사들은 용의자의 법적 권리가 존중되도록 하면서 정보를 수집하기 위해 구조화된 심문 기법을 사용한다." },
      { word: "chain of custody", pron: "/tʃeɪn əv ˈkʌstədi/", pos: "n.", meanings: ["증거 보관 절차", "증거 연속성"], example: "Any break in the chain of custody of evidence can render it inadmissible in court proceedings.", exampleKr: "증거 보관 절차의 어떤 단절도 법원 절차에서 증거를 채택 불가능하게 만들 수 있다." },
      { word: "forensic psychology", pron: "/fəˈrensɪk saɪˈkɒlədʒi/", pos: "n.", meanings: ["법정 심리학", "범죄 심리학"], example: "Forensic psychology applies psychological principles to legal contexts including criminal profiling and competency evaluations.", exampleKr: "법정 심리학은 범죄자 프로파일링과 역량 평가를 포함한 법적 맥락에 심리학적 원리를 적용한다." },
      { word: "white-collar crime", pron: "/waɪt ˈkɒlər kraɪm/", pos: "n.", meanings: ["화이트칼라 범죄", "사무직 범죄"], example: "White-collar crimes such as fraud and embezzlement cause enormous financial losses to businesses and individuals.", exampleKr: "사기와 횡령 같은 화이트칼라 범죄는 기업과 개인에게 엄청난 재정적 손실을 야기한다." },
      { word: "victimology", pron: "/ˌvɪktɪˈmɒlədʒi/", pos: "n.", meanings: ["피해자학"], example: "Victimology studies the relationship between offenders and their victims to better understand patterns of crime.", exampleKr: "피해자학은 범죄 패턴을 더 잘 이해하기 위해 범죄자와 피해자 사이의 관계를 연구한다." },
      { word: "plea bargain", pron: "/pliː ˈbɑːrɡɪn/", pos: "n.", meanings: ["사전 형량 합의", "플리 바겐"], example: "The defendant accepted a plea bargain, pleading guilty to a lesser charge to avoid a lengthy trial.", exampleKr: "피고는 긴 재판을 피하기 위해 더 가벼운 혐의에 유죄를 인정하는 사전 형량 합의를 받아들였다." },
      { word: "surveillance", pron: "/sɜːˈveɪləns/", pos: "n.", meanings: ["감시", "사찰"], example: "Closed-circuit television surveillance has become ubiquitous in modern cities, recording public spaces around the clock.", exampleKr: "폐쇄회로 텔레비전 감시는 현대 도시에서 어디서나 볼 수 있게 되어 공공장소를 24시간 기록한다." },
      { word: "cybercrime", pron: "/ˈsaɪbəkraɪm/", pos: "n.", meanings: ["사이버 범죄"], example: "Cybercrime costs the global economy hundreds of billions of dollars annually through ransomware and data breaches.", exampleKr: "사이버 범죄는 랜섬웨어와 데이터 유출을 통해 매년 전 세계 경제에 수천억 달러의 비용을 야기한다." },
      { word: "homicide", pron: "/ˈhɒmɪsaɪd/", pos: "n.", meanings: ["살인", "살인 사건"], example: "The homicide rate in the city declined sharply following targeted law enforcement interventions in high-risk areas.", exampleKr: "위험 지역에 대한 표적 법 집행 개입 이후 그 도시의 살인율이 급격히 감소했다." },
      { word: "eyewitness", pron: "/ˈaɪwɪtnɪs/", pos: "n.", meanings: ["목격자"], example: "Eyewitness testimony, though compelling to juries, is often unreliable due to the fallibility of human memory.", exampleKr: "목격자 증언은 배심원들에게 설득력 있지만, 인간 기억의 오류 가능성으로 인해 종종 신뢰할 수 없다." },
      { word: "criminology", pron: "/ˌkrɪmɪˈnɒlədʒi/", pos: "n.", meanings: ["범죄학"], example: "Criminology examines the causes of criminal behaviour to inform policies aimed at reducing offending in society.", exampleKr: "범죄학은 사회에서 범행을 줄이기 위한 정책을 알리기 위해 범죄 행동의 원인을 조사한다." },
      { word: "motive", pron: "/ˈməʊtɪv/", pos: "n.", meanings: ["동기", "범행 이유"], example: "Establishing a clear motive is an important element in building a convincing prosecution case.", exampleKr: "명확한 동기를 확립하는 것은 설득력 있는 기소 사건을 만드는 데 중요한 요소이다." },
      { word: "evidence", pron: "/ˈevɪdəns/", pos: "n.", meanings: ["증거", "물증"], example: "The prosecution presented compelling physical evidence linking the accused directly to the scene of the crime.", exampleKr: "검찰은 피고인을 범죄 현장에 직접 연결하는 강력한 물적 증거를 제시했다." },
      { word: "suspect", pron: "/ˈsʌspekt/", pos: "n.", meanings: ["용의자", "혐의자"], example: "Police identified three suspects in connection with the robbery but lacked sufficient evidence to make arrests.", exampleKr: "경찰은 강도 사건과 관련하여 세 명의 용의자를 식별했지만 체포할 충분한 증거가 부족했다." }
    ]
  },
  150: {
    theme: "종합 복습 I",
    words: [
      { word: "paradigm", pron: "/ˈpærədaɪm/", pos: "n.", meanings: ["패러다임", "사고 틀"], example: "The discovery of quantum mechanics created a paradigm shift in physics, overturning centuries of Newtonian certainty.", exampleKr: "양자 역학의 발견은 물리학에서 패러다임 전환을 일으켜 수 세기간의 뉴턴적 확실성을 뒤집었다." },
      { word: "rhetoric", pron: "/ˈretərɪk/", pos: "n.", meanings: ["수사학", "언변"], example: "Powerful rhetoric can inspire action, but it can equally be used to mislead audiences with impressive-sounding language.", exampleKr: "강력한 수사학은 행동을 고무시킬 수 있지만, 인상적으로 들리는 언어로 청중을 오도하는 데도 똑같이 사용될 수 있다." },
      { word: "anomaly", pron: "/əˈnɒməli/", pos: "n.", meanings: ["이상", "변칙"], example: "Scientists investigated the temperature anomaly, which deviated significantly from historical averages for the region.", exampleKr: "과학자들은 그 지역의 역사적 평균에서 상당히 벗어난 온도 이상을 조사했다." },
      { word: "pragmatic", pron: "/præɡˈmætɪk/", pos: "adj.", meanings: ["실용적인", "현실적인"], example: "A pragmatic approach to policy focuses on what works in practice rather than what sounds theoretically ideal.", exampleKr: "정책에 대한 실용적인 접근은 이론적으로 이상적으로 들리는 것보다 실제로 효과적인 것에 초점을 맞춘다." },
      { word: "consensus", pron: "/kənˈsensəs/", pos: "n.", meanings: ["합의", "동의"], example: "The scientific consensus on climate change is that it is primarily caused by human greenhouse gas emissions.", exampleKr: "기후 변화에 대한 과학적 합의는 주로 인간의 온실 가스 배출에 의해 야기된다는 것이다." },
      { word: "catalyst", pron: "/ˈkætəlɪst/", pos: "n.", meanings: ["촉매", "계기"], example: "The financial crisis served as a catalyst for sweeping reforms to banking regulation across multiple countries.", exampleKr: "금융 위기는 여러 나라에 걸쳐 은행 규제의 전면적인 개혁을 위한 촉매역할을 했다." },
      { word: "hierarchy", pron: "/ˈhaɪərɑːrki/", pos: "n.", meanings: ["위계", "계층 구조"], example: "Flat organisational structures challenge traditional hierarchy by distributing decision-making across multiple levels.", exampleKr: "수평적 조직 구조는 의사결정을 여러 단계에 분산시킴으로써 전통적인 위계를 도전한다." },
      { word: "precedent", pron: "/ˈpresɪdənt/", pos: "n.", meanings: ["선례", "전례"], example: "The court's ruling set a legal precedent that would shape how similar cases were decided for decades.", exampleKr: "법원의 판결은 수십 년간 유사한 사건들이 어떻게 결정되는지를 형성할 법적 선례를 세웠다." },
      { word: "empirical", pron: "/ɪmˈpɪrɪkəl/", pos: "adj.", meanings: ["경험적인", "실증적인"], example: "Empirical research based on observation and experiment forms the bedrock of all modern scientific disciplines.", exampleKr: "관찰과 실험에 기반한 경험적 연구는 모든 현대 과학 분야의 토대를 형성한다." },
      { word: "momentum", pron: "/məˈmentəm/", pos: "n.", meanings: ["기세", "운동량", "모멘텀"], example: "The campaign gained momentum as more celebrities endorsed the candidate and donations began to pour in.", exampleKr: "더 많은 유명인이 후보자를 지지하고 기부금이 쏟아지면서 캠페인이 기세를 탔다." },
      { word: "dilemma", pron: "/dɪˈlemə/", pos: "n.", meanings: ["딜레마", "진퇴양난"], example: "The company faced an ethical dilemma between maximising profit and maintaining its environmental commitments.", exampleKr: "그 회사는 이익 극대화와 환경 약속 유지 사이에서 윤리적 딜레마에 직면했다." },
      { word: "coherence", pron: "/kəʊˈhɪərəns/", pos: "n.", meanings: ["일관성", "응집성"], example: "The essay was well-researched but lacked coherence, jumping between unrelated ideas without clear transitions.", exampleKr: "그 에세이는 잘 조사되었지만, 명확한 전환 없이 관련 없는 아이디어 사이를 오가며 일관성이 부족했다." },
      { word: "inference", pron: "/ˈɪnfərəns/", pos: "n.", meanings: ["추론", "추리"], example: "Drawing valid inferences from incomplete data requires careful analysis and an awareness of potential bias.", exampleKr: "불완전한 데이터에서 타당한 추론을 도출하려면 신중한 분석과 잠재적 편향에 대한 인식이 필요하다." },
      { word: "discrepancy", pron: "/dɪsˈkrepənsi/", pos: "n.", meanings: ["불일치", "차이"], example: "Auditors found a significant discrepancy between the reported and actual financial figures, triggering an investigation.", exampleKr: "감사인들은 보고된 재무 수치와 실제 수치 사이의 중대한 불일치를 발견하여 조사를 촉발시켰다." },
      { word: "synthesis", pron: "/ˈsɪnθəsɪs/", pos: "n.", meanings: ["종합", "합성"], example: "A good literature review goes beyond summarising sources to offer a synthesis of the main ideas and debates.", exampleKr: "좋은 문헌 검토는 출처를 요약하는 것을 넘어 주요 아이디어와 논쟁의 종합을 제공한다." },
      { word: "corroborate", pron: "/kəˈrɒbəreɪt/", pos: "v.", meanings: ["확증하다", "뒷받침하다"], example: "Multiple independent witnesses corroborated the account, strengthening the case for the prosecution significantly.", exampleKr: "여러 독립적인 목격자들이 그 진술을 확증하여 기소 측의 사건을 상당히 강화했다." },
      { word: "validate", pron: "/ˈvælɪdeɪt/", pos: "v.", meanings: ["검증하다", "확인하다"], example: "Researchers use peer review to validate their findings before publishing results in academic journals.", exampleKr: "연구자들은 학술 저널에 결과를 게재하기 전에 동료 검토를 통해 연구 결과를 검증한다." },
      { word: "implication", pron: "/ˌɪmplɪˈkeɪʃən/", pos: "n.", meanings: ["함의", "의미", "영향"], example: "The implications of the policy change for small businesses were not fully considered before its implementation.", exampleKr: "정책 변경이 소기업에 미치는 영향은 시행 전에 충분히 고려되지 않았다." },
      { word: "perpetuate", pron: "/pəˈpetʃʊeɪt/", pos: "v.", meanings: ["영속시키다", "지속하게 하다"], example: "Stereotypes in media perpetuate harmful assumptions about social groups that persist across generations.", exampleKr: "미디어의 고정관념은 세대를 거쳐 지속되는 사회 집단에 대한 해로운 가정들을 영속시킨다." },
      { word: "ambiguous", pron: "/æmˈbɪɡjʊəs/", pos: "adj.", meanings: ["모호한", "중의적인"], example: "The contract's ambiguous wording led to a dispute over responsibilities that required legal mediation to resolve.", exampleKr: "계약서의 모호한 표현은 해결하기 위해 법적 조정이 필요한 책임에 대한 분쟁을 일으켰다." }
    ]
  }
});
