/**
 * data_days_116_120.js - Day 116~120 단어 데이터
 * data_days_111_115.js 이후에 로드해야 합니다
 */
Object.assign(VOCA_DATA, {
  116: {
    theme: "수학통계 어휘",
    words: [
      { word: "theorem", pron: "/θɪərəm/", pos: "n.", meanings: ["정리", "이론"], example: "Pythagoras' theorem states that the square of the hypotenuse equals the sum of the squares of the other two sides.", exampleKr: "피타고라스의 정리는 빗변의 제곱이 나머지 두 변의 제곱합과 같다고 말한다." },
      { word: "coefficient", pron: "/kəʊɪfɪʃənt/", pos: "n.", meanings: ["계수"], example: "In the expression 4x squared plus 3x, the coefficient of the x squared term is 4.", exampleKr: "4x 제곱 + 3x라는 식에서 x 제곱 항의 계수는 4이다." },
      { word: "asymptote", pron: "/æsɪmptəʊt/", pos: "n.", meanings: ["점근선"], example: "The curve approaches its asymptote ever more closely but never actually reaches it.", exampleKr: "곡선은 점근선에 점점 가까워지지만 실제로는 결코 도달하지 않는다." },
      { word: "derivative", pron: "/dɪrɪvətɪv/", pos: "n.", meanings: ["도함수", "파생물"], example: "The derivative of a function measures the rate at which its output changes relative to its input.", exampleKr: "함수의 도함수는 입력값에 대해 출력값이 변하는 비율을 측정한다." },
      { word: "integral", pron: "/ɪntɪɡrəl/", pos: "n./adj.", meanings: ["적분", "필수적인"], example: "Calculating the integral of the velocity-time graph gives the total displacement over the given period.", exampleKr: "속도-시간 그래프의 적분을 계산하면 주어진 기간 동안의 총 변위를 구할 수 있다." },
      { word: "axiom", pron: "/æksiəm/", pos: "n.", meanings: ["공리", "자명한 이치"], example: "Euclid's geometry is founded on five fundamental axioms that are accepted as true without formal proof.", exampleKr: "유클리드 기하학은 공식적인 증명 없이 참으로 받아들여지는 다섯 가지 기본 공리 위에 세워져 있다." },
      { word: "probability", pron: "/prɒbəbɪlɪti/", pos: "n.", meanings: ["확률", "가능성"], example: "The probability of rolling a six on a fair die is exactly one in six, or approximately 16.7 per cent.", exampleKr: "공정한 주사위에서 6이 나올 확률은 6분의 1, 즉 약 16.7퍼센트이다." },
      { word: "variance", pron: "/veəriəns/", pos: "n.", meanings: ["분산", "차이"], example: "A high variance in exam scores suggests that students have very different levels of understanding.", exampleKr: "시험 점수의 높은 분산은 학생들이 매우 다른 수준의 이해도를 가지고 있음을 시사한다." },
      { word: "regression", pron: "/rɪɡreʃən/", pos: "n.", meanings: ["회귀", "회귀 분석"], example: "Multiple regression analysis was used to identify which variables most accurately predicted customer satisfaction.", exampleKr: "다중 회귀 분석이 고객 만족도를 가장 정확하게 예측하는 변수를 파악하는 데 사용되었다." },
      { word: "hypothesis", pron: "/haɪpɒθɪsɪs/", pos: "n.", meanings: ["가설"], example: "The researchers formulated a clear hypothesis that could be rigorously tested through controlled experiments.", exampleKr: "연구자들은 통제된 실험을 통해 엄격하게 검증될 수 있는 명확한 가설을 세웠다." },
      { word: "permutation", pron: "/pɜːrmjʊteɪʃən/", pos: "n.", meanings: ["순열", "변환"], example: "The number of permutations of five objects arranged in a line is 5 factorial, which equals 120.", exampleKr: "한 줄로 배열된 5개 객체의 순열 수는 5 팩토리얼로, 120에 해당한다." },
      { word: "correlation", pron: "/kɒrəleɪʃən/", pos: "n.", meanings: ["상관관계", "연관성"], example: "A strong positive correlation was found between regular physical exercise and reported levels of well-being.", exampleKr: "규칙적인 신체 운동과 보고된 행복 수준 사이에 강한 양의 상관관계가 발견되었다." },
      { word: "logarithm", pron: "/lɒɡərɪðəm/", pos: "n.", meanings: ["로그", "대수"], example: "Logarithms convert multiplicative relationships into additive ones, simplifying calculations involving very large numbers.", exampleKr: "로그는 곱셈 관계를 덧셈 관계로 변환하여 매우 큰 수를 포함하는 계산을 단순화한다." },
      { word: "matrix", pron: "/meɪtrɪks/", pos: "n.", meanings: ["행렬", "모체"], example: "Matrices are used in computer graphics to represent geometric transformations such as rotation and scaling.", exampleKr: "행렬은 컴퓨터 그래픽에서 회전 및 크기 조정과 같은 기하학적 변환을 표현하는 데 사용된다." },
      { word: "binomial", pron: "/baɪnəʊmiəl/", pos: "n./adj.", meanings: ["이항식", "이항의"], example: "The binomial theorem provides a formula for expanding any positive integer power of a two-term expression.", exampleKr: "이항 정리는 두 항으로 이루어진 식의 양의 정수 거듭제곱을 전개하는 공식을 제공한다." },
      { word: "median", pron: "/miːdiən/", pos: "n.", meanings: ["중앙값", "중위수"], example: "When a data set contains extreme outliers, the median is typically a more representative measure than the mean.", exampleKr: "데이터 세트에 극단적인 이상값이 있을 때 중앙값은 일반적으로 평균보다 더 대표적인 측정값이다." },
      { word: "deviation", pron: "/diːvieɪʃən/", pos: "n.", meanings: ["편차", "이탈"], example: "A low standard deviation indicates that data points cluster tightly around the mean of the distribution.", exampleKr: "낮은 표준 편차는 데이터 포인트가 분포의 평균 근처에 촘촘하게 모여 있음을 나타낸다." },
      { word: "interpolation", pron: "/ɪntɜːrpəleɪʃən/", pos: "n.", meanings: ["보간법", "내삽"], example: "Interpolation was used to estimate values between the known data points recorded in the experiment.", exampleKr: "실험에서 기록된 알려진 데이터 포인트 사이의 값을 추정하기 위해 보간법이 사용되었다." },
      { word: "fractal", pron: "/fræktəl/", pos: "n.", meanings: ["프랙탈"], example: "Fractals display self-similar patterns that repeat at every scale of magnification, from large to infinitely small.", exampleKr: "프랙탈은 크게서 매우 작은 것까지 모든 배율 척도에서 반복되는 자기 유사 패턴을 보여준다." },
      { word: "algorithm", pron: "/ælɡərɪðəm/", pos: "n.", meanings: ["알고리즘", "연산 규칙"], example: "Efficient sorting algorithms are fundamental to computer science and underlie many real-world applications.", exampleKr: "효율적인 정렬 알고리즘은 컴퓨터 과학의 기본이며 많은 실제 응용 프로그램의 기반이 된다." }
    ]
  },
  117: {
    theme: "화학물리학 어휘",
    words: [
      { word: "catalyst", pron: "/kætəlɪst/", pos: "n.", meanings: ["촉매", "촉진제"], example: "A catalyst speeds up a chemical reaction without being consumed or permanently altered in the process.", exampleKr: "촉매는 그 과정에서 소비되거나 영구적으로 변형되지 않으면서 화학 반응을 가속시킨다." },
      { word: "isotope", pron: "/aɪsətəʊp/", pos: "n.", meanings: ["동위원소"], example: "Carbon-14 is a radioactive isotope widely used in archaeological dating of organic materials.", exampleKr: "탄소-14는 유기 물질의 고고학적 연대 측정에 널리 사용되는 방사성 동위원소이다." },
      { word: "molecule", pron: "/mɒlɪkjuːl/", pos: "n.", meanings: ["분자"], example: "A water molecule consists of two hydrogen atoms bonded to a single oxygen atom.", exampleKr: "물 분자는 하나의 산소 원자에 결합된 두 개의 수소 원자로 구성되어 있다." },
      { word: "osmosis", pron: "/ɒzməʊsɪs/", pos: "n.", meanings: ["삼투", "삼투 현상"], example: "Osmosis drives water across cell membranes from areas of low solute concentration to areas of high concentration.", exampleKr: "삼투는 낮은 용질 농도 영역에서 높은 농도 영역으로 세포막을 통해 물을 이동시킨다." },
      { word: "valence", pron: "/veɪləns/", pos: "n.", meanings: ["원자가", "결합 능력"], example: "An element's valence determines how many bonds it can form with other atoms in a compound.", exampleKr: "원소의 원자가는 화합물에서 다른 원자와 형성할 수 있는 결합의 수를 결정한다." },
      { word: "entropy", pron: "/entrəpi/", pos: "n.", meanings: ["엔트로피", "무질서도"], example: "The second law of thermodynamics states that the entropy of an isolated system tends to increase over time.", exampleKr: "열역학 제2법칙은 고립된 시스템의 엔트로피가 시간이 지남에 따라 증가하는 경향이 있다고 말한다." },
      { word: "viscosity", pron: "/vɪskɒsɪti/", pos: "n.", meanings: ["점도", "점성"], example: "Honey has a much higher viscosity than water, which is why it flows so much more slowly.", exampleKr: "꿀은 물보다 점도가 훨씬 높아서 훨씬 더 느리게 흐른다." },
      { word: "diffraction", pron: "/dɪfrækʃən/", pos: "n.", meanings: ["회절"], example: "X-ray diffraction is used to determine the atomic structure of crystalline materials.", exampleKr: "X선 회절은 결정성 물질의 원자 구조를 결정하는 데 사용된다." },
      { word: "refraction", pron: "/rɪfrækʃən/", pos: "n.", meanings: ["굴절"], example: "The refraction of light as it passes from air into water explains why objects appear displaced underwater.", exampleKr: "빛이 공기에서 물로 지나갈 때의 굴절은 물 속에서 물체가 이동된 것처럼 보이는 이유를 설명한다." },
      { word: "ionisation", pron: "/aɪənɪzeɪʃən/", pos: "n.", meanings: ["이온화"], example: "Ionisation occurs when an atom gains or loses electrons, resulting in a positively or negatively charged ion.", exampleKr: "이온화는 원자가 전자를 얻거나 잃을 때 발생하여 양전하 또는 음전하를 띤 이온이 생성된다." },
      { word: "half-life", pron: "/hɑːf laɪf/", pos: "n.", meanings: ["반감기"], example: "The half-life of carbon-14 is approximately 5,730 years, making it suitable for dating ancient organic remains.", exampleKr: "탄소-14의 반감기는 약 5,730년으로, 고대 유기물 잔유물의 연대 측정에 적합하다." },
      { word: "centrifuge", pron: "/sentrɪfjuːdʒ/", pos: "n./v.", meanings: ["원심분리기", "원심분리하다"], example: "A centrifuge spins samples at high speed to separate components of different densities.", exampleKr: "원심분리기는 샘플을 고속으로 회전시켜 다른 밀도의 성분을 분리한다." },
      { word: "sublimation", pron: "/sʌblɪmeɪʃən/", pos: "n.", meanings: ["승화"], example: "Sublimation is the direct transition of a substance from solid to gas, bypassing the liquid phase entirely.", exampleKr: "승화는 물질이 고체에서 액체 단계를 완전히 건너뛰고 기체로 직접 전환되는 것이다." },
      { word: "alloy", pron: "/ælɔɪ/", pos: "n./v.", meanings: ["합금", "합금하다"], example: "Stainless steel is an alloy combining iron with chromium and nickel to resist corrosion.", exampleKr: "스테인리스 스틸은 부식에 저항하기 위해 철에 크롬과 니켈을 결합한 합금이다." },
      { word: "thermodynamics", pron: "/θɜːrməʊdaɪnæmɪks/", pos: "n.", meanings: ["열역학"], example: "Thermodynamics governs how energy is transferred, converted, and conserved within physical and chemical systems.", exampleKr: "열역학은 물리적, 화학적 시스템 내에서 에너지가 어떻게 전달되고 변환되며 보존되는지를 다룬다." },
      { word: "photon", pron: "/fəʊtɒn/", pos: "n.", meanings: ["광자", "빛 입자"], example: "A photon is the fundamental particle of light and carries a quantum of electromagnetic energy.", exampleKr: "광자는 빛의 기본 입자로 전자기 에너지의 양자를 운반한다." },
      { word: "inertia", pron: "/ɪnɜːrʃə/", pos: "n.", meanings: ["관성", "타성"], example: "Newton's first law describes inertia as the tendency of an object to resist changes in its state of motion.", exampleKr: "뉴턴의 제1법칙은 관성을 물체가 운동 상태의 변화에 저항하는 경향으로 설명한다." },
      { word: "oxidation", pron: "/ɒksɪdeɪʃən/", pos: "n.", meanings: ["산화"], example: "Oxidation of iron in the presence of water and oxygen produces iron oxide, commonly known as rust.", exampleKr: "물과 산소가 존재할 때 철의 산화는 일반적으로 녹이라고 알려진 산화철을 생성한다." },
      { word: "polymer", pron: "/pɒlɪmər/", pos: "n.", meanings: ["고분자", "중합체"], example: "Plastics are synthetic polymers composed of long chains of repeated molecular units called monomers.", exampleKr: "플라스틱은 단량체라고 불리는 반복 분자 단위의 긴 사슬로 구성된 합성 고분자이다." },
      { word: "electrolysis", pron: "/ɪlektrɒlɪsɪs/", pos: "n.", meanings: ["전기분해"], example: "Electrolysis uses electric current to drive a non-spontaneous chemical reaction, separating compounds into their elements.", exampleKr: "전기분해는 전류를 사용하여 비자발적 화학 반응을 유도하며, 화합물을 원소로 분리한다." }
    ]
  },
  118: {
    theme: "생물학생명과학",
    words: [
      { word: "chromosome", pron: "/krəʊməsəʊm/", pos: "n.", meanings: ["염색체"], example: "Human cells typically contain 46 chromosomes, arranged in 23 pairs that carry genetic information.", exampleKr: "인간 세포는 보통 유전 정보를 담고 있는 23쌍으로 배열된 46개의 염색체를 포함하고 있다." },
      { word: "protein", pron: "/prəʊtiːn/", pos: "n.", meanings: ["단백질"], example: "Proteins are essential macromolecules that carry out most of the structural and functional roles within cells.", exampleKr: "단백질은 세포 내에서 대부분의 구조적, 기능적 역할을 수행하는 필수 거대분자이다." },
      { word: "enzyme", pron: "/enzaɪm/", pos: "n.", meanings: ["효소"], example: "Enzymes act as biological catalysts, dramatically accelerating chemical reactions within living organisms.", exampleKr: "효소는 생물학적 촉매로 작용하여 살아있는 유기체 내의 화학 반응을 극적으로 가속시킨다." },
      { word: "mutation", pron: "/mjuːteɪʃən/", pos: "n.", meanings: ["돌연변이", "변이"], example: "A mutation in the cancer-suppressing gene can cause cells to multiply uncontrollably, leading to tumour formation.", exampleKr: "암 억제 유전자의 돌연변이는 세포가 통제 불가능하게 증식하여 종양 형성으로 이어질 수 있다." },
      { word: "mitosis", pron: "/maɪtəʊsɪs/", pos: "n.", meanings: ["유사분열", "체세포분열"], example: "Mitosis produces two genetically identical daughter cells from a single parent cell for growth and repair.", exampleKr: "유사분열은 성장과 수복을 위해 하나의 모세포에서 유전적으로 동일한 두 개의 딸세포를 생산한다." },
      { word: "meiosis", pron: "/maɪəʊsɪs/", pos: "n.", meanings: ["감수분열"], example: "Meiosis produces reproductive cells with half the chromosome number of the original cell.", exampleKr: "감수분열은 원래 세포 염색체 수의 절반을 가진 생식 세포를 생산한다." },
      { word: "phenotype", pron: "/fiːnətaɪp/", pos: "n.", meanings: ["표현형"], example: "An organism's phenotype includes all observable characteristics shaped by its genes and environmental factors.", exampleKr: "유기체의 표현형은 유전자와 환경 요인에 의해 형성된 모든 관찰 가능한 특성을 포함한다." },
      { word: "genotype", pron: "/dʒiːnətaɪp/", pos: "n.", meanings: ["유전자형", "유전형"], example: "Two organisms can share the same phenotype while having completely different underlying genotypes.", exampleKr: "두 유기체는 동일한 표현형을 공유하면서도 완전히 다른 유전자형을 가질 수 있다." },
      { word: "symbiosis", pron: "/sɪmbaɪəʊsɪs/", pos: "n.", meanings: ["공생", "공생 관계"], example: "The relationship between clownfish and sea anemones is a classic example of mutualistic symbiosis.", exampleKr: "흰동가리와 말미잘 사이의 관계는 상리 공생의 고전적인 예이다." },
      { word: "homeostasis", pron: "/həʊmiəsteɪsɪs/", pos: "n.", meanings: ["항상성"], example: "The human body maintains homeostasis by regulating core temperature, blood pressure, and glucose concentration.", exampleKr: "인체는 체온, 혈압, 포도당 농도를 조절함으로써 항상성을 유지한다." },
      { word: "nucleotide", pron: "/njuːkliətaɪd/", pos: "n.", meanings: ["뉴클레오타이드"], example: "Nucleotides are the building blocks of DNA and RNA, each consisting of a sugar, a phosphate group, and a base.", exampleKr: "뉴클레오타이드는 DNA와 RNA의 구성 요소로, 각각 당, 인산기, 염기로 구성된다." },
      { word: "ribosome", pron: "/raɪbəsəʊm/", pos: "n.", meanings: ["리보솜"], example: "Ribosomes are molecular machines found in all cells that translate genetic information to synthesise proteins.", exampleKr: "리보솜은 모든 세포에서 발견되는 분자 기계로 유전 정보를 번역하여 단백질을 합성한다." },
      { word: "plasmid", pron: "/plæzmɪd/", pos: "n.", meanings: ["플라스미드"], example: "Plasmids are small, circular DNA molecules in bacteria that replicate independently of the main chromosome.", exampleKr: "플라스미드는 세균에 있는 작은 원형 DNA 분자로 주요 염색체와 독립적으로 복제된다." },
      { word: "taxonomy", pron: "/tæksɒnəmi/", pos: "n.", meanings: ["분류학", "분류 체계"], example: "Taxonomy classifies all living organisms into kingdoms, phyla, classes, orders, families, genera, and species.", exampleKr: "분류학은 모든 생물을 계, 문, 강, 목, 과, 속, 종으로 분류한다." },
      { word: "vertebrate", pron: "/vɜːrtɪbrɪt/", pos: "n./adj.", meanings: ["척추동물", "척추가 있는"], example: "Vertebrates include fish, amphibians, reptiles, birds, and mammals, all united by the presence of a spinal column.", exampleKr: "척추동물에는 물고기, 양서류, 파충류, 조류, 포유류가 포함되며, 모두 척추의 존재로 통합된다." },
      { word: "invertebrate", pron: "/ɪnvɜːrtɪbrɪt/", pos: "n./adj.", meanings: ["무척추동물", "척추가 없는"], example: "Invertebrates make up over 95 per cent of all known animal species, from insects to molluscs.", exampleKr: "무척추동물은 곤충에서 연체동물까지 알려진 모든 동물 종의 95퍼센트 이상을 차지한다." },
      { word: "carnivore", pron: "/kɑːrnɪvɔːr/", pos: "n.", meanings: ["육식동물"], example: "As apex carnivores, wolves play a crucial role in regulating prey populations and maintaining ecosystem balance.", exampleKr: "최상위 육식동물로서 늑대는 먹이 개체군을 조절하고 생태계 균형을 유지하는 데 중요한 역할을 한다." },
      { word: "herbivore", pron: "/hɜːrbɪvɔːr/", pos: "n.", meanings: ["초식동물"], example: "Herbivores like deer and rabbits play a vital role in shaping the vegetation structure of their habitats.", exampleKr: "사슴과 토끼 같은 초식동물은 서식지의 식생 구조를 형성하는 데 중요한 역할을 한다." },
      { word: "omnivore", pron: "/ɒmnɪvɔːr/", pos: "n.", meanings: ["잡식동물"], example: "Humans are omnivores, capable of digesting both plant and animal foods to meet their nutritional needs.", exampleKr: "인간은 잡식동물로서 영양 필요를 충족시키기 위해 식물성 식품과 동물성 식품 모두를 소화할 수 있다." },
      { word: "photosynthesis", pron: "/fəʊtəʊsɪnθɪsɪs/", pos: "n.", meanings: ["광합성"], example: "Through photosynthesis, green plants convert sunlight, carbon dioxide, and water into glucose and oxygen.", exampleKr: "광합성을 통해 녹색 식물은 햇빛, 이산화탄소, 물을 포도당과 산소로 변환한다." }
    ]
  },
  119: {
    theme: "컴퓨터과학프로그래밍",
    words: [
      { word: "recursion", pron: "/rɪkɜːrʃən/", pos: "n.", meanings: ["재귀", "재귀 호출"], example: "Recursion in programming refers to a function that calls itself to solve smaller instances of the same problem.", exampleKr: "프로그래밍에서 재귀는 같은 문제의 더 작은 인스턴스를 해결하기 위해 자신을 호출하는 함수를 말한다." },
      { word: "abstraction", pron: "/æbstrækʃən/", pos: "n.", meanings: ["추상화"], example: "Abstraction in software design hides complex implementation details behind a simple, clean interface.", exampleKr: "소프트웨어 설계에서 추상화는 복잡한 구현 세부사항을 간단하고 깔끔한 인터페이스 뒤에 숨긴다." },
      { word: "polymorphism", pron: "/pɒlɪmɔːrfɪzəm/", pos: "n.", meanings: ["다형성"], example: "Polymorphism allows a single interface to represent different underlying data types in object-oriented programming.", exampleKr: "다형성은 객체 지향 프로그래밍에서 단일 인터페이스가 다양한 기본 데이터 유형을 표현할 수 있게 한다." },
      { word: "encapsulation", pron: "/ɪnkæpsjʊleɪʃən/", pos: "n.", meanings: ["캡슐화"], example: "Encapsulation bundles data and the methods that operate on it into a single, self-contained unit called a class.", exampleKr: "캡슐화는 데이터와 그것을 처리하는 메서드를 클래스라는 하나의 자체 포함 단위로 묶는다." },
      { word: "inheritance", pron: "/ɪnherɪtəns/", pos: "n.", meanings: ["상속", "계승"], example: "Inheritance enables a new class to reuse and extend the properties and methods of an existing parent class.", exampleKr: "상속은 새 클래스가 기존 부모 클래스의 속성과 메서드를 재사용하고 확장할 수 있게 한다." },
      { word: "compiler", pron: "/kəmpaɪlər/", pos: "n.", meanings: ["컴파일러"], example: "A compiler translates source code written in a high-level language into machine code understood by the processor.", exampleKr: "컴파일러는 고급 언어로 작성된 소스 코드를 프로세서가 이해하는 기계 코드로 번역한다." },
      { word: "bandwidth", pron: "/bændwɪdθ/", pos: "n.", meanings: ["대역폭", "전송 용량"], example: "Streaming high-definition video requires significant bandwidth to deliver smooth, uninterrupted playback.", exampleKr: "고화질 비디오 스트리밍은 원활하고 끊김 없는 재생을 제공하기 위해 상당한 대역폭이 필요하다." },
      { word: "latency", pron: "/leɪtənsi/", pos: "n.", meanings: ["지연 시간", "레이턴시"], example: "High latency in online gaming causes noticeable delays between player actions and on-screen responses.", exampleKr: "온라인 게임에서의 높은 지연 시간은 플레이어 행동과 화면 반응 사이에 눈에 띄는 지연을 초래한다." },
      { word: "cryptography", pron: "/krɪptɒɡrəfi/", pos: "n.", meanings: ["암호학", "암호화"], example: "Cryptography secures digital communications by transforming data into a form unreadable without the correct decryption key.", exampleKr: "암호학은 올바른 복호화 키 없이는 읽을 수 없는 형태로 데이터를 변환하여 디지털 통신을 보호한다." },
      { word: "concurrency", pron: "/kənkɜːrənsi/", pos: "n.", meanings: ["동시성", "병행성"], example: "Concurrency allows multiple tasks to be executed simultaneously, making programmes more efficient on multi-core processors.", exampleKr: "동시성은 여러 작업이 동시에 실행될 수 있게 하여 멀티코어 프로세서에서 프로그램을 더 효율적으로 만든다." },
      { word: "heuristic", pron: "/hjʊrɪstɪk/", pos: "adj./n.", meanings: ["발견적인", "휴리스틱"], example: "A heuristic approach finds a good-enough solution quickly when finding the perfect solution would take too long.", exampleKr: "휴리스틱 방식은 완벽한 해결책을 찾는 데 너무 오래 걸릴 때 충분히 좋은 해결책을 빠르게 찾는다." },
      { word: "debugging", pron: "/diːbʌɡɪŋ/", pos: "n.", meanings: ["디버깅", "오류 수정"], example: "Systematic debugging involves isolating and identifying the exact line of code that is causing unexpected behaviour.", exampleKr: "체계적인 디버깅은 예기치 않은 동작을 유발하는 정확한 코드 행을 분리하고 식별하는 것을 포함한다." },
      { word: "repository", pron: "/rɪpɒzɪtəri/", pos: "n.", meanings: ["저장소", "리포지토리"], example: "The team used a shared code repository to track changes, collaborate efficiently, and manage version history.", exampleKr: "팀은 변경 사항을 추적하고, 효율적으로 협업하며, 버전 기록을 관리하기 위해 공유 코드 저장소를 사용했다." },
      { word: "middleware", pron: "/mɪdəlweər/", pos: "n.", meanings: ["미들웨어"], example: "Middleware acts as a bridge between the operating system and the applications running on top of it.", exampleKr: "미들웨어는 운영 체제와 그 위에서 실행되는 애플리케이션 사이의 다리 역할을 한다." },
      { word: "scalability", pron: "/skeɪləbɪlɪti/", pos: "n.", meanings: ["확장성", "확장 가능성"], example: "Scalability is a critical design requirement for any system expected to handle growing volumes of traffic.", exampleKr: "확장성은 증가하는 트래픽 양을 처리할 것이 예상되는 모든 시스템의 중요한 설계 요구사항이다." },
      { word: "iteration", pron: "/ɪtəreɪʃən/", pos: "n.", meanings: ["반복", "이터레이션"], example: "Agile development uses short iterations to deliver incremental improvements and respond quickly to change.", exampleKr: "애자일 개발은 단계적 개선을 제공하고 변화에 신속하게 대응하기 위해 짧은 반복 주기를 사용한다." },
      { word: "dependency", pron: "/dɪpendənsi/", pos: "n.", meanings: ["의존성", "종속성"], example: "Managing dependencies carefully is essential to maintaining a stable and maintainable codebase over time.", exampleKr: "의존성을 신중하게 관리하는 것은 시간이 지남에 따라 안정적이고 유지 관리 가능한 코드베이스를 유지하는 데 필수적이다." },
      { word: "refactoring", pron: "/riːfæktərɪŋ/", pos: "n.", meanings: ["리팩터링", "코드 재구조화"], example: "Refactoring improves the internal structure of existing code without changing its external behaviour or functionality.", exampleKr: "리팩터링은 외부 동작이나 기능을 변경하지 않고 기존 코드의 내부 구조를 개선한다." },
      { word: "authentication", pron: "/ɔːθentɪkeɪʃən/", pos: "n.", meanings: ["인증", "신원 확인"], example: "Two-factor authentication adds an important extra layer of security beyond just a username and password.", exampleKr: "이중 인증은 사용자 이름과 비밀번호 이상의 중요한 추가 보안 레이어를 추가한다." },
      { word: "virtualisation", pron: "/vɜːrtʃʊəlaɪzeɪʃən/", pos: "n.", meanings: ["가상화"], example: "Server virtualisation allows multiple virtual machines to run concurrently on a single physical hardware host.", exampleKr: "서버 가상화는 단일 물리적 하드웨어 호스트에서 여러 가상 머신이 동시에 실행될 수 있게 한다." }
    ]
  },
  120: {
    theme: "해양수산 어휘",
    words: [
      { word: "oceanography", pron: "/əʊʃənɒɡrəfi/", pos: "n.", meanings: ["해양학"], example: "Oceanography combines elements of physics, chemistry, biology, and geology to study the world's oceans.", exampleKr: "해양학은 세계의 바다를 연구하기 위해 물리학, 화학, 생물학, 지질학의 요소를 결합한다." },
      { word: "bathymetry", pron: "/bəθɪmɪtri/", pos: "n.", meanings: ["수심 측량", "해저 지형학"], example: "Advanced bathymetry surveys have revealed enormous mountain ranges and deep trenches on the ocean floor.", exampleKr: "고급 수심 측량 조사는 해저에 거대한 산맥과 깊은 해구를 드러냈다." },
      { word: "benthic", pron: "/benθɪk/", pos: "adj.", meanings: ["해저의", "저서의"], example: "Benthic organisms live on or in the sediment at the bottom of oceans, rivers, and lakes.", exampleKr: "저서 생물은 바다, 강, 호수 바닥의 퇴적물 위나 안에서 살아간다." },
      { word: "thermocline", pron: "/θɜːrməklaɪn/", pos: "n.", meanings: ["수온약층"], example: "The thermocline is a layer of water where temperature decreases sharply with increasing depth.", exampleKr: "수온약층은 깊이가 증가함에 따라 수온이 급격히 감소하는 수층이다." },
      { word: "salinity", pron: "/səlɪnɪti/", pos: "n.", meanings: ["염도", "염분"], example: "The salinity of seawater averages around 35 parts per thousand, varying by region and depth.", exampleKr: "해수의 염도는 평균 약 35퍼밀(천분의 35)이며, 지역과 깊이에 따라 달라진다." },
      { word: "tidal", pron: "/taɪdəl/", pos: "adj.", meanings: ["조류의", "조석의"], example: "Tidal energy harnesses the movement of ocean tides to generate clean, renewable electricity.", exampleKr: "조력 에너지는 바다 조석의 움직임을 이용하여 청정 재생 가능 전기를 생산한다." },
      { word: "upwelling", pron: "/ʌpwelɪŋ/", pos: "n.", meanings: ["용승", "해수 상승"], example: "Coastal upwelling brings nutrient-rich deep water to the surface, supporting highly productive fisheries.", exampleKr: "연안 용승은 영양분이 풍부한 심해수를 표면으로 끌어올려 매우 생산적인 어장을 지원한다." },
      { word: "bioluminescence", pron: "/baɪəʊluːmɪnesəns/", pos: "n.", meanings: ["생물 발광"], example: "Bioluminescence, the production of light by living organisms, is common in deep-sea creatures.", exampleKr: "생물 발광, 즉 생물에 의한 빛 생산은 심해 생물에서 흔히 볼 수 있다." },
      { word: "plankton", pron: "/plæŋktən/", pos: "n.", meanings: ["플랑크톤"], example: "Plankton forms the base of the marine food chain and produces roughly half of Earth's oxygen through photosynthesis.", exampleKr: "플랑크톤은 해양 먹이사슬의 기반을 형성하며 광합성을 통해 지구 산소의 약 절반을 생산한다." },
      { word: "coral reef", pron: "/kɒrəl riːf/", pos: "n.", meanings: ["산호초"], example: "Coral reefs support roughly a quarter of all marine species despite covering less than one per cent of the ocean floor.", exampleKr: "산호초는 해저의 1퍼센트 미만을 덮고 있음에도 불구하고 모든 해양 종의 약 4분의 1을 부양한다." },
      { word: "eutrophication", pron: "/juːtrɒfɪkeɪʃən/", pos: "n.", meanings: ["부영양화"], example: "Eutrophication, caused by excess nutrients from agricultural runoff, depletes oxygen in water bodies.", exampleKr: "농업 유출수의 과잉 영양분으로 인한 부영양화는 수역의 산소를 고갈시킨다." },
      { word: "trawling", pron: "/trɔːlɪŋ/", pos: "n.", meanings: ["트롤 어업", "저인망 어업"], example: "Deep-sea trawling destroys fragile seabed habitats and catches large quantities of non-target species.", exampleKr: "심해 트롤 어업은 취약한 해저 서식지를 파괴하고 많은 양의 비목표 종을 포획한다." },
      { word: "aquaculture", pron: "/ækwəkʌltʃər/", pos: "n.", meanings: ["양식업", "수산 양식"], example: "Aquaculture is the fastest-growing food production sector, now supplying over half of all seafood consumed globally.", exampleKr: "양식업은 가장 빠르게 성장하는 식품 생산 부문으로 현재 전 세계적으로 소비되는 모든 해산물의 절반 이상을 공급한다." },
      { word: "maritime", pron: "/mærɪtaɪm/", pos: "adj.", meanings: ["해상의", "해양의"], example: "The country has a long maritime history, with trade routes connecting it to ports across the globe.", exampleKr: "그 나라는 오랜 해상 역사를 가지고 있으며, 무역 항로는 전 세계의 항구와 그 나라를 연결한다." },
      { word: "pelagic", pron: "/pɪlædʒɪk/", pos: "adj.", meanings: ["원양의", "외양의"], example: "Pelagic fish such as tuna and mackerel live and feed in the open sea, far from the coastline.", exampleKr: "참다랑어와 고등어와 같은 원양 어류는 해안선에서 떨어진 공해에서 생활하고 먹이를 찾는다." },
      { word: "littoral", pron: "/lɪtərəl/", pos: "adj./n.", meanings: ["연안의", "연안 지역"], example: "The littoral zone, where land meets sea, hosts rich and diverse ecosystems including mangroves and salt marshes.", exampleKr: "육지와 바다가 만나는 연안 지역은 맹그로브와 염습지를 포함한 풍부하고 다양한 생태계를 보유하고 있다." },
      { word: "shoal", pron: "/ʃəʊl/", pos: "n.", meanings: ["물고기 떼", "여울"], example: "A shoal of sardines swirled through the water in perfect unison, confusing the predators below.", exampleKr: "정어리 떼가 완벽한 조화로 물속을 선회하며 아래의 포식자들을 혼란스럽게 했다." },
      { word: "estuary", pron: "/estʃʊəri/", pos: "n.", meanings: ["강어귀", "하구"], example: "Estuaries, where rivers meet the sea, are among the most biologically productive environments on Earth.", exampleKr: "강과 바다가 만나는 강어귀는 지구상에서 생물학적으로 가장 생산적인 환경 중 하나이다." },
      { word: "seamount", pron: "/siːmaʊnt/", pos: "n.", meanings: ["해산", "수중 산"], example: "Seamounts, underwater volcanic mountains, are biodiversity hotspots that support unique deep-sea communities.", exampleKr: "수중 화산산인 해산은 독특한 심해 군락을 지원하는 생물 다양성의 온상이다." },
      { word: "ichthyology", pron: "/ɪkθiɒlədʒi/", pos: "n.", meanings: ["어류학"], example: "Ichthyology is the scientific branch devoted to the study and classification of fish species worldwide.", exampleKr: "어류학은 전 세계 어류 종의 연구와 분류에 전념하는 과학 분야이다." }
    ]
  }
});
