/**
 * data_days_131_135.js - Day 131~135 단어 데이터
 * data_days_126_130.js 이후에 로드해야 합니다
 */
Object.assign(VOCA_DATA, {
  131: {
    theme: "미디어저널리즘",
    words: [
      { word: "investigative journalism", pron: "/ɪnvestɪɡətɪv dʒɜːrnəlɪzəm/", pos: "n.", meanings: ["탐사 저널리즘"], example: "Investigative journalism exposed the corruption scandal, leading to the resignation of senior government officials.", exampleKr: "탐사 저널리즘이 부패 스캔들을 폭로하여 고위 정부 관리들의 사임으로 이어졌다." },
      { word: "editorial", pron: "/edɪtɔːriəl/", pos: "n./adj.", meanings: ["사설", "편집의"], example: "The newspaper's editorial praised the government's economic reforms while urging caution on welfare cuts.", exampleKr: "신문의 사설은 정부의 경제 개혁을 칭찬하면서도 복지 삭감에 대해 신중할 것을 촉구했다." },
      { word: "propaganda", pron: "/prɒpəɡændə/", pos: "n.", meanings: ["선전", "프로파간다"], example: "State-sponsored propaganda manipulates public opinion by systematically distorting facts and suppressing dissent.", exampleKr: "국가 후원 선전은 사실을 체계적으로 왜곡하고 반대 의견을 억압하여 여론을 조종한다." },
      { word: "censorship", pron: "/sensəʃɪp/", pos: "n.", meanings: ["검열"], example: "Censorship of the internet restricts citizens' access to independent news sources and political viewpoints.", exampleKr: "인터넷 검열은 시민들이 독립적인 뉴스 소스와 정치적 관점에 접근하는 것을 제한한다." },
      { word: "tabloid", pron: "/tæblɔɪd/", pos: "n./adj.", meanings: ["타블로이드", "선정적인"], example: "The tabloid sensationalised the celebrity's private life with exaggerated and misleading headlines.", exampleKr: "타블로이드는 과장되고 오해를 불러일으키는 헤드라인으로 그 유명인의 사생활을 자극적으로 보도했다." },
      { word: "impartiality", pron: "/ɪmpɑːrʃiælɪti/", pos: "n.", meanings: ["공정성", "중립성"], example: "Public broadcasters have a legal obligation to maintain impartiality in their news coverage and reporting.", exampleKr: "공영 방송사는 뉴스 보도에서 공정성을 유지해야 하는 법적 의무가 있다." },
      { word: "clickbait", pron: "/klɪkbeɪt/", pos: "n.", meanings: ["낚시성 기사", "클릭베이트"], example: "Clickbait headlines are designed to provoke curiosity and generate traffic rather than inform readers accurately.", exampleKr: "낚시성 기사 헤드라인은 독자에게 정확히 알리기보다는 호기심을 자극하고 트래픽을 유발하도록 설계되어 있다." },
      { word: "disinformation", pron: "/dɪsɪnfəmeɪʃən/", pos: "n.", meanings: ["허위 정보", "가짜 뉴스"], example: "State actors have used disinformation campaigns to sow division and undermine trust in democratic institutions.", exampleKr: "국가 행위자들은 분열을 조장하고 민주주의 제도에 대한 신뢰를 약화시키기 위해 허위 정보 캠페인을 사용해 왔다." },
      { word: "media literacy", pron: "/miːdiə lɪtərəsi/", pos: "n.", meanings: ["미디어 리터러시"], example: "Media literacy education teaches students to critically evaluate sources and distinguish reliable news from misinformation.", exampleKr: "미디어 리터러시 교육은 학생들이 출처를 비판적으로 평가하고 신뢰할 수 있는 뉴스를 잘못된 정보와 구별하도록 가르친다." },
      { word: "paywall", pron: "/peɪwɔːl/", pos: "n.", meanings: ["유료 구독 벽", "페이월"], example: "Many newspapers have introduced paywalls to generate revenue as advertising income has declined sharply.", exampleKr: "많은 신문사들이 광고 수입이 급격히 감소함에 따라 수익을 창출하기 위해 페이월을 도입했다." },
      { word: "scoop", pron: "/skuːp/", pos: "n./v.", meanings: ["특종", "특종 보도하다"], example: "The journalist landed a major scoop by interviewing the whistleblower before any other outlet.", exampleKr: "그 기자는 다른 어떤 매체보다 먼저 내부 고발자를 인터뷰하여 주요 특종을 잡았다." },
      { word: "op-ed", pron: "/ɒp ed/", pos: "n.", meanings: ["논평 기사", "외부 기고 칼럼"], example: "She submitted an op-ed to the newspaper arguing for stronger regulation of social media platforms.", exampleKr: "그녀는 소셜 미디어 플랫폼에 대한 더 강력한 규제를 주장하는 논평 기사를 신문에 제출했다." },
      { word: "retraction", pron: "/rɪtrækʃən/", pos: "n.", meanings: ["정정 보도", "취소"], example: "The newspaper published a formal retraction after the inaccurate story had already spread widely online.", exampleKr: "신문사는 부정확한 기사가 이미 온라인에서 널리 퍼진 후 공식 정정 보도를 게재했다." },
      { word: "pundit", pron: "/pʌndɪt/", pos: "n.", meanings: ["전문가", "논평가"], example: "Political pundits warned that the government's economic policy would lead to inflation and public discontent.", exampleKr: "정치 평론가들은 정부의 경제 정책이 인플레이션과 공중의 불만으로 이어질 것이라고 경고했다." },
      { word: "broadsheet", pron: "/brɔːdʃiːt/", pos: "n.", meanings: ["대형판 신문", "고급 신문"], example: "Broadsheet newspapers traditionally target educated readers seeking in-depth analysis rather than sensational stories.", exampleKr: "대형판 신문은 전통적으로 자극적인 기사보다는 심층 분석을 원하는 교양 있는 독자층을 대상으로 한다." },
      { word: "press freedom", pron: "/pres friːdəm/", pos: "n.", meanings: ["언론의 자유"], example: "A free and independent press is considered a cornerstone of democratic governance and accountability.", exampleKr: "자유롭고 독립적인 언론은 민주적 통치와 책임성의 초석으로 여겨진다." },
      { word: "embed", pron: "/ɪmbed/", pos: "v./n.", meanings: ["종군 기자로 동행하다", "내장하다"], example: "A journalist embedded with the military unit filed daily reports from the front line of the conflict.", exampleKr: "군 부대에 종군한 기자는 분쟁 최전선에서 매일 보도를 보냈다." },
      { word: "hyperlocal", pron: "/haɪpələʊkəl/", pos: "adj.", meanings: ["초지역적인", "극지역 맞춤형"], example: "Hyperlocal news outlets cover stories affecting individual streets, schools, and small communities.", exampleKr: "초지역 뉴스 매체는 개별 거리, 학교, 소규모 커뮤니티에 영향을 미치는 이야기들을 다룬다." },
      { word: "broadcast", pron: "/brɔːdkɑːst/", pos: "n./v.", meanings: ["방송", "방송하다"], example: "The historic speech was broadcast live to an audience of over one billion viewers worldwide.", exampleKr: "그 역사적인 연설은 전 세계 10억 명 이상의 시청자에게 생방송으로 전달되었다." },
      { word: "feature story", pron: "/fiːtʃər stɔːri/", pos: "n.", meanings: ["특집 기사", "특집 보도"], example: "The magazine ran a feature story exploring the social consequences of long-term unemployment in rural areas.", exampleKr: "그 잡지는 농촌 지역에서의 장기 실업의 사회적 결과를 탐구하는 특집 기사를 게재했다." }
    ]
  },
  132: {
    theme: "부동산건설 어휘",
    words: [
      { word: "mortgage", pron: "/mɔːrɡɪdʒ/", pos: "n./v.", meanings: ["담보 대출", "모기지"], example: "Rising interest rates have made mortgage repayments significantly more expensive for homeowners across the country.", exampleKr: "금리 상승으로 전국의 주택 소유자들에게 담보 대출 상환이 상당히 더 비싸졌다." },
      { word: "equity", pron: "/ekwɪti/", pos: "n.", meanings: ["자기 자본", "주식"], example: "As house prices rose, homeowners built up substantial equity in their properties over many years.", exampleKr: "집값이 오르면서 주택 소유자들은 수년에 걸쳐 자신의 부동산에서 상당한 자기 자본을 쌓았다." },
      { word: "easement", pron: "/iːzmənt/", pos: "n.", meanings: ["지역권", "통행권"], example: "The property includes an easement that grants the neighbour the right to cross the land to reach the road.", exampleKr: "그 부동산에는 이웃이 도로에 도달하기 위해 토지를 가로질러 갈 권리를 부여하는 지역권이 포함되어 있다." },
      { word: "conveyancing", pron: "/kənveɪənsɪŋ/", pos: "n.", meanings: ["부동산 양도", "소유권 이전"], example: "Conveyancing involves the legal transfer of property ownership from seller to buyer, usually handled by a solicitor.", exampleKr: "부동산 양도는 보통 변호사가 처리하는 부동산 소유권의 매도인에서 매수인으로의 법적 이전을 포함한다." },
      { word: "freehold", pron: "/friːhəʊld/", pos: "n.", meanings: ["영구 소유권", "완전 소유권"], example: "Buying the freehold of a flat gives the owner permanent ownership of the building and the land it stands on.", exampleKr: "아파트의 영구 소유권을 구입하면 소유자에게 건물과 그것이 서 있는 토지의 영구적인 소유권이 주어진다." },
      { word: "tenancy", pron: "/tenənsi/", pos: "n.", meanings: ["임차", "임대"], example: "The tenancy agreement stipulated that the rent would be reviewed annually and could increase by up to five per cent.", exampleKr: "임대 계약서는 임대료가 매년 검토될 것이며 최대 5퍼센트까지 인상될 수 있다고 명시했다." },
      { word: "depreciation", pron: "/dɪpriːʃieɪʃən/", pos: "n.", meanings: ["가치 감소", "감가상각"], example: "The depreciation of older properties in declining neighbourhoods can significantly reduce owner wealth over time.", exampleKr: "쇠퇴하는 지역의 오래된 부동산의 가치 감소는 시간이 지남에 따라 소유자의 재산을 크게 줄일 수 있다." },
      { word: "subcontractor", pron: "/sʌbkəntræktər/", pos: "n.", meanings: ["하청업자", "하도급 업체"], example: "The main contractor engaged specialist subcontractors for the electrical, plumbing, and roofing work.", exampleKr: "원청업자는 전기, 배관, 지붕 공사에 전문 하청업자들을 고용했다." },
      { word: "foreclosure", pron: "/fɔːrkləʊʒər/", pos: "n.", meanings: ["담보권 실행", "담보 주택 압류"], example: "Following months of missed payments, the bank initiated foreclosure proceedings on the family's home.", exampleKr: "몇 달간의 미납 후, 은행은 가족의 주택에 대한 담보권 실행 절차를 시작했다." },
      { word: "foundation", pron: "/faʊndeɪʃən/", pos: "n.", meanings: ["기초", "기반"], example: "Poor foundation work can lead to structural problems such as subsidence and cracking in walls and floors.", exampleKr: "부실한 기초 공사는 지반 침하, 벽과 바닥의 균열과 같은 구조적 문제로 이어질 수 있다." },
      { word: "covenant", pron: "/kʌvənənt/", pos: "n.", meanings: ["제한 규약", "서약"], example: "A restrictive covenant on the property prevented the new owner from converting it into commercial premises.", exampleKr: "부동산의 제한 규약은 새 소유자가 그것을 상업용 건물로 전환하는 것을 막았다." },
      { word: "capital gains", pron: "/kæpɪtəl ɡeɪnz/", pos: "n.", meanings: ["자본 이득", "양도 차익"], example: "Capital gains tax applies when a property is sold for more than it originally cost the owner.", exampleKr: "자본 이득세는 부동산이 원래 소유자에게 든 비용보다 더 비싸게 팔릴 때 적용된다." },
      { word: "eminent domain", pron: "/emɪnənt dəmeɪn/", pos: "n.", meanings: ["국가 수용권", "공용 수용"], example: "The government exercised eminent domain to acquire private land for the construction of the new motorway.", exampleKr: "정부는 새 고속도로 건설을 위해 사유지를 취득하기 위해 국가 수용권을 행사했다." },
      { word: "site survey", pron: "/saɪt sɜːrveɪ/", pos: "n.", meanings: ["현장 조사", "부지 측량"], example: "A thorough site survey must be completed before construction can begin to identify any ground conditions or hazards.", exampleKr: "지반 조건이나 위험 요소를 파악하기 위해 공사가 시작되기 전에 철저한 현장 조사가 완료되어야 한다." },
      { word: "REIT", pron: "/riːt/", pos: "n.", meanings: ["부동산 투자 신탁"], example: "Investors can gain exposure to commercial real estate through REITs without directly owning property.", exampleKr: "투자자들은 부동산을 직접 소유하지 않고 리츠(REIT)를 통해 상업용 부동산에 투자할 수 있다." },
      { word: "planning permission", pron: "/plænɪŋ pəmɪʃən/", pos: "n.", meanings: ["건축 허가", "개발 허가"], example: "The developer applied for planning permission to convert the former warehouse into luxury residential apartments.", exampleKr: "개발업자는 이전 창고를 고급 주거 아파트로 전환하기 위한 건축 허가를 신청했다." },
      { word: "strata title", pron: "/strɑːtə taɪtəl/", pos: "n.", meanings: ["집합 건물 소유권"], example: "Under a strata title arrangement, each apartment owner holds title to their unit and shares ownership of common areas.", exampleKr: "집합 건물 소유권 체계에서 각 아파트 소유자는 자신의 세대 소유권을 갖고 공용 면적의 소유권을 공유한다." },
      { word: "yield", pron: "/jiːld/", pos: "n.", meanings: ["임대 수익률", "수익"], example: "Investors compare rental yields across locations to identify the most attractive property investment opportunities.", exampleKr: "투자자들은 가장 매력적인 부동산 투자 기회를 찾기 위해 지역별 임대 수익률을 비교한다." },
      { word: "off-plan", pron: "/ɒf plæn/", pos: "adj.", meanings: ["사전 분양의", "선분양의"], example: "Buying off-plan can secure a property at today's price but carries the risk that market values may fall before completion.", exampleKr: "선분양으로 구매하면 오늘의 가격으로 부동산을 확보할 수 있지만 완공 전에 시장 가치가 하락할 위험이 있다." },
      { word: "stamp duty", pron: "/stæmp djuːti/", pos: "n.", meanings: ["인지세", "취득세"], example: "First-time buyers in many countries benefit from stamp duty exemptions or reductions to ease affordability.", exampleKr: "많은 나라에서 생애 첫 주택 구매자들은 구매 가능성을 높이기 위해 인지세 면제 또는 감면의 혜택을 받는다." }
    ]
  },
  133: {
    theme: "보험금융 II",
    words: [
      { word: "premium", pron: "/priːmiəm/", pos: "n.", meanings: ["보험료", "프리미엄"], example: "The insurance premium increased significantly after the policyholder made several claims in quick succession.", exampleKr: "보험 계약자가 연속해서 여러 번 보험금을 청구한 후 보험료가 크게 인상되었다." },
      { word: "underwrite", pron: "/ʌndəraɪt/", pos: "v.", meanings: ["보험을 인수하다", "지원하다"], example: "The bank agreed to underwrite the bond issue, guaranteeing to buy any unsold securities at the agreed price.", exampleKr: "은행은 채권 발행을 인수하여 합의된 가격에 팔리지 않은 유가증권을 매입하기로 보장했다." },
      { word: "annuity", pron: "/ənjuːɪti/", pos: "n.", meanings: ["연금", "연금 보험"], example: "An annuity provides a guaranteed regular income for life in exchange for an upfront lump-sum payment.", exampleKr: "연금은 초기 일시금 지급 대가로 평생 보장된 정기 수입을 제공한다." },
      { word: "deductible", pron: "/dɪdʌktɪbəl/", pos: "n./adj.", meanings: ["보험 공제액", "공제 가능한"], example: "Choosing a higher deductible lowers the monthly premium but means paying more out of pocket when a claim arises.", exampleKr: "높은 공제액을 선택하면 월 보험료가 낮아지지만 보험금 청구 시 더 많은 자기 부담이 발생한다." },
      { word: "indemnity", pron: "/ɪndemnɪti/", pos: "n.", meanings: ["보상", "배상", "면책"], example: "Professional indemnity insurance protects consultants against claims arising from errors in their professional advice.", exampleKr: "전문가 배상 책임 보험은 컨설턴트를 전문적인 조언의 오류로 인한 청구로부터 보호한다." },
      { word: "hedge fund", pron: "/hedʒ fʌnd/", pos: "n.", meanings: ["헤지 펀드"], example: "Hedge funds use complex strategies including short selling and leverage to generate returns regardless of market direction.", exampleKr: "헤지 펀드는 시장 방향에 관계없이 수익을 창출하기 위해 공매도 및 레버리지를 포함한 복잡한 전략을 사용한다." },
      { word: "derivatives", pron: "/dɪrɪvətɪvz/", pos: "n.", meanings: ["파생 상품"], example: "Financial derivatives, such as futures and options, derive their value from an underlying asset's price movements.", exampleKr: "선물이나 옵션과 같은 금융 파생 상품은 기초 자산의 가격 움직임에서 가치를 도출한다." },
      { word: "leveraged buyout", pron: "/levərɪdʒd baɪaʊt/", pos: "n.", meanings: ["차입 매수", "LBO"], example: "A leveraged buyout uses borrowed funds to acquire a company, with the acquired firm's assets often serving as collateral.", exampleKr: "차입 매수는 차입 자금을 사용하여 기업을 인수하며, 종종 인수된 기업의 자산이 담보로 사용된다." },
      { word: "liquidity", pron: "/lɪkwɪdɪti/", pos: "n.", meanings: ["유동성"], example: "Banks must hold sufficient liquidity to meet unexpected customer withdrawals without becoming insolvent.", exampleKr: "은행은 지급 불능 없이 예기치 않은 고객 인출을 충족시키기 위해 충분한 유동성을 보유해야 한다." },
      { word: "portfolio", pron: "/pɔːrtfəʊliəʊ/", pos: "n.", meanings: ["포트폴리오", "투자 종목 묶음"], example: "Diversifying a portfolio across different asset classes reduces the impact of poor performance in any single investment.", exampleKr: "포트폴리오를 다양한 자산 등급에 걸쳐 분산시키면 단일 투자에서의 부진한 성과의 영향을 줄인다." },
      { word: "dividend", pron: "/dɪvɪdend/", pos: "n.", meanings: ["배당금", "배당"], example: "The company declared a quarterly dividend of 30 pence per share for its shareholders.", exampleKr: "회사는 주주들에게 주당 30펜스의 분기 배당금을 선언했다." },
      { word: "volatility", pron: "/vɒlətɪlɪti/", pos: "n.", meanings: ["변동성", "변동률"], example: "High market volatility makes investors nervous and can trigger panic selling or irrational buying.", exampleKr: "높은 시장 변동성은 투자자들을 불안하게 만들고 패닉 매도나 비합리적인 매수를 촉발할 수 있다." },
      { word: "amortisation", pron: "/əmɔːrtɪzeɪʃən/", pos: "n.", meanings: ["상환", "감가상각"], example: "The amortisation schedule showed that most early repayments would go toward interest rather than reducing principal.", exampleKr: "상환 일정은 초기 상환의 대부분이 원금을 줄이기보다는 이자로 가게 된다는 것을 보여주었다." },
      { word: "reinsurance", pron: "/riːɪnʃʊərəns/", pos: "n.", meanings: ["재보험"], example: "Reinsurance allows insurers to transfer a portion of their risk to a third party for a share of the premiums.", exampleKr: "재보험은 보험사가 보험료의 일부를 대가로 위험의 일부를 제3자에게 이전할 수 있게 한다." },
      { word: "insolvency", pron: "/ɪnsɒlvənsi/", pos: "n.", meanings: ["지급 불능", "도산"], example: "The company filed for insolvency protection after being unable to meet its debt obligations to creditors.", exampleKr: "회사는 채권자들에 대한 채무 의무를 이행할 수 없게 된 후 지급 불능 보호 신청을 했다." },
      { word: "collateral", pron: "/kəlætərəl/", pos: "n./adj.", meanings: ["담보", "부수적인"], example: "The bank required substantial collateral before agreeing to extend the business loan.", exampleKr: "은행은 사업 대출을 연장하는 데 합의하기 전에 상당한 담보를 요구했다." },
      { word: "securitisation", pron: "/sɪkjʊərɪtaɪzeɪʃən/", pos: "n.", meanings: ["증권화"], example: "The securitisation of mortgage loans allows banks to sell debt obligations to investors and free up lending capacity.", exampleKr: "모기지 대출의 증권화는 은행이 투자자에게 채무 의무를 매각하고 대출 역량을 확보할 수 있게 한다." },
      { word: "fiduciary", pron: "/fɪdjuːʃɪəri/", pos: "n./adj.", meanings: ["수탁자", "신탁의"], example: "Financial advisers have a fiduciary duty to act in the best interests of their clients, not their own.", exampleKr: "금융 고문은 자신의 이익이 아닌 고객의 최선의 이익을 위해 행동해야 하는 신탁 의무가 있다." },
      { word: "risk management", pron: "/rɪsk mænɪdʒmənt/", pos: "n.", meanings: ["위험 관리"], example: "Sound risk management identifies, assesses, and mitigates potential threats before they cause financial loss.", exampleKr: "건전한 위험 관리는 잠재적 위협이 재정적 손실을 초래하기 전에 식별, 평가, 완화한다." },
      { word: "actuarial", pron: "/æktʃʊeəriəl/", pos: "adj.", meanings: ["보험통계학의", "위험 계산의"], example: "Actuarial analysis uses statistical data to calculate the likelihood and cost of future insurance claims.", exampleKr: "보험통계학적 분석은 통계 데이터를 사용하여 미래 보험금 청구의 가능성과 비용을 계산한다." }
    ]
  },
  134: {
    theme: "소비자마케팅 어휘",
    words: [
      { word: "demographics", pron: "/deməɡræfɪks/", pos: "n.", meanings: ["인구 통계", "인구학적 요소"], example: "Marketers analyse demographics such as age, income, and education level to better target their campaigns.", exampleKr: "마케터들은 캠페인을 더 잘 타겟팅하기 위해 연령, 소득, 교육 수준과 같은 인구 통계를 분석한다." },
      { word: "brand equity", pron: "/brænd ekwɪti/", pos: "n.", meanings: ["브랜드 자산", "브랜드 가치"], example: "Strong brand equity allows companies to charge premium prices and retain loyal customers over time.", exampleKr: "강력한 브랜드 자산은 기업이 프리미엄 가격을 책정하고 시간이 지남에 따라 충성 고객을 유지할 수 있게 한다." },
      { word: "market segmentation", pron: "/mɑːrkɪt seɡmenteɪʃən/", pos: "n.", meanings: ["시장 세분화"], example: "Market segmentation divides consumers into distinct groups to develop tailored products and marketing messages.", exampleKr: "시장 세분화는 맞춤형 제품과 마케팅 메시지를 개발하기 위해 소비자를 구별되는 집단으로 나눈다." },
      { word: "value proposition", pron: "/væljuː prɒpəzɪʃən/", pos: "n.", meanings: ["가치 제안"], example: "A compelling value proposition clearly explains why a product is better than alternatives for a specific customer.", exampleKr: "설득력 있는 가치 제안은 특정 고객에게 제품이 대안보다 나은 이유를 명확하게 설명한다." },
      { word: "viral marketing", pron: "/vaɪrəl mɑːrkɪtɪŋ/", pos: "n.", meanings: ["바이럴 마케팅"], example: "Viral marketing campaigns spread rapidly through social sharing, reaching millions of people at minimal cost.", exampleKr: "바이럴 마케팅 캠페인은 소셜 공유를 통해 빠르게 확산되어 최소한의 비용으로 수백만 명에게 도달한다." },
      { word: "conversion rate", pron: "/kənvɜːrʒən reɪt/", pos: "n.", meanings: ["전환율"], example: "The website redesign improved the conversion rate from visitor to paying customer by 40 per cent.", exampleKr: "웹사이트 재설계는 방문자에서 유료 고객으로의 전환율을 40퍼센트 향상시켰다." },
      { word: "churn rate", pron: "/tʃɜːrn reɪt/", pos: "n.", meanings: ["이탈률", "고객 이탈률"], example: "A high churn rate indicates that customers are dissatisfied and switching to competing products or services.", exampleKr: "높은 이탈률은 고객들이 불만족스러워 경쟁 제품이나 서비스로 이탈하고 있다는 것을 나타낸다." },
      { word: "influencer", pron: "/ɪnfluənsər/", pos: "n.", meanings: ["인플루언서"], example: "Brands collaborate with social media influencers whose followers trust their recommendations and lifestyle endorsements.", exampleKr: "브랜드들은 팔로워들이 그들의 추천과 라이프스타일 홍보를 신뢰하는 소셜 미디어 인플루언서들과 협력한다." },
      { word: "engagement rate", pron: "/ɪnɡeɪdʒmənt reɪt/", pos: "n.", meanings: ["참여율", "인게이지먼트율"], example: "A high engagement rate on social media posts suggests that the content resonates strongly with the audience.", exampleKr: "소셜 미디어 게시물의 높은 참여율은 콘텐츠가 청중과 강하게 공명하고 있다는 것을 시사한다." },
      { word: "SEO", pron: "/es iː əʊ/", pos: "n.", meanings: ["검색 엔진 최적화"], example: "Effective SEO strategies improve a website's ranking in search results, driving organic traffic without paid advertising.", exampleKr: "효과적인 검색 엔진 최적화 전략은 웹사이트의 검색 결과 순위를 높여 유료 광고 없이 자연 트래픽을 유도한다." },
      { word: "market share", pron: "/mɑːrkɪt ʃeər/", pos: "n.", meanings: ["시장 점유율"], example: "The company's aggressive pricing strategy helped it capture a significant share of the highly competitive market.", exampleKr: "회사의 공격적인 가격 전략은 매우 경쟁적인 시장에서 상당한 점유율을 확보하는 데 도움이 되었다." },
      { word: "customer acquisition", pron: "/kʌstəmər ækwɪzɪʃən/", pos: "n.", meanings: ["고객 확보", "신규 고객 유치"], example: "High customer acquisition costs must be recouped through sustained spending by retained customers over time.", exampleKr: "높은 고객 확보 비용은 시간이 지남에 따라 유지된 고객들의 지속적인 지출을 통해 회수되어야 한다." },
      { word: "SWOT analysis", pron: "/swɒt ənæləsɪs/", pos: "n.", meanings: ["SWOT 분석"], example: "A SWOT analysis maps a company's strengths, weaknesses, opportunities, and threats to inform strategy.", exampleKr: "SWOT 분석은 전략을 수립하기 위해 회사의 강점, 약점, 기회, 위협을 파악한다." },
      { word: "target audience", pron: "/tɑːrɡɪt ɔːdiəns/", pos: "n.", meanings: ["목표 고객", "타겟 고객층"], example: "Understanding the target audience's behaviour and preferences is essential for crafting effective marketing messages.", exampleKr: "목표 고객의 행동과 선호도를 이해하는 것은 효과적인 마케팅 메시지를 작성하는 데 필수적이다." },
      { word: "brand loyalty", pron: "/brænd lɔɪəlti/", pos: "n.", meanings: ["브랜드 충성도"], example: "Building brand loyalty through outstanding customer experience is far cheaper than constantly acquiring new customers.", exampleKr: "뛰어난 고객 경험을 통해 브랜드 충성도를 구축하는 것은 지속적으로 신규 고객을 확보하는 것보다 훨씬 저렴하다." },
      { word: "endorsement", pron: "/ɪndɔːrsmənt/", pos: "n.", meanings: ["홍보", "지지 협찬"], example: "Celebrity endorsements can rapidly boost a brand's visibility but must align credibly with the product being promoted.", exampleKr: "유명인 홍보는 브랜드의 인지도를 빠르게 높일 수 있지만 홍보 중인 제품과 신뢰할 수 있게 일치해야 한다." },
      { word: "B2B", pron: "/biː tʊ biː/", pos: "n.", meanings: ["기업 간 거래", "B2B"], example: "B2B marketing focuses on building long-term business relationships rather than individual consumer transactions.", exampleKr: "B2B 마케팅은 개인 소비자 거래보다는 장기적인 비즈니스 관계 구축에 중점을 둔다." },
      { word: "positioning", pron: "/pəzɪʃənɪŋ/", pos: "n.", meanings: ["포지셔닝", "시장 위치 설정"], example: "Effective brand positioning distinguishes a product from competitors in consumers' minds through a unique selling message.", exampleKr: "효과적인 브랜드 포지셔닝은 독특한 판매 메시지를 통해 소비자의 마음속에서 경쟁사로부터 제품을 차별화한다." },
      { word: "customer lifetime value", pron: "/kʌstəmər laɪftaɪm væljuː/", pos: "n.", meanings: ["고객 생애 가치", "LTV"], example: "Customer lifetime value predicts the total revenue a business can expect from a single customer over their relationship.", exampleKr: "고객 생애 가치는 비즈니스가 단일 고객과의 관계 동안 기대할 수 있는 총 수익을 예측한다." },
      { word: "omnichannel", pron: "/ɒmnɪtʃænəl/", pos: "adj.", meanings: ["옴니채널의", "통합 채널의"], example: "An omnichannel strategy ensures customers enjoy a seamless experience whether they shop online, via app, or in store.", exampleKr: "옴니채널 전략은 고객이 온라인, 앱, 매장 중 어디에서 쇼핑하든 원활한 경험을 누릴 수 있도록 보장한다." }
    ]
  },
  135: {
    theme: "신경과학 어휘",
    words: [
      { word: "neurotransmitter", pron: "/njʊərəʊtrænsmɪtər/", pos: "n.", meanings: ["신경전달물질"], example: "Neurotransmitters are chemical messengers that carry signals across synapses between neurons in the brain.", exampleKr: "신경전달물질은 뇌의 뉴런 사이 시냅스를 가로질러 신호를 전달하는 화학적 전달자이다." },
      { word: "synapse", pron: "/sɪnæps/", pos: "n.", meanings: ["시냅스"], example: "A synapse is the tiny gap between two neurons through which chemical or electrical signals are transmitted.", exampleKr: "시냅스는 화학적 또는 전기적 신호가 전달되는 두 뉴런 사이의 작은 틈이다." },
      { word: "cerebral cortex", pron: "/səriːbrəl kɔːrteks/", pos: "n.", meanings: ["대뇌 피질"], example: "The cerebral cortex is the outermost layer of the brain, responsible for higher cognitive functions such as language and reasoning.", exampleKr: "대뇌 피질은 언어와 추론과 같은 높은 인지 기능을 담당하는 뇌의 가장 바깥 층이다." },
      { word: "hippocampus", pron: "/hɪpəkæmpəs/", pos: "n.", meanings: ["해마", "기억 중추"], example: "The hippocampus plays a central role in forming and consolidating new long-term memories from short-term ones.", exampleKr: "해마는 단기 기억으로부터 새로운 장기 기억을 형성하고 강화하는 데 중심적인 역할을 한다." },
      { word: "amygdala", pron: "/əmɪɡdələ/", pos: "n.", meanings: ["편도체", "감정 중추"], example: "The amygdala processes emotional responses, particularly fear, and plays a key role in the stress response.", exampleKr: "편도체는 감정적 반응, 특히 공포를 처리하며 스트레스 반응에서 중요한 역할을 한다." },
      { word: "prefrontal cortex", pron: "/priːfrʌntəl kɔːrteks/", pos: "n.", meanings: ["전전두피질"], example: "The prefrontal cortex governs executive functions such as decision-making, planning, and impulse control.", exampleKr: "전전두피질은 의사 결정, 계획, 충동 조절과 같은 실행 기능을 관장한다." },
      { word: "dopamine", pron: "/dəʊpəmiːn/", pos: "n.", meanings: ["도파민"], example: "Dopamine is often called the reward chemical because it is released in response to pleasurable activities.", exampleKr: "도파민은 즐거운 활동에 반응하여 방출되기 때문에 종종 보상 화학물질이라고 불린다." },
      { word: "serotonin", pron: "/serətəʊnɪn/", pos: "n.", meanings: ["세로토닌"], example: "Low levels of serotonin have been linked to depression, and many antidepressant drugs work by boosting serotonin activity.", exampleKr: "낮은 세로토닌 수준은 우울증과 관련되어 있으며, 많은 항우울제는 세로토닌 활성을 높여 작용한다." },
      { word: "axon", pron: "/æksɒn/", pos: "n.", meanings: ["축삭", "신경 돌기"], example: "The axon is the long thin extension of a neuron that transmits electrical impulses away from the cell body.", exampleKr: "축삭은 세포체에서 멀리 전기 충격을 전달하는 뉴런의 길고 얇은 돌기이다." },
      { word: "dendrite", pron: "/dendraɪt/", pos: "n.", meanings: ["수상돌기"], example: "Dendrites receive incoming signals from other neurons and carry them toward the cell body for processing.", exampleKr: "수상돌기는 다른 뉴런으로부터 들어오는 신호를 받아 처리를 위해 세포체 쪽으로 전달한다." },
      { word: "neural pathway", pron: "/njʊərəl pɑːθweɪ/", pos: "n.", meanings: ["신경 경로"], example: "Repeated practice strengthens neural pathways, making skills become more automatic and less effortful over time.", exampleKr: "반복적인 연습은 신경 경로를 강화하여 시간이 지남에 따라 기술이 더 자동적이고 덜 힘들게 된다." },
      { word: "neurogenesis", pron: "/njʊərəʊdʒenɪsɪs/", pos: "n.", meanings: ["신경발생", "신경세포 생성"], example: "Research suggests that neurogenesis, the creation of new neurons, continues throughout adulthood in certain brain regions.", exampleKr: "연구에 따르면 새로운 뉴런 생성인 신경발생은 특정 뇌 영역에서 성인기까지 계속된다고 한다." },
      { word: "action potential", pron: "/ækʃən pətenʃəl/", pos: "n.", meanings: ["활동 전위"], example: "An action potential is the electrical signal that travels along a neuron's axon when it is sufficiently stimulated.", exampleKr: "활동 전위는 뉴런이 충분히 자극을 받을 때 축삭을 따라 이동하는 전기 신호이다." },
      { word: "myelin", pron: "/maɪəlɪn/", pos: "n.", meanings: ["마이엘린", "수초"], example: "Myelin sheaths insulate axons, dramatically increasing the speed of neural signal transmission.", exampleKr: "미엘린 초는 축삭을 절연하여 신경 신호 전달 속도를 극적으로 높인다." },
      { word: "dopamine pathway", pron: "/dəʊpəmiːn pɑːθweɪ/", pos: "n.", meanings: ["도파민 경로"], example: "Addictive substances hijack the brain's dopamine pathways, creating intense cravings that override rational decision-making.", exampleKr: "중독성 물질은 뇌의 도파민 경로를 장악하여 합리적인 의사 결정을 압도하는 강렬한 갈망을 만들어낸다." },
      { word: "cortisol", pron: "/kɔːrtɪsɒl/", pos: "n.", meanings: ["코르티솔"], example: "Cortisol, the primary stress hormone, is released by the adrenal glands in response to perceived threats.", exampleKr: "주요 스트레스 호르몬인 코르티솔은 인지된 위협에 반응하여 부신에서 방출된다." },
      { word: "oxytocin", pron: "/ɒksɪtəʊsɪn/", pos: "n.", meanings: ["옥시토신"], example: "Oxytocin, sometimes called the bonding hormone, strengthens social ties and is released during physical contact.", exampleKr: "때때로 유대감 호르몬이라고 불리는 옥시토신은 사회적 유대를 강화하고 신체적 접촉 시 방출된다." },
      { word: "circadian rhythm", pron: "/sɜːrkeɪdiən rɪðəm/", pos: "n.", meanings: ["일주기 리듬", "생체 시계"], example: "Disrupting the circadian rhythm through shift work or travel across time zones impairs cognitive performance.", exampleKr: "교대 근무나 시간대를 넘어선 여행을 통한 일주기 리듬 교란은 인지 기능을 손상시킨다." },
      { word: "neurodegeneration", pron: "/njʊərəʊdɪdʒenəreɪʃən/", pos: "n.", meanings: ["신경 퇴화", "신경 퇴행"], example: "Diseases like Alzheimer's and Parkinson's involve progressive neurodegeneration that destroys brain cells over time.", exampleKr: "알츠하이머와 파킨슨병 같은 질환은 시간이 지남에 따라 뇌 세포를 파괴하는 점진적인 신경 퇴화를 수반한다." },
      { word: "neuroimaging", pron: "/njʊərəʊɪmɪdʒɪŋ/", pos: "n.", meanings: ["뇌 영상 촬영", "신경 영상"], example: "Advances in neuroimaging allow scientists to observe brain activity in real time, transforming our understanding of cognition.", exampleKr: "뇌 영상 촬영 기술의 발전은 과학자들이 실시간으로 뇌 활동을 관찰할 수 있게 하여 인지에 대한 이해를 변화시켰다." }
    ]
  }
});
