/**
 * data_days_111_115.js - Day 111~115 단어 데이터
 * data_days_101_110.js 이후에 로드해야 합니다
 */
Object.assign(VOCA_DATA, {
  111: {
    theme: "법률사법 어휘",
    words: [
      { word: "jurisdiction", pron: "/dʒʊərɪsdɪkʃən/", pos: "n.", meanings: ["관할권", "사법권"], example: "The case was transferred to a federal court with jurisdiction over interstate commerce disputes.", exampleKr: "그 사건은 주간 통상 분쟁에 대한 관할권을 가진 연방 법원으로 이송되었다." },
      { word: "statute", pron: "/stætʃuːt/", pos: "n.", meanings: ["법령", "성문법"], example: "The statute prohibits workplace discrimination on grounds of age, gender, or ethnicity.", exampleKr: "그 법령은 연령, 성별 또는 민족성을 근거로 한 직장 내 차별을 금지한다." },
      { word: "plaintiff", pron: "/pleɪntɪf/", pos: "n.", meanings: ["원고", "고소인"], example: "The plaintiff claimed that the defendant had breached the terms of their written contract.", exampleKr: "원고는 피고가 서면 계약 조건을 위반했다고 주장했다." },
      { word: "defendant", pron: "/dɪfendənt/", pos: "n.", meanings: ["피고", "피의자"], example: "The defendant pleaded not guilty and requested a jury trial to contest the charges.", exampleKr: "피고는 무죄를 주장하며 혐의에 이의를 제기하기 위해 배심원 재판을 요청했다." },
      { word: "testimony", pron: "/testɪməni/", pos: "n.", meanings: ["증언", "진술"], example: "The witness gave compelling testimony that contradicted the defence lawyer's account of events.", exampleKr: "증인은 변호인의 사건 설명과 모순되는 설득력 있는 증언을 했다." },
      { word: "verdict", pron: "/vɜːrdɪkt/", pos: "n.", meanings: ["판결", "평결"], example: "After three days of deliberation, the jury returned a unanimous verdict of guilty.", exampleKr: "3일간의 숙의 끝에 배심원단은 만장일치 유죄 평결을 내렸다." },
      { word: "acquittal", pron: "/əkwɪtəl/", pos: "n.", meanings: ["무죄 판결", "석방"], example: "The acquittal was celebrated by the defendant's family, who had maintained his innocence throughout.", exampleKr: "내내 그의 결백을 주장했던 피고의 가족들은 무죄 판결을 축하했다." },
      { word: "subpoena", pron: "/səpiːnə/", pos: "n./v.", meanings: ["소환장", "소환하다"], example: "The journalist was served with a subpoena to testify about confidential sources in the investigation.", exampleKr: "그 기자는 수사에서 기밀 소식통에 대해 증언하도록 소환장을 받았다." },
      { word: "indictment", pron: "/ɪndaɪtmənt/", pos: "n.", meanings: ["기소", "공소"], example: "The grand jury handed down an indictment against three senior executives for fraud.", exampleKr: "대배심은 사기 혐의로 세 명의 고위 임원들에 대한 기소를 결정했다." },
      { word: "litigation", pron: "/lɪtɪɡeɪʃən/", pos: "n.", meanings: ["소송", "법정 분쟁"], example: "The company spent millions on litigation before eventually reaching an out-of-court settlement.", exampleKr: "그 회사는 법원 외 합의에 도달하기 전에 소송에 수백만 달러를 지출했다." },
      { word: "precedent", pron: "/presɪdənt/", pos: "n.", meanings: ["판례", "선례"], example: "The landmark ruling set a precedent that lower courts would be bound to follow in similar cases.", exampleKr: "그 획기적인 판결은 하급 법원들이 유사 사건에서 따라야 할 판례를 세웠다." },
      { word: "injunction", pron: "/ɪndʒʌŋkʃən/", pos: "n.", meanings: ["금지 명령", "가처분"], example: "The court granted an injunction to stop the company from releasing the disputed product.", exampleKr: "법원은 그 회사가 분쟁 중인 제품을 출시하지 못하도록 금지 명령을 내렸다." },
      { word: "affidavit", pron: "/æfɪdeɪvɪt/", pos: "n.", meanings: ["선서 진술서", "공증 진술서"], example: "She submitted a signed affidavit confirming she had witnessed the transaction firsthand.", exampleKr: "그녀는 자신이 그 거래를 직접 목격했음을 확인하는 서명된 선서 진술서를 제출했다." },
      { word: "culpable", pron: "/kʌlpəbəl/", pos: "adj.", meanings: ["과실이 있는", "비난받을 만한"], example: "The investigation concluded that the manager was culpable for the serious safety failures at the plant.", exampleKr: "조사는 관리자가 공장의 심각한 안전 실패에 대해 과실이 있다고 결론지었다." },
      { word: "malfeasance", pron: "/mælfiːzəns/", pos: "n.", meanings: ["직권 남용", "불법 행위"], example: "Several officials were investigated for malfeasance after public funds went missing from the account.", exampleKr: "공공 계좌에서 자금이 사라진 후 여러 공무원들이 직권 남용으로 조사를 받았다." },
      { word: "liability", pron: "/laɪəbɪlɪti/", pos: "n.", meanings: ["법적 책임", "배상 의무"], example: "The manufacturer accepted liability for defective products sold during the affected period.", exampleKr: "제조업체는 해당 기간에 판매된 결함 있는 제품에 대한 법적 책임을 인정했다." },
      { word: "restitution", pron: "/restɪtjuːʃən/", pos: "n.", meanings: ["배상", "원상복구"], example: "The judge ordered full restitution to victims to compensate for their documented financial losses.", exampleKr: "판사는 피해자들의 기록된 재정적 손실을 보상하기 위해 완전한 배상을 명령했다." },
      { word: "perjury", pron: "/pɜːrdʒəri/", pos: "n.", meanings: ["위증죄", "위증"], example: "The witness was charged with perjury after it emerged that his courtroom testimony was false.", exampleKr: "증인은 그의 법정 증언이 거짓이었던 것이 밝혀진 후 위증죄로 기소되었다." },
      { word: "arbitration", pron: "/ɑːrbɪtreɪʃən/", pos: "n.", meanings: ["중재", "조정"], example: "Both parties agreed to resolve the dispute through binding arbitration rather than going to court.", exampleKr: "양 당사자는 법원에 가는 대신 구속력 있는 중재를 통해 분쟁을 해결하기로 합의했다." },
      { word: "extradition", pron: "/ekstrədɪʃən/", pos: "n.", meanings: ["범죄인 인도", "인도 조약"], example: "The country signed an extradition treaty obliging it to surrender accused persons to requesting nations.", exampleKr: "그 나라는 요청하는 국가에 피의자를 넘겨줄 의무가 있는 범죄인 인도 조약에 서명했다." }
    ]
  },
  112: {
    theme: "천문학우주 어휘",
    words: [
      { word: "nebula", pron: "/nebjʊlə/", pos: "n.", meanings: ["성운"], example: "The Orion Nebula is one of the most studied stellar nurseries in our entire galaxy.", exampleKr: "오리온 성운은 우리 은하에서 가장 많이 연구된 별의 탄생 지역 중 하나이다." },
      { word: "quasar", pron: "/kweɪzɑːr/", pos: "n.", meanings: ["퀘이사", "준성"], example: "Quasars, powered by supermassive black holes, are among the most luminous objects in the observable universe.", exampleKr: "초대질량 블랙홀에 의해 구동되는 퀘이사는 관측 가능한 우주에서 가장 밝은 천체 중 하나이다." },
      { word: "pulsar", pron: "/pʌlsɑːr/", pos: "n.", meanings: ["펄서", "맥동성"], example: "A pulsar emits beams of electromagnetic radiation at extremely regular intervals, behaving like a cosmic lighthouse.", exampleKr: "펄서는 우주의 등대처럼 매우 규칙적인 간격으로 전자기 복사 빔을 방출한다." },
      { word: "supernova", pron: "/suːpənoʊvə/", pos: "n.", meanings: ["초신성"], example: "A supernova explosion can, for a brief period, outshine an entire galaxy of hundreds of billions of stars.", exampleKr: "초신성 폭발은 짧은 기간 동안 수천억 개의 별로 이루어진 은하 전체보다 더 밝게 빛날 수 있다." },
      { word: "parallax", pron: "/pærəlæks/", pos: "n.", meanings: ["시차"], example: "Astronomers use stellar parallax to measure distances to nearby stars with remarkable precision.", exampleKr: "천문학자들은 인근 별까지의 거리를 놀라운 정밀도로 측정하기 위해 항성 시차를 사용한다." },
      { word: "redshift", pron: "/redʃɪft/", pos: "n.", meanings: ["적색편이"], example: "The redshift of distant galaxies provided early evidence that the universe is constantly expanding.", exampleKr: "멀리 있는 은하들의 적색편이는 우주가 끊임없이 팽창하고 있다는 초기 증거를 제공했다." },
      { word: "aphelion", pron: "/æphiːliən/", pos: "n.", meanings: ["원일점"], example: "Earth reaches its aphelion, the point farthest from the Sun, around the beginning of July each year.", exampleKr: "지구는 매년 7월 초에 태양에서 가장 멀리 떨어진 지점인 원일점에 도달한다." },
      { word: "perihelion", pron: "/perɪhiːliən/", pos: "n.", meanings: ["근일점"], example: "At perihelion, Earth is about 147 million kilometres from the Sun, slightly closer than its annual average.", exampleKr: "근일점에서 지구는 태양과 약 1억 4700만 킬로미터 떨어져 있어 연평균보다 약간 더 가깝다." },
      { word: "solstice", pron: "/sɒlstɪs/", pos: "n.", meanings: ["지점", "하지 또는 동지"], example: "The summer solstice, with the longest day of the year, has been celebrated across many cultures throughout history.", exampleKr: "1년 중 낮이 가장 긴 하지는 역사를 통해 많은 문화에서 기념되어 왔다." },
      { word: "equinox", pron: "/iːkwɪnɒks/", pos: "n.", meanings: ["주야 평분시", "춘분 또는 추분"], example: "At the autumn equinox, day and night are of approximately equal length across the entire planet.", exampleKr: "추분이 되면 지구 전체에 걸쳐 낮과 밤의 길이가 거의 같아진다." },
      { word: "magnetosphere", pron: "/mæɡniːtəsfɪər/", pos: "n.", meanings: ["자기권"], example: "Earth's magnetosphere shields the surface from harmful solar wind particles and cosmic radiation.", exampleKr: "지구의 자기권은 지표면을 해로운 태양풍 입자와 우주 복사로부터 보호한다." },
      { word: "exoplanet", pron: "/eksəʊplænɪt/", pos: "n.", meanings: ["외계행성"], example: "Over five thousand exoplanets have been confirmed, and astronomers continue to discover hundreds more each year.", exampleKr: "5,000개 이상의 외계행성이 확인되었으며, 천문학자들은 매년 수백 개를 계속 발견하고 있다." },
      { word: "corona", pron: "/kəroʊnə/", pos: "n.", meanings: ["코로나", "태양 대기"], example: "The solar corona is only visible from Earth during a total solar eclipse, when the moon covers the sun.", exampleKr: "태양의 코로나는 달이 태양을 가리는 개기일식 동안에만 지구에서 볼 수 있다." },
      { word: "asteroid", pron: "/æstərɔɪd/", pos: "n.", meanings: ["소행성"], example: "Most asteroids orbit the Sun in the asteroid belt, a region located between Mars and Jupiter.", exampleKr: "대부분의 소행성은 화성과 목성 사이에 위치한 소행성대에서 태양을 공전한다." },
      { word: "cosmology", pron: "/kɒzmɒlədʒi/", pos: "n.", meanings: ["우주론"], example: "Modern cosmology has transformed our understanding of the universe's origin, large-scale structure, and eventual fate.", exampleKr: "현대 우주론은 우주의 기원, 대규모 구조, 궁극적인 운명에 대한 우리의 이해를 변화시켰다." },
      { word: "interstellar", pron: "/ɪntəstelər/", pos: "adj.", meanings: ["성간의", "별 사이의"], example: "The Voyager probe has entered interstellar space, making it the first human-made object beyond our solar system.", exampleKr: "보이저 탐사선은 태양계 밖의 최초 인공물이 되어 성간 우주에 진입했다." },
      { word: "dark matter", pron: "/dɑːrk mætər/", pos: "n.", meanings: ["암흑물질"], example: "Dark matter cannot be observed directly, but its existence is inferred from its gravitational effects on visible galaxies.", exampleKr: "암흑물질은 직접 관측할 수 없지만, 가시 은하에 미치는 중력 효과로 그 존재가 추론된다." },
      { word: "singularity", pron: "/sɪŋɡjʊlærɪti/", pos: "n.", meanings: ["특이점"], example: "At the singularity inside a black hole, the known laws of physics break down completely.", exampleKr: "블랙홀 내부의 특이점에서는 알려진 물리학 법칙이 완전히 무너진다." },
      { word: "light-year", pron: "/laɪt jɪər/", pos: "n.", meanings: ["광년"], example: "Proxima Centauri, the nearest star to our Sun, is approximately 4.24 light-years away.", exampleKr: "태양에 가장 가까운 별인 프록시마 켄타우리는 약 4.24광년 떨어져 있다." },
      { word: "accretion disk", pron: "/əkriːʃən dɪsk/", pos: "n.", meanings: ["강착 원반"], example: "The accretion disk surrounding the black hole glows intensely as infalling matter is heated to extreme temperatures.", exampleKr: "빨려 들어가는 물질이 극한 온도로 가열되면서 블랙홀을 둘러싼 강착 원반이 강렬하게 빛난다." }
    ]
  },
  113: {
    theme: "지리지질학 어휘",
    words: [
      { word: "tectonics", pron: "/tektɒnɪks/", pos: "n.", meanings: ["판 구조론", "지각 구조론"], example: "Plate tectonics explains many geological phenomena, from earthquakes to the formation of mountain ranges.", exampleKr: "판 구조론은 지진에서 산맥 형성에 이르기까지 많은 지질학적 현상을 설명한다." },
      { word: "stratum", pron: "/streɪtəm/", pos: "n.", meanings: ["지층", "층"], example: "Each stratum of rock preserves a record of the environmental conditions that existed when it was formed.", exampleKr: "각 지층은 형성될 당시 존재했던 환경 조건의 기록을 보존한다." },
      { word: "watershed", pron: "/wɔːtərʃed/", pos: "n.", meanings: ["분수령", "집수 지역"], example: "The Congo Basin forms the watershed for a vast network of rivers across central Africa.", exampleKr: "콩고 분지는 중앙 아프리카 전역의 광대한 강 네트워크의 분수령을 형성한다." },
      { word: "alluvial", pron: "/əluːviəl/", pos: "adj.", meanings: ["충적의", "퇴적토의"], example: "The fertile alluvial plains along the Nile have supported civilisation and agriculture for thousands of years.", exampleKr: "나일강을 따라 펼쳐진 비옥한 충적 평야는 수천 년 동안 문명과 농업을 지탱해 왔다." },
      { word: "archipelago", pron: "/ɑːrkɪpeləɡoʊ/", pos: "n.", meanings: ["군도", "제도"], example: "Indonesia is the world's largest archipelago, comprising more than seventeen thousand islands.", exampleKr: "인도네시아는 17,000개 이상의 섬으로 이루어진 세계에서 가장 큰 군도이다." },
      { word: "lithosphere", pron: "/lɪθəsfɪər/", pos: "n.", meanings: ["암석권", "지각"], example: "The lithosphere is the rigid outer shell of Earth, broken into tectonic plates that move gradually over time.", exampleKr: "암석권은 지구의 단단한 외각으로, 시간이 지남에 따라 서서히 이동하는 지각판으로 나뉘어져 있다." },
      { word: "subduction", pron: "/səbdʌkʃən/", pos: "n.", meanings: ["섭입", "지각 침강"], example: "Subduction zones, where one plate dives beneath another, are hotspots of volcanic and seismic activity.", exampleKr: "한 판이 다른 판 아래로 내려가는 섭입대는 화산 및 지진 활동의 온상이다." },
      { word: "topography", pron: "/təpɒɡrəfi/", pos: "n.", meanings: ["지형", "지형학"], example: "The complex topography of the Himalayas creates highly localised weather patterns and distinct microclimates.", exampleKr: "히말라야의 복잡한 지형은 매우 국지적인 기상 패턴과 뚜렷한 미기후를 만들어낸다." },
      { word: "sediment", pron: "/sedɪmənt/", pos: "n.", meanings: ["퇴적물", "침전물"], example: "River sediment carried downstream to a delta gradually builds up to form new land over centuries.", exampleKr: "삼각주로 하류로 운반된 강의 퇴적물은 수세기에 걸쳐 서서히 쌓여 새로운 육지를 형성한다." },
      { word: "cartography", pron: "/kɑːrtɒɡrəfi/", pos: "n.", meanings: ["지도학", "지도 제작"], example: "Cartography evolved from hand-drawn maps to digital satellite imaging and interactive global platforms.", exampleKr: "지도학은 손으로 그린 지도에서 디지털 위성 영상과 인터랙티브 글로벌 플랫폼으로 발전했다." },
      { word: "meridian", pron: "/mərɪdiən/", pos: "n.", meanings: ["경선", "자오선"], example: "The Prime Meridian, established at Greenwich, serves as the zero-degree reference for global longitude.", exampleKr: "그리니치에 설정된 본초 자오선은 전 세계 경도의 0도 기준으로 사용된다." },
      { word: "peninsula", pron: "/pənɪnsjʊlə/", pos: "n.", meanings: ["반도"], example: "The Korean Peninsula is divided at the 38th parallel, separating the two countries politically.", exampleKr: "한반도는 38선에서 두 나라를 정치적으로 분리하며 나뉘어져 있다." },
      { word: "fjord", pron: "/fjɔːrd/", pos: "n.", meanings: ["피오르드", "협만"], example: "Norway's dramatic fjords were carved by glaciers during the last ice age.", exampleKr: "노르웨이의 장엄한 피오르드는 마지막 빙하기에 빙하에 의해 형성되었다." },
      { word: "latitude", pron: "/lætɪtjuːd/", pos: "n.", meanings: ["위도", "위선"], example: "The tropical belt lies between 23.5 degrees north and south latitude, receiving intense solar radiation year-round.", exampleKr: "열대 지역은 북위 23.5도와 남위 23.5도 사이에 위치하며 연중 강렬한 태양 복사를 받는다." },
      { word: "tundra", pron: "/tʌndrə/", pos: "n.", meanings: ["툰드라", "동토대"], example: "The Arctic tundra is one of Earth's most fragile ecosystems, highly vulnerable to climate change.", exampleKr: "북극 툰드라는 기후 변화에 매우 취약한 지구상에서 가장 예민한 생태계 중 하나이다." },
      { word: "precipitation", pron: "/prɪsɪpɪteɪʃən/", pos: "n.", meanings: ["강수량", "강수"], example: "Annual precipitation in tropical rainforests often exceeds 2,500 millimetres, sustaining immense biodiversity.", exampleKr: "열대 우림의 연간 강수량은 종종 2,500밀리미터를 초과하여 엄청난 생물 다양성을 유지한다." },
      { word: "isthmus", pron: "/ɪsməs/", pos: "n.", meanings: ["지협", "좁은 육지"], example: "The Isthmus of Panama connects North and South America and separates the Pacific from the Atlantic Ocean.", exampleKr: "파나마 지협은 북아메리카와 남아메리카를 연결하고 태평양과 대서양을 분리한다." },
      { word: "glacier", pron: "/ɡleɪsiər/", pos: "n.", meanings: ["빙하"], example: "Mountain glaciers around the world are retreating at unprecedented rates due to global warming.", exampleKr: "지구 온난화로 인해 전 세계 산악 빙하가 전례 없는 속도로 후퇴하고 있다." },
      { word: "stalactite", pron: "/stæləktaɪt/", pos: "n.", meanings: ["종유석"], example: "Stalactites form over thousands of years as mineral-rich water slowly drips from cave ceilings.", exampleKr: "종유석은 광물이 풍부한 물이 동굴 천장에서 천천히 떨어지면서 수천 년에 걸쳐 형성된다." },
      { word: "epicentre", pron: "/epɪsentər/", pos: "n.", meanings: ["진앙", "진원지"], example: "The epicentre of the earthquake was located just off the coast, triggering an immediate tsunami warning.", exampleKr: "지진의 진앙은 해안 바로 앞바다에 위치하여 즉각적인 쓰나미 경보를 발령시켰다." }
    ]
  },
  114: {
    theme: "음악공연 예술",
    words: [
      { word: "symphony", pron: "/sɪmfəni/", pos: "n.", meanings: ["교향곡", "심포니"], example: "Beethoven composed his Ninth Symphony after becoming completely deaf, showing extraordinary creative determination.", exampleKr: "베토벤은 완전히 청각을 잃은 후 9번 교향곡을 작곡하여 비범한 창의적 의지를 보여주었다." },
      { word: "improvisation", pron: "/ɪmprɒvɪzeɪʃən/", pos: "n.", meanings: ["즉흥 연주", "즉흥 창작"], example: "Jazz improvisation requires musicians to create spontaneous melodies within a given harmonic structure.", exampleKr: "재즈 즉흥 연주는 음악가들이 주어진 화성 구조 안에서 자발적인 멜로디를 만들어내도록 요구한다." },
      { word: "dissonance", pron: "/dɪsənəns/", pos: "n.", meanings: ["불협화음", "불일치"], example: "Composers sometimes use dissonance deliberately to create tension that is later resolved by a harmonious ending.", exampleKr: "작곡가들은 때때로 나중에 조화로운 결말로 해소되는 긴장감을 만들기 위해 의도적으로 불협화음을 사용한다." },
      { word: "cadence", pron: "/keɪdəns/", pos: "n.", meanings: ["종지", "리듬감"], example: "The piece ended with a perfect cadence, providing a satisfying sense of harmonic resolution and closure.", exampleKr: "그 곡은 화성적 해결과 마무리의 만족스러운 감각을 제공하는 완전 종지로 끝났다." },
      { word: "timbre", pron: "/tæmbrə/", pos: "n.", meanings: ["음색", "음질"], example: "Each instrument has a distinctive timbre that allows listeners to identify it even within a large orchestra.", exampleKr: "각 악기는 청중이 대규모 오케스트라 안에서도 식별할 수 있는 독특한 음색을 가지고 있다." },
      { word: "choreography", pron: "/kɒriɒɡrəfi/", pos: "n.", meanings: ["안무", "안무법"], example: "The choreography blended classical ballet technique with contemporary movement to create a striking new performance style.", exampleKr: "안무는 고전 발레 기법과 현대적 움직임을 결합하여 놀라운 새로운 공연 스타일을 만들어냈다." },
      { word: "libretto", pron: "/lɪbretəʊ/", pos: "n.", meanings: ["대본", "오페라 각본"], example: "The libretto of the opera was originally written in Italian and later translated into many languages.", exampleKr: "오페라의 대본은 원래 이탈리아어로 쓰였다가 나중에 많은 언어로 번역되었다." },
      { word: "repertoire", pron: "/repətwɑːr/", pos: "n.", meanings: ["레퍼토리", "연주 목록"], example: "The pianist's extensive repertoire spans works from the Baroque era through to contemporary compositions.", exampleKr: "그 피아니스트의 광범위한 레퍼토리는 바로크 시대부터 현대 작품까지 아우른다." },
      { word: "virtuoso", pron: "/vɜːrtʃuoʊsoʊ/", pos: "n.", meanings: ["거장", "명연주자"], example: "The young violinist was hailed as a virtuoso after her dazzling debut performance at the age of sixteen.", exampleKr: "그 젊은 바이올리니스트는 16세에 화려한 데뷔 공연 후 거장으로 칭송받았다." },
      { word: "concerto", pron: "/kəntʃɜːrtəʊ/", pos: "n.", meanings: ["협주곡"], example: "Vivaldi composed over 500 concertos during his lifetime, most of them written for violin and small orchestra.", exampleKr: "비발디는 생애 동안 500개 이상의 협주곡을 작곡했으며, 대부분은 바이올린과 소규모 오케스트라를 위한 것이었다." },
      { word: "modulation", pron: "/mɒdjʊleɪʃən/", pos: "n.", meanings: ["전조", "조바꿈"], example: "The unexpected modulation to a distant key gave the final movement a deeply surprising emotional quality.", exampleKr: "먼 조성으로의 예기치 않은 전조는 마지막 악장에 깊이 놀라운 감정적 특성을 부여했다." },
      { word: "aria", pron: "/ɑːriə/", pos: "n.", meanings: ["아리아", "독창곡"], example: "The soprano delivered a flawless and emotionally powerful performance of the opera's most celebrated aria.", exampleKr: "소프라노는 오페라에서 가장 유명한 아리아를 흠 없이 감정적으로 강렬하게 연주했다." },
      { word: "percussion", pron: "/pəkʌʃən/", pos: "n.", meanings: ["타악기", "타악기 연주"], example: "West African music traditions place percussion instruments at the very heart of communal musical expression.", exampleKr: "서아프리카 음악 전통은 공동체 음악 표현의 핵심에 타악기를 놓는다." },
      { word: "overture", pron: "/oʊvərtʃər/", pos: "n.", meanings: ["서곡", "오버추어"], example: "The overture to the opera introduced all of the main musical themes before the curtain finally rose.", exampleKr: "오페라의 서곡은 막이 오르기 전에 모든 주요 음악 주제를 소개했다." },
      { word: "syncopation", pron: "/sɪŋkəpeɪʃən/", pos: "n.", meanings: ["당김음", "싱코페이션"], example: "African-American music traditions introduced syncopation into Western popular music, laying the foundations for jazz.", exampleKr: "아프리카계 미국인 음악 전통은 서양 대중 음악에 당김음을 도입하여 재즈의 기초를 마련했다." },
      { word: "harmonics", pron: "/hɑːrmɒnɪks/", pos: "n.", meanings: ["배음", "화음 이론"], example: "The distinctive bell-like tone is shaped by its rich harmonics, which give each instrument a unique character.", exampleKr: "종 모양의 독특한 음색은 각 악기에 고유한 특성을 부여하는 풍부한 배음에 의해 형성된다." },
      { word: "a cappella", pron: "/ɑː kəpelə/", pos: "adv./adj.", meanings: ["무반주의", "무반주로"], example: "The choir performed the national anthem a cappella, and their unaccompanied voices filled the entire stadium.", exampleKr: "합창단은 무반주로 국가를 공연했고, 그들의 반주 없는 목소리가 경기장 전체를 가득 채웠다." },
      { word: "staccato", pron: "/stəkɑːtəʊ/", pos: "adj./adv.", meanings: ["스타카토의", "끊어서"], example: "The composer marked the passage staccato, requiring each note to be played short, crisp, and clearly detached.", exampleKr: "작곡가는 그 구절을 스타카토로 표시하여 각 음을 짧고 선명하게 분리해서 연주하도록 요구했다." },
      { word: "legato", pron: "/lɪɡɑːtəʊ/", pos: "adj./adv.", meanings: ["레가토의", "부드럽게 이어서"], example: "The cellist played the slow movement in a deeply expressive and flowing legato style.", exampleKr: "첼리스트는 느린 악장을 매우 표현력 있고 흐르는 듯한 레가토 스타일로 연주했다." },
      { word: "diminuendo", pron: "/dɪmɪnjuendəʊ/", pos: "n./adv.", meanings: ["점점 여리게", "디미누엔도"], example: "The orchestra played an extended diminuendo as the final movement gradually faded into silence.", exampleKr: "오케스트라는 마지막 악장이 점차 침묵으로 사라지면서 긴 디미누엔도를 연주했다." }
    ]
  },
  115: {
    theme: "건축도시 설계",
    words: [
      { word: "facade", pron: "/fəsɑːd/", pos: "n.", meanings: ["건물 정면", "파사드"], example: "The historic facade of the building was carefully restored while the entire interior was modernised.", exampleKr: "건물의 역사적인 정면은 내부 전체가 현대화되는 동안 신중하게 복원되었다." },
      { word: "cantilever", pron: "/kæntɪliːvər/", pos: "n.", meanings: ["캔틸레버", "돌출보"], example: "Frank Lloyd Wright's Fallingwater is famous for its dramatic cantilever structure extending directly over a waterfall.", exampleKr: "프랭크 로이드 라이트의 낙수장은 폭포 바로 위로 뻗은 극적인 캔틸레버 구조로 유명하다." },
      { word: "atrium", pron: "/eɪtriəm/", pos: "n.", meanings: ["아트리움", "중앙 홀"], example: "The hotel's central atrium rises twenty storeys and is flooded with natural light through a vast glass roof.", exampleKr: "호텔의 중앙 아트리움은 광대한 유리 지붕을 통해 자연광이 넘쳐흐르며 20층까지 솟아 있다." },
      { word: "gentrification", pron: "/dʒentrɪfɪkeɪʃən/", pos: "n.", meanings: ["젠트리피케이션", "도심 고급화"], example: "Gentrification improved the neighbourhood's infrastructure but displaced many low-income families who could no longer afford rents.", exampleKr: "젠트리피케이션은 지역 기반 시설을 개선했지만 더 이상 임대료를 감당할 수 없는 많은 저소득 가정을 내쫓았다." },
      { word: "zoning", pron: "/zoʊnɪŋ/", pos: "n.", meanings: ["용도 지역제", "구역 지정"], example: "Strict zoning regulations prevent industrial development from encroaching on residential neighbourhoods.", exampleKr: "엄격한 용도 지역제 규정은 산업 개발이 주거 지역을 침범하는 것을 방지한다." },
      { word: "urban sprawl", pron: "/ɜːrbən sprɔːl/", pos: "n.", meanings: ["도시 확산", "무분별한 개발"], example: "Unchecked urban sprawl has consumed vast tracts of farmland, raising serious concerns about food security.", exampleKr: "통제되지 않은 도시 확산은 광대한 농지를 잠식하여 식량 안보에 대한 심각한 우려를 높이고 있다." },
      { word: "retrofit", pron: "/retrəʊfɪt/", pos: "v./n.", meanings: ["개조하다", "사후 설치"], example: "Many older buildings are being retrofitted with double glazing and insulation to improve their energy efficiency.", exampleKr: "많은 오래된 건물들이 에너지 효율을 높이기 위해 이중 창유리와 단열재로 개조되고 있다." },
      { word: "vernacular", pron: "/vərnækjʊlər/", pos: "adj./n.", meanings: ["토착의", "지역 고유 건축 양식"], example: "Vernacular architecture uses locally available materials and traditional methods adapted to the regional climate.", exampleKr: "토착 건축은 지역 기후에 맞게 조정된 현지에서 구할 수 있는 재료와 전통적인 방법을 사용한다." },
      { word: "mezzanine", pron: "/mezəniːn/", pos: "n.", meanings: ["중간층", "메자닌"], example: "The bookshop expanded its display space by adding a mezzanine level overlooking the main floor below.", exampleKr: "그 서점은 아래 주층을 내려다보는 메자닌 층을 추가하여 전시 공간을 확장했다." },
      { word: "renovation", pron: "/renəveɪʃən/", pos: "n.", meanings: ["보수", "개조"], example: "The renovation of the Victorian railway station preserved its architectural character while introducing modern facilities.", exampleKr: "빅토리아 시대 기차역의 보수는 현대 시설을 도입하면서 건축적 특성을 보존했다." },
      { word: "plinth", pron: "/plɪnθ/", pos: "n.", meanings: ["주춧돌", "기단"], example: "The commemorative statue was mounted on a granite plinth inscribed with the dedication.", exampleKr: "기념 동상은 헌정문이 새겨진 화강암 받침대 위에 세워졌다." },
      { word: "portico", pron: "/pɔːrtɪkoʊ/", pos: "n.", meanings: ["기둥 현관", "포르티코"], example: "The grand portico of the government building, with its marble columns, projects an unmistakable air of authority.", exampleKr: "대리석 기둥이 있는 정부 청사의 웅장한 기둥 현관은 뚜렷한 권위의 분위기를 자아낸다." },
      { word: "parapet", pron: "/pærəpɪt/", pos: "n.", meanings: ["흉벽", "난간"], example: "A low parapet ran along the edge of the flat roof, providing a safety barrier for maintenance workers.", exampleKr: "낮은 흉벽이 평평한 지붕 가장자리를 따라 이어져 유지 보수 작업자들을 위한 안전 장벽을 제공했다." },
      { word: "fenestration", pron: "/fenɪstreɪʃən/", pos: "n.", meanings: ["창문 배치", "개구부 설계"], example: "The fenestration was carefully designed to maximise natural daylight while minimising unwanted solar heat gain.", exampleKr: "창문 배치는 불필요한 태양열 획득을 최소화하면서 자연 채광을 극대화하도록 신중하게 설계되었다." },
      { word: "cornice", pron: "/kɔːrnɪs/", pos: "n.", meanings: ["처마 돌림띠", "코니스"], example: "The ornate cornice along the roofline is a hallmark of the building's classical architectural style.", exampleKr: "지붕선을 따라 이어진 화려한 코니스는 건물의 고전 건축 양식의 특징이다." },
      { word: "blueprint", pron: "/bluːprɪnt/", pos: "n.", meanings: ["청사진", "설계 도면"], example: "The architect presented detailed blueprints showing both structural elements and aesthetic details of the new building.", exampleKr: "건축가는 새 건물의 구조적 요소와 미적 세부사항을 보여주는 상세한 청사진을 제시했다." },
      { word: "load-bearing", pron: "/loʊd berɪŋ/", pos: "adj.", meanings: ["하중 지탱하는", "내력의"], example: "The original load-bearing walls could not be removed without seriously compromising the building's structural integrity.", exampleKr: "원래의 내력벽은 건물의 구조적 무결성을 심각하게 손상시키지 않고는 제거할 수 없었다." },
      { word: "infrastructure", pron: "/ɪnfrəstrʌktʃər/", pos: "n.", meanings: ["기반 시설", "인프라"], example: "Ageing infrastructure such as roads, bridges, and water mains requires significant investment to remain safe.", exampleKr: "도로, 교량, 수도관 등 노후화된 기반 시설은 안전을 유지하기 위해 상당한 투자가 필요하다." },
      { word: "pediment", pron: "/pedɪmənt/", pos: "n.", meanings: ["페디먼트", "삼각 박공"], example: "Greek temples typically featured a triangular pediment resting on top of the columns at each end.", exampleKr: "그리스 신전은 일반적으로 양 끝의 기둥 위에 삼각형 페디먼트가 얹혀 있는 형태를 특징으로 하였다." },
      { word: "pilaster", pron: "/pɪlæstər/", pos: "n.", meanings: ["벽 기둥", "필라스터"], example: "Shallow pilasters set into the wall gave the otherwise plain exterior a sense of classical order.", exampleKr: "벽에 박혀 있는 얕은 필라스터는 평범한 외관에 고전적인 질서감을 부여했다." }
    ]
  }
});
