/**
 * data_days_126_130.js - Day 126~130 단어 데이터
 * data_days_121_125.js 이후에 로드해야 합니다
 */
Object.assign(VOCA_DATA, {
  126: {
    theme: "에너지자원 어휘",
    words: [
      { word: "photovoltaic", pron: "/fəʊtəʊvɒlteɪɪk/", pos: "adj.", meanings: ["광전지의", "태양광 발전의"], example: "Photovoltaic panels convert sunlight directly into electricity and are now widely installed on rooftops worldwide.", exampleKr: "광전지 패널은 햇빛을 직접 전기로 변환하며 현재 전 세계 지붕에 널리 설치되고 있다." },
      { word: "turbine", pron: "/tɜːrbaɪn/", pos: "n.", meanings: ["터빈"], example: "Wind turbines generate electricity by harnessing the kinetic energy of moving air masses.", exampleKr: "풍력 터빈은 이동하는 공기 질량의 운동 에너지를 활용하여 전기를 생성한다." },
      { word: "geothermal", pron: "/dʒiːəʊθɜːrməl/", pos: "adj.", meanings: ["지열의"], example: "Iceland generates most of its electricity and heating from geothermal sources beneath the volcanic island.", exampleKr: "아이슬란드는 화산 섬 아래의 지열 자원으로부터 대부분의 전기와 난방을 생산한다." },
      { word: "nuclear fission", pron: "/njuːkliər fɪʃən/", pos: "n.", meanings: ["핵분열"], example: "Nuclear fission releases enormous energy by splitting heavy atomic nuclei such as uranium or plutonium.", exampleKr: "핵분열은 우라늄이나 플루토늄과 같은 무거운 원자핵을 분열시켜 엄청난 에너지를 방출한다." },
      { word: "nuclear fusion", pron: "/njuːkliər fjuːʒən/", pos: "n.", meanings: ["핵융합"], example: "Nuclear fusion, the process powering the sun, promises virtually limitless clean energy but remains technically challenging.", exampleKr: "태양에 동력을 공급하는 과정인 핵융합은 사실상 무한한 청정 에너지를 약속하지만 기술적으로 여전히 어렵다." },
      { word: "carbon capture", pron: "/kɑːrbən kæptʃər/", pos: "n.", meanings: ["탄소 포집", "탄소 격리"], example: "Carbon capture technology traps greenhouse gases at emission sources before they enter the atmosphere.", exampleKr: "탄소 포집 기술은 온실 기체가 대기에 들어가기 전에 배출원에서 포착한다." },
      { word: "grid", pron: "/ɡrɪd/", pos: "n.", meanings: ["전력망", "그리드"], example: "Integrating large amounts of solar and wind energy into the grid requires sophisticated storage and balancing systems.", exampleKr: "대량의 태양광과 풍력 에너지를 전력망에 통합하려면 정교한 저장 및 균형 조정 시스템이 필요하다." },
      { word: "fracking", pron: "/frækɪŋ/", pos: "n.", meanings: ["수압 파쇄", "프래킹"], example: "Fracking extracts oil and gas from shale rock by injecting high-pressure fluid underground.", exampleKr: "프래킹은 고압의 유체를 지하에 주입하여 셰일 암석에서 석유와 가스를 추출한다." },
      { word: "biofuel", pron: "/baɪəʊfjuːəl/", pos: "n.", meanings: ["바이오 연료"], example: "Biofuels derived from plant materials offer a renewable alternative to petroleum-based transportation fuels.", exampleKr: "식물성 재료에서 생산된 바이오 연료는 석유 기반 교통 연료에 대한 재생 가능한 대안을 제공한다." },
      { word: "hydropower", pron: "/haɪdrəpaʊər/", pos: "n.", meanings: ["수력 발전"], example: "Hydropower accounts for the largest share of renewable electricity generation globally, using controlled water flow.", exampleKr: "수력 발전은 통제된 수류를 이용하여 전 세계 재생 가능 발전에서 가장 큰 비중을 차지한다." },
      { word: "depletion", pron: "/dɪpliːʃən/", pos: "n.", meanings: ["고갈", "감소"], example: "The depletion of the ozone layer, caused by chlorofluorocarbons, led to the Montreal Protocol in 1987.", exampleKr: "염화불화탄소에 의한 오존층 고갈은 1987년 몬트리올 의정서로 이어졌다." },
      { word: "refinery", pron: "/rɪfaɪnəri/", pos: "n.", meanings: ["정유소", "정제소"], example: "Oil refineries process crude petroleum into usable products such as petrol, diesel, and jet fuel.", exampleKr: "정유소는 원유를 휘발유, 디젤, 제트 연료와 같은 사용 가능한 제품으로 가공한다." },
      { word: "energy efficiency", pron: "/enədʒi ɪfɪʃənsi/", pos: "n.", meanings: ["에너지 효율성", "에너지 효율"], example: "Improving the energy efficiency of buildings is one of the cheapest ways to reduce carbon emissions.", exampleKr: "건물의 에너지 효율성을 향상시키는 것은 탄소 배출량을 줄이는 가장 저렴한 방법 중 하나이다." },
      { word: "offshore drilling", pron: "/ɒfʃɔːr drɪlɪŋ/", pos: "n.", meanings: ["해저 굴착", "해양 시추"], example: "Offshore drilling platforms extract oil and gas from beneath the sea floor in deep water locations.", exampleKr: "해저 굴착 플랫폼은 심해 위치에서 해저 아래로부터 석유와 가스를 추출한다." },
      { word: "fossil fuel", pron: "/fɒsəl fjuːəl/", pos: "n.", meanings: ["화석 연료"], example: "The burning of fossil fuels is the primary driver of the greenhouse gas emissions causing climate change.", exampleKr: "화석 연료의 연소는 기후 변화를 일으키는 온실 가스 배출의 주요 원인이다." },
      { word: "smart grid", pron: "/smɑːrt ɡrɪd/", pos: "n.", meanings: ["스마트 그리드"], example: "A smart grid uses digital technology to monitor and optimise the distribution of electricity across the network.", exampleKr: "스마트 그리드는 디지털 기술을 사용하여 네트워크 전반의 전기 배분을 모니터링하고 최적화한다." },
      { word: "peak demand", pron: "/piːk dɪmɑːnd/", pos: "n.", meanings: ["최대 수요", "피크 수요"], example: "Grid operators must have sufficient generating capacity to meet peak demand on the hottest or coldest days of the year.", exampleKr: "전력망 운영자는 연중 가장 덥거나 추운 날의 최대 수요를 충족시킬 충분한 발전 용량을 갖춰야 한다." },
      { word: "energy storage", pron: "/enədʒi stɔːrɪdʒ/", pos: "n.", meanings: ["에너지 저장"], example: "Large-scale battery energy storage is essential for balancing intermittent supply from renewable sources.", exampleKr: "대규모 배터리 에너지 저장은 재생 가능 자원의 간헐적 공급을 균형 잡는 데 필수적이다." },
      { word: "carbon neutral", pron: "/kɑːrbən njuːtrəl/", pos: "adj.", meanings: ["탄소 중립의"], example: "Many countries have pledged to become carbon neutral by 2050 in response to international climate agreements.", exampleKr: "많은 국가들이 국제 기후 협정에 따라 2050년까지 탄소 중립을 달성하기로 약속했다." },
      { word: "liquefied natural gas", pron: "/lɪkwɪfaɪd nætʃərəl ɡæs/", pos: "n.", meanings: ["액화 천연 가스", "LNG"], example: "Liquefied natural gas is cooled to minus 162 degrees Celsius to reduce its volume for efficient transport.", exampleKr: "액화 천연 가스는 효율적인 운반을 위해 부피를 줄이고자 섭씨 영하 162도까지 냉각된다." }
    ]
  },
  127: {
    theme: "국제관계외교 II",
    words: [
      { word: "multilateralism", pron: "/mʌltilætərəlɪzəm/", pos: "n.", meanings: ["다자주의"], example: "Multilateralism, involving cooperation among many nations, is seen as essential for tackling global challenges.", exampleKr: "많은 나라들의 협력을 포함하는 다자주의는 전 세계적인 도전을 해결하는 데 필수적인 것으로 여겨진다." },
      { word: "sovereignty", pron: "/sɒvrɪnti/", pos: "n.", meanings: ["주권", "자주권"], example: "The principle of national sovereignty holds that each state has the right to govern itself without outside interference.", exampleKr: "국가 주권의 원칙은 각 국가가 외부 간섭 없이 자체적으로 통치할 권리가 있다는 것을 말한다." },
      { word: "sanction", pron: "/sæŋkʃən/", pos: "n./v.", meanings: ["제재", "허가하다"], example: "Economic sanctions targeting key industries are used to pressure governments without resorting to military force.", exampleKr: "핵심 산업을 겨냥한 경제 제재는 군사력에 의존하지 않고 정부에 압력을 가하는 데 사용된다." },
      { word: "treaty", pron: "/triːti/", pos: "n.", meanings: ["조약", "협정"], example: "The Treaty of Paris formally ended the American Revolutionary War and recognised the independence of the United States.", exampleKr: "파리 조약은 미국 독립 전쟁을 공식적으로 종결하고 미국의 독립을 인정했다." },
      { word: "diplomacy", pron: "/dɪpləʊməsi/", pos: "n.", meanings: ["외교", "외교술"], example: "Skilled diplomacy resolved the dispute peacefully, avoiding confrontation between the two neighbouring nations.", exampleKr: "숙련된 외교는 두 인접 국가 간의 대결을 피하며 분쟁을 평화적으로 해결했다." },
      { word: "deterrence", pron: "/dɪterəns/", pos: "n.", meanings: ["억제력", "억지"], example: "Nuclear deterrence rests on the assumption that the threat of overwhelming retaliation will prevent attack.", exampleKr: "핵 억제력은 압도적인 보복의 위협이 공격을 방지할 것이라는 가정에 기반한다." },
      { word: "ratification", pron: "/rætɪfɪkeɪʃən/", pos: "n.", meanings: ["비준", "승인"], example: "Ratification by two-thirds of the Senate is required before a treaty becomes binding law in the United States.", exampleKr: "미국에서 조약이 구속력 있는 법률이 되기 전에 상원의 3분의 2의 비준이 필요하다." },
      { word: "ceasefire", pron: "/siːsfaɪər/", pos: "n.", meanings: ["휴전", "정전"], example: "Both sides agreed to an immediate ceasefire to allow humanitarian aid to reach civilians trapped in the conflict zone.", exampleKr: "양측은 분쟁 지역에 갇힌 민간인들에게 인도주의적 원조가 도달할 수 있도록 즉각적인 휴전에 합의했다." },
      { word: "veto", pron: "/viːtəʊ/", pos: "n./v.", meanings: ["거부권", "거부하다"], example: "The five permanent members of the UN Security Council each hold a veto over its binding resolutions.", exampleKr: "유엔 안보리의 5개 상임이사국은 각각 안보리의 구속력 있는 결의에 대한 거부권을 가지고 있다." },
      { word: "annexation", pron: "/ænekseɪʃən/", pos: "n.", meanings: ["합병", "병합"], example: "The annexation of territory by force is prohibited under the Charter of the United Nations.", exampleKr: "무력에 의한 영토 합병은 유엔 헌장에 따라 금지되어 있다." },
      { word: "non-proliferation", pron: "/nɒn prəlɪfəreɪʃən/", pos: "n.", meanings: ["비확산"], example: "The Nuclear Non-Proliferation Treaty aims to prevent the spread of nuclear weapons to additional states.", exampleKr: "핵비확산조약(NPT)은 핵무기가 추가 국가들로 확산되는 것을 방지하는 것을 목표로 한다." },
      { word: "hegemony", pron: "/hɪdʒemənɪ/", pos: "n.", meanings: ["패권", "주도권"], example: "Critics argue that US hegemony in global affairs has shaped international institutions in its own interests.", exampleKr: "비판론자들은 국제 문제에서 미국의 패권이 자국의 이익에 맞게 국제 제도를 형성해 왔다고 주장한다." },
      { word: "bilateral", pron: "/baɪlætərəl/", pos: "adj.", meanings: ["양자의", "양국 간의"], example: "The two countries signed a bilateral trade agreement that eliminated tariffs on a wide range of goods.", exampleKr: "두 나라는 광범위한 상품에 대한 관세를 철폐하는 양자 무역 협정에 서명했다." },
      { word: "espionage", pron: "/espiənɑːʒ/", pos: "n.", meanings: ["스파이 활동", "첩보"], example: "Industrial espionage involves stealing proprietary information from companies to gain a competitive advantage.", exampleKr: "산업 스파이 활동은 경쟁 우위를 얻기 위해 기업으로부터 독점 정보를 훔치는 것을 포함한다." },
      { word: "summit", pron: "/sʌmɪt/", pos: "n.", meanings: ["정상회담", "정상"], example: "The G7 summit brought together leaders of the world's major economies to discuss pressing global challenges.", exampleKr: "G7 정상회담은 시급한 전 세계적 도전을 논의하기 위해 세계 주요 경제국의 지도자들을 모았다." },
      { word: "humanitarian aid", pron: "/hjuːmænɪteəriən eɪd/", pos: "n.", meanings: ["인도주의적 원조"], example: "International organisations delivered humanitarian aid including food, medicine, and clean water to displaced populations.", exampleKr: "국제 기구들은 실향 주민들에게 식량, 의약품, 깨끗한 물을 포함한 인도주의적 원조를 제공했다." },
      { word: "refugee", pron: "/refjʊdʒiː/", pos: "n.", meanings: ["난민"], example: "Under international law, refugees are entitled to protection from deportation to countries where they face persecution.", exampleKr: "국제법에 따라 난민은 박해를 받을 위험이 있는 나라로의 추방으로부터 보호를 받을 권리가 있다." },
      { word: "reparations", pron: "/repəreɪʃənz/", pos: "n.", meanings: ["배상금", "보상"], example: "Reparations paid by Germany after World War One were so severe that they contributed to economic collapse.", exampleKr: "1차 세계대전 후 독일이 지불한 배상금은 너무 가혹하여 경제 붕괴에 기여했다." },
      { word: "coalition", pron: "/kəʊəlɪʃən/", pos: "n.", meanings: ["연합", "연립"], example: "A broad international coalition was assembled to respond to the humanitarian crisis in the region.", exampleKr: "그 지역의 인도주의적 위기에 대응하기 위해 광범위한 국제 연합이 구성되었다." },
      { word: "extraterritorial", pron: "/ekstrəterɪtɔːriəl/", pos: "adj.", meanings: ["치외법권의", "역외의"], example: "Extraterritorial jurisdiction allows some countries to prosecute their citizens for crimes committed abroad.", exampleKr: "치외법권 관할권은 일부 국가들이 자국 시민이 해외에서 저지른 범죄에 대해 기소할 수 있게 한다." }
    ]
  },
  128: {
    theme: "교육학습 이론",
    words: [
      { word: "pedagogy", pron: "/pedəɡɒdʒi/", pos: "n.", meanings: ["교육학", "교수법"], example: "Effective pedagogy considers how students learn best and adapts teaching methods to diverse learner needs.", exampleKr: "효과적인 교육학은 학생들이 가장 잘 배우는 방법을 고려하고 다양한 학습자의 필요에 교수법을 적응시킨다." },
      { word: "curriculum", pron: "/kərɪkjʊləm/", pos: "n.", meanings: ["교육과정", "커리큘럼"], example: "The national curriculum sets out what students should learn at each stage of their compulsory education.", exampleKr: "국가 교육과정은 학생들이 의무 교육의 각 단계에서 무엇을 배워야 하는지를 설명한다." },
      { word: "metacognition", pron: "/metəkɒɡnɪʃən/", pos: "n.", meanings: ["초인지", "메타인지"], example: "Metacognition, thinking about one's own thinking, is strongly linked to academic achievement and self-regulation.", exampleKr: "자신의 사고에 대해 생각하는 메타인지는 학업 성취 및 자기 조절과 강하게 연결되어 있다." },
      { word: "scaffolding", pron: "/skæfəldɪŋ/", pos: "n.", meanings: ["비계 교수법", "지원 구조"], example: "In scaffolding, teachers provide structured support that is gradually removed as learners develop independence.", exampleKr: "비계 교수법에서 교사는 학습자가 독립성을 개발함에 따라 점차 제거되는 구조적 지원을 제공한다." },
      { word: "constructivism", pron: "/kənstrʌktɪvɪzəm/", pos: "n.", meanings: ["구성주의"], example: "Constructivism holds that learners actively build knowledge through experience rather than passively receiving information.", exampleKr: "구성주의는 학습자가 정보를 수동적으로 받는 것이 아니라 경험을 통해 능동적으로 지식을 구축한다고 주장한다." },
      { word: "formative assessment", pron: "/fɔːrmətɪv əsesmənt/", pos: "n.", meanings: ["형성평가"], example: "Formative assessment provides ongoing feedback during learning, helping students identify gaps and improve continuously.", exampleKr: "형성평가는 학습 중에 지속적인 피드백을 제공하여 학생들이 부족한 부분을 파악하고 지속적으로 개선하도록 돕는다." },
      { word: "summative assessment", pron: "/sʌmətɪv əsesmənt/", pos: "n.", meanings: ["총괄평가"], example: "Summative assessment evaluates student learning at the end of an instructional period through tests or examinations.", exampleKr: "총괄평가는 시험이나 고사를 통해 교수 기간 말에 학생의 학습 성과를 평가한다." },
      { word: "differentiated instruction", pron: "/dɪfərenʃieɪtɪd ɪnstrʌkʃən/", pos: "n.", meanings: ["차별화 교수법", "맞춤 교수법"], example: "Differentiated instruction tailors teaching content, process, and assessment to match individual student readiness and interests.", exampleKr: "차별화 교수법은 개별 학생의 준비도와 관심사에 맞게 교수 내용, 과정, 평가를 조정한다." },
      { word: "inquiry-based learning", pron: "/ɪnkwaɪəri beɪst lɜːrnɪŋ/", pos: "n.", meanings: ["탐구 기반 학습"], example: "Inquiry-based learning encourages students to pose questions, investigate problems, and construct their own understanding.", exampleKr: "탐구 기반 학습은 학생들이 질문을 제기하고, 문제를 조사하며, 자신만의 이해를 구성하도록 장려한다." },
      { word: "flipped classroom", pron: "/flɪpt klɑːsruːm/", pos: "n.", meanings: ["플립드 클래스룸", "역전 학습"], example: "In a flipped classroom, students watch instructional videos at home and use class time for practice and discussion.", exampleKr: "플립드 클래스룸에서 학생들은 집에서 강의 동영상을 시청하고 수업 시간에 연습과 토론에 활용한다." },
      { word: "intrinsic motivation", pron: "/ɪntrɪnzɪk məʊtɪveɪʃən/", pos: "n.", meanings: ["내재적 동기"], example: "Intrinsic motivation, driven by love of learning rather than external rewards, leads to deeper and more lasting knowledge.", exampleKr: "외부 보상이 아닌 학습에 대한 사랑에 의한 내재적 동기는 더 깊고 오래 지속되는 지식으로 이어진다." },
      { word: "extrinsic motivation", pron: "/ɪkstrɪnzɪk məʊtɪveɪʃən/", pos: "n.", meanings: ["외재적 동기"], example: "While extrinsic motivation like grades or prizes can be effective short-term, it rarely sustains long-term engagement.", exampleKr: "성적이나 상품과 같은 외재적 동기는 단기적으로 효과적일 수 있지만 장기적인 참여를 지속시키는 경우는 드물다." },
      { word: "syllabus", pron: "/sɪləbəs/", pos: "n.", meanings: ["강의 계획서", "학습 요목"], example: "The syllabus outlines the topics, assessment methods, and learning outcomes for a course or module.", exampleKr: "강의 계획서는 과목이나 모듈의 주제, 평가 방법, 학습 성과를 개략적으로 설명한다." },
      { word: "literacy", pron: "/lɪtərəsi/", pos: "n.", meanings: ["문해력", "리터러시"], example: "Strong literacy skills are foundational not just for academic success but for participation in modern society.", exampleKr: "강한 문해력은 학업 성취뿐만 아니라 현대 사회 참여의 기초가 된다." },
      { word: "numeracy", pron: "/njuːmərəsi/", pos: "n.", meanings: ["수리력", "수 감각"], example: "Good numeracy skills enable people to manage finances, interpret statistics, and make informed decisions in daily life.", exampleKr: "좋은 수리력은 사람들이 일상생활에서 재정을 관리하고 통계를 해석하며 정보에 기반한 결정을 내릴 수 있게 한다." },
      { word: "critical thinking", pron: "/krɪtɪkəl θɪŋkɪŋ/", pos: "n.", meanings: ["비판적 사고"], example: "Critical thinking involves analysing arguments, evaluating evidence, and resisting the influence of cognitive biases.", exampleKr: "비판적 사고는 논점 분석, 증거 평가, 인지 편향의 영향에 저항하는 것을 포함한다." },
      { word: "rubric", pron: "/ruːbrɪk/", pos: "n.", meanings: ["채점 기준표", "루브릭"], example: "Teachers use a rubric to ensure that student work is assessed consistently against clearly defined criteria.", exampleKr: "교사들은 명확하게 정의된 기준에 대해 학생 작업이 일관되게 평가되도록 채점 기준표를 사용한다." },
      { word: "accreditation", pron: "/əkredɪteɪʃən/", pos: "n.", meanings: ["인가", "인증"], example: "Accreditation by a recognised body confirms that an institution meets established standards of educational quality.", exampleKr: "공인된 기관의 인가는 교육 기관이 확립된 교육 품질 기준을 충족한다는 것을 확인한다." },
      { word: "blended learning", pron: "/blendɪd lɜːrnɪŋ/", pos: "n.", meanings: ["혼합 학습", "블렌디드 러닝"], example: "Blended learning combines traditional face-to-face teaching with online digital resources for a more flexible experience.", exampleKr: "혼합 학습은 더 유연한 경험을 위해 전통적인 면대면 교육과 온라인 디지털 자원을 결합한다." },
      { word: "Bloom's taxonomy", pron: "/bluːmz tæksɒnəmi/", pos: "n.", meanings: ["블룸의 분류 체계"], example: "Bloom's taxonomy classifies learning objectives from basic recall up to high-order skills like synthesis and evaluation.", exampleKr: "블룸의 분류 체계는 기본 기억부터 종합과 평가 같은 고차원적 기술까지 학습 목표를 분류한다." }
    ]
  },
  129: {
    theme: "심리학 심화",
    words: [
      { word: "unconscious", pron: "/ʌnkɒnʃəs/", pos: "adj./n.", meanings: ["무의식적인", "무의식"], example: "Freud proposed that unconscious desires and conflicts drive much of human behaviour without our awareness.", exampleKr: "프로이트는 무의식적 욕망과 갈등이 우리의 인식 없이 인간 행동의 많은 부분을 이끈다고 제안했다." },
      { word: "cognitive dissonance", pron: "/kɒɡnɪtɪv dɪsənəns/", pos: "n.", meanings: ["인지 부조화"], example: "Cognitive dissonance occurs when a person holds contradictory beliefs and experiences discomfort as a result.", exampleKr: "인지 부조화는 사람이 모순된 믿음을 가지고 그 결과로 불편함을 경험할 때 발생한다." },
      { word: "attribution", pron: "/ætrɪbjuːʃən/", pos: "n.", meanings: ["귀인", "귀속"], example: "Attribution Theory examines how people explain the causes of events in their own and others' lives.", exampleKr: "귀인 이론은 사람들이 자신과 타인의 삶에서 사건의 원인을 어떻게 설명하는지를 조사한다." },
      { word: "conditioning", pron: "/kəndɪʃənɪŋ/", pos: "n.", meanings: ["조건화", "조건 형성"], example: "Classical conditioning associates a neutral stimulus with a meaningful one, producing a learnt response.", exampleKr: "고전적 조건화는 중립적인 자극을 의미 있는 자극과 연합시켜 학습된 반응을 유발한다." },
      { word: "habituation", pron: "/həbɪtʃʊeɪʃən/", pos: "n.", meanings: ["습관화", "둔감화"], example: "Habituation explains why we stop noticing a constant background noise after a relatively short period of exposure.", exampleKr: "습관화는 우리가 비교적 짧은 노출 기간 후에 지속적인 배경 소음을 더 이상 인식하지 못하는 이유를 설명한다." },
      { word: "narcissism", pron: "/nɑːrsɪsɪzəm/", pos: "n.", meanings: ["자기애", "나르시시즘"], example: "Clinical narcissism involves an inflated sense of self-importance, a lack of empathy, and a need for admiration.", exampleKr: "임상적 자기애는 과장된 자기 중요성, 공감 결여, 칭찬에 대한 욕구를 포함한다." },
      { word: "empathy", pron: "/empəθi/", pos: "n.", meanings: ["공감", "감정이입"], example: "Empathy enables individuals to understand and share the feelings of another, fostering meaningful social connection.", exampleKr: "공감은 개인이 다른 사람의 감정을 이해하고 공유할 수 있게 하여 의미 있는 사회적 연결을 촉진한다." },
      { word: "conformity", pron: "/kənfɔːrmɪti/", pos: "n.", meanings: ["동조", "순응"], example: "Solomon Asch's conformity experiments revealed the powerful pressure people feel to agree with group consensus.", exampleKr: "솔로몬 아쉬의 동조 실험은 사람들이 집단 합의에 동의해야 한다는 강력한 압박을 느낀다는 것을 드러냈다." },
      { word: "cognitive bias", pron: "/kɒɡnɪtɪv baɪəs/", pos: "n.", meanings: ["인지 편향"], example: "Confirmation bias, a common cognitive bias, leads people to seek information that confirms their existing beliefs.", exampleKr: "일반적인 인지 편향인 확증 편향은 사람들이 기존 믿음을 확인하는 정보를 찾도록 이끈다." },
      { word: "transference", pron: "/trænsfrəns/", pos: "n.", meanings: ["전이", "감정 전이"], example: "In psychotherapy, transference occurs when a patient redirects feelings about someone else onto the therapist.", exampleKr: "심리치료에서 전이는 환자가 다른 사람에 대한 감정을 치료사에게 돌릴 때 발생한다." },
      { word: "repression", pron: "/rɪpreʃən/", pos: "n.", meanings: ["억압", "억제"], example: "Freud believed repression pushes unwanted thoughts and memories into the unconscious mind to avoid conscious pain.", exampleKr: "프로이트는 억압이 의식적 고통을 피하기 위해 원하지 않는 생각과 기억을 무의식 속으로 밀어 넣는다고 믿었다." },
      { word: "self-efficacy", pron: "/self efɪkəsi/", pos: "n.", meanings: ["자기효능감"], example: "High self-efficacy, belief in one's own ability to succeed, is strongly associated with motivation and achievement.", exampleKr: "성공할 수 있는 자신의 능력에 대한 믿음인 높은 자기효능감은 동기 부여 및 성취와 강하게 연관되어 있다." },
      { word: "locus of control", pron: "/ləʊkəs əv kəntrəʊl/", pos: "n.", meanings: ["통제 소재", "통제의 귀인"], example: "Those with an internal locus of control believe their actions determine outcomes, leading to greater persistence.", exampleKr: "내적 통제 소재를 가진 사람들은 자신의 행동이 결과를 결정한다고 믿어 더 큰 인내로 이어진다." },
      { word: "neuroplasticity", pron: "/njʊərəʊplæstɪsɪti/", pos: "n.", meanings: ["신경가소성"], example: "Neuroplasticity, the brain's ability to reorganise itself, underlies learning, memory, and recovery from brain injury.", exampleKr: "신경가소성, 즉 뇌가 자신을 재구성하는 능력은 학습, 기억, 뇌 손상으로부터의 회복의 기초가 된다." },
      { word: "introspection", pron: "/ɪntrəspekʃən/", pos: "n.", meanings: ["내성", "자기 성찰"], example: "Introspection involves examining one's own thoughts and feelings, though its reliability as a research method is debated.", exampleKr: "내성은 자신의 생각과 감정을 검토하는 것을 포함하지만, 연구 방법으로서의 신뢰성은 논의 중이다." },
      { word: "psychopathology", pron: "/saɪkəʊpəθɒlədʒi/", pos: "n.", meanings: ["정신병리학"], example: "Psychopathology studies the causes, development, and symptoms of mental disorders across the lifespan.", exampleKr: "정신병리학은 생애 전반에 걸쳐 정신 질환의 원인, 발전, 증상을 연구한다." },
      { word: "mindfulness", pron: "/maɪndfʊlnɪs/", pos: "n.", meanings: ["마음챙김"], example: "Mindfulness practice trains attention to the present moment, reducing anxiety and improving emotional regulation.", exampleKr: "마음챙김 수련은 현재 순간에 집중하도록 훈련하여 불안을 줄이고 감정 조절을 개선한다." },
      { word: "desensitisation", pron: "/diːsensɪtɪzeɪʃən/", pos: "n.", meanings: ["둔감화", "감각 둔화"], example: "Systematic desensitisation gradually exposes phobia sufferers to feared stimuli to reduce their anxiety response.", exampleKr: "체계적 둔감화는 공포증 환자를 두려운 자극에 점차적으로 노출시켜 불안 반응을 줄인다." },
      { word: "attachment theory", pron: "/ətætʃmənt θɪəri/", pos: "n.", meanings: ["애착 이론"], example: "Attachment theory describes how the quality of early bonds between infants and caregivers shapes later relationships.", exampleKr: "애착 이론은 영아와 양육자 사이의 초기 유대 관계의 질이 어떻게 이후의 관계를 형성하는지 설명한다." },
      { word: "placebo effect", pron: "/pləsiːbəʊ ɪfekt/", pos: "n.", meanings: ["위약 효과", "플라시보 효과"], example: "The placebo effect demonstrates that expectation and belief can produce measurable improvements in health outcomes.", exampleKr: "위약 효과는 기대와 믿음이 건강 결과에서 측정 가능한 개선을 유발할 수 있다는 것을 보여준다." }
    ]
  },
  130: {
    theme: "사회복지NGO 어휘",
    words: [
      { word: "philanthropy", pron: "/fɪlænθrəpi/", pos: "n.", meanings: ["자선", "박애주의"], example: "Corporate philanthropy can fund vital research, arts programmes, and community projects that governments cannot support.", exampleKr: "기업 자선 활동은 정부가 지원할 수 없는 중요한 연구, 예술 프로그램, 지역사회 프로젝트에 자금을 지원할 수 있다." },
      { word: "advocacy", pron: "/ædvəkəsi/", pos: "n.", meanings: ["옹호", "지지 활동"], example: "Advocacy campaigns by NGOs helped change public policy on child labour in dozens of countries.", exampleKr: "NGO의 옹호 캠페인은 수십 개 국가에서 아동 노동에 대한 공공 정책을 변화시키는 데 도움이 되었다." },
      { word: "beneficiary", pron: "/benɪfɪʃəri/", pos: "n.", meanings: ["수혜자", "수익자"], example: "The project identified the most vulnerable households as primary beneficiaries of the food distribution programme.", exampleKr: "프로젝트는 식품 분배 프로그램의 주요 수혜자로 가장 취약한 가구를 식별했다." },
      { word: "grant", pron: "/ɡrɑːnt/", pos: "n./v.", meanings: ["보조금", "지원하다"], example: "The foundation awarded a substantial grant to fund three years of research into childhood poverty.", exampleKr: "재단은 아동 빈곤 연구 3년을 지원하기 위해 상당한 보조금을 수여했다." },
      { word: "stakeholder", pron: "/steɪkhəʊldər/", pos: "n.", meanings: ["이해관계자"], example: "Involving all key stakeholders in the planning process ensures that diverse perspectives shape the final outcome.", exampleKr: "계획 과정에 모든 주요 이해관계자를 참여시키면 다양한 관점이 최종 결과를 형성하게 된다." },
      { word: "welfare", pron: "/welfeər/", pos: "n.", meanings: ["복지", "후생"], example: "The welfare state provides a safety net that protects citizens from extreme poverty and social exclusion.", exampleKr: "복지 국가는 시민들을 극빈층과 사회적 배제로부터 보호하는 안전망을 제공한다." },
      { word: "grassroots", pron: "/ɡrɑːsruːts/", pos: "adj./n.", meanings: ["풀뿌리의", "대중 기반의"], example: "The grassroots campaign mobilised thousands of ordinary citizens to demand action on housing affordability.", exampleKr: "풀뿌리 캠페인은 주거 경제성에 대한 조치를 요구하기 위해 수천 명의 일반 시민을 동원했다." },
      { word: "empowerment", pron: "/ɪmpaʊərmənt/", pos: "n.", meanings: ["역량 강화", "권한 부여"], example: "Economic empowerment programmes give women the financial independence to make decisions for themselves and their families.", exampleKr: "경제적 역량 강화 프로그램은 여성에게 자신과 가족을 위한 결정을 내릴 재정적 독립성을 제공한다." },
      { word: "social capital", pron: "/səʊʃəl kæpɪtəl/", pos: "n.", meanings: ["사회 자본"], example: "Communities with high social capital, characterised by trust and cooperation, tend to be more resilient in crises.", exampleKr: "신뢰와 협력으로 특징지어지는 높은 사회 자본을 가진 지역사회는 위기 시에 더 탄력적인 경향이 있다." },
      { word: "inclusion", pron: "/ɪnkluːʒən/", pos: "n.", meanings: ["포용", "포함"], example: "Social inclusion ensures that all groups, regardless of ability or background, can participate fully in society.", exampleKr: "사회적 포용은 능력이나 배경에 관계없이 모든 집단이 사회에 완전히 참여할 수 있도록 보장한다." },
      { word: "marginalised", pron: "/mɑːrdʒɪnəlaɪzd/", pos: "adj.", meanings: ["소외된", "주변화된"], example: "Marginalised communities often lack access to quality healthcare, education, and economic opportunities.", exampleKr: "소외된 지역사회는 종종 양질의 의료, 교육, 경제적 기회에 대한 접근이 부족하다." },
      { word: "humanitarian", pron: "/hjuːmænɪteəriən/", pos: "adj./n.", meanings: ["인도주의의", "인도주의자"], example: "Humanitarian organisations operate in conflict zones to provide life-saving assistance to affected populations.", exampleKr: "인도주의 기관들은 영향을 받은 주민들에게 생명을 구하는 지원을 제공하기 위해 분쟁 지역에서 활동한다." },
      { word: "capacity building", pron: "/kəpæsɪti bɪldɪŋ/", pos: "n.", meanings: ["역량 강화", "능력 개발"], example: "Capacity building programmes train local staff so that communities can sustain development projects independently.", exampleKr: "역량 강화 프로그램은 지역 사회가 개발 프로젝트를 독립적으로 지속할 수 있도록 지역 직원을 훈련시킨다." },
      { word: "transparency", pron: "/trænspærənsi/", pos: "n.", meanings: ["투명성"], example: "Financial transparency is essential for maintaining donor trust and ensuring that funds reach intended recipients.", exampleKr: "재정 투명성은 기부자의 신뢰를 유지하고 자금이 의도한 수령자에게 도달하도록 보장하는 데 필수적이다." },
      { word: "accountability", pron: "/əkaʊntəbɪlɪti/", pos: "n.", meanings: ["책임성", "책무"], example: "Accountability mechanisms ensure that organisations and officials can be held responsible for their decisions and actions.", exampleKr: "책임성 메커니즘은 조직과 관리들이 자신의 결정과 행동에 대해 책임을 질 수 있도록 보장한다." },
      { word: "outreach", pron: "/aʊtriːtʃ/", pos: "n.", meanings: ["지원 활동", "아웃리치"], example: "Mobile health outreach teams provide basic medical care to remote communities far from established clinics.", exampleKr: "이동식 의료 아웃리치 팀은 기존 클리닉에서 멀리 떨어진 외딴 지역사회에 기본 의료 서비스를 제공한다." },
      { word: "subsidy", pron: "/sʌbsɪdi/", pos: "n.", meanings: ["보조금", "지원금"], example: "Government subsidies for low-income housing keep rents affordable for families on the lowest incomes.", exampleKr: "저소득 주택에 대한 정부 보조금은 최저 소득 가정에게 임대료를 감당할 수 있는 수준으로 유지한다." },
      { word: "volunteerism", pron: "/vɒləntɪərɪzəm/", pos: "n.", meanings: ["자원봉사 정신", "자원봉사주의"], example: "A culture of volunteerism strengthens communities by connecting people with different skills and backgrounds.", exampleKr: "자원봉사 정신의 문화는 다양한 기술과 배경을 가진 사람들을 연결하여 지역사회를 강화한다." },
      { word: "disparity", pron: "/dɪspærɪti/", pos: "n.", meanings: ["격차", "불평등"], example: "Growing income disparity between the wealthy and the poor threatens social cohesion and democratic institutions.", exampleKr: "부유층과 빈곤층 사이의 커지는 소득 격차는 사회적 결속력과 민주적 제도를 위협한다." },
      { word: "social enterprise", pron: "/səʊʃəl entəpraɪz/", pos: "n.", meanings: ["사회적 기업"], example: "A social enterprise generates revenue through commercial activity while using profits to address social or environmental challenges.", exampleKr: "사회적 기업은 상업적 활동을 통해 수익을 창출하면서 이익을 사회적 또는 환경적 문제 해결에 사용한다." }
    ]
  }
});
