/**
 * data_days_121_125.js - Day 121~125 단어 데이터
 * data_days_116_120.js 이후에 로드해야 합니다
 */
Object.assign(VOCA_DATA, {
  121: {
    theme: "스포츠 과학",
    words: [
      { word: "biomechanics", pron: "/baɪəʊməkænɪks/", pos: "n.", meanings: ["생체역학"], example: "Biomechanics analyses the forces and movements involved in athletic performance to prevent injury and improve technique.", exampleKr: "생체역학은 부상을 예방하고 기술을 향상시키기 위해 운동 경기에 관련된 힘과 움직임을 분석한다." },
      { word: "aerobic", pron: "/eərəʊbɪk/", pos: "adj.", meanings: ["유산소의", "에어로빅의"], example: "Aerobic exercise like running and cycling improves cardiovascular fitness and increases lung capacity over time.", exampleKr: "달리기나 사이클링 같은 유산소 운동은 심혈관 건강을 향상시키고 시간이 지남에 따라 폐활량을 증가시킨다." },
      { word: "anaerobic", pron: "/ænərəʊbɪk/", pos: "adj.", meanings: ["무산소의"], example: "Sprinting and weightlifting are anaerobic activities that rely on energy sources that do not require oxygen.", exampleKr: "단거리 달리기와 역도는 산소를 필요로 하지 않는 에너지원에 의존하는 무산소 활동이다." },
      { word: "hypertrophy", pron: "/haɪpɜːrtrəfi/", pos: "n.", meanings: ["비대", "근육 성장"], example: "Muscle hypertrophy, the enlargement of muscle fibres through resistance training, requires adequate protein intake.", exampleKr: "저항 훈련을 통한 근육 섬유 확대인 근육 비대는 충분한 단백질 섭취를 필요로 한다." },
      { word: "stamina", pron: "/stæmɪnə/", pos: "n.", meanings: ["체력", "지구력"], example: "Long-distance runners develop impressive stamina through months of consistent high-volume training.", exampleKr: "장거리 달리기 선수들은 몇 달간의 꾸준한 고용량 훈련을 통해 인상적인 체력을 개발한다." },
      { word: "proprioception", pron: "/prəʊpriəsepʃən/", pos: "n.", meanings: ["고유감각", "자기수용감각"], example: "Proprioception allows athletes to sense the position and movement of their body without looking at their limbs.", exampleKr: "고유감각은 운동선수가 팔다리를 보지 않고도 신체의 위치와 움직임을 감지할 수 있게 한다." },
      { word: "kinetic", pron: "/kɪnetɪk/", pos: "adj.", meanings: ["운동의", "운동에너지의"], example: "Kinetic energy, the energy of motion, is central to the analysis of speed and force in sport.", exampleKr: "운동 에너지, 즉 움직임의 에너지는 스포츠에서 속도와 힘 분석의 핵심이다." },
      { word: "endurance", pron: "/ɪndjʊərəns/", pos: "n.", meanings: ["지구력", "인내력"], example: "Endurance athletes train their bodies to sustain effort over prolonged periods by improving metabolic efficiency.", exampleKr: "지구력 운동선수들은 대사 효율성을 향상시켜 장기간 동안 노력을 지속하도록 몸을 훈련시킨다." },
      { word: "agility", pron: "/ədʒɪlɪti/", pos: "n.", meanings: ["민첩성", "기민함"], example: "Agility drills train athletes to change direction rapidly without losing speed or body control.", exampleKr: "민첩성 훈련은 운동선수가 속도나 신체 제어를 잃지 않고 빠르게 방향을 바꾸도록 훈련시킨다." },
      { word: "flexibility", pron: "/fleksɪbɪlɪti/", pos: "n.", meanings: ["유연성", "융통성"], example: "Regular stretching improves joint flexibility, reducing injury risk and enhancing range of motion in sport.", exampleKr: "규칙적인 스트레칭은 관절 유연성을 향상시켜 스포츠에서 부상 위험을 줄이고 운동 범위를 넓힌다." },
      { word: "lactate", pron: "/lækteɪt/", pos: "n.", meanings: ["젖산"], example: "As exercise intensity rises, lactate accumulates in the muscles faster than it can be cleared away.", exampleKr: "운동 강도가 높아질수록 젖산이 제거될 수 있는 것보다 더 빠르게 근육에 축적된다." },
      { word: "concussion", pron: "/kənkʌʃən/", pos: "n.", meanings: ["뇌진탕"], example: "Concussion protocols now require athletes to undergo thorough assessment before returning to competitive play.", exampleKr: "뇌진탕 프로토콜은 이제 운동선수가 경쟁 경기에 복귀하기 전에 철저한 평가를 받도록 요구한다." },
      { word: "doping", pron: "/dəʊpɪŋ/", pos: "n.", meanings: ["도핑", "약물 사용"], example: "Strict anti-doping regulations are in place to ensure fair competition and protect athlete health.", exampleKr: "공정한 경쟁을 보장하고 선수 건강을 보호하기 위해 엄격한 반도핑 규정이 마련되어 있다." },
      { word: "plyometric", pron: "/plaɪəmetrɪk/", pos: "adj.", meanings: ["플라이오메트릭의", "폭발적 근력 훈련의"], example: "Plyometric exercises such as box jumps develop explosive power by training muscles to exert maximum force rapidly.", exampleKr: "박스 점프와 같은 플라이오메트릭 운동은 근육이 빠르게 최대 힘을 발휘하도록 훈련하여 폭발적인 힘을 개발한다." },
      { word: "dehydration", pron: "/diːhaɪdreɪʃən/", pos: "n.", meanings: ["탈수", "수분 부족"], example: "Even mild dehydration during exercise can impair concentration, reduce performance, and increase fatigue.", exampleKr: "운동 중 가벼운 탈수조차도 집중력을 손상시키고, 성능을 저하시키며, 피로를 증가시킬 수 있다." },
      { word: "overtraining", pron: "/əʊvətreɪnɪŋ/", pos: "n.", meanings: ["과훈련", "오버트레이닝"], example: "Overtraining syndrome occurs when athletes train beyond their body's capacity to recover, leading to chronic fatigue.", exampleKr: "과훈련 증후군은 운동선수가 신체의 회복 능력을 초과하여 훈련할 때 발생하여 만성 피로로 이어진다." },
      { word: "cartilage", pron: "/kɑːrtɪlɪdʒ/", pos: "n.", meanings: ["연골"], example: "Cartilage acts as a cushion in joints, but unlike bone, it has very limited capacity for self-repair.", exampleKr: "연골은 관절에서 쿠션 역할을 하지만 뼈와 달리 자가 복구 능력이 매우 제한적이다." },
      { word: "interval training", pron: "/ɪntəvəl treɪnɪŋ/", pos: "n.", meanings: ["인터벌 트레이닝", "간헐적 훈련"], example: "High-intensity interval training alternates between short bursts of maximum effort and brief recovery periods.", exampleKr: "고강도 인터벌 트레이닝은 최대 노력의 짧은 폭발과 짧은 회복 기간을 번갈아 가며 진행한다." },
      { word: "periodisation", pron: "/pɪəriədaɪzeɪʃən/", pos: "n.", meanings: ["주기화", "훈련 주기 계획"], example: "Periodisation systematically varies training load and intensity throughout the season to peak at competition time.", exampleKr: "주기화는 경기 시즌 동안 체계적으로 훈련 부하와 강도를 변화시켜 경기 시간에 최고조에 달하게 한다." },
      { word: "calisthenics", pron: "/kælɪsθenɪks/", pos: "n.", meanings: ["맨손 체조", "자중 운동"], example: "Calisthenics uses the body's own weight for resistance, requiring no equipment but delivering impressive functional strength.", exampleKr: "맨손 체조는 저항을 위해 신체 자체 체중을 사용하며, 장비가 필요 없지만 인상적인 기능적 근력을 제공한다." }
    ]
  },
  122: {
    theme: "항공교통 어휘",
    words: [
      { word: "aerodynamics", pron: "/eərəʊdaɪnæmɪks/", pos: "n.", meanings: ["공기역학"], example: "Aerodynamics determines how air flows around an aircraft, influencing its speed, lift, and fuel efficiency.", exampleKr: "공기역학은 공기가 항공기 주위를 어떻게 흐르는지를 결정하며, 속도, 양력, 연료 효율성에 영향을 미친다." },
      { word: "altitude", pron: "/æltɪtjuːd/", pos: "n.", meanings: ["고도", "높이"], example: "Commercial aircraft typically cruise at an altitude of between 9,000 and 12,000 metres above sea level.", exampleKr: "상업용 항공기는 일반적으로 해수면에서 9,000에서 12,000미터 사이의 고도에서 순항한다." },
      { word: "turbulence", pron: "/tɜːrbjʊləns/", pos: "n.", meanings: ["난기류", "혼란"], example: "Passengers were advised to fasten their seatbelts as the aircraft entered a patch of severe turbulence.", exampleKr: "항공기가 심한 난기류 구간에 진입하면서 승객들은 안전벨트를 매도록 안내받았다." },
      { word: "fuselage", pron: "/fjuːzəlɑːdʒ/", pos: "n.", meanings: ["동체", "기체"], example: "The fuselage is the main body of the aircraft, accommodating passengers, crew, and cargo.", exampleKr: "동체는 승객, 승무원, 화물을 수용하는 항공기의 주요 본체이다." },
      { word: "transponder", pron: "/trænspɒndər/", pos: "n.", meanings: ["트랜스폰더", "응답기"], example: "Air traffic controllers use transponder signals to track aircraft positions on their radar screens.", exampleKr: "항공 교통 관제사들은 레이더 화면에서 항공기 위치를 추적하기 위해 트랜스폰더 신호를 사용한다." },
      { word: "taxiway", pron: "/tæksiweɪ/", pos: "n.", meanings: ["유도로", "택시웨이"], example: "Aircraft move along designated taxiways between the terminal and the runway before take-off and after landing.", exampleKr: "항공기는 이륙 전과 착륙 후 터미널과 활주로 사이의 지정된 유도로를 따라 이동한다." },
      { word: "thrust", pron: "/θrʌst/", pos: "n./v.", meanings: ["추진력", "밀다"], example: "The four engines produce sufficient thrust to accelerate the heavy wide-body aircraft to take-off speed.", exampleKr: "4개의 엔진은 무거운 광동체 항공기를 이륙 속도까지 가속시키기에 충분한 추진력을 생성한다." },
      { word: "autopilot", pron: "/ɔːtəʊpaɪlət/", pos: "n.", meanings: ["자동 조종 장치", "오토파일럿"], example: "Modern autopilot systems can control the aircraft's heading, altitude, and speed with minimal pilot intervention.", exampleKr: "현대의 자동 조종 장치 시스템은 최소한의 조종사 개입으로 항공기의 방향, 고도, 속도를 제어할 수 있다." },
      { word: "hydraulic", pron: "/haɪdrɔːlɪk/", pos: "adj.", meanings: ["유압의", "수압의"], example: "Aircraft brakes and flight control surfaces are operated by powerful hydraulic systems pressurised by engine pumps.", exampleKr: "항공기 브레이크와 비행 조종면은 엔진 펌프에 의해 가압되는 강력한 유압 시스템으로 작동된다." },
      { word: "commute", pron: "/kəmjuːt/", pos: "n./v.", meanings: ["통근", "통근하다"], example: "Many workers commute long distances between affordable suburban housing and expensive city-centre workplaces.", exampleKr: "많은 근로자들이 저렴한 교외 주거지와 비싼 도심 직장 사이를 장거리 통근한다." },
      { word: "congestion", pron: "/kəndʒestʃən/", pos: "n.", meanings: ["교통 체증", "혼잡"], example: "Congestion charging schemes in city centres have successfully reduced traffic volumes and improved air quality.", exampleKr: "도심의 혼잡 통행료 제도는 교통량을 성공적으로 줄이고 대기 질을 개선했다." },
      { word: "airspace", pron: "/eəspeɪs/", pos: "n.", meanings: ["영공", "항공 공간"], example: "Each country controls its own airspace and charges fees for foreign aircraft passing through it.", exampleKr: "각 나라는 자국의 영공을 통제하고 그것을 통과하는 외국 항공기에 수수료를 부과한다." },
      { word: "disembark", pron: "/dɪsɪmbɑːrk/", pos: "v.", meanings: ["하선하다", "내리다"], example: "Passengers were asked to remain seated until the aircraft came to a complete stop and it was safe to disembark.", exampleKr: "승객들은 항공기가 완전히 멈추고 하선이 안전할 때까지 착석해 있도록 요청받았다." },
      { word: "transit", pron: "/trænsɪt/", pos: "n.", meanings: ["대중교통", "통과"], example: "Integrated transit systems combining buses, trams, and metro lines reduce car dependency in urban areas.", exampleKr: "버스, 트램, 지하철 노선을 결합한 통합 대중교통 시스템은 도시 지역의 자동차 의존도를 줄인다." },
      { word: "intermodal", pron: "/ɪntərməʊdəl/", pos: "adj.", meanings: ["복합 수송의", "다중 교통 수단의"], example: "Intermodal transport hubs allow passengers to switch seamlessly between rail, bus, and ferry services.", exampleKr: "복합 수송 허브는 승객이 철도, 버스, 페리 서비스 사이를 원활하게 전환할 수 있게 한다." },
      { word: "propulsion", pron: "/prəpʌlʃən/", pos: "n.", meanings: ["추진력", "추진"], example: "Electric propulsion systems are increasingly being developed as cleaner alternatives to fossil fuel engines.", exampleKr: "전기 추진 시스템이 화석 연료 엔진에 대한 더 깨끗한 대안으로 점점 더 개발되고 있다." },
      { word: "docking", pron: "/dɒkɪŋ/", pos: "n.", meanings: ["도킹", "접안"], example: "Autonomous docking technology allows ships to berth at port without the need for tugboat assistance.", exampleKr: "자율 도킹 기술은 예인선의 도움 없이 선박이 항구에 접안할 수 있게 한다." },
      { word: "waypoint", pron: "/weɪpɔɪnt/", pos: "n.", meanings: ["경유지", "항법 지점"], example: "Pilots navigate along a series of waypoints defined by GPS coordinates to reach their destination accurately.", exampleKr: "조종사들은 목적지에 정확하게 도달하기 위해 GPS 좌표로 정의된 일련의 경유지를 따라 항법을 진행한다." },
      { word: "manifest", pron: "/mænɪfest/", pos: "n./v.", meanings: ["화물 목록", "명백하게 드러내다"], example: "The cargo manifest lists every item loaded onto the aircraft, including weight and destination details.", exampleKr: "화물 목록은 무게와 목적지 세부사항을 포함하여 항공기에 실린 모든 물품을 열거한다." },
      { word: "supersonic", pron: "/suːpəsɒnɪk/", pos: "adj.", meanings: ["초음속의"], example: "Supersonic passenger aircraft travel faster than the speed of sound, dramatically cutting long-haul flight times.", exampleKr: "초음속 여객기는 음속보다 빠르게 이동하여 장거리 비행 시간을 극적으로 단축한다." }
    ]
  },
  123: {
    theme: "미술시각 예술",
    words: [
      { word: "chiaroscuro", pron: "/kiɑːrəskjʊərəʊ/", pos: "n.", meanings: ["명암법", "명암 대비"], example: "Caravaggio's dramatic use of chiaroscuro created powerful contrasts of light and shadow in his religious paintings.", exampleKr: "카라바조의 극적인 명암법 사용은 그의 종교화에서 빛과 그림자의 강력한 대비를 만들어냈다." },
      { word: "perspective", pron: "/pəspektɪv/", pos: "n.", meanings: ["원근법", "시각"], example: "Renaissance artists mastered linear perspective to create convincing illusions of three-dimensional depth on flat surfaces.", exampleKr: "르네상스 화가들은 평평한 표면에 3차원 깊이의 설득력 있는 환상을 만들기 위해 선형 원근법을 마스터했다." },
      { word: "impasto", pron: "/ɪmpæstəʊ/", pos: "n.", meanings: ["임파스토", "두꺼운 물감 기법"], example: "Van Gogh's thick impasto technique gave his canvases an intensely physical, textured quality.", exampleKr: "반 고흐의 두꺼운 임파스토 기법은 그의 캔버스에 강렬하게 물리적인 질감 있는 특성을 부여했다." },
      { word: "fresco", pron: "/freskəʊ/", pos: "n.", meanings: ["프레스코화", "회벽화"], example: "Michelangelo spent four years painting the famous fresco on the ceiling of the Sistine Chapel.", exampleKr: "미켈란젤로는 시스티나 예배당 천장에 있는 유명한 프레스코화를 그리는 데 4년을 보냈다." },
      { word: "mosaic", pron: "/məʊzeɪɪk/", pos: "n.", meanings: ["모자이크"], example: "Byzantine churches were adorned with stunning gold and glass mosaics depicting religious scenes.", exampleKr: "비잔틴 교회들은 종교적 장면을 묘사하는 화려한 금과 유리 모자이크로 장식되었다." },
      { word: "lithograph", pron: "/lɪθəɡrɑːf/", pos: "n.", meanings: ["석판화"], example: "Toulouse-Lautrec's vibrant lithographs were used as posters advertising the Moulin Rouge cabaret.", exampleKr: "툴루즈-로트렉의 생동감 넘치는 석판화는 물랭 루주 카바레 광고 포스터로 사용되었다." },
      { word: "palette", pron: "/pælɪt/", pos: "n.", meanings: ["팔레트", "색조 범위"], example: "The artist chose a limited palette of earth tones to convey a sense of warmth and intimacy.", exampleKr: "화가는 따뜻함과 친밀감을 전달하기 위해 흙 색조의 제한된 팔레트를 선택했다." },
      { word: "surrealism", pron: "/sərɪəlɪzəm/", pos: "n.", meanings: ["초현실주의"], example: "Surrealism explored the irrational world of dreams and the unconscious mind through bizarre and dreamlike imagery.", exampleKr: "초현실주의는 기이하고 꿈같은 이미지를 통해 꿈과 무의식의 비합리적인 세계를 탐구했다." },
      { word: "iconography", pron: "/aɪkənɒɡrəfi/", pos: "n.", meanings: ["도상학", "도상"], example: "Religious iconography uses symbolic visual language to communicate theological ideas to viewers of all backgrounds.", exampleKr: "종교적 도상학은 모든 배경을 가진 시청자에게 신학적 아이디어를 전달하기 위해 상징적인 시각적 언어를 사용한다." },
      { word: "avant-garde", pron: "/ævɒnt ɡɑːrd/", pos: "adj./n.", meanings: ["전위적", "아방가르드"], example: "The avant-garde movement challenged conventional artistic standards by pushing boundaries of form and concept.", exampleKr: "아방가르드 운동은 형식과 개념의 경계를 밀어붙임으로써 전통적인 예술 기준에 도전했다." },
      { word: "baroque", pron: "/bərɒk/", pos: "adj./n.", meanings: ["바로크 양식의", "바로크"], example: "Baroque art is characterised by dramatic expression, rich detail, and grandeur intended to evoke emotional responses.", exampleKr: "바로크 예술은 감정적 반응을 불러일으키기 위한 극적인 표현, 풍부한 디테일, 웅장함을 특징으로 한다." },
      { word: "impressionism", pron: "/ɪmpreʃənɪzəm/", pos: "n.", meanings: ["인상주의"], example: "Impressionism captured fleeting light and atmosphere through loose brushwork rather than precise, detailed forms.", exampleKr: "인상주의는 정밀하고 세밀한 형태가 아닌 느슨한 붓질을 통해 순간적인 빛과 분위기를 포착했다." },
      { word: "cubism", pron: "/kjuːbɪzəm/", pos: "n.", meanings: ["입체주의", "큐비즘"], example: "Cubism, pioneered by Picasso and Braque, depicted subjects from multiple viewpoints simultaneously on a flat surface.", exampleKr: "피카소와 브라크가 개척한 입체주의는 평평한 표면에 여러 시점에서 동시에 대상을 묘사했다." },
      { word: "installation", pron: "/ɪnstəleɪʃən/", pos: "n.", meanings: ["설치 미술", "설치"], example: "Her large-scale installation filled the entire gallery with suspended mirrors that distorted visitors' reflections.", exampleKr: "그녀의 대규모 설치 미술은 방문객의 반영을 왜곡하는 매달린 거울로 전시관 전체를 가득 채웠다." },
      { word: "provenance", pron: "/prɒvənəns/", pos: "n.", meanings: ["출처", "유래"], example: "Auction houses require full provenance documentation before accepting valuable artworks for public sale.", exampleKr: "경매사들은 귀중한 미술품을 공개 판매를 위해 수락하기 전에 완전한 출처 문서를 요구한다." },
      { word: "etching", pron: "/etʃɪŋ/", pos: "n.", meanings: ["에칭", "동판화"], example: "Rembrandt's etchings are celebrated for their subtle tonal range and deeply expressive line work.", exampleKr: "렘브란트의 에칭은 섬세한 음색 범위와 깊이 표현력 있는 선 작업으로 유명하다." },
      { word: "collage", pron: "/kɒlɑːʒ/", pos: "n.", meanings: ["콜라주"], example: "The artist created a striking collage by assembling newspaper clippings, photographs, and painted elements together.", exampleKr: "그 화가는 신문 스크랩, 사진, 채색된 요소들을 모아 인상적인 콜라주를 만들었다." },
      { word: "composition", pron: "/kɒmpəzɪʃən/", pos: "n.", meanings: ["구도", "구성"], example: "A well-balanced composition guides the viewer's eye through the image and creates a sense of visual harmony.", exampleKr: "잘 균형 잡힌 구도는 시청자의 시선을 이미지를 통해 이끌고 시각적 조화감을 만들어낸다." },
      { word: "triptych", pron: "/trɪptɪk/", pos: "n.", meanings: ["세 폭 제단화", "트립티크"], example: "The altarpiece was painted as a triptych, with a large central panel flanked by two smaller wings.", exampleKr: "그 제단화는 두 개의 작은 측면 날개가 있는 큰 중앙 패널이 있는 세 폭으로 그려졌다." },
      { word: "monochrome", pron: "/mɒnəkrəʊm/", pos: "adj./n.", meanings: ["단색의", "흑백의"], example: "The photographer chose to present the series in monochrome to emphasise form, texture, and emotional tone.", exampleKr: "사진작가는 형태, 질감, 감정적 톤을 강조하기 위해 그 시리즈를 흑백으로 발표하기로 선택했다." }
    ]
  },
  124: {
    theme: "무역물류 어휘",
    words: [
      { word: "tariff", pron: "/tærɪf/", pos: "n.", meanings: ["관세", "요금"], example: "Import tariffs on steel were raised to protect domestic manufacturers from cheaper foreign competition.", exampleKr: "국내 제조업체를 더 저렴한 외국 경쟁으로부터 보호하기 위해 철강에 대한 수입 관세가 인상되었다." },
      { word: "embargo", pron: "/ɪmbɑːrɡəʊ/", pos: "n./v.", meanings: ["통상 금지", "금수"], example: "The international community imposed a trade embargo to pressure the government into changing its policies.", exampleKr: "국제 사회는 정부가 정책을 바꾸도록 압박하기 위해 무역 금수 조치를 부과했다." },
      { word: "logistics", pron: "/lədʒɪstɪks/", pos: "n.", meanings: ["물류", "병참"], example: "Efficient logistics management is essential for ensuring goods reach customers on time and in good condition.", exampleKr: "효율적인 물류 관리는 상품이 제 시간에 좋은 상태로 고객에게 도달하도록 보장하는 데 필수적이다." },
      { word: "consignment", pron: "/kənsaɪnmənt/", pos: "n.", meanings: ["탁송품", "위탁 화물"], example: "The consignment of electronics was held at customs pending inspection of the accompanying documentation.", exampleKr: "전자제품 탁송품은 동반 서류 검사가 진행되는 동안 세관에서 보류되었다." },
      { word: "freight", pron: "/freɪt/", pos: "n./v.", meanings: ["화물", "화물 운송하다"], example: "Air freight is significantly faster than sea freight but costs considerably more per unit of cargo.", exampleKr: "항공 화물은 해상 화물보다 상당히 빠르지만 화물 단위당 비용이 상당히 더 많이 든다." },
      { word: "quarantine", pron: "/kwɒrəntiːn/", pos: "n./v.", meanings: ["검역", "격리"], example: "Fresh produce arriving from affected regions was placed in quarantine pending phytosanitary inspection.", exampleKr: "영향을 받은 지역에서 도착한 신선 농산물은 식물 검역 검사가 진행되는 동안 검역 대기 중이었다." },
      { word: "customs", pron: "/kʌstəmz/", pos: "n.", meanings: ["세관", "관세"], example: "All goods entering the country must be declared at customs, where duties may be assessed and collected.", exampleKr: "모든 상품은 관세가 평가되고 징수될 수 있는 세관에서 신고되어야 한다." },
      { word: "invoice", pron: "/ɪnvɔɪs/", pos: "n./v.", meanings: ["청구서", "청구서를 발행하다"], example: "The supplier issued a detailed invoice specifying the quantity, unit price, and total amount due.", exampleKr: "공급업체는 수량, 단가, 총 지불 금액을 명시한 상세한 청구서를 발행했다." },
      { word: "bill of lading", pron: "/bɪl əv leɪdɪŋ/", pos: "n.", meanings: ["선하증권"], example: "A bill of lading is a legal document issued by a carrier to acknowledge receipt of cargo for shipment.", exampleKr: "선하증권은 운송을 위한 화물 수령을 확인하기 위해 운송업체가 발행하는 법적 문서이다." },
      { word: "supply chain", pron: "/səplaɪ tʃeɪn/", pos: "n.", meanings: ["공급망", "공급 사슬"], example: "Disruptions to the global supply chain during the pandemic revealed dangerous dependencies on single suppliers.", exampleKr: "팬데믹 기간 동안 글로벌 공급망의 혼란은 단일 공급업체에 대한 위험한 의존성을 드러냈다." },
      { word: "quota", pron: "/kwəʊtə/", pos: "n.", meanings: ["할당량", "쿼터"], example: "Import quotas limit the quantity of a specific good that can enter a country during a defined period.", exampleKr: "수입 쿼터는 정해진 기간 동안 특정 상품이 국가에 들어올 수 있는 수량을 제한한다." },
      { word: "dumping", pron: "/dʌmpɪŋ/", pos: "n.", meanings: ["덤핑", "염가 판매"], example: "Anti-dumping measures protect domestic industries from foreign goods sold below their cost of production.", exampleKr: "반덤핑 조치는 생산 비용 이하로 판매되는 외국 상품으로부터 국내 산업을 보호한다." },
      { word: "just-in-time", pron: "/dʒʌst ɪn taɪm/", pos: "adj.", meanings: ["적시 생산의", "JIT"], example: "Just-in-time manufacturing reduces warehouse costs by receiving raw materials only when needed for production.", exampleKr: "적시 생산 방식은 생산에 필요할 때만 원자재를 받아 창고 비용을 줄인다." },
      { word: "inventory", pron: "/ɪnvəntri/", pos: "n.", meanings: ["재고", "재고 목록"], example: "Accurate inventory management prevents both costly stockouts and expensive surplus holdings in the warehouse.", exampleKr: "정확한 재고 관리는 창고에서 비용이 많이 드는 품절과 비싼 잉여 재고 모두를 방지한다." },
      { word: "trade deficit", pron: "/treɪd defɪsɪt/", pos: "n.", meanings: ["무역 적자"], example: "A persistent trade deficit can weaken a currency, as demand for foreign goods exceeds export revenues.", exampleKr: "지속적인 무역 적자는 외국 상품에 대한 수요가 수출 수익을 초과하면서 통화를 약화시킬 수 있다." },
      { word: "free trade zone", pron: "/friː treɪd zəʊn/", pos: "n.", meanings: ["자유 무역 지대", "자유 무역 구역"], example: "Goods can be manufactured and re-exported from a free trade zone without incurring customs duties.", exampleKr: "자유 무역 지대에서 상품은 관세를 부담하지 않고 제조되고 재수출될 수 있다." },
      { word: "containerisation", pron: "/kənteɪnəraɪzeɪʃən/", pos: "n.", meanings: ["컨테이너화"], example: "Containerisation transformed global trade by standardising cargo, dramatically cutting loading times and costs.", exampleKr: "컨테이너화는 화물을 표준화하여 글로벌 무역을 변화시키고, 적재 시간과 비용을 극적으로 줄였다." },
      { word: "waybill", pron: "/weɪbɪl/", pos: "n.", meanings: ["화물 운송장", "운송 명세서"], example: "An air waybill accompanies every freight shipment and serves as both a receipt and a contract of carriage.", exampleKr: "항공 운송장은 모든 화물 운송에 동반되며 영수증이자 운송 계약서 역할을 한다." },
      { word: "arbitrage", pron: "/ɑːrbɪtrɑːʒ/", pos: "n.", meanings: ["차익 거래"], example: "Traders exploit arbitrage opportunities by simultaneously buying and selling the same asset in different markets.", exampleKr: "거래자들은 서로 다른 시장에서 동일한 자산을 동시에 사고팔아 차익 거래 기회를 활용한다." },
      { word: "bonded warehouse", pron: "/bɒndɪd weəhaʊs/", pos: "n.", meanings: ["보세 창고"], example: "Imported goods can be stored in a bonded warehouse without paying duties until they enter the domestic market.", exampleKr: "수입 상품은 국내 시장에 반입될 때까지 관세를 지불하지 않고 보세 창고에 보관될 수 있다." }
    ]
  },
  125: {
    theme: "농업식품과학",
    words: [
      { word: "irrigation", pron: "/ɪrɪɡeɪʃən/", pos: "n.", meanings: ["관개", "물대기"], example: "Drip irrigation delivers water directly to plant roots, reducing waste and improving crop yields in arid regions.", exampleKr: "점적 관개는 물을 식물 뿌리에 직접 공급하여 건조 지역에서 낭비를 줄이고 작물 수확량을 높인다." },
      { word: "pesticide", pron: "/pestɪsaɪd/", pos: "n.", meanings: ["농약", "살충제"], example: "Overuse of pesticides contaminates waterways and harms beneficial insects such as bees and butterflies.", exampleKr: "농약의 과다 사용은 수로를 오염시키고 꿀벌과 나비와 같은 유익한 곤충에 해를 끼친다." },
      { word: "fertiliser", pron: "/fɜːrtɪlaɪzər/", pos: "n.", meanings: ["비료"], example: "Synthetic fertilisers increase crop yields dramatically but can lead to soil degradation and water pollution when misapplied.", exampleKr: "합성 비료는 작물 수확량을 극적으로 증가시키지만 잘못 사용될 경우 토양 황폐화와 수질 오염으로 이어질 수 있다." },
      { word: "crop rotation", pron: "/krɒp rəʊteɪʃən/", pos: "n.", meanings: ["윤작", "돌려 짓기"], example: "Crop rotation improves soil fertility and reduces pest pressure by planting different crops in sequence.", exampleKr: "윤작은 다른 작물을 순서대로 심어 토양 비옥도를 높이고 해충 압력을 줄인다." },
      { word: "permaculture", pron: "/pɜːrməkʌltʃər/", pos: "n.", meanings: ["퍼머컬처", "지속 가능 농업"], example: "Permaculture designs agricultural systems that mimic natural ecosystems to produce food sustainably without external inputs.", exampleKr: "퍼머컬처는 외부 투입 없이 지속 가능하게 식품을 생산하기 위해 자연 생태계를 모방하는 농업 시스템을 설계한다." },
      { word: "genetically modified", pron: "/dʒənetɪkli mɒdɪfaɪd/", pos: "adj.", meanings: ["유전자 변형의", "GMO"], example: "Genetically modified crops can be engineered to resist drought, pests, or disease, boosting food security.", exampleKr: "유전자 변형 작물은 가뭄, 해충 또는 질병에 저항하도록 개발될 수 있어 식량 안보를 강화할 수 있다." },
      { word: "agroforestry", pron: "/æɡrəʊfɒrɪstri/", pos: "n.", meanings: ["농림업"], example: "Agroforestry integrates trees with crops or livestock to improve biodiversity and long-term soil health.", exampleKr: "농림업은 생물 다양성과 장기적인 토양 건강을 향상시키기 위해 작물이나 가축과 나무를 통합한다." },
      { word: "pasteurisation", pron: "/pɑːstʃəraɪzeɪʃən/", pos: "n.", meanings: ["저온 살균"], example: "Pasteurisation heats liquid food to a specific temperature to kill harmful bacteria while preserving nutritional value.", exampleKr: "저온 살균은 영양가를 보존하면서 해로운 박테리아를 죽이기 위해 액체 식품을 특정 온도로 가열한다." },
      { word: "fermentation", pron: "/fɜːrmenteɪʃən/", pos: "n.", meanings: ["발효"], example: "Fermentation by microorganisms transforms raw ingredients into foods like bread, cheese, wine, and yogurt.", exampleKr: "미생물에 의한 발효는 원자재를 빵, 치즈, 와인, 요구르트와 같은 식품으로 변환한다." },
      { word: "emulsifier", pron: "/ɪmʌlsɪfaɪər/", pos: "n.", meanings: ["유화제"], example: "Emulsifiers like lecithin are added to food products to keep oil and water components from separating.", exampleKr: "레시틴과 같은 유화제는 기름과 물 성분이 분리되지 않도록 식품에 첨가된다." },
      { word: "hydroponics", pron: "/haɪdrəpɒnɪks/", pos: "n.", meanings: ["수경재배"], example: "Hydroponics grows plants in nutrient-rich water solutions without soil, enabling year-round production in controlled environments.", exampleKr: "수경재배는 흙 없이 영양분이 풍부한 수용액에서 식물을 재배하여 통제된 환경에서 연중 생산을 가능하게 한다." },
      { word: "yield", pron: "/jiːld/", pos: "n./v.", meanings: ["수확량", "생산하다"], example: "New hybrid varieties have dramatically increased the yield that farmers can harvest from a given area of land.", exampleKr: "새로운 잡종 품종은 농부들이 주어진 토지 면적에서 수확할 수 있는 수확량을 극적으로 증가시켰다." },
      { word: "pollination", pron: "/pɒlɪneɪʃən/", pos: "n.", meanings: ["수분", "꽃가루 매개"], example: "Pollination by bees and other insects is essential for the reproduction of most flowering crop plants.", exampleKr: "꿀벌과 다른 곤충에 의한 수분은 대부분의 꽃 피는 작물의 생식에 필수적이다." },
      { word: "monoculture", pron: "/mɒnəkʌltʃər/", pos: "n.", meanings: ["단작", "단일재배"], example: "Monoculture farming maximises short-term efficiency but increases vulnerability to pests, disease, and market fluctuations.", exampleKr: "단작 농업은 단기 효율성을 극대화하지만 해충, 질병, 시장 변동에 대한 취약성을 높인다." },
      { word: "grafting", pron: "/ɡrɑːftɪŋ/", pos: "n.", meanings: ["접목", "이식"], example: "Grafting allows growers to combine the disease-resistant rootstock of one plant with the productive top of another.", exampleKr: "접목은 재배자가 한 식물의 내병성 대목과 다른 식물의 생산적인 위 부분을 결합할 수 있게 한다." },
      { word: "soil erosion", pron: "/sɔɪl ɪrəʊʒən/", pos: "n.", meanings: ["토양 침식"], example: "Soil erosion caused by wind and rain can be significantly reduced through the adoption of cover crops.", exampleKr: "바람과 비에 의한 토양 침식은 피복 작물을 채택함으로써 크게 줄일 수 있다." },
      { word: "agribusiness", pron: "/æɡrɪbɪznɪs/", pos: "n.", meanings: ["농기업", "농업 비즈니스"], example: "Large agribusiness corporations have transformed farming from family-scale operations into industrial enterprises.", exampleKr: "대형 농기업 회사들은 농업을 가족 규모의 운영에서 산업 기업으로 변화시켰다." },
      { word: "organic farming", pron: "/ɔːrɡænɪk fɑːrmɪŋ/", pos: "n.", meanings: ["유기농 농업"], example: "Organic farming prohibits the use of synthetic chemicals and GMOs, relying instead on natural inputs and processes.", exampleKr: "유기농 농업은 합성 화학물질과 GMO 사용을 금지하고 대신 천연 투입물과 공정에 의존한다." },
      { word: "food security", pron: "/fuːd sɪkjʊərɪti/", pos: "n.", meanings: ["식량 안보"], example: "Achieving global food security requires not just producing enough food, but ensuring equitable access to it.", exampleKr: "글로벌 식량 안보를 달성하려면 충분한 식량을 생산하는 것뿐만 아니라 공평한 접근을 보장하는 것이 필요하다." },
      { word: "drought-resistant", pron: "/draʊt rɪzɪstənt/", pos: "adj.", meanings: ["가뭄에 강한", "내건성의"], example: "Drought-resistant crop varieties are vital for feeding growing populations in water-scarce regions of the world.", exampleKr: "가뭄에 강한 작물 품종은 세계의 물 부족 지역에서 증가하는 인구를 먹이는 데 필수적이다." }
    ]
  }
});
