/**
 * data_days_101_110.js - Day 101~110 단어 데이터
 * data_days_076_100.js 이후에 로드해야 합니다
 */
  VOCA_DATA[101] = {
    theme: "의학·보건 어휘",
    words: [
      { word: "diagnosis", pron: "/ˌdaɪəɡˈnoʊsɪs/", pos: "n.", meanings: ["진단", "진단 결과"], example: "An early diagnosis significantly improves the chances of successful treatment for most cancers.", exampleKr: "조기 진단은 대부분의 암에 대한 성공적인 치료 가능성을 크게 향상시킨다." },
      { word: "prognosis", pron: "/prɒɡˈnoʊsɪs/", pos: "n.", meanings: ["예후", "예측", "전망"], example: "The patient received a positive prognosis after the tumour was found to be non-invasive.", exampleKr: "종양이 비침습성으로 밝혀진 후 환자는 긍정적인 예후를 받았다." },
      { word: "pathogen", pron: "/ˈpæθədʒən/", pos: "n.", meanings: ["병원체", "병원균"], example: "The laboratory identified the pathogen responsible for the outbreak within 48 hours.", exampleKr: "실험실은 48시간 내에 발병의 원인이 되는 병원체를 식별했다." },
      { word: "immunise", pron: "/ˈɪmjʊnaɪz/", pos: "v.", meanings: ["면역시키다", "예방접종하다"], example: "It is recommended to immunise children against measles, mumps, and rubella in early childhood.", exampleKr: "어린 시절 초기에 아이들에게 홍역, 볼거리, 풍진에 대한 예방접종을 하도록 권고된다." },
      { word: "chronic", pron: "/ˈkrɒnɪk/", pos: "adj.", meanings: ["만성의", "오래 지속되는"], example: "Chronic stress weakens the immune system and increases vulnerability to a range of illnesses.", exampleKr: "만성 스트레스는 면역 체계를 약화시키고 다양한 질병에 대한 취약성을 증가시킨다." },
      { word: "acute", pron: "/əˈkjuːt/", pos: "adj.", meanings: ["급성의", "심각한", "예리한"], example: "The patient was admitted to intensive care following an acute asthma attack.", exampleKr: "환자는 급성 천식 발작 후 중환자실에 입원했다." },
      { word: "benign", pron: "/bɪˈnaɪn/", pos: "adj.", meanings: ["양성의", "온화한", "무해한"], example: "The biopsy results confirmed that the growth was benign and required no further intervention.", exampleKr: "생검 결과는 종양이 양성이며 추가 개입이 필요하지 않다는 것을 확인했다." },
      { word: "malignant", pron: "/məˈlɪɡnənt/", pos: "adj.", meanings: ["악성의", "극도로 해로운"], example: "Malignant cells spread rapidly and require immediate and aggressive medical treatment.", exampleKr: "악성 세포는 빠르게 퍼지므로 즉각적이고 적극적인 의학적 치료가 필요하다." },
      { word: "remedy", pron: "/ˈremədi/", pos: "n./v.", meanings: ["치료법", "해결책", "치유하다"], example: "Herbal remedies have been used for centuries, though few have been rigorously tested in clinical trials.", exampleKr: "허브 치료법은 수세기 동안 사용되어 왔지만, 임상 시험에서 엄격하게 검증된 것은 거의 없다." },
      { word: "placebo", pron: "/pləˈsiːboʊ/", pos: "n.", meanings: ["위약", "플라시보"], example: "In the trial, patients who received the placebo showed a surprising degree of symptomatic improvement.", exampleKr: "시험에서 위약을 투여받은 환자들은 놀라운 정도의 증상 개선을 보였다." },
      { word: "pandemic", pron: "/pænˈdemɪk/", pos: "n.", meanings: ["팬데믹", "세계적 유행병"], example: "The pandemic exposed deep inequalities in how different countries' health systems cope with emergencies.", exampleKr: "팬데믹은 서로 다른 나라의 의료 시스템이 비상 상황에 대처하는 방식의 깊은 불평등을 드러냈다." },
      { word: "epidemic", pron: "/ˌepɪˈdemɪk/", pos: "n.", meanings: ["유행병", "급속한 확산"], example: "A flu epidemic swept through the school, forcing its closure for two weeks.", exampleKr: "유행성 독감이 학교를 휩쓸어 2주간 폐교를 강요했다." },
      { word: "contagious", pron: "/kənˈteɪdʒəs/", pos: "adj.", meanings: ["전염성의", "전염되는"], example: "Measles is one of the most contagious infectious diseases known to medical science.", exampleKr: "홍역은 의학적으로 알려진 가장 전염성이 강한 감염병 중 하나이다." },
      { word: "vaccination", pron: "/ˌvæksɪˈneɪʃən/", pos: "n.", meanings: ["예방접종", "백신 접종"], example: "High rates of vaccination create herd immunity that protects those who cannot be vaccinated.", exampleKr: "높은 예방접종률은 접종을 받을 수 없는 사람들을 보호하는 집단 면역을 형성한다." },
      { word: "symptom", pron: "/ˈsɪmptəm/", pos: "n.", meanings: ["증상", "징후"], example: "Early symptoms of the disease are often mistaken for a common cold, causing dangerous delays.", exampleKr: "이 질병의 초기 증상은 종종 일반 감기로 오해되어 위험한 지연을 초래한다." },
      { word: "metabolism", pron: "/məˈtæbəlɪzəm/", pos: "n.", meanings: ["신진대사", "물질대사"], example: "Regular exercise boosts metabolism and helps the body burn calories more efficiently.", exampleKr: "규칙적인 운동은 신진대사를 촉진하고 신체가 더 효율적으로 칼로리를 소모하는 데 도움이 된다." },
      { word: "therapeutic", pron: "/ˌθerəˈpjuːtɪk/", pos: "adj.", meanings: ["치료의", "치료 효과가 있는"], example: "The therapeutic benefits of music are increasingly recognised in clinical and mental health settings.", exampleKr: "음악의 치료적 효과는 임상 및 정신 건강 환경에서 점점 더 인정받고 있다." },
      { word: "palliative", pron: "/ˈpæliətɪv/", pos: "adj./n.", meanings: ["완화적인", "증상 완화 치료"], example: "When a cure is no longer possible, palliative care focuses on comfort and quality of life.", exampleKr: "더 이상 치유가 불가능할 때, 완화 치료는 편안함과 삶의 질에 초점을 맞춘다." },
      { word: "relapse", pron: "/rɪˈlæps/", pos: "v./n.", meanings: ["재발하다", "재발"], example: "Patients who stop medication too soon risk a relapse, which can be harder to treat than the original episode.", exampleKr: "너무 일찍 약을 중단하는 환자들은 재발의 위험을 무릅쓰는데, 재발은 처음 증상보다 치료하기 더 어려울 수 있다." },
      { word: "resilience", pron: "/rɪˈzɪliəns/", pos: "n.", meanings: ["회복력", "탄력성", "강인함"], example: "Healthcare workers demonstrated extraordinary resilience during the prolonged crisis.", exampleKr: "의료 종사자들은 장기간의 위기 동안 특별한 회복력을 보여주었다." }
    ]
  };

  VOCA_DATA[102] = {
    theme: "환경·생태 어휘",
    words: [
      { word: "biodiversity", pron: "/ˌbaɪoʊdaɪˈvɜːrsɪti/", pos: "n.", meanings: ["생물 다양성"], example: "Tropical rainforests harbour extraordinary biodiversity, containing over half of all known species.", exampleKr: "열대 우림은 알려진 모든 종의 절반 이상을 포함하는 비범한 생물 다양성을 품고 있다." },
      { word: "ecosystem", pron: "/ˈiːkəʊsɪstəm/", pos: "n.", meanings: ["생태계"], example: "The introduction of an invasive species can permanently destabilise a previously balanced ecosystem.", exampleKr: "침입 종의 도입은 이전에 균형 잡혀 있던 생태계를 영구적으로 불안정하게 만들 수 있다." },
      { word: "deforestation", pron: "/dɪˌfɒrɪˈsteɪʃən/", pos: "n.", meanings: ["삼림 벌채", "산림 파괴"], example: "Deforestation in the Amazon releases vast quantities of stored carbon dioxide into the atmosphere.", exampleKr: "아마존의 삼림 벌채는 막대한 양의 저장된 이산화탄소를 대기 중에 방출한다." },
      { word: "erosion", pron: "/ɪˈroʊʒən/", pos: "n.", meanings: ["침식", "잠식", "부식"], example: "Coastal erosion is accelerating as rising sea levels expose more shoreline to wave action.", exampleKr: "해수면 상승으로 더 많은 해안선이 파도에 노출됨에 따라 해안 침식이 가속화되고 있다." },
      { word: "greenhouse gas", pron: "/ˈɡriːnhaʊs ɡæs/", pos: "n.", meanings: ["온실 기체"], example: "Carbon dioxide is the most significant greenhouse gas produced by human industrial activity.", exampleKr: "이산화탄소는 인간의 산업 활동에 의해 생성되는 가장 중요한 온실 기체이다." },
      { word: "habitat", pron: "/ˈhæbɪtæt/", pos: "n.", meanings: ["서식지", "생활환경"], example: "Urban expansion has destroyed critical habitat for migratory birds along the eastern coastline.", exampleKr: "도시 확장이 동부 해안선을 따른 철새들의 중요한 서식지를 파괴했다." },
      { word: "carbon footprint", pron: "/ˈkɑːrbən ˈfʊtprɪnt/", pos: "n.", meanings: ["탄소 발자국"], example: "Switching to plant-based foods can significantly reduce an individual's carbon footprint.", exampleKr: "식물성 식품으로 전환하면 개인의 탄소 발자국을 크게 줄일 수 있다." },
      { word: "renewable", pron: "/rɪˈnjuːəbəl/", pos: "adj.", meanings: ["재생 가능한", "지속 가능한"], example: "Investment in renewable energy sources has grown faster than almost any other sector in the past decade.", exampleKr: "재생 가능 에너지원에 대한 투자는 지난 10년 동안 거의 다른 어떤 분야보다 빠르게 성장했다." },
      { word: "sustainability", pron: "/səˌsteɪnəˈbɪlɪti/", pos: "n.", meanings: ["지속가능성"], example: "Corporate sustainability reports are increasingly scrutinised by investors and consumers alike.", exampleKr: "기업의 지속가능성 보고서는 투자자와 소비자 모두에게 점점 더 면밀히 검토되고 있다." },
      { word: "acidification", pron: "/əˌsɪdɪfɪˈkeɪʃən/", pos: "n.", meanings: ["산성화"], example: "Ocean acidification threatens coral reefs, which support around a quarter of all marine species.", exampleKr: "해양 산성화는 모든 해양 종의 약 4분의 1을 부양하는 산호초를 위협한다." },
      { word: "permafrost", pron: "/ˈpɜːrməfrɒst/", pos: "n.", meanings: ["영구 동토층"], example: "Thawing permafrost in Siberia is releasing methane, a potent greenhouse gas, at alarming rates.", exampleKr: "시베리아의 영구 동토층 해빙은 강력한 온실 기체인 메탄을 우려스러운 속도로 방출하고 있다." },
      { word: "mitigation", pron: "/ˌmɪtɪˈɡeɪʃən/", pos: "n.", meanings: ["완화", "경감", "감소"], example: "Climate mitigation strategies focus on reducing emissions before irreversible damage occurs.", exampleKr: "기후 완화 전략은 돌이킬 수 없는 피해가 발생하기 전에 배출량을 줄이는 데 초점을 맞춘다." },
      { word: "sequestration", pron: "/ˌsiːkweˈstreɪʃən/", pos: "n.", meanings: ["격리", "탄소 격리", "압류"], example: "Carbon sequestration through reforestation is one of the more cost-effective tools in climate policy.", exampleKr: "재조림을 통한 탄소 격리는 기후 정책에서 가장 비용 효율적인 수단 중 하나이다." },
      { word: "fauna", pron: "/ˈfɔːnə/", pos: "n.", meanings: ["동물상", "(특정 지역의) 동물군"], example: "The island's isolated fauna evolved independently and includes species found nowhere else on Earth.", exampleKr: "섬의 격리된 동물군은 독립적으로 진화했으며 지구상 다른 어디에서도 찾아볼 수 없는 종들을 포함한다." },
      { word: "flora", pron: "/ˈflɔːrə/", pos: "n.", meanings: ["식물상", "(특정 지역의) 식물군"], example: "The botanical survey catalogued over three hundred species of native flora in the nature reserve.", exampleKr: "식물 조사는 자연 보호 구역에서 300종 이상의 토착 식물군을 목록화했다." },
      { word: "contamination", pron: "/kənˌtæmɪˈneɪʃən/", pos: "n.", meanings: ["오염", "오염물질"], example: "Industrial contamination of groundwater has made the wells in several villages unsafe to drink from.", exampleKr: "지하수의 산업적 오염으로 여러 마을의 우물이 음용에 불안전해졌다." },
      { word: "photosynthesis", pron: "/ˌfoʊtəʊˈsɪnθɪsɪs/", pos: "n.", meanings: ["광합성"], example: "Photosynthesis is the process by which plants convert sunlight into chemical energy.", exampleKr: "광합성은 식물이 햇빛을 화학 에너지로 변환하는 과정이다." },
      { word: "extinction", pron: "/ɪkˈstɪŋkʃən/", pos: "n.", meanings: ["멸종", "소멸"], example: "Scientists warn that we are living through the sixth mass extinction event in Earth's history.", exampleKr: "과학자들은 우리가 지구 역사상 여섯 번째 대량 멸종 사건을 살고 있다고 경고한다." },
      { word: "biome", pron: "/ˈbaɪoʊm/", pos: "n.", meanings: ["생물군계", "바이옴"], example: "The boreal forest biome stretches across the northern latitudes of North America, Europe, and Asia.", exampleKr: "북방 삼림 생물군계는 북미, 유럽, 아시아의 북위도를 가로질러 펼쳐진다." },
      { word: "watershed", pron: "/ˈwɔːtərʃed/", pos: "n.", meanings: ["분수령", "전환점", "유역"], example: "The summit proved to be a watershed moment in international climate diplomacy.", exampleKr: "그 정상 회담은 국제 기후 외교에서 전환점이 되는 순간임이 입증되었다." }
    ]
  };

  VOCA_DATA[103] = {
    theme: "경제·금융 어휘",
    words: [
      { word: "liquidity", pron: "/lɪˈkwɪdɪti/", pos: "n.", meanings: ["유동성", "현금화 가능성"], example: "During a financial panic, even solvent banks can fail simply because they run out of liquidity.", exampleKr: "금융 공황 시에는 지급 능력이 있는 은행조차 단순히 유동성이 고갈되어 실패할 수 있다." },
      { word: "inflation", pron: "/ɪnˈfleɪʃən/", pos: "n.", meanings: ["인플레이션", "물가 상승"], example: "Persistent inflation erodes the purchasing power of savings and disproportionately harms low-income households.", exampleKr: "지속적인 인플레이션은 저축의 구매력을 잠식하고 저소득 가구에 불균형적으로 피해를 준다." },
      { word: "deflation", pron: "/dɪˈfleɪʃən/", pos: "n.", meanings: ["디플레이션", "물가 하락"], example: "Deflation can become a self-reinforcing trap as consumers delay purchases expecting prices to fall further.", exampleKr: "디플레이션은 소비자들이 가격이 더 하락하기를 기대하며 구매를 연기함에 따라 자기 강화 함정이 될 수 있다." },
      { word: "recession", pron: "/rɪˈseʃən/", pos: "n.", meanings: ["경기 침체", "불황"], example: "A recession is technically defined as two consecutive quarters of negative economic growth.", exampleKr: "경기 침체는 기술적으로 두 분기 연속 마이너스 경제 성장으로 정의된다." },
      { word: "austerity", pron: "/ɒˈsterɪti/", pos: "n.", meanings: ["긴축", "내핍", "절약"], example: "Critics argued that austerity measures reduced public services exactly when people needed them most.", exampleKr: "비평가들은 긴축 조치가 사람들이 가장 필요로 할 때 정확히 공공 서비스를 축소했다고 주장했다." },
      { word: "fiscal", pron: "/ˈfɪskəl/", pos: "adj.", meanings: ["재정의", "회계의"], example: "The government's fiscal position deteriorated sharply after emergency spending during the crisis.", exampleKr: "정부의 재정 상황은 위기 동안 긴급 지출 후 급격히 악화되었다." },
      { word: "monetary", pron: "/ˈmɒnɪtri/", pos: "adj.", meanings: ["통화의", "화폐의"], example: "The central bank's monetary policy committee voted to raise interest rates for the third consecutive time.", exampleKr: "중앙은행의 통화 정책 위원회는 세 번 연속으로 금리 인상에 투표했다." },
      { word: "collateral", pron: "/kəˈlætərəl/", pos: "n./adj.", meanings: ["담보", "부수적인", "측면의"], example: "Banks require collateral to secure loans, reducing the risk of losses if the borrower defaults.", exampleKr: "은행은 차용인이 채무를 이행하지 않을 경우 손실 위험을 줄이기 위해 대출을 담보로 담보물을 요구한다." },
      { word: "equity", pron: "/ˈekwɪti/", pos: "n.", meanings: ["주식", "자기자본", "공평성"], example: "Private equity firms typically look for undervalued companies they can restructure and sell at a profit.", exampleKr: "사모 펀드 회사들은 일반적으로 구조 조정하여 수익을 남기고 매각할 수 있는 저평가된 기업들을 찾는다." },
      { word: "hedge", pron: "/hedʒ/", pos: "v./n.", meanings: ["위험 분산하다", "헷지", "방어 수단"], example: "Investors hedge their portfolios using derivatives to offset potential losses in volatile markets.", exampleKr: "투자자들은 변동성이 큰 시장에서 잠재적 손실을 상쇄하기 위해 파생상품을 사용하여 포트폴리오를 헤지한다." },
      { word: "arbitrage", pron: "/ˈɑːrbɪtrɑːʒ/", pos: "n.", meanings: ["차익거래", "재정 거래"], example: "High-frequency traders exploit tiny price discrepancies through arbitrage across different exchanges.", exampleKr: "고빈도 거래자들은 서로 다른 거래소 간의 차익거래를 통해 작은 가격 불일치를 이용한다." },
      { word: "leverage", pron: "/ˈlevərɪdʒ/", pos: "n./v.", meanings: ["레버리지", "지렛대 효과", "활용하다"], example: "Excessive leverage amplifies gains in good times but can lead to catastrophic losses in downturns.", exampleKr: "과도한 레버리지는 호황기에는 이익을 증폭시키지만 불황기에는 치명적인 손실로 이어질 수 있다." },
      { word: "portfolio", pron: "/pɔːrtˈfoʊlioʊ/", pos: "n.", meanings: ["포트폴리오", "투자 자산", "작품집"], example: "A diversified portfolio across asset classes reduces exposure to any single market's volatility.", exampleKr: "자산 클래스 전반에 걸쳐 다각화된 포트폴리오는 단일 시장의 변동성에 대한 노출을 줄인다." },
      { word: "volatility", pron: "/ˌvɒləˈtɪlɪti/", pos: "n.", meanings: ["변동성", "불안정성"], example: "Market volatility spiked dramatically when the unexpected election result came through.", exampleKr: "예상치 못한 선거 결과가 나왔을 때 시장 변동성이 급격히 치솟았다." },
      { word: "dividend", pron: "/ˈdɪvɪdend/", pos: "n.", meanings: ["배당금", "이익"], example: "Companies that consistently pay dividends attract investors seeking stable income streams.", exampleKr: "일관되게 배당금을 지급하는 기업들은 안정적인 수입원을 원하는 투자자들을 끌어들인다." },
      { word: "commodity", pron: "/kəˈmɒdɪti/", pos: "n.", meanings: ["원자재", "상품", "물자"], example: "Oil remains the world's most traded commodity, with its price influencing economies globally.", exampleKr: "석유는 여전히 세계에서 가장 많이 거래되는 원자재로, 그 가격이 전 세계 경제에 영향을 미친다." },
      { word: "quantitative easing", pron: "/ˈkwɒntɪtətɪv ˈiːzɪŋ/", pos: "n.", meanings: ["양적 완화"], example: "The central bank launched quantitative easing, purchasing government bonds to inject money into the economy.", exampleKr: "중앙은행은 경제에 돈을 주입하기 위해 국채를 매입하는 양적 완화를 시작했다." },
      { word: "stagflation", pron: "/stæɡˈfleɪʃən/", pos: "n.", meanings: ["스태그플레이션", "경기 침체형 인플레이션"], example: "The 1970s oil shocks triggered a period of stagflation that conventional monetary policy struggled to address.", exampleKr: "1970년대 석유 충격은 전통적인 통화 정책이 해결하기 어려운 스태그플레이션 기간을 촉발했다." },
      { word: "yield", pron: "/jiːld/", pos: "n./v.", meanings: ["수익률", "산출량", "산출하다"], example: "When bond prices fall, their yield rises, reflecting higher compensation for risk.", exampleKr: "채권 가격이 하락하면 위험에 대한 보상이 높아지는 것을 반영하여 수익률이 상승한다." },
      { word: "default", pron: "/dɪˈfɔːlt/", pos: "n./v.", meanings: ["채무 불이행", "디폴트", "기본값"], example: "A sovereign default occurs when a government cannot or will not meet its debt obligations.", exampleKr: "국가 부도는 정부가 채무 의무를 이행할 수 없거나 이행하지 않을 때 발생한다." }
    ]
  };

  VOCA_DATA[104] = {
    theme: "법률·사법 어휘",
    words: [
      { word: "jurisprudence", pron: "/ˌdʒʊərɪsˈpruːdəns/", pos: "n.", meanings: ["법학", "법철학", "판례법"], example: "Constitutional jurisprudence evolves over time as courts interpret founding documents in new social contexts.", exampleKr: "헌법 법학은 법원이 새로운 사회적 맥락에서 헌법 문서를 해석함에 따라 시간이 지남에 따라 발전한다." },
      { word: "litigation", pron: "/ˌlɪtɪˈɡeɪʃən/", pos: "n.", meanings: ["소송", "법적 분쟁"], example: "Lengthy commercial litigation can cost companies millions in legal fees before a verdict is reached.", exampleKr: "장기 상업 소송은 판결에 도달하기 전에 기업들에게 수백만 달러의 법률 비용이 들 수 있다." },
      { word: "plaintiff", pron: "/ˈpleɪntɪf/", pos: "n.", meanings: ["원고", "고소인"], example: "The plaintiff claimed substantial damages for losses suffered due to the defendant's negligence.", exampleKr: "원고는 피고의 과실로 인한 손실에 대해 상당한 손해배상을 청구했다." },
      { word: "defendant", pron: "/dɪˈfendənt/", pos: "n.", meanings: ["피고", "피고인"], example: "The defendant maintained their innocence throughout the lengthy and high-profile trial.", exampleKr: "피고는 길고 세간의 이목을 집중시킨 재판 내내 무죄를 주장했다." },
      { word: "jurisdiction", pron: "/ˌdʒʊərɪsˈdɪkʃən/", pos: "n.", meanings: ["관할권", "사법권", "재판 관할"], example: "Cybercrimes often cross national borders, raising difficult questions about jurisdiction.", exampleKr: "사이버 범죄는 종종 국경을 넘어 관할권에 대한 어려운 문제를 제기한다." },
      { word: "subpoena", pron: "/səˈpiːnə/", pos: "n./v.", meanings: ["소환장", "법원 출두 명령", "소환하다"], example: "The congressional committee issued a subpoena compelling the executive to produce all internal documents.", exampleKr: "의회 위원회는 임원이 모든 내부 문서를 제출하도록 강요하는 소환장을 발부했다." },
      { word: "indictment", pron: "/ɪnˈdaɪtmənt/", pos: "n.", meanings: ["기소", "고발", "강한 비판"], example: "The grand jury handed down an indictment on twelve separate counts of wire fraud.", exampleKr: "대배심은 12개의 개별 전신 사기 혐의에 대한 기소를 결정했다." },
      { word: "acquittal", pron: "/əˈkwɪtəl/", pos: "n.", meanings: ["무죄 방면", "무죄 선고"], example: "The acquittal shocked many observers who believed the evidence against the accused was overwhelming.", exampleKr: "무죄 선고는 피고에 대한 증거가 압도적이라고 믿었던 많은 관찰자들을 충격에 빠뜨렸다." },
      { word: "injunction", pron: "/ɪnˈdʒʌŋkʃən/", pos: "n.", meanings: ["법원 명령", "금지 명령"], example: "The court granted an injunction preventing the company from destroying the documents pending trial.", exampleKr: "법원은 재판 계류 중 회사가 문서를 파기하는 것을 막는 금지 명령을 허가했다." },
      { word: "affidavit", pron: "/ˌæfɪˈdeɪvɪt/", pos: "n.", meanings: ["선서 진술서", "공증 진술서"], example: "The witness submitted a signed affidavit confirming the sequence of events on the night in question.", exampleKr: "증인은 문제의 밤 사건 순서를 확인하는 서명된 선서 진술서를 제출했다." },
      { word: "arbitration", pron: "/ˌɑːrbɪˈtreɪʃən/", pos: "n.", meanings: ["중재", "중재 재판"], example: "The contract specified that all disputes would be resolved through binding arbitration rather than court proceedings.", exampleKr: "계약은 모든 분쟁이 법원 절차 대신 구속력 있는 중재를 통해 해결될 것으로 명시했다." },
      { word: "statute", pron: "/ˈstætʃuːt/", pos: "n.", meanings: ["법령", "성문법", "규정"], example: "Under the statute of limitations, the lawsuit could not be filed more than three years after the incident.", exampleKr: "공소시효 법령에 따라 사건 발생 후 3년 이상이 지난 후에는 소송을 제기할 수 없었다." },
      { word: "tort", pron: "/tɔːrt/", pos: "n.", meanings: ["불법행위", "민사상 위법행위"], example: "Negligence is the most commonly litigated tort in civil law jurisdictions worldwide.", exampleKr: "과실은 전 세계 민법 관할권에서 가장 흔하게 소송되는 불법행위이다." },
      { word: "habeas corpus", pron: "/ˌheɪbiəs ˈkɔːrpəs/", pos: "n.", meanings: ["인신 보호 영장"], example: "The right of habeas corpus prevents governments from detaining citizens indefinitely without charge.", exampleKr: "인신 보호 영장의 권리는 정부가 혐의 없이 시민을 무기한 구금하는 것을 막는다." },
      { word: "deposition", pron: "/ˌdepəˈzɪʃən/", pos: "n.", meanings: ["증언 청취", "선서 증언", "폐위"], example: "During deposition, witnesses answer questions under oath in a process similar to courtroom testimony.", exampleKr: "증언 청취 중에 증인들은 법정 증언과 유사한 절차에서 선서 하에 질문에 답한다." },
      { word: "plea bargain", pron: "/ˈpliː ˌbɑːrɡɪn/", pos: "n.", meanings: ["유죄 협상", "플리 바기닝"], example: "The defendant accepted a plea bargain, agreeing to testify against co-conspirators in exchange for a reduced sentence.", exampleKr: "피고는 감형을 대가로 공모자들에 대해 증언하기로 합의하면서 유죄 협상을 받아들였다." },
      { word: "testimony", pron: "/ˈtestɪmoʊni/", pos: "n.", meanings: ["증언", "증거", "고백"], example: "Eyewitness testimony is notoriously unreliable and has contributed to many wrongful convictions.", exampleKr: "목격자 증언은 악명 높을 정도로 신뢰할 수 없으며 많은 억울한 유죄 판결에 기여했다." },
      { word: "verdict", pron: "/ˈvɜːrdɪkt/", pos: "n.", meanings: ["평결", "판결", "결론"], example: "The jury deliberated for three days before returning a unanimous verdict of not guilty.", exampleKr: "배심원단은 만장일치로 무죄 평결을 내리기 전에 3일 동안 심의했다." },
      { word: "larceny", pron: "/ˈlɑːrsəni/", pos: "n.", meanings: ["절도죄", "도둑질"], example: "Grand larceny charges require the stolen property to exceed a threshold value set by the jurisdiction.", exampleKr: "중절도 혐의는 도난된 재산이 관할권에서 정한 임계값을 초과하도록 요구한다." },
      { word: "perjury", pron: "/ˈpɜːrdʒəri/", pos: "n.", meanings: ["위증죄", "위증"], example: "The witness faced charges of perjury after it emerged that their sworn testimony was entirely fabricated.", exampleKr: "증인의 선서 증언이 완전히 날조된 것으로 드러난 후 증인은 위증 혐의에 직면했다." }
    ]
  };

  VOCA_DATA[105] = {
    theme: "과학·기술 어휘",
    words: [
      { word: "hypothesis", pron: "/haɪˈpɒθɪsɪs/", pos: "n.", meanings: ["가설", "추정"], example: "A hypothesis must be testable and falsifiable to qualify as legitimate scientific inquiry.", exampleKr: "가설은 정당한 과학적 탐구로 인정받기 위해 검증 가능하고 반증 가능해야 한다." },
      { word: "empirical", pron: "/ɪmˈpɪrɪkəl/", pos: "adj.", meanings: ["경험적인", "실증적인", "실험적인"], example: "Policymakers should base decisions on empirical evidence rather than ideological assumptions.", exampleKr: "정책 입안자들은 이념적 가정보다는 실증적 증거에 기반하여 결정을 내려야 한다." },
      { word: "replication", pron: "/ˌreplɪˈkeɪʃən/", pos: "n.", meanings: ["재현", "복제", "반복 실험"], example: "Scientific findings are only considered robust when independent researchers can achieve replication.", exampleKr: "과학적 발견은 독립적인 연구자들이 재현을 달성할 수 있을 때만 신뢰할 수 있는 것으로 간주된다." },
      { word: "catalyst", pron: "/ˈkætəlɪst/", pos: "n.", meanings: ["촉매", "계기", "변화를 일으키는 것"], example: "Platinum acts as a catalyst in catalytic converters, reducing toxic exhaust emissions.", exampleKr: "백금은 촉매 변환기에서 촉매 역할을 하며 독성 배기 가스 배출을 줄인다." },
      { word: "synthesis", pron: "/ˈsɪnθɪsɪs/", pos: "n.", meanings: ["합성", "종합", "통합"], example: "The synthesis of a new antibiotic compound took over a decade of painstaking laboratory research.", exampleKr: "새로운 항생제 화합물의 합성에는 10년 이상의 힘든 실험실 연구가 걸렸다." },
      { word: "logarithm", pron: "/ˈlɒɡərɪðəm/", pos: "n.", meanings: ["로그", "대수"], example: "The Richter scale uses a logarithm, meaning each integer step represents a tenfold increase in amplitude.", exampleKr: "리히터 척도는 로그를 사용하므로 각 정수 단계는 진폭의 10배 증가를 나타낸다." },
      { word: "genome", pron: "/ˈdʒiːnoʊm/", pos: "n.", meanings: ["유전체", "게놈"], example: "Sequencing the human genome opened up entirely new possibilities in personalised medicine.", exampleKr: "인간 유전체의 서열 분석은 맞춤 의학에서 완전히 새로운 가능성을 열었다." },
      { word: "nanotechnology", pron: "/ˌnænoʊtekˈnɒlədʒi/", pos: "n.", meanings: ["나노기술", "나노공학"], example: "Nanotechnology could allow doctors to deliver drugs directly to cancer cells with minimal side effects.", exampleKr: "나노기술은 의사들이 최소한의 부작용으로 암세포에 직접 약물을 전달할 수 있게 할 수 있다." },
      { word: "quantum", pron: "/ˈkwɒntəm/", pos: "adj./n.", meanings: ["양자의", "양자", "특정량"], example: "Quantum computers exploit the properties of subatomic particles to process information exponentially faster.", exampleKr: "양자 컴퓨터는 아원자 입자의 특성을 이용하여 정보를 기하급수적으로 더 빠르게 처리한다." },
      { word: "fusion", pron: "/ˈfjuːʒən/", pos: "n.", meanings: ["핵융합", "융합", "결합"], example: "Nuclear fusion promises virtually unlimited clean energy if the technical challenges can be overcome.", exampleKr: "핵융합은 기술적 과제를 극복할 수 있다면 사실상 무한한 청정 에너지를 약속한다." },
      { word: "osmosis", pron: "/ɒzˈmoʊsɪs/", pos: "n.", meanings: ["삼투압", "삼투 현상"], example: "Osmosis regulates water balance in cells throughout the body's tissues and organs.", exampleKr: "삼투압은 신체의 조직과 기관 전체에서 세포의 수분 균형을 조절한다." },
      { word: "entropy", pron: "/ˈentrəpi/", pos: "n.", meanings: ["엔트로피", "무질서도", "열역학적 상태"], example: "The second law of thermodynamics states that entropy in a closed system always increases over time.", exampleKr: "열역학 제2법칙은 닫힌 계에서 엔트로피는 항상 시간이 지남에 따라 증가한다고 명시한다." },
      { word: "isotope", pron: "/ˈaɪsətəʊp/", pos: "n.", meanings: ["동위원소"], example: "Radioactive isotopes are used in medical imaging to help diagnose conditions non-invasively.", exampleKr: "방사성 동위원소는 비침습적으로 질환을 진단하는 데 도움이 되는 의료 영상에 사용된다." },
      { word: "mitosis", pron: "/maɪˈtoʊsɪs/", pos: "n.", meanings: ["유사분열", "체세포 분열"], example: "Cancerous tumours grow through uncontrolled mitosis, dividing far more rapidly than healthy cells.", exampleKr: "암성 종양은 통제되지 않은 유사분열을 통해 성장하며, 건강한 세포보다 훨씬 빠르게 분열한다." },
      { word: "polymer", pron: "/ˈpɒlɪmər/", pos: "n.", meanings: ["폴리머", "중합체", "고분자 화합물"], example: "Many everyday materials, from plastics to proteins, are made up of polymer chains of repeating units.", exampleKr: "플라스틱에서 단백질에 이르기까지 많은 일상적인 물질은 반복 단위의 폴리머 사슬로 이루어져 있다." },
      { word: "radioactive", pron: "/ˌreɪdioʊˈæktɪv/", pos: "adj.", meanings: ["방사성의", "방사능이 있는"], example: "Radioactive waste from nuclear power plants must be stored safely for thousands of years.", exampleKr: "원자력 발전소의 방사성 폐기물은 수천 년 동안 안전하게 보관되어야 한다." },
      { word: "semiconductor", pron: "/ˌsemɪkənˈdʌktər/", pos: "n.", meanings: ["반도체"], example: "Semiconductors are the foundation of modern electronics, from smartphones to supercomputers.", exampleKr: "반도체는 스마트폰에서 슈퍼컴퓨터에 이르기까지 현대 전자 기기의 기초이다." },
      { word: "spectrum", pron: "/ˈspektrəm/", pos: "n.", meanings: ["스펙트럼", "범위", "분포"], example: "The electromagnetic spectrum includes visible light, radio waves, and X-rays at different wavelengths.", exampleKr: "전자기 스펙트럼은 서로 다른 파장의 가시광선, 라디오파, X선을 포함한다." },
      { word: "velocity", pron: "/vəˈlɒsɪti/", pos: "n.", meanings: ["속도", "속력"], example: "Terminal velocity is reached when air resistance exactly balances the gravitational force on a falling object.", exampleKr: "종단 속도는 공기 저항이 낙하하는 물체에 대한 중력과 정확히 균형을 이룰 때 도달된다." },
      { word: "wavelength", pron: "/ˈweɪvleŋθ/", pos: "n.", meanings: ["파장", "공감대"], example: "Violet light has the shortest wavelength in the visible spectrum and the highest energy of visible colours.", exampleKr: "보라색 빛은 가시 스펙트럼에서 가장 짧은 파장을 가지며 가시 색상 중 가장 높은 에너지를 가진다." }
    ]
  };

  VOCA_DATA[106] = {
    theme: "심리·행동 어휘",
    words: [
      { word: "cognition", pron: "/kɒɡˈnɪʃən/", pos: "n.", meanings: ["인지", "인식", "지각"], example: "Research into cognition has revealed that the human brain processes information in parallel streams.", exampleKr: "인지 연구를 통해 인간의 뇌가 정보를 병렬 흐름으로 처리한다는 것이 밝혀졌다." },
      { word: "bias", pron: "/ˈbaɪəs/", pos: "n.", meanings: ["편향", "편견", "선입견"], example: "Confirmation bias leads people to seek information that supports what they already believe.", exampleKr: "확증 편향은 사람들이 이미 믿고 있는 것을 지지하는 정보를 찾도록 이끈다." },
      { word: "subconscious", pron: "/ˌsʌbˈkɒnʃəs/", pos: "adj./n.", meanings: ["잠재의식의", "잠재의식"], example: "Many of our daily decisions are driven by subconscious processes we are not aware of.", exampleKr: "우리의 일상적인 결정 중 많은 부분이 우리가 인식하지 못하는 잠재의식적 과정에 의해 이루어진다." },
      { word: "cognitive dissonance", pron: "/ˈkɒɡnətɪv ˈdɪsənəns/", pos: "n.", meanings: ["인지 부조화"], example: "Cognitive dissonance arises when a person holds two contradictory beliefs simultaneously.", exampleKr: "인지 부조화는 사람이 두 가지 모순되는 믿음을 동시에 가질 때 발생한다." },
      { word: "intrinsic motivation", pron: "/ɪnˈtrɪnsɪk ˌmoʊtɪˈveɪʃən/", pos: "n.", meanings: ["내재적 동기"], example: "Students driven by intrinsic motivation learn more deeply than those motivated purely by grades.", exampleKr: "내재적 동기에 의해 이끌리는 학생들은 순전히 성적에 의해 동기 부여된 학생들보다 더 깊이 배운다." },
      { word: "empathy", pron: "/ˈempəθi/", pos: "n.", meanings: ["공감", "감정이입"], example: "Empathy is the ability to understand and share the feelings of another person.", exampleKr: "공감은 다른 사람의 감정을 이해하고 공유하는 능력이다." },
      { word: "anxiety", pron: "/æŋˈzaɪəti/", pos: "n.", meanings: ["불안", "걱정", "염려"], example: "Generalised anxiety disorder causes persistent worry that is disproportionate to actual circumstances.", exampleKr: "범불안장애는 실제 상황에 비해 과도한 지속적인 걱정을 유발한다." },
      { word: "phobia", pron: "/ˈfoʊbiə/", pos: "n.", meanings: ["공포증", "공포"], example: "A specific phobia of spiders affects millions of people and can be treated with exposure therapy.", exampleKr: "거미에 대한 특정 공포증은 수백만 명에게 영향을 미치며 노출 치료로 치료할 수 있다." },
      { word: "resilience", pron: "/rɪˈzɪliəns/", pos: "n.", meanings: ["회복력", "탄력성"], example: "Children who develop resilience early cope far better with academic pressures and social challenges.", exampleKr: "일찍 회복력을 기른 아이들은 학업 압박과 사회적 도전에 훨씬 더 잘 대처한다." },
      { word: "attachment theory", pron: "/əˈtætʃmənt ˈθɪəri/", pos: "n.", meanings: ["애착 이론"], example: "Attachment theory suggests that early bonds with caregivers shape a person's relationships throughout life.", exampleKr: "애착 이론은 돌봄 제공자와의 초기 유대가 평생 동안 사람의 관계를 형성한다고 제안한다." },
      { word: "reinforcement", pron: "/ˌriːɪnˈfɔːrsmənt/", pos: "n.", meanings: ["강화", "보강", "강화 요인"], example: "Positive reinforcement is more effective than punishment in shaping long-term behaviour.", exampleKr: "긍정적 강화는 장기적인 행동을 형성하는 데 처벌보다 더 효과적이다." },
      { word: "narcissism", pron: "/ˈnɑːrsɪsɪzəm/", pos: "n.", meanings: ["자기애", "나르시시즘", "자아도취"], example: "Clinical narcissism is characterised by an inflated sense of self-importance and lack of empathy.", exampleKr: "임상적 자기애는 과장된 자기 중요성 감각과 공감 능력 부재가 특징이다." },
      { word: "perception", pron: "/pəˈsepʃən/", pos: "n.", meanings: ["인식", "지각", "인지"], example: "Our perception of colour depends on context, lighting, and the brain's interpretation of signals.", exampleKr: "색에 대한 우리의 인식은 맥락, 조명, 그리고 뇌의 신호 해석에 따라 달라진다." },
      { word: "trauma", pron: "/ˈtrɔːmə/", pos: "n.", meanings: ["트라우마", "외상", "정신적 충격"], example: "Unresolved childhood trauma can manifest in anxiety, depression, and relationship difficulties in adulthood.", exampleKr: "해결되지 않은 어린 시절의 트라우마는 성인기에 불안, 우울, 관계 어려움으로 나타날 수 있다." },
      { word: "habituation", pron: "/həˌbɪtʃuˈeɪʃən/", pos: "n.", meanings: ["습관화", "둔감화"], example: "Habituation explains why we stop noticing background sounds that we initially found distracting.", exampleKr: "습관화는 처음에는 주의를 분산시키던 배경 소음을 왜 더 이상 의식하지 못하는지를 설명한다." },
      { word: "self-efficacy", pron: "/self ˈefɪkəsi/", pos: "n.", meanings: ["자기 효능감"], example: "High self-efficacy belief is one of the strongest predictors of academic and professional success.", exampleKr: "높은 자기 효능감 믿음은 학업적, 직업적 성공의 가장 강력한 예측 변수 중 하나이다." },
      { word: "attribution", pron: "/ˌætrɪˈbjuːʃən/", pos: "n.", meanings: ["귀인", "귀속", "원인 돌리기"], example: "People with an internal attribution style tend to take personal responsibility for both successes and failures.", exampleKr: "내적 귀인 양식을 가진 사람들은 성공과 실패 모두에 대해 개인적인 책임을 지는 경향이 있다." },
      { word: "conditioning", pron: "/kənˈdɪʃənɪŋ/", pos: "n.", meanings: ["조건화", "조건 반응"], example: "Classical conditioning, first described by Pavlov, shows how associations between stimuli can alter behaviour.", exampleKr: "파블로프가 처음 설명한 고전적 조건화는 자극 간의 연합이 어떻게 행동을 변화시킬 수 있는지를 보여준다." },
      { word: "groupthink", pron: "/ˈɡruːpθɪŋk/", pos: "n.", meanings: ["집단 사고", "집단적 동조"], example: "Groupthink in leadership teams can stifle critical analysis and lead to disastrous collective decisions.", exampleKr: "리더십 팀에서의 집단 사고는 비판적 분석을 억누르고 재앙적인 집단적 결정으로 이어질 수 있다." },
      { word: "catharsis", pron: "/kəˈθɑːrsɪs/", pos: "n.", meanings: ["카타르시스", "정화", "감정 해소"], example: "Writing a diary can provide catharsis by allowing people to process difficult emotions safely.", exampleKr: "일기를 쓰는 것은 사람들이 어려운 감정을 안전하게 처리할 수 있게 하여 카타르시스를 제공할 수 있다." }
    ]
  };

  VOCA_DATA[107] = {
    theme: "사회학·문화 어휘",
    words: [
      { word: "assimilation", pron: "/əˌsɪmɪˈleɪʃən/", pos: "n.", meanings: ["동화", "흡수", "문화 동화"], example: "Rapid cultural assimilation can risk the erasure of minority languages and traditional practices.", exampleKr: "급속한 문화 동화는 소수 언어와 전통 관습의 소멸 위험을 초래할 수 있다." },
      { word: "pluralism", pron: "/ˈplʊərəlɪzəm/", pos: "n.", meanings: ["다원주의", "복수주의"], example: "Cultural pluralism embraces the coexistence of diverse ethnic and religious identities within a single society.", exampleKr: "문화적 다원주의는 단일 사회 내에서 다양한 민족적, 종교적 정체성의 공존을 포용한다." },
      { word: "stigma", pron: "/ˈstɪɡmə/", pos: "n.", meanings: ["낙인", "오명", "편견"], example: "The stigma surrounding mental illness prevents many people from seeking the help they need.", exampleKr: "정신 질환을 둘러싼 낙인은 많은 사람들이 필요한 도움을 구하는 것을 막는다." },
      { word: "stratification", pron: "/ˌstrætɪfɪˈkeɪʃən/", pos: "n.", meanings: ["계층화", "계층 구조"], example: "Social stratification based on wealth determines access to education, healthcare, and opportunity.", exampleKr: "부에 기반한 사회적 계층화는 교육, 의료, 기회에 대한 접근을 결정한다." },
      { word: "hegemony", pron: "/hɪˈdʒemənɪ/", pos: "n.", meanings: ["패권", "헤게모니", "주도권"], example: "Cultural hegemony describes how dominant groups shape the norms and values of an entire society.", exampleKr: "문화적 패권은 지배 집단이 어떻게 전체 사회의 규범과 가치를 형성하는지를 설명한다." },
      { word: "diaspora", pron: "/daɪˈæspərə/", pos: "n.", meanings: ["디아스포라", "이산 공동체"], example: "The Irish diaspora spread across every continent following the Great Famine of the 1840s.", exampleKr: "아일랜드 디아스포라는 1840년대 대기근 이후 모든 대륙으로 퍼졌다." },
      { word: "xenophobia", pron: "/ˌzenəˈfoʊbiə/", pos: "n.", meanings: ["외국인 혐오", "이방인 공포증"], example: "Economic hardship can give rise to xenophobia as people search for scapegoats for their difficulties.", exampleKr: "경제적 어려움은 사람들이 자신의 어려움에 대한 희생양을 찾으면서 외국인 혐오를 초래할 수 있다." },
      { word: "multiculturalism", pron: "/ˌmʌltiˈkʌltʃərəlɪzəm/", pos: "n.", meanings: ["다문화주의"], example: "Canada's official policy of multiculturalism encourages citizens to maintain their distinct cultural identities.", exampleKr: "캐나다의 공식적인 다문화주의 정책은 시민들이 자신의 고유한 문화적 정체성을 유지하도록 장려한다." },
      { word: "reciprocity", pron: "/ˌresɪˈprɒsɪti/", pos: "n.", meanings: ["상호성", "호혜", "상호 관계"], example: "Reciprocity is fundamental to social bonds; people feel obliged to return favours and gifts.", exampleKr: "상호성은 사회적 유대의 근본이다; 사람들은 호의와 선물을 돌려줄 의무감을 느낀다." },
      { word: "taboo", pron: "/təˈbuː/", pos: "n./adj.", meanings: ["금기", "터부", "금기시된"], example: "Discussing death openly was long considered taboo in many Western cultures.", exampleKr: "죽음에 대해 공개적으로 이야기하는 것은 서양 문화의 많은 곳에서 오랫동안 금기시되었다." },
      { word: "norm", pron: "/nɔːrm/", pos: "n.", meanings: ["규범", "기준", "표준"], example: "Social norms govern everyday behaviour in ways that are often invisible to those who follow them.", exampleKr: "사회적 규범은 그것을 따르는 사람들에게 종종 보이지 않는 방식으로 일상적인 행동을 지배한다." },
      { word: "solidarity", pron: "/ˌsɒlɪˈdærɪti/", pos: "n.", meanings: ["연대", "단결", "결속"], example: "International solidarity among workers across borders is central to global labour rights movements.", exampleKr: "국경을 초월한 노동자들 사이의 국제적 연대는 글로벌 노동권 운동의 핵심이다." },
      { word: "subculture", pron: "/ˈsʌbkʌltʃər/", pos: "n.", meanings: ["하위문화", "서브컬처"], example: "The punk subculture of the 1970s was both a musical movement and a form of political protest.", exampleKr: "1970년대 펑크 하위문화는 음악 운동이자 정치적 저항의 한 형태였다." },
      { word: "socialisation", pron: "/ˌsoʊʃəlaɪˈzeɪʃən/", pos: "n.", meanings: ["사회화", "사회 적응"], example: "Primary socialisation occurs within the family and shapes a child's fundamental values and identity.", exampleKr: "일차적 사회화는 가족 안에서 발생하며 아이의 근본적인 가치관과 정체성을 형성한다." },
      { word: "inequality", pron: "/ˌɪnɪˈkwɒlɪti/", pos: "n.", meanings: ["불평등", "불균형"], example: "Growing income inequality is linked to increased social tensions and declining civic trust.", exampleKr: "증가하는 소득 불평등은 사회적 긴장의 증가와 시민 신뢰의 감소와 연관되어 있다." },
      { word: "marginalisation", pron: "/ˌmɑːrdʒɪnəlaɪˈzeɪʃən/", pos: "n.", meanings: ["소외", "주변화"], example: "The marginalisation of indigenous peoples from political processes perpetuates historical injustices.", exampleKr: "원주민들의 정치 과정에서의 소외는 역사적 불의를 영속시킨다." },
      { word: "meritocracy", pron: "/ˌmerɪˈtɒkrəsi/", pos: "n.", meanings: ["능력주의", "실력 사회"], example: "Critics argue that meritocracy is a myth because starting conditions are rarely equal.", exampleKr: "비평가들은 출발 조건이 거의 평등하지 않기 때문에 능력주의는 신화에 불과하다고 주장한다." },
      { word: "gentrification", pron: "/ˌdʒentrɪfɪˈkeɪʃən/", pos: "n.", meanings: ["젠트리피케이션", "고급화"], example: "Gentrification of inner-city neighbourhoods often displaces long-term residents who can no longer afford rents.", exampleKr: "도심 지역의 젠트리피케이션은 종종 더 이상 임대료를 감당할 수 없는 장기 거주자들을 내쫓는다." },
      { word: "cultural relativism", pron: "/ˈkʌltʃərəl ˈrelətɪvɪzəm/", pos: "n.", meanings: ["문화 상대주의"], example: "Cultural relativism holds that practices should be understood within their own cultural framework.", exampleKr: "문화 상대주의는 관습이 자신의 문화적 틀 안에서 이해되어야 한다고 주장한다." },
      { word: "social mobility", pron: "/ˈsoʊʃəl moʊˈbɪlɪti/", pos: "n.", meanings: ["사회 이동성"], example: "Education has historically been the primary vehicle for upward social mobility across generations.", exampleKr: "교육은 역사적으로 세대를 거쳐 상향 사회 이동성을 위한 주요 수단이었다." }
    ]
  };

  VOCA_DATA[108] = {
    theme: "철학·사상 어휘",
    words: [
      { word: "existentialism", pron: "/ˌeɡzɪˈstenʃəlɪzəm/", pos: "n.", meanings: ["실존주의"], example: "Existentialism holds that individuals are free to define their own meaning in an absurd universe.", exampleKr: "실존주의는 개인이 부조리한 우주에서 자신만의 의미를 자유롭게 정의할 수 있다고 주장한다." },
      { word: "empiricism", pron: "/ɪmˈpɪrɪsɪzəm/", pos: "n.", meanings: ["경험주의", "실증주의"], example: "Empiricism argues that all knowledge ultimately derives from sensory experience rather than innate ideas.", exampleKr: "경험주의는 모든 지식이 선천적 관념이 아닌 감각적 경험에서 궁극적으로 비롯된다고 주장한다." },
      { word: "rationalism", pron: "/ˈræʃənəlɪzəm/", pos: "n.", meanings: ["합리주의", "이성주의"], example: "Descartes' rationalism posited that certain truths can be known through reason alone, without experience.", exampleKr: "데카르트의 합리주의는 특정 진리가 경험 없이 오직 이성만으로 알 수 있다고 주장했다." },
      { word: "utilitarianism", pron: "/juːˌtɪlɪˈteəriənɪzəm/", pos: "n.", meanings: ["공리주의"], example: "Utilitarianism judges actions by their consequences, favouring whatever produces the greatest happiness.", exampleKr: "공리주의는 결과에 의해 행동을 판단하며, 가장 큰 행복을 생산하는 것을 선호한다." },
      { word: "nihilism", pron: "/ˈnaɪɪlɪzəm/", pos: "n.", meanings: ["허무주의", "니힐리즘"], example: "Nihilism rejects all religious and moral principles, holding that life is without meaning or purpose.", exampleKr: "허무주의는 모든 종교적, 도덕적 원칙을 거부하며 삶이 의미나 목적 없다고 주장한다." },
      { word: "determinism", pron: "/dɪˈtɜːrmɪnɪzəm/", pos: "n.", meanings: ["결정론"], example: "Hard determinism holds that every human action is the inevitable result of prior causes.", exampleKr: "강한 결정론은 모든 인간의 행동이 이전 원인들의 불가피한 결과라고 주장한다." },
      { word: "dialectic", pron: "/ˌdaɪəˈlektɪk/", pos: "n.", meanings: ["변증법", "변증법적 논의"], example: "Hegel's dialectic describes history as a process of thesis, antithesis, and synthesis.", exampleKr: "헤겔의 변증법은 역사를 정-반-합의 과정으로 설명한다." },
      { word: "epistemology", pron: "/ɪˌpɪstɪˈmɒlədʒi/", pos: "n.", meanings: ["인식론", "지식론"], example: "Epistemology asks fundamental questions about what we can know and how we can know it.", exampleKr: "인식론은 우리가 무엇을 알 수 있고 어떻게 알 수 있는지에 대한 근본적인 질문을 던진다." },
      { word: "ontology", pron: "/ɒnˈtɒlədʒi/", pos: "n.", meanings: ["존재론", "본체론"], example: "Ontology is the branch of philosophy that examines the fundamental nature of being and existence.", exampleKr: "존재론은 존재와 실재의 근본적인 본질을 탐구하는 철학의 한 분야이다." },
      { word: "pragmatism", pron: "/ˈpræɡmətɪzəm/", pos: "n.", meanings: ["실용주의"], example: "Pragmatism evaluates ideas by their practical consequences and usefulness in the real world.", exampleKr: "실용주의는 아이디어를 현실 세계에서의 실제적 결과와 유용성에 의해 평가한다." },
      { word: "solipsism", pron: "/ˈsɒlɪpsɪzəm/", pos: "n.", meanings: ["유아론", "독아론"], example: "Solipsism is the extreme philosophical view that only one's own mind is certain to exist.", exampleKr: "유아론은 자신의 마음만이 확실히 존재한다는 극단적인 철학적 견해이다." },
      { word: "deontology", pron: "/ˌdiːɒnˈtɒlədʒi/", pos: "n.", meanings: ["의무론", "도덕 의무론"], example: "Deontological ethics holds that some actions are inherently right or wrong regardless of their consequences.", exampleKr: "의무론적 윤리는 일부 행동이 결과에 상관없이 본질적으로 옳거나 그르다고 주장한다." },
      { word: "stoicism", pron: "/ˈstoʊɪsɪzəm/", pos: "n.", meanings: ["스토아 철학", "금욕주의"], example: "Stoicism teaches that we can find peace by focusing on what we can control and accepting what we cannot.", exampleKr: "스토아 철학은 우리가 통제할 수 있는 것에 집중하고 통제할 수 없는 것을 받아들이면 평화를 찾을 수 있다고 가르친다." },
      { word: "phenomenology", pron: "/fɪˌnɒmɪˈnɒlədʒi/", pos: "n.", meanings: ["현상학"], example: "Phenomenology examines the structures of conscious experience from the perspective of the first person.", exampleKr: "현상학은 1인칭 시각에서 의식적 경험의 구조를 탐구한다." },
      { word: "agnosticism", pron: "/æɡˈnɒstɪsɪzəm/", pos: "n.", meanings: ["불가지론"], example: "Agnosticism holds that the existence or non-existence of a deity cannot be known or proved.", exampleKr: "불가지론은 신의 존재 또는 비존재를 알 수 없거나 증명할 수 없다고 주장한다." },
      { word: "transcendentalism", pron: "/ˌtrænsenˈdentəlɪzəm/", pos: "n.", meanings: ["초월주의"], example: "American transcendentalism, championed by Emerson, celebrated nature, intuition, and self-reliance.", exampleKr: "에머슨이 주창한 미국 초월주의는 자연, 직관, 자립을 찬양했다." },
      { word: "moral relativism", pron: "/ˈmɒrəl ˈrelətɪvɪzəm/", pos: "n.", meanings: ["도덕 상대주의"], example: "Moral relativism holds that no single ethical framework is universally valid across all cultures and contexts.", exampleKr: "도덕 상대주의는 단 하나의 윤리적 틀이 모든 문화와 맥락에 걸쳐 보편적으로 유효하지 않다고 주장한다." },
      { word: "free will", pron: "/friː wɪl/", pos: "n.", meanings: ["자유 의지"], example: "The debate over free will and determinism is one of the oldest and most contested in all of philosophy.", exampleKr: "자유 의지와 결정론에 대한 논쟁은 철학 전체에서 가장 오래되고 가장 논쟁이 많은 논쟁 중 하나이다." },
      { word: "reductionism", pron: "/rɪˈdʌkʃənɪzəm/", pos: "n.", meanings: ["환원주의"], example: "Reductionism attempts to explain complex phenomena by breaking them down into simpler constituent parts.", exampleKr: "환원주의는 복잡한 현상을 더 단순한 구성 요소로 분해하여 설명하려고 시도한다." },
      { word: "relativism", pron: "/ˈrelətɪvɪzəm/", pos: "n.", meanings: ["상대주의"], example: "Cognitive relativism argues that truth and knowledge are always relative to a particular perspective.", exampleKr: "인식론적 상대주의는 진리와 지식이 항상 특정 관점에 상대적이라고 주장한다." }
    ]
  };

  VOCA_DATA[109] = {
    theme: "역사·문명 어휘",
    words: [
      { word: "imperialism", pron: "/ɪmˈpɪərɪəlɪzəm/", pos: "n.", meanings: ["제국주의"], example: "European imperialism reshaped the political and cultural landscape of Africa, Asia, and the Americas.", exampleKr: "유럽 제국주의는 아프리카, 아시아, 아메리카의 정치적, 문화적 지형을 재편했다." },
      { word: "feudalism", pron: "/ˈfjuːdəlɪzəm/", pos: "n.", meanings: ["봉건제도", "봉건주의"], example: "Feudalism structured medieval society around obligations between lords, knights, and serfs.", exampleKr: "봉건제도는 영주, 기사, 농노 사이의 의무를 중심으로 중세 사회를 구조화했다." },
      { word: "colonialism", pron: "/kəˈloʊniəlɪzəm/", pos: "n.", meanings: ["식민주의"], example: "The legacy of colonialism continues to shape economic and political realities in former colonies.", exampleKr: "식민주의의 유산은 계속해서 이전 식민지들의 경제적, 정치적 현실을 형성하고 있다." },
      { word: "Renaissance", pron: "/ˈrenəsɑːns/", pos: "n.", meanings: ["르네상스", "문예 부흥"], example: "The Renaissance represented a profound intellectual and artistic transformation across Europe from the 14th century.", exampleKr: "르네상스는 14세기부터 유럽 전역에 걸친 심오한 지적, 예술적 변혁을 나타냈다." },
      { word: "Enlightenment", pron: "/ɪnˈlaɪtənmənt/", pos: "n.", meanings: ["계몽주의", "계몽 시대"], example: "The Enlightenment prioritised reason, science, and individual rights over religious authority.", exampleKr: "계몽주의는 종교적 권위보다 이성, 과학, 개인의 권리를 우선시했다." },
      { word: "nationalism", pron: "/ˈnæʃənəlɪzəm/", pos: "n.", meanings: ["민족주의", "국민주의"], example: "The rise of nationalism in the 19th century contributed directly to the outbreak of the First World War.", exampleKr: "19세기 민족주의의 부상은 제1차 세계 대전 발발에 직접적으로 기여했다." },
      { word: "reformation", pron: "/ˌrefəˈmeɪʃən/", pos: "n.", meanings: ["종교 개혁", "개혁"], example: "The Protestant Reformation, initiated by Luther in 1517, permanently divided Western Christianity.", exampleKr: "1517년 루터에 의해 시작된 종교 개혁은 서방 기독교를 영구적으로 분열시켰다." },
      { word: "manifest destiny", pron: "/ˈmænɪfest ˈdestɪni/", pos: "n.", meanings: ["명백한 운명"], example: "The doctrine of manifest destiny was used to justify the westward expansion of the United States.", exampleKr: "명백한 운명 교리는 미국의 서쪽으로의 팽창을 정당화하는 데 사용되었다." },
      { word: "totalitarianism", pron: "/toʊˌtælɪˈteəriənɪzəm/", pos: "n.", meanings: ["전체주의"], example: "Totalitarian regimes use surveillance, propaganda, and terror to maintain total control over society.", exampleKr: "전체주의 정권은 사회에 대한 완전한 통제를 유지하기 위해 감시, 선전, 테러를 사용한다." },
      { word: "revolution", pron: "/ˌrevəˈluːʃən/", pos: "n.", meanings: ["혁명", "대변혁"], example: "The French Revolution dismantled centuries of aristocratic privilege and reshaped European politics.", exampleKr: "프랑스 혁명은 수세기에 걸친 귀족 특권을 해체하고 유럽 정치를 재편했다." },
      { word: "industrialisation", pron: "/ɪnˌdʌstriəlaɪˈzeɪʃən/", pos: "n.", meanings: ["산업화", "공업화"], example: "Rapid industrialisation in 19th-century Britain created both immense wealth and severe urban poverty.", exampleKr: "19세기 영국의 급격한 산업화는 엄청난 부와 심각한 도시 빈곤을 동시에 만들어 냈다." },
      { word: "apartheid", pron: "/əˈpɑːrtheɪt/", pos: "n.", meanings: ["아파르트헤이트", "인종 차별 정책"], example: "The apartheid system in South Africa enforced racial segregation through law until 1994.", exampleKr: "남아프리카의 아파르트헤이트 제도는 1994년까지 법률을 통해 인종 분리를 강요했다." },
      { word: "genocide", pron: "/ˈdʒenəsaɪd/", pos: "n.", meanings: ["학살", "제노사이드", "집단 학살"], example: "The international community failed to intervene to prevent the genocide in Rwanda in 1994.", exampleKr: "국제 사회는 1994년 르완다에서의 집단 학살을 막기 위해 개입하지 못했다." },
      { word: "propaganda", pron: "/ˌprɒpəˈɡændə/", pos: "n.", meanings: ["선전", "프로파간다"], example: "Wartime propaganda shaped public opinion and was used to maintain morale and demonise the enemy.", exampleKr: "전시 선전은 여론을 형성하고 사기를 유지하며 적을 악마화하는 데 사용되었다." },
      { word: "sovereignty", pron: "/ˈsɒvrənti/", pos: "n.", meanings: ["주권", "통치권"], example: "Globalisation has complicated the concept of national sovereignty as states cede authority to international bodies.", exampleKr: "세계화는 국가들이 국제 기구에 권한을 양도함에 따라 국가 주권의 개념을 복잡하게 만들었다." },
      { word: "Cold War", pron: "/koʊld wɔːr/", pos: "n.", meanings: ["냉전"], example: "The Cold War divided the world into US and Soviet spheres of influence for over four decades.", exampleKr: "냉전은 40년 이상 세계를 미국과 소련의 영향권으로 나눴다." },
      { word: "decolonisation", pron: "/diːˌkɒlənɪˈzeɪʃən/", pos: "n.", meanings: ["탈식민지화", "독립"], example: "The wave of decolonisation after World War II fundamentally transformed the map of Africa and Asia.", exampleKr: "2차 세계 대전 이후 탈식민지화의 물결이 아프리카와 아시아의 지도를 근본적으로 변화시켰다." },
      { word: "mercantilism", pron: "/ˈmɜːrkəntɪlɪzəm/", pos: "n.", meanings: ["중상주의"], example: "Mercantilism fuelled European colonial expansion by equating national wealth with accumulated gold and silver.", exampleKr: "중상주의는 국가의 부를 축적된 금과 은과 동일시함으로써 유럽의 식민지 확장을 부추겼다." },
      { word: "secularism", pron: "/ˈsekjʊlərɪzəm/", pos: "n.", meanings: ["세속주의", "정교 분리"], example: "Secularism insists that government and public policy should be based on reason rather than religious doctrine.", exampleKr: "세속주의는 정부와 공공 정책이 종교적 교리가 아닌 이성에 기반해야 한다고 주장한다." },
      { word: "suffrage", pron: "/ˈsʌfrɪdʒ/", pos: "n.", meanings: ["참정권", "투표권"], example: "Universal suffrage, including women's right to vote, was only achieved in most democracies in the 20th century.", exampleKr: "여성의 투표권을 포함한 보통 선거권은 20세기에 들어서야 대부분의 민주주의 국가에서 달성되었다." }
    ]
  };

  VOCA_DATA[110] = {
    theme: "언어학·커뮤니케이션 어휘",
    words: [
      { word: "linguistics", pron: "/lɪŋˈɡwɪstɪks/", pos: "n.", meanings: ["언어학"], example: "Linguistics covers everything from the sounds of language to its social and historical dimensions.", exampleKr: "언어학은 언어의 소리에서부터 사회적, 역사적 차원에 이르기까지 모든 것을 다룬다." },
      { word: "semantics", pron: "/sɪˈmæntɪks/", pos: "n.", meanings: ["의미론", "의미론적 분석"], example: "Semantics studies how meaning is constructed and conveyed in language.", exampleKr: "의미론은 의미가 언어에서 어떻게 구성되고 전달되는지를 연구한다." },
      { word: "syntax", pron: "/ˈsɪntæks/", pos: "n.", meanings: ["통사론", "구문론"], example: "Children acquire the syntax of their mother tongue naturally, without formal instruction.", exampleKr: "아이들은 공식적인 교육 없이 자연스럽게 모국어의 통사론을 습득한다." },
      { word: "phonetics", pron: "/fəˈnetɪks/", pos: "n.", meanings: ["음성학"], example: "Phonetics analyses the physical properties of speech sounds across all human languages.", exampleKr: "음성학은 모든 인간 언어에 걸쳐 발화 음성의 물리적 특성을 분석한다." },
      { word: "pragmatics", pron: "/præɡˈmætɪks/", pos: "n.", meanings: ["화용론"], example: "Pragmatics examines how context shapes the meaning and interpretation of utterances.", exampleKr: "화용론은 맥락이 어떻게 발화의 의미와 해석을 형성하는지를 탐구한다." },
      { word: "metaphor", pron: "/ˈmetəfər/", pos: "n.", meanings: ["은유", "비유"], example: "Politicians use metaphor strategically to frame issues in ways that shape public perception.", exampleKr: "정치인들은 대중의 인식을 형성하는 방식으로 문제를 틀 잡기 위해 전략적으로 은유를 사용한다." },
      { word: "rhetoric", pron: "/ˈretərɪk/", pos: "n.", meanings: ["수사학", "웅변술", "미사여구"], example: "Effective rhetoric persuades audiences by combining logical argument with emotional appeal.", exampleKr: "효과적인 수사학은 논리적 논증과 감정적 호소를 결합하여 청중을 설득한다." },
      { word: "dialect", pron: "/ˈdaɪəlekt/", pos: "n.", meanings: ["방언", "사투리"], example: "Regional dialects enrich a language's diversity but can also create barriers to understanding.", exampleKr: "지역 방언은 언어의 다양성을 풍부하게 하지만 이해에 장벽을 만들 수도 있다." },
      { word: "discourse", pron: "/ˈdɪskɔːrs/", pos: "n.", meanings: ["담론", "담화", "논의"], example: "Public discourse about immigration has become increasingly polarised and emotionally charged.", exampleKr: "이민에 대한 공개적인 담론은 점점 더 양극화되고 감정적으로 격화되었다." },
      { word: "connotation", pron: "/ˌkɒnəˈteɪʃən/", pos: "n.", meanings: ["함축적 의미", "내포", "어감"], example: "The word 'slim' has positive connotations, while 'thin' can sometimes sound pejorative.", exampleKr: "'날씬한'이라는 단어는 긍정적인 함축을 가지고 있는 반면, '마른'은 때때로 경멸적으로 들릴 수 있다." },
      { word: "colloquialism", pron: "/kəˈloʊkwiəlɪzəm/", pos: "n.", meanings: ["구어체 표현", "일상어"], example: "Colloquialisms add authenticity to dialogue in fiction but can make academic writing feel informal.", exampleKr: "구어체 표현은 소설의 대화에 진정성을 더하지만 학술 글쓰기를 비격식적으로 느껴지게 할 수 있다." },
      { word: "euphemism", pron: "/ˈjuːfəmɪzəm/", pos: "n.", meanings: ["완곡어법", "완곡 표현"], example: "Governments sometimes use euphemisms to obscure the harsh realities of military operations.", exampleKr: "정부들은 때때로 군사 작전의 냉혹한 현실을 가리기 위해 완곡어법을 사용한다." },
      { word: "hyperbole", pron: "/haɪˈpɜːrbəli/", pos: "n.", meanings: ["과장법", "과장된 표현"], example: "Advertising frequently relies on hyperbole to make products seem far more desirable than they truly are.", exampleKr: "광고는 제품을 실제보다 훨씬 더 바람직하게 보이게 하기 위해 자주 과장법에 의존한다." },
      { word: "etymology", pron: "/ˌetɪˈmɒlədʒi/", pos: "n.", meanings: ["어원학", "어원"], example: "Understanding etymology helps explain why English contains so many words of Latin and French origin.", exampleKr: "어원학을 이해하면 영어에 왜 라틴어와 프랑스어 기원의 단어가 그렇게 많은지를 설명하는 데 도움이 된다." },
      { word: "bilingualism", pron: "/baɪˈlɪŋɡwəlɪzəm/", pos: "n.", meanings: ["이중 언어 사용", "이중 언어 능력"], example: "Research suggests that bilingualism may delay the onset of dementia and improve cognitive reserve.", exampleKr: "연구에 따르면 이중 언어 사용은 치매 발병을 지연시키고 인지적 여유를 향상시킬 수 있다고 한다." },
      { word: "lingua franca", pron: "/ˌlɪŋɡwə ˈfræŋkə/", pos: "n.", meanings: ["링구아 프랑카", "공통어"], example: "English now functions as the global lingua franca of science, commerce, and aviation.", exampleKr: "영어는 이제 과학, 상업, 항공의 글로벌 공통어 역할을 한다." },
      { word: "code-switching", pron: "/koʊd ˈswɪtʃɪŋ/", pos: "n.", meanings: ["코드 전환", "언어 전환"], example: "Bilingual speakers often engage in code-switching, moving between languages within a single conversation.", exampleKr: "이중 언어 사용자들은 종종 하나의 대화 안에서 언어 사이를 이동하는 코드 전환을 한다." },
      { word: "irony", pron: "/ˈaɪrəni/", pos: "n.", meanings: ["아이러니", "반어법", "역설"], example: "Socratic irony involves feigning ignorance to expose the inconsistencies in another's argument.", exampleKr: "소크라테스식 아이러니는 타인의 논증에서 불일치를 드러내기 위해 무지를 가장하는 것을 포함한다." },
      { word: "ambiguity", pron: "/ˌæmbɪˈɡjuːɪti/", pos: "n.", meanings: ["모호함", "다의성", "불확실성"], example: "Legal documents are drafted to minimise ambiguity, since unclear language can lead to expensive disputes.", exampleKr: "법적 문서는 모호함을 최소화하도록 작성된다, 왜냐하면 불명확한 언어는 비용이 많이 드는 분쟁으로 이어질 수 있기 때문이다." },
      { word: "neologism", pron: "/niˈɒlədʒɪzəm/", pos: "n.", meanings: ["신조어", "새로 만든 말"], example: "Technology has accelerated the creation of neologisms such as 'selfie', 'tweet', and 'podcast'.", exampleKr: "기술은 '셀피', '트윗', '팟캐스트'와 같은 신조어의 생성을 가속화했다." }
    ]
  };

