/**
 * data_days_141_145.js - Day 141~145 단어 데이터
 * data_days_136_140.js 이후에 로드해야 합니다
 */
Object.assign(VOCA_DATA, {
  141: {
    theme: "스타트업·혁신 어휘",
    words: [
      { word: "venture capital", pron: "/ˈventʃər ˈkæpɪtəl/", pos: "n.", meanings: ["벤처 캐피털", "창업 투자"], example: "The startup secured ten million dollars in venture capital to fund its rapid expansion into new markets.", exampleKr: "스타트업은 새로운 시장으로의 급속한 확장을 위해 1,000만 달러의 벤처 캐피털을 확보했다." },
      { word: "pivot", pron: "/ˈpɪvət/", pos: "v./n.", meanings: ["방향 전환하다", "피봇"], example: "After their original product failed, the founders pivoted towards a completely different business model.", exampleKr: "원래 제품이 실패한 후, 창업자들은 완전히 다른 비즈니스 모델로 방향을 전환했다." },
      { word: "unicorn", pron: "/ˈjuːnɪkɔːrn/", pos: "n.", meanings: ["유니콘 기업", "십억 달러 가치 스타트업"], example: "The payments company became a unicorn after its valuation exceeded one billion dollars in its latest funding round.", exampleKr: "그 결제 회사는 최신 펀딩 라운드에서 기업 가치가 10억 달러를 초과한 후 유니콘이 되었다." },
      { word: "disruptive", pron: "/dɪsˈrʌptɪv/", pos: "adj.", meanings: ["혁신적인", "기존 질서를 파괴하는"], example: "Airbnb's disruptive business model transformed the hospitality industry by turning homes into temporary accommodation.", exampleKr: "에어비앤비의 혁신적인 비즈니스 모델은 주택을 임시 숙박으로 전환하여 숙박 산업을 변화시켰다." },
      { word: "incubator", pron: "/ˈɪŋkjʊbeɪtər/", pos: "n.", meanings: ["인큐베이터", "창업 지원 기관"], example: "The university incubator provides startups with office space, mentorship, and access to a network of investors.", exampleKr: "대학 인큐베이터는 스타트업에 사무 공간, 멘토링, 투자자 네트워크 접근을 제공한다." },
      { word: "accelerator", pron: "/əkˈseləreɪtər/", pos: "n.", meanings: ["액셀러레이터", "창업 가속 프로그램"], example: "The startup accelerator compressed two years of growth into four months through intensive training and investor access.", exampleKr: "스타트업 액셀러레이터는 집중적인 훈련과 투자자 접근을 통해 2년간의 성장을 4개월로 압축했다." },
      { word: "MVP", pron: "/ˌem viː ˈpiː/", pos: "n.", meanings: ["최소 기능 제품", "MVP"], example: "Launching an MVP allows a startup to test its core value proposition with real users before full development.", exampleKr: "MVP 출시는 스타트업이 완전한 개발 전에 실제 사용자와 함께 핵심 가치 제안을 테스트할 수 있게 한다." },
      { word: "bootstrapping", pron: "/ˈbuːtstræpɪŋ/", pos: "n.", meanings: ["자력 창업", "부트스트래핑"], example: "By bootstrapping their company for three years, the founders retained full ownership and avoided giving up equity.", exampleKr: "3년간 자력 창업으로 회사를 운영함으로써 창업자들은 완전한 소유권을 유지하고 지분 포기를 피했다." },
      { word: "burn rate", pron: "/bɜːrn reɪt/", pos: "n.", meanings: ["자금 소진 속도", "번 레이트"], example: "With a high burn rate and declining revenues, the startup had only three months of runway remaining.", exampleKr: "높은 자금 소진 속도와 감소하는 수익으로 인해 스타트업에는 3개월의 런웨이만 남아 있었다." },
      { word: "crowdfunding", pron: "/ˈkraʊdfʌndɪŋ/", pos: "n.", meanings: ["크라우드펀딩"], example: "The independent film secured its production budget entirely through crowdfunding from over ten thousand small donors.", exampleKr: "독립 영화는 1만 명 이상의 소액 기부자들의 크라우드펀딩을 통해 제작 예산 전액을 확보했다." },
      { word: "scalable", pron: "/ˈskeɪləbəl/", pos: "adj.", meanings: ["확장 가능한"], example: "Investors look for scalable business models that can grow revenues without proportionally increasing costs.", exampleKr: "투자자들은 비용을 비례적으로 늘리지 않고 수익을 늘릴 수 있는 확장 가능한 비즈니스 모델을 찾는다." },
      { word: "angel investor", pron: "/ˈeɪndʒəl ɪnˈvestər/", pos: "n.", meanings: ["엔젤 투자자"], example: "An angel investor provides early-stage capital in exchange for equity, often offering mentorship alongside funding.", exampleKr: "엔젤 투자자는 지분의 대가로 초기 자본을 제공하며, 종종 자금 지원과 함께 멘토링을 제공한다." },
      { word: "IPO", pron: "/ˌaɪ piː ˈəʊ/", pos: "n.", meanings: ["기업공개", "상장"], example: "The company filed for an IPO, listing its shares on the stock exchange and raising capital from public investors.", exampleKr: "그 회사는 기업공개를 신청하여 주식 거래소에 주식을 상장하고 공개 투자자로부터 자본을 조달했다." },
      { word: "product-market fit", pron: "/ˈprɒdʌkt ˈmɑːrkɪt fɪt/", pos: "n.", meanings: ["제품-시장 적합성"], example: "Achieving product-market fit means the product solves a real problem for a defined group of enthusiastic customers.", exampleKr: "제품-시장 적합성을 달성한다는 것은 제품이 열정적인 고객 집단의 실제 문제를 해결한다는 것을 의미한다." },
      { word: "runway", pron: "/ˈrʌnweɪ/", pos: "n.", meanings: ["런웨이", "잔여 자금 기간"], example: "The startup extended its runway by cutting costs aggressively after its planned funding round fell through.", exampleKr: "스타트업은 계획된 펀딩 라운드가 무산된 후 비용을 공격적으로 삭감하여 런웨이를 연장했다." },
      { word: "exit strategy", pron: "/ˈeksɪt ˈstrætɪdʒi/", pos: "n.", meanings: ["출구 전략"], example: "The founders discussed exit strategy options including acquisition, merger, or an eventual public listing.", exampleKr: "창업자들은 인수, 합병 또는 최종 상장을 포함한 출구 전략 옵션을 논의했다." },
      { word: "disruption", pron: "/dɪsˈrʌpʃən/", pos: "n.", meanings: ["파괴적 혁신", "혼란"], example: "Digital disruption has transformed traditional industries from retail to banking within just two decades.", exampleKr: "디지털 혁신은 불과 20년 만에 소매업에서 금융업까지 전통 산업을 변화시켰다." },
      { word: "first-mover advantage", pron: "/fɜːrst muːvər ədˈvɑːntɪdʒ/", pos: "n.", meanings: ["선점자 우위", "선발 주자 이점"], example: "Amazon's first-mover advantage in e-commerce allowed it to build insurmountable scale before competitors emerged.", exampleKr: "전자상거래에서 아마존의 선점자 우위는 경쟁자가 등장하기 전에 극복할 수 없는 규모를 구축하게 했다." },
      { word: "innovation ecosystem", pron: "/ˌɪnəˈveɪʃən ˈiːkəʊsɪstəm/", pos: "n.", meanings: ["혁신 생태계"], example: "Silicon Valley's innovation ecosystem thrives due to proximity of universities, investors, and experienced talent.", exampleKr: "실리콘 밸리의 혁신 생태계는 대학, 투자자, 경험 있는 인재의 근접성으로 인해 번성한다." },
      { word: "business model canvas", pron: "/ˈbɪznɪs ˈmɒdəl ˈkænvəs/", pos: "n.", meanings: ["비즈니스 모델 캔버스"], example: "The team used a business model canvas to map out all nine key components of their proposed venture.", exampleKr: "팀은 비즈니스 모델 캔버스를 사용하여 제안된 사업의 9가지 주요 구성 요소를 모두 정리했다." }
    ]
  },
  142: {
    theme: "특허·지식재산 어휘",
    words: [
      { word: "patent", pron: "/ˈpeɪtənt/", pos: "n./v.", meanings: ["특허", "특허를 취득하다"], example: "The inventor filed a patent application to protect his novel device from being copied by competitors.", exampleKr: "발명가는 그의 혁신적인 장치가 경쟁자들에 의해 복제되는 것을 보호하기 위해 특허 신청을 했다." },
      { word: "trademark", pron: "/ˈtreɪdmɑːrk/", pos: "n./v.", meanings: ["상표", "상표 등록하다"], example: "The company trademarked its distinctive logo to prevent other brands from using a confusingly similar design.", exampleKr: "그 회사는 다른 브랜드가 혼동스럽게 비슷한 디자인을 사용하는 것을 방지하기 위해 독특한 로고를 상표 등록했다." },
      { word: "copyright", pron: "/ˈkɒpiraɪt/", pos: "n.", meanings: ["저작권"], example: "Copyright automatically protects original creative works such as novels, music, and software from unauthorised copying.", exampleKr: "저작권은 소설, 음악, 소프트웨어와 같은 원본 창작물을 무단 복제로부터 자동으로 보호한다." },
      { word: "intellectual property", pron: "/ˌɪntəˈlektʃʊəl ˈprɒpəti/", pos: "n.", meanings: ["지식 재산권", "IP"], example: "Strong intellectual property protection encourages entrepreneurs to invest in research and creative development.", exampleKr: "강력한 지식 재산 보호는 기업가들이 연구 및 창의적 개발에 투자하도록 장려한다." },
      { word: "infringement", pron: "/ɪnˈfrɪndʒmənt/", pos: "n.", meanings: ["침해", "위반"], example: "The fashion brand pursued legal action for copyright infringement against the manufacturer copying its designs.", exampleKr: "패션 브랜드는 자사 디자인을 복제한 제조업체에 대해 저작권 침해로 법적 조치를 취했다." },
      { word: "licensing", pron: "/ˈlaɪsənsɪŋ/", pos: "n.", meanings: ["라이선싱", "허가 계약"], example: "Technology licensing allows inventors to earn royalties by permitting others to use their patented technology.", exampleKr: "기술 라이선싱은 발명가가 특허 기술의 사용을 다른 사람에게 허가하여 로열티를 벌 수 있게 한다." },
      { word: "royalty", pron: "/ˈrɔɪəlti/", pos: "n.", meanings: ["로열티", "사용료"], example: "Authors receive royalties each time their book is sold or their work is reproduced under licence.", exampleKr: "저자들은 책이 판매되거나 작품이 라이선스 하에 재현될 때마다 로열티를 받는다." },
      { word: "trade secret", pron: "/treɪd ˈsiːkrɪt/", pos: "n.", meanings: ["영업 비밀", "산업 기밀"], example: "The formula for Coca-Cola is one of the most famous trade secrets in the history of business.", exampleKr: "코카콜라의 제조법은 비즈니스 역사상 가장 유명한 영업 비밀 중 하나이다." },
      { word: "plagiarism", pron: "/ˈpleɪdʒərɪzəm/", pos: "n.", meanings: ["표절"], example: "Academic plagiarism, copying others' work without attribution, can result in expulsion from a university.", exampleKr: "출처 표기 없이 타인의 작업을 복사하는 학문적 표절은 대학에서 퇴학으로 이어질 수 있다." },
      { word: "fair use", pron: "/feər juːs/", pos: "n.", meanings: ["공정 이용", "공정 사용"], example: "Fair use permits limited reproduction of copyrighted material for commentary, criticism, and educational purposes.", exampleKr: "공정 이용은 논평, 비평, 교육 목적을 위해 저작권이 있는 자료의 제한적인 재현을 허용한다." },
      { word: "public domain", pron: "/ˈpʌblɪk dəˈmeɪn/", pos: "n.", meanings: ["공유 영역", "퍼블릭 도메인"], example: "Works in the public domain are free to use, reproduce, and adapt without requiring permission or payment.", exampleKr: "공유 영역의 작품은 허가나 지불 없이 자유롭게 사용, 재현, 각색할 수 있다." },
      { word: "prior art", pron: "/ˈpraɪər ɑːrt/", pos: "n.", meanings: ["선행 기술", "공지 기술"], example: "A patent application can be rejected if the examiner finds prior art that shows the invention was already known.", exampleKr: "특허 심사관이 발명이 이미 알려져 있음을 보여주는 선행 기술을 발견하면 특허 신청이 거절될 수 있다." },
      { word: "open source", pron: "/ˈəʊpən sɔːrs/", pos: "adj./n.", meanings: ["오픈 소스의", "공개 소스"], example: "Open source software is freely available for anyone to use, modify, and distribute under an open licence.", exampleKr: "오픈 소스 소프트웨어는 공개 라이선스 하에 누구나 무료로 사용, 수정, 배포할 수 있다." },
      { word: "NDA", pron: "/ˌen diː ˈeɪ/", pos: "n.", meanings: ["비밀 유지 계약", "NDA"], example: "All employees sign an NDA before accessing sensitive information about the company's upcoming product launch.", exampleKr: "모든 직원들은 회사의 다가오는 제품 출시에 관한 민감한 정보에 접근하기 전에 NDA에 서명한다." },
      { word: "patent claim", pron: "/ˈpeɪtənt kleɪm/", pos: "n.", meanings: ["특허 청구항", "청구 범위"], example: "Patent claims define the exact scope of the protection granted to the inventor by the patent office.", exampleKr: "특허 청구항은 특허청이 발명가에게 부여한 보호의 정확한 범위를 정의한다." },
      { word: "reverse engineering", pron: "/rɪˌvɜːrs ˈendʒɪnɪərɪŋ/", pos: "n.", meanings: ["역공학", "역설계"], example: "Competitor analysis sometimes involves reverse engineering a product to understand how it was designed and manufactured.", exampleKr: "경쟁자 분석은 때때로 제품이 어떻게 설계되고 제조되었는지 이해하기 위해 역공학을 포함한다." },
      { word: "utility patent", pron: "/juːˈtɪlɪti ˈpeɪtənt/", pos: "n.", meanings: ["실용 특허"], example: "A utility patent protects how an invention functions, and is the most common type of patent granted.", exampleKr: "실용 특허는 발명이 어떻게 기능하는지를 보호하며, 가장 일반적으로 부여되는 특허 유형이다." },
      { word: "design patent", pron: "/dɪˈzaɪn ˈpeɪtənt/", pos: "n.", meanings: ["디자인 특허"], example: "Apple obtained a design patent on the distinctive rounded corners of its iPhone, sparking industry-wide litigation.", exampleKr: "애플은 아이폰의 독특한 둥근 모서리에 대한 디자인 특허를 획득하여 업계 전반에 걸친 소송을 촉발시켰다." },
      { word: "trade dress", pron: "/treɪd dres/", pos: "n.", meanings: ["상품 외관", "트레이드 드레스"], example: "Trade dress protects the overall visual appearance of a product or packaging that identifies its commercial origin.", exampleKr: "트레이드 드레스는 상업적 출처를 식별하는 제품이나 포장의 전체적인 시각적 외관을 보호한다." },
      { word: "patent troll", pron: "/ˈpeɪtənt trɒl/", pos: "n.", meanings: ["특허 괴물", "특허 포식자"], example: "Patent trolls acquire broad patents solely to threaten lawsuits against companies actually producing innovative products.", exampleKr: "특허 괴물은 실제로 혁신적인 제품을 생산하는 기업들에게 소송 위협을 가하기 위해 넓은 특허를 취득한다." }
    ]
  },
  143: {
    theme: "영화·방송 어휘",
    words: [
      { word: "cinematography", pron: "/ˌsɪnɪməˈtɒɡrəfi/", pos: "n.", meanings: ["촬영 기법", "영화 촬영술"], example: "The film's outstanding cinematography used natural light and long takes to create a deeply immersive atmosphere.", exampleKr: "그 영화의 뛰어난 촬영 기법은 자연광과 긴 촬영을 사용하여 깊이 몰입적인 분위기를 만들었다." },
      { word: "mise-en-scene", pron: "/miːz ɑ̃ ˈsen/", pos: "n.", meanings: ["미장센", "장면 배치"], example: "The director's meticulous mise-en-scene ensured every visual element within the frame carried symbolic meaning.", exampleKr: "감독의 꼼꼼한 미장센은 프레임 내의 모든 시각적 요소가 상징적 의미를 담도록 보장했다." },
      { word: "montage", pron: "/ˈmɒntɑːʒ/", pos: "n.", meanings: ["몽타주", "장면 편집"], example: "Eisenstein used montage to create emotional impact by combining images that generate meaning through their juxtaposition.", exampleKr: "에이젠슈테인은 병치를 통해 의미를 생성하는 이미지를 결합하여 감정적 충격을 만들기 위해 몽타주를 사용했다." },
      { word: "screenplay", pron: "/ˈskriːnpleɪ/", pos: "n.", meanings: ["시나리오", "대본"], example: "The Academy Award for Best Screenplay recognised a script that balanced sharp dialogue with complex, believable characters.", exampleKr: "아카데미 최우수 시나리오상은 날카로운 대화와 복잡하고 믿음직한 인물들을 균형 있게 다룬 각본을 인정했다." },
      { word: "genre", pron: "/ˈʒɒnrə/", pos: "n.", meanings: ["장르"], example: "The film defied easy classification by blending elements of the horror, comedy, and science fiction genres.", exampleKr: "그 영화는 공포, 코미디, 공상과학 장르의 요소를 혼합하여 쉬운 분류를 거부했다." },
      { word: "auteur", pron: "/ˈoʊtɜːr/", pos: "n.", meanings: ["오테르", "작가주의 감독"], example: "Stanley Kubrick is celebrated as one of cinema's greatest auteurs for his unique and uncompromising personal vision.", exampleKr: "스탠리 큐브릭은 독특하고 타협하지 않는 개인적 비전으로 영화 역사상 가장 위대한 작가주의 감독 중 하나로 기념된다." },
      { word: "storyboard", pron: "/ˈstɔːribɔːrd/", pos: "n.", meanings: ["스토리보드"], example: "The director sketched out an elaborate storyboard to plan the visual sequence of each scene before filming.", exampleKr: "감독은 촬영 전에 각 장면의 시각적 순서를 계획하기 위해 정교한 스토리보드를 스케치했다." },
      { word: "dubbing", pron: "/ˈdʌbɪŋ/", pos: "n.", meanings: ["더빙", "음성 교체"], example: "The popular anime series was dubbed into fourteen languages to reach audiences across the world.", exampleKr: "그 인기 있는 애니메이션 시리즈는 전 세계 시청자들에게 도달하기 위해 14개 언어로 더빙되었다." },
      { word: "box office", pron: "/bɒks ˈɒfɪs/", pos: "n.", meanings: ["흥행 수익", "매표소"], example: "Despite mixed critical reviews, the action sequel shattered box office records in its opening weekend.", exampleKr: "엇갈린 비평에도 불구하고, 그 액션 속편은 개봉 주말에 흥행 기록을 깼다." },
      { word: "streaming", pron: "/ˈstriːmɪŋ/", pos: "n.", meanings: ["스트리밍", "온라인 방송"], example: "The rise of streaming platforms has fundamentally changed how films and television series are produced and consumed.", exampleKr: "스트리밍 플랫폼의 부상은 영화와 TV 시리즈가 제작되고 소비되는 방식을 근본적으로 변화시켰다." },
      { word: "franchise", pron: "/ˈfrænʧaɪz/", pos: "n.", meanings: ["프랜차이즈", "시리즈물"], example: "The Marvel Cinematic Universe became the most profitable film franchise in history with its interconnected storylines.", exampleKr: "마블 시네마틱 유니버스는 연결된 스토리라인으로 역사상 가장 수익성이 높은 영화 프랜차이즈가 되었다." },
      { word: "post-production", pron: "/pəʊst prəˈdʌkʃən/", pos: "n.", meanings: ["후반 제작"], example: "Post-production involves editing, colour grading, sound mixing, and adding visual effects after filming is complete.", exampleKr: "후반 제작은 촬영이 완료된 후 편집, 색감 보정, 사운드 믹싱, 시각 효과 추가를 포함한다." },
      { word: "continuity", pron: "/ˌkɒntɪˈnjuːɪti/", pos: "n.", meanings: ["연속성", "장면 연속"], example: "A continuity error was spotted in the battle scene, where a character's costume changed between shots.", exampleKr: "전투 장면에서 연속성 오류가 발견되었는데, 두 샷 사이에 인물의 의상이 변했다." },
      { word: "cameo", pron: "/ˈkæmiəʊ/", pos: "n.", meanings: ["카메오", "특별 출연"], example: "Alfred Hitchcock was famous for making brief cameo appearances in almost every film he directed.", exampleKr: "알프레드 히치콕은 그가 감독한 거의 모든 영화에 짧은 카메오로 출연하는 것으로 유명했다." },
      { word: "narrative arc", pron: "/ˈnærətɪv ɑːrk/", pos: "n.", meanings: ["서사 호", "스토리 구조"], example: "A compelling narrative arc takes characters from an initial situation through conflict to a meaningful resolution.", exampleKr: "설득력 있는 서사 호는 인물들을 초기 상황에서 갈등을 거쳐 의미 있는 해결로 이끈다." },
      { word: "blockbuster", pron: "/ˈblɒkbʌstər/", pos: "n.", meanings: ["블록버스터", "대형 흥행작"], example: "Summer blockbusters rely on spectacular visual effects, star power, and global marketing to draw mass audiences.", exampleKr: "여름 블록버스터는 대규모 관객을 끌어들이기 위해 화려한 시각 효과, 스타 파워, 글로벌 마케팅에 의존한다." },
      { word: "documentary", pron: "/ˌdɒkjʊˈmentəri/", pos: "n.", meanings: ["다큐멘터리"], example: "The award-winning documentary exposed the working conditions of labourers in the fast fashion supply chain.", exampleKr: "수상 경력의 다큐멘터리는 패스트 패션 공급망에서 노동자들의 근무 조건을 폭로했다." },
      { word: "pilot episode", pron: "/ˈpaɪlət ˈepɪsəʊd/", pos: "n.", meanings: ["파일럿 에피소드", "시범 방송"], example: "The network ordered a full season after the pilot episode attracted record viewing figures.", exampleKr: "파일럿 에피소드가 기록적인 시청률을 기록한 후 방송국은 전체 시즌을 주문했다." },
      { word: "trailer", pron: "/ˈtreɪlər/", pos: "n.", meanings: ["예고편"], example: "The teaser trailer released six months before the film generated enormous anticipation and social media buzz.", exampleKr: "영화 6개월 전에 공개된 티저 예고편은 엄청난 기대감과 소셜 미디어 화제를 만들어냈다." },
      { word: "cinematographer", pron: "/ˌsɪnɪˈmætəɡrəfər/", pos: "n.", meanings: ["촬영 감독", "영상 감독"], example: "The cinematographer and director collaborated closely to ensure every shot reflected the film's emotional tone.", exampleKr: "촬영 감독과 감독은 모든 샷이 영화의 감정적 톤을 반영하도록 긴밀히 협력했다." }
    ]
  },
  144: {
    theme: "동식물·생태 II",
    words: [
      { word: "apex predator", pron: "/ˈeɪpeks ˈpredətər/", pos: "n.", meanings: ["최상위 포식자", "정점 포식자"], example: "As the apex predator of the savannah, lions regulate the population of herbivores and maintain ecosystem balance.", exampleKr: "사바나의 최상위 포식자로서 사자는 초식동물의 개체 수를 조절하고 생태계 균형을 유지한다." },
      { word: "ecological niche", pron: "/ˌiːkəˈlɒdʒɪkəl niːʃ/", pos: "n.", meanings: ["생태적 지위", "생태 틈새"], example: "Each species occupies a specific ecological niche, defined by its role in the food web and environmental requirements.", exampleKr: "각 종은 먹이 그물에서의 역할과 환경적 요구 사항에 의해 정의되는 특정 생태적 지위를 차지한다." },
      { word: "keystone species", pron: "/ˈkiːstəʊn ˈspiːʃiːz/", pos: "n.", meanings: ["핵심 종", "키스톤 종"], example: "Wolves are a keystone species whose reintroduction in Yellowstone triggered a cascade of ecological recovery.", exampleKr: "늑대는 옐로스톤에서의 재도입이 생태 회복의 연쇄를 촉발시킨 핵심 종이다." },
      { word: "biomass", pron: "/ˈbaɪəʊmæs/", pos: "n.", meanings: ["생물량", "바이오매스"], example: "Scientists measure the total biomass of an ecosystem to assess its productivity and energy storage capacity.", exampleKr: "과학자들은 생산성과 에너지 저장 용량을 평가하기 위해 생태계의 총 생물량을 측정한다." },
      { word: "carrying capacity", pron: "/ˈkæriɪŋ kəˈpæsɪti/", pos: "n.", meanings: ["수용 용량", "환경 수용력"], example: "When a population exceeds its carrying capacity, it depletes resources, triggering a decline in numbers.", exampleKr: "개체군이 수용 용량을 초과하면 자원을 고갈시켜 개체 수 감소를 촉발한다." },
      { word: "trophic level", pron: "/ˈtrɒfɪk levəl/", pos: "n.", meanings: ["영양 단계", "먹이 단계"], example: "Energy is lost at each trophic level, which is why apex predators are always far fewer in number than their prey.", exampleKr: "에너지는 각 영양 단계에서 손실되므로 최상위 포식자는 항상 먹이보다 수가 훨씬 적다." },
      { word: "food web", pron: "/fuːd web/", pos: "n.", meanings: ["먹이 그물", "먹이망"], example: "A food web illustrates the complex network of predator-prey relationships within an ecological community.", exampleKr: "먹이 그물은 생태 군락 내 포식자-피식자 관계의 복잡한 네트워크를 보여준다." },
      { word: "invasive species", pron: "/ɪnˈveɪsɪv ˈspiːʃiːz/", pos: "n.", meanings: ["침입 종", "외래 침입 생물"], example: "The invasive cane toad devastated native amphibian populations across much of Australia after its introduction.", exampleKr: "침입 종인 수수꺼비두꺼비는 호주 전역에 도입된 후 토종 양서류 개체군을 황폐화시켰다." },
      { word: "endemic", pron: "/ɪnˈdemɪk/", pos: "adj./n.", meanings: ["고유한", "고유종", "풍토의"], example: "Australian marsupials are endemic to the continent, having evolved in geographical isolation for millions of years.", exampleKr: "호주의 유대류는 수백만 년 동안 지리적 고립 속에서 진화하여 대륙 고유의 동물이다." },
      { word: "migratory", pron: "/ˈmaɪɡrətəri/", pos: "adj.", meanings: ["이주하는", "철새의"], example: "Migratory birds travel thousands of kilometres between their breeding and wintering grounds each year.", exampleKr: "철새들은 매년 번식지와 월동지 사이를 수천 킬로미터씩 이동한다." },
      { word: "dormancy", pron: "/ˈdɔːrməns i/", pos: "n.", meanings: ["휴지기", "동면"], example: "Plants enter dormancy during winter to conserve energy until favourable growing conditions return in spring.", exampleKr: "식물은 봄에 유리한 생장 조건이 돌아올 때까지 에너지를 보존하기 위해 겨울 동안 휴지기에 들어간다." },
      { word: "pollinator", pron: "/ˈpɒlɪneɪtər/", pos: "n.", meanings: ["수분 매개자", "꽃가루받이 생물"], example: "Bees and butterflies are vital pollinators without which many flowering plants could not reproduce.", exampleKr: "꿀벌과 나비는 없으면 많은 꽃 식물이 번식할 수 없는 중요한 수분 매개자이다." },
      { word: "biodegradable", pron: "/ˌbaɪəʊdɪˈɡreɪdəbəl/", pos: "adj.", meanings: ["생분해성의"], example: "Switching to biodegradable packaging reduces plastic pollution as it breaks down naturally without lasting harm.", exampleKr: "생분해성 포장으로 전환하면 지속적인 해를 끼치지 않고 자연적으로 분해되어 플라스틱 오염을 줄인다." },
      { word: "decomposer", pron: "/ˌdiːkəmˈpəʊzər/", pos: "n.", meanings: ["분해자", "부패 미생물"], example: "Fungi and bacteria serve as decomposers, breaking down dead matter and recycling nutrients back into the soil.", exampleKr: "균류와 박테리아는 분해자로 작용하여 죽은 물질을 분해하고 영양소를 토양으로 다시 순환시킨다." },
      { word: "rewilding", pron: "/riːˈwaɪldɪŋ/", pos: "n.", meanings: ["야생화", "생태 복원"], example: "Rewilding projects reintroduce native species and restore natural processes to degraded landscapes.", exampleKr: "야생화 프로젝트는 토종 종을 재도입하고 황폐화된 경관에 자연 과정을 복원한다." },
      { word: "pheromone", pron: "/ˈferəməʊn/", pos: "n.", meanings: ["페로몬"], example: "Insects use pheromones to communicate with members of their own species, signalling danger or attracting mates.", exampleKr: "곤충들은 위험을 알리거나 짝을 유인하기 위해 같은 종의 개체들과 소통하는 데 페로몬을 사용한다." },
      { word: "camouflage", pron: "/ˈkæməflɑːʒ/", pos: "n./v.", meanings: ["위장", "위장하다"], example: "The Arctic fox's white winter coat provides effective camouflage against the snow, concealing it from predators.", exampleKr: "북극여우의 흰 겨울 털은 눈에 대한 효과적인 위장을 제공하여 포식자로부터 숨긴다." },
      { word: "nocturnal", pron: "/nɒkˈtɜːrnəl/", pos: "adj.", meanings: ["야행성의"], example: "Owls are nocturnal hunters whose exceptional night vision and silent flight make them highly effective predators.", exampleKr: "올빼미는 뛰어난 야간 시력과 무음 비행으로 매우 효과적인 포식자가 되는 야행성 사냥꾼이다." },
      { word: "territorial", pron: "/ˌterɪˈtɔːriəl/", pos: "adj.", meanings: ["영역적인", "영토를 지키는"], example: "Many bird species are fiercely territorial during nesting season, aggressively defending their patch from rivals.", exampleKr: "많은 새 종들은 둥지 짓는 철에 매우 영역적이 되어 경쟁자들로부터 자신의 구역을 공격적으로 방어한다." },
      { word: "symbiont", pron: "/ˈsɪmbiɒnt/", pos: "n.", meanings: ["공생 생물", "공생자"], example: "Mycorrhizal fungi are beneficial symbionts that help plant roots absorb water and nutrients more efficiently.", exampleKr: "균근 균류는 식물 뿌리가 물과 영양분을 더 효율적으로 흡수하는 데 도움을 주는 유익한 공생 생물이다." }
    ]
  },
  145: {
    theme: "기상·기후과학 어휘",
    words: [
      { word: "atmospheric pressure", pron: "/ˌætməsˈferɪk ˈpreʃər/", pos: "n.", meanings: ["기압", "대기압"], example: "Changes in atmospheric pressure are used by meteorologists to predict the approach of weather systems.", exampleKr: "기압의 변화는 기상학자들이 기상 시스템의 접근을 예측하는 데 사용된다." },
      { word: "jet stream", pron: "/dʒet striːm/", pos: "n.", meanings: ["제트 기류"], example: "The polar jet stream strongly influences weather patterns across the northern hemisphere, guiding storms eastward.", exampleKr: "극지방 제트 기류는 북반구 전역의 기상 패턴에 강하게 영향을 미치며 폭풍을 동쪽으로 안내한다." },
      { word: "monsoon", pron: "/mɒnˈsuːn/", pos: "n.", meanings: ["계절풍", "몬순"], example: "The South Asian monsoon brings torrential rains from June to September, essential for agriculture across the region.", exampleKr: "남아시아 계절풍은 6월부터 9월까지 폭우를 가져와 지역 전반의 농업에 필수적이다." },
      { word: "El Nino", pron: "/el ˈniːnjəʊ/", pos: "n.", meanings: ["엘니뇨"], example: "El Nino events warm the eastern Pacific and disrupt weather patterns worldwide, causing droughts in some regions.", exampleKr: "엘니뇨 현상은 동태평양을 따뜻하게 하고 전 세계 기상 패턴을 교란하여 일부 지역에서 가뭄을 유발한다." },
      { word: "cyclone", pron: "/ˈsaɪkləʊn/", pos: "n.", meanings: ["사이클론", "열대 저기압"], example: "A powerful cyclone made landfall on the coast, bringing destructive winds and widespread flooding to the region.", exampleKr: "강력한 사이클론이 해안에 상륙하여 그 지역에 파괴적인 바람과 광범위한 홍수를 가져왔다." },
      { word: "anticyclone", pron: "/ˌæntɪˈsaɪkləʊn/", pos: "n.", meanings: ["고기압", "반사이클론"], example: "A blocking anticyclone over Europe brought weeks of dry, sunny weather during the summer heatwave.", exampleKr: "유럽 상공의 차단 고기압이 여름 폭염 동안 수 주간의 건조하고 맑은 날씨를 가져왔다." },
      { word: "humidity", pron: "/hjuːˈmɪdɪti/", pos: "n.", meanings: ["습도", "습기"], example: "High humidity combined with extreme temperatures created dangerously uncomfortable conditions during the tropical summer.", exampleKr: "높은 습도와 극한 온도의 결합은 열대 여름 동안 위험할 정도로 불쾌한 조건을 만들었다." },
      { word: "storm surge", pron: "/stɔːrm sɜːrdʒ/", pos: "n.", meanings: ["폭풍 해일"], example: "The storm surge pushed several metres of seawater inland, inundating coastal communities before evacuation was complete.", exampleKr: "폭풍 해일은 대피가 완료되기 전에 해안 지역사회를 침수시키며 수 미터의 해수를 내륙으로 밀어넣었다." },
      { word: "carbon cycle", pron: "/ˈkɑːrbən ˈsaɪkəl/", pos: "n.", meanings: ["탄소 순환"], example: "The carbon cycle describes how carbon moves through the atmosphere, oceans, soil, and living organisms.", exampleKr: "탄소 순환은 탄소가 대기, 바다, 토양, 살아있는 생물을 통해 어떻게 이동하는지를 설명한다." },
      { word: "albedo", pron: "/ælˈbiːdəʊ/", pos: "n.", meanings: ["반사율", "알베도"], example: "Sea ice has a high albedo, reflecting sunlight back into space; its melting accelerates warming by reducing this effect.", exampleKr: "해빙은 높은 반사율을 가지며 햇빛을 우주로 반사하는데, 그것의 녹음은 이 효과를 줄여 온난화를 가속시킨다." },
      { word: "greenhouse effect", pron: "/ˈɡriːnhaʊs ɪˈfekt/", pos: "n.", meanings: ["온실 효과"], example: "The natural greenhouse effect warms Earth to habitable temperatures; human activities have intensified it dangerously.", exampleKr: "자연적인 온실 효과는 지구를 거주 가능한 온도로 따뜻하게 하지만, 인간 활동은 그것을 위험하게 강화시켰다." },
      { word: "desertification", pron: "/dɪˌzɜːrtɪfɪˈkeɪʃən/", pos: "n.", meanings: ["사막화"], example: "Unsustainable farming practices and climate change are driving desertification across large parts of sub-Saharan Africa.", exampleKr: "지속 불가능한 농업 관행과 기후 변화가 사하라 이남 아프리카의 상당 부분에 걸쳐 사막화를 촉진하고 있다." },
      { word: "sea level rise", pron: "/siː ˈlevəl raɪz/", pos: "n.", meanings: ["해수면 상승"], example: "Sea level rise driven by thermal expansion and glacier melt threatens low-lying coastal cities and island nations.", exampleKr: "열팽창과 빙하 녹음에 의해 촉진된 해수면 상승은 낮은 지대의 해안 도시와 섬나라를 위협한다." },
      { word: "drought", pron: "/draʊt/", pos: "n.", meanings: ["가뭄"], example: "A prolonged drought depleted reservoirs and forced severe water rationing across several southern European countries.", exampleKr: "장기간의 가뭄이 저수지를 고갈시키고 여러 남유럽 국가에 걸쳐 심각한 물 배급을 강제했다." },
      { word: "floodplain", pron: "/ˈflʌdpleɪn/", pos: "n.", meanings: ["범람원", "홍수 평야"], example: "Building on floodplains increases flood risk and can exacerbate disasters during extreme rainfall events.", exampleKr: "범람원에 건설하는 것은 홍수 위험을 높이고 극단적인 강우 현상 동안 재해를 악화시킬 수 있다." },
      { word: "microclimate", pron: "/ˈmaɪkrəʊklaɪmɪt/", pos: "n.", meanings: ["미기후", "소기후"], example: "Urban heat islands create microclimates that are significantly warmer than surrounding rural areas.", exampleKr: "도시 열섬은 주변 농촌 지역보다 상당히 더 따뜻한 미기후를 만들어낸다." },
      { word: "paleoclimatology", pron: "/ˌpeɪliəʊˌklaɪməˈtɒlədʒi/", pos: "n.", meanings: ["고기후학", "과거 기후 연구"], example: "Paleoclimatology uses ice cores and tree rings to reconstruct Earth's climate history over millions of years.", exampleKr: "고기후학은 빙하 코어와 나이테를 사용하여 수백만 년에 걸친 지구의 기후 역사를 재구성한다." },
      { word: "precipitation anomaly", pron: "/prɪˌsɪpɪˈteɪʃən əˈnɒməli/", pos: "n.", meanings: ["강수 편차", "이상 강수"], example: "Extreme precipitation anomalies, both droughts and floods, are becoming more frequent with climate change.", exampleKr: "가뭄과 홍수 모두 포함하는 극단적인 강수 편차가 기후 변화와 함께 더 자주 발생하고 있다." },
      { word: "wind shear", pron: "/wɪnd ʃɪər/", pos: "n.", meanings: ["윈드시어", "바람 전단"], example: "Strong wind shear at altitude can disrupt the structure of developing hurricanes, limiting their intensity.", exampleKr: "고고도에서의 강한 바람 전단은 발달 중인 허리케인의 구조를 교란하여 강도를 제한할 수 있다." },
      { word: "La Nina", pron: "/lɑː ˈniːnjə/", pos: "n.", meanings: ["라니냐"], example: "La Nina events typically cause above-average rainfall across parts of Asia and Australia while drying out South America.", exampleKr: "라니냐 현상은 일반적으로 아시아와 호주 일부에 평균 이상의 강우를 일으키는 반면 남아메리카를 건조하게 만든다." }
    ]
  }
});
