/**
 * data_days_136_140.js - Day 136~140 단어 데이터
 * data_days_131_135.js 이후에 로드해야 합니다
 */
Object.assign(VOCA_DATA, {
  136: {
    theme: "통신네트워크 어휘",
    words: [
      { word: "fibre optic", pron: "/faɪbər ɒptɪk/", pos: "adj./n.", meanings: ["광섬유의", "광섬유"], example: "Fibre optic cables transmit data as pulses of light, enabling far faster and more reliable internet connections.", exampleKr: "광섬유 케이블은 데이터를 빛의 펄스로 전송하여 훨씬 빠르고 신뢰할 수 있는 인터넷 연결을 가능하게 한다." },
      { word: "protocol", pron: "/prəʊtəkɒl/", pos: "n.", meanings: ["통신 규약", "프로토콜"], example: "TCP/IP is the fundamental communication protocol suite that governs how data travels across the internet.", exampleKr: "TCP/IP는 데이터가 인터넷을 통해 이동하는 방식을 관장하는 기본 통신 프로토콜 집합이다." },
      { word: "encryption", pron: "/ɪnkrɪpʃən/", pos: "n.", meanings: ["암호화"], example: "End-to-end encryption ensures that only the sender and intended recipient can read the content of a message.", exampleKr: "종단 간 암호화는 발신자와 의도한 수신자만이 메시지 내용을 읽을 수 있도록 보장한다." },
      { word: "packet", pron: "/pækɪt/", pos: "n.", meanings: ["패킷", "데이터 단위"], example: "Internet data is broken into small packets for transmission and reassembled at the receiving end.", exampleKr: "인터넷 데이터는 전송을 위해 작은 패킷으로 분해되었다가 수신 측에서 재조립된다." },
      { word: "router", pron: "/ruːtər/", pos: "n.", meanings: ["라우터", "경로 설정기"], example: "A router directs data packets between networks, choosing the most efficient path for each transmission.", exampleKr: "라우터는 각 전송에 가장 효율적인 경로를 선택하여 네트워크 간에 데이터 패킷을 안내한다." },
      { word: "throughput", pron: "/θruːpʊt/", pos: "n.", meanings: ["처리량", "전송 속도"], example: "Network engineers monitor throughput to ensure the system can handle peak traffic without performance degradation.", exampleKr: "네트워크 엔지니어들은 시스템이 성능 저하 없이 최대 트래픽을 처리할 수 있는지 확인하기 위해 처리량을 모니터링한다." },
      { word: "spectrum", pron: "/spektrəm/", pos: "n.", meanings: ["주파수 스펙트럼", "전자기 스펙트럼"], example: "Mobile operators bid billions of dollars for spectrum licences that allow them to provide wireless services.", exampleKr: "이동통신 사업자들은 무선 서비스를 제공할 수 있게 하는 스펙트럼 면허를 위해 수십억 달러를 입찰한다." },
      { word: "5G", pron: "/faɪv dʒiː/", pos: "n.", meanings: ["5G", "5세대 이동통신"], example: "5G networks offer dramatically faster speeds and lower latency than earlier generations, enabling new applications.", exampleKr: "5G 네트워크는 이전 세대보다 훨씬 빠른 속도와 낮은 지연 시간을 제공하여 새로운 응용 프로그램을 가능하게 한다." },
      { word: "Internet of Things", pron: "/ɪntərnet əv θɪŋz/", pos: "n.", meanings: ["사물 인터넷", "IoT"], example: "The Internet of Things connects everyday devices to the internet, enabling remote monitoring and automated control.", exampleKr: "사물 인터넷은 일상 기기를 인터넷에 연결하여 원격 모니터링과 자동화된 제어를 가능하게 한다." },
      { word: "cloud computing", pron: "/klaʊd kəmpjuːtɪŋ/", pos: "n.", meanings: ["클라우드 컴퓨팅"], example: "Cloud computing delivers on-demand access to computing resources over the internet without local hardware requirements.", exampleKr: "클라우드 컴퓨팅은 로컬 하드웨어 요구 사항 없이 인터넷을 통해 컴퓨팅 자원에 대한 요청 기반 접근을 제공한다." },
      { word: "VPN", pron: "/viː piː en/", pos: "n.", meanings: ["가상 사설망", "VPN"], example: "A VPN encrypts a user's internet connection, hiding their identity and enabling access to geo-restricted content.", exampleKr: "VPN은 사용자의 인터넷 연결을 암호화하여 신원을 숨기고 지역 제한 콘텐츠에 대한 접근을 가능하게 한다." },
      { word: "peer-to-peer", pron: "/pɪər tə pɪər/", pos: "adj.", meanings: ["P2P의", "동등 방식의"], example: "Peer-to-peer file sharing distributes content across a network of users without relying on a central server.", exampleKr: "P2P 파일 공유는 중앙 서버에 의존하지 않고 사용자 네트워크 전체에 콘텐츠를 배포한다." },
      { word: "cybersecurity", pron: "/saɪbəsɪkjʊərɪti/", pos: "n.", meanings: ["사이버 보안"], example: "Cybersecurity threats have grown substantially as more critical infrastructure has been connected to the internet.", exampleKr: "더 많은 중요 인프라가 인터넷에 연결되면서 사이버 보안 위협이 상당히 증가했다." },
      { word: "broadband", pron: "/brɔːdbænd/", pos: "n./adj.", meanings: ["고속 인터넷", "광대역의"], example: "Reliable broadband access has become as essential as water and electricity for modern homes and businesses.", exampleKr: "신뢰할 수 있는 고속 인터넷 접속은 현대 가정과 기업에게 물이나 전기만큼 필수적이 되었다." },
      { word: "firewall", pron: "/faɪərwɔːl/", pos: "n.", meanings: ["방화벽"], example: "A corporate firewall blocks unauthorised external access while allowing legitimate internal network traffic to pass.", exampleKr: "기업 방화벽은 무단 외부 접근을 차단하면서 합법적인 내부 네트워크 트래픽은 통과시킨다." },
      { word: "codec", pron: "/kəʊdek/", pos: "n.", meanings: ["코덱", "부호화복호화 장치"], example: "Video streaming platforms use efficient codecs to compress large video files while maintaining acceptable playback quality.", exampleKr: "비디오 스트리밍 플랫폼은 허용 가능한 재생 품질을 유지하면서 대용량 영상 파일을 압축하기 위해 효율적인 코덱을 사용한다." },
      { word: "uplink", pron: "/ʌplɪŋk/", pos: "n.", meanings: ["업링크", "상향 링크"], example: "Satellite uplinks transmit television broadcasts from Earth-based stations to orbiting communication satellites.", exampleKr: "위성 업링크는 지상 방송국에서 궤도를 도는 통신 위성으로 TV 방송을 전송한다." },
      { word: "jitter", pron: "/dʒɪtər/", pos: "n.", meanings: ["지터", "신호 불규칙성"], example: "High jitter in a network connection causes voice calls and video streams to sound or appear distorted.", exampleKr: "네트워크 연결의 높은 지터는 음성 통화 및 비디오 스트림을 왜곡되게 들리거나 보이게 한다." },
      { word: "satellite communication", pron: "/sætəlaɪt kəmjuːnɪkeɪʃən/", pos: "n.", meanings: ["위성 통신"], example: "Satellite communication provides connectivity to remote locations where terrestrial infrastructure cannot reach.", exampleKr: "위성 통신은 지상 인프라가 도달할 수 없는 외딴 지역에 연결성을 제공한다." },
      { word: "mesh network", pron: "/meʃ netwɜːrk/", pos: "n.", meanings: ["메시 네트워크"], example: "A mesh network links multiple nodes so that if one fails, traffic is rerouted automatically through others.", exampleKr: "메시 네트워크는 여러 노드를 연결하여 하나가 실패하면 트래픽이 자동으로 다른 노드를 통해 재라우팅된다." }
    ]
  },
  137: {
    theme: "공공행정정책 어휘",
    words: [
      { word: "bureaucracy", pron: "/bjʊrɒkrəsi/", pos: "n.", meanings: ["관료제", "관료주의"], example: "Excessive bureaucracy slows decision-making and frustrates citizens trying to access public services.", exampleKr: "과도한 관료주의는 의사 결정을 늦추고 공공 서비스에 접근하려는 시민들을 좌절시킨다." },
      { word: "governance", pron: "/ɡʌvənəns/", pos: "n.", meanings: ["거버넌스", "통치"], example: "Good governance includes transparency, accountability, and the rule of law applied equally to all citizens.", exampleKr: "좋은 거버넌스는 모든 시민에게 동등하게 적용되는 투명성, 책임성, 법치주의를 포함한다." },
      { word: "legislation", pron: "/ledʒɪsleɪʃən/", pos: "n.", meanings: ["법률", "입법"], example: "New data protection legislation imposes strict obligations on companies regarding the handling of personal information.", exampleKr: "새로운 데이터 보호 법률은 개인 정보 처리와 관련하여 기업에 엄격한 의무를 부과한다." },
      { word: "referendum", pron: "/refərendəm/", pos: "n.", meanings: ["국민투표"], example: "The government held a referendum to let citizens decide whether to change the country's electoral system.", exampleKr: "정부는 국민이 국가의 선거 제도를 변경할지 결정할 수 있도록 국민투표를 실시했다." },
      { word: "constituency", pron: "/kənstɪtʃʊənsi/", pos: "n.", meanings: ["선거구", "지지 기반"], example: "The newly elected MP pledged to represent every voter in the constituency, regardless of their political affiliation.", exampleKr: "새로 선출된 의원은 정치적 소속에 관계없이 선거구의 모든 유권자를 대표하겠다고 약속했다." },
      { word: "lobbying", pron: "/lɒbiɪŋ/", pos: "n.", meanings: ["로비 활동"], example: "Corporate lobbying allows wealthy interest groups to exert disproportionate influence over public policy decisions.", exampleKr: "기업 로비 활동은 부유한 이익 집단이 공공 정책 결정에 불균형적인 영향력을 행사할 수 있게 한다." },
      { word: "fiscal policy", pron: "/fɪskəl pɒlɪsi/", pos: "n.", meanings: ["재정 정책"], example: "Expansionary fiscal policy increases government spending to stimulate economic activity during a recession.", exampleKr: "확장적 재정 정책은 경기 침체 시 경제 활동을 자극하기 위해 정부 지출을 늘린다." },
      { word: "monetary policy", pron: "/mʌnɪtəri pɒlɪsi/", pos: "n.", meanings: ["통화 정책"], example: "The central bank uses monetary policy tools such as interest rates to control inflation and support growth.", exampleKr: "중앙은행은 금리와 같은 통화 정책 수단을 사용하여 인플레이션을 제어하고 성장을 지원한다." },
      { word: "civil service", pron: "/sɪvəl sɜːrvɪs/", pos: "n.", meanings: ["공무원 제도", "행정 공무원"], example: "A professional civil service implements government policy impartially, regardless of which party holds power.", exampleKr: "전문적인 공무원 제도는 어느 정당이 권력을 보유하는지에 관계없이 공정하게 정부 정책을 실행한다." },
      { word: "austerity", pron: "/ɒsterɪti/", pos: "n.", meanings: ["긴축 정책", "내핍"], example: "Years of fiscal austerity reduced the national debt but also cut spending on vital public services.", exampleKr: "수년간의 재정 긴축은 국가 부채를 줄였지만 중요한 공공 서비스 지출도 삭감했다." },
      { word: "privatisation", pron: "/praɪvɪtaɪzeɪʃən/", pos: "n.", meanings: ["민영화"], example: "The privatisation of the national railway improved efficiency in some regions but raised fares significantly elsewhere.", exampleKr: "국가 철도의 민영화는 일부 지역에서 효율성을 향상시켰지만 다른 지역에서는 요금을 상당히 올렸다." },
      { word: "nationalisation", pron: "/næʃənəlaɪzeɪʃən/", pos: "n.", meanings: ["국유화"], example: "The government voted for the nationalisation of the energy sector following a series of corporate pricing scandals.", exampleKr: "정부는 일련의 기업 가격 책정 스캔들 이후 에너지 부문의 국유화를 결의했다." },
      { word: "devolution", pron: "/devəluːʃən/", pos: "n.", meanings: ["권한 이양", "분권화"], example: "Devolution transferred significant powers from the national parliament to regional assemblies and local governments.", exampleKr: "권한 이양은 국가 의회에서 지역 의회와 지방 정부로 상당한 권한을 이전했다." },
      { word: "ombudsman", pron: "/ɒmbʊdzmən/", pos: "n.", meanings: ["옴부즈만", "민원 조사관"], example: "Citizens can refer complaints about government agencies to the ombudsman when other channels have been exhausted.", exampleKr: "시민들은 다른 채널이 소진되었을 때 정부 기관에 대한 민원을 옴부즈만에게 제기할 수 있다." },
      { word: "think tank", pron: "/θɪŋk tæŋk/", pos: "n.", meanings: ["씽크탱크", "정책 연구소"], example: "Independent think tanks produce evidence-based research to inform and influence public policy debates.", exampleKr: "독립적인 씽크탱크는 공공 정책 토론을 알리고 영향을 미치기 위해 증거에 기반한 연구를 생성한다." },
      { word: "white paper", pron: "/waɪt peɪpər/", pos: "n.", meanings: ["백서", "정책 보고서"], example: "The government published a comprehensive white paper outlining its strategy for reforming the healthcare system.", exampleKr: "정부는 의료 시스템 개혁을 위한 전략을 설명하는 포괄적인 백서를 발표했다." },
      { word: "mandate", pron: "/mændeɪt/", pos: "n./v.", meanings: ["위임", "권한"], example: "The landslide election victory gave the new government a strong mandate to implement its ambitious reform programme.", exampleKr: "압도적인 선거 우세는 새 정부에게 야심찬 개혁 프로그램을 실행할 강한 위임을 부여했다." },
      { word: "redistribution", pron: "/riːdɪstrɪbjuːʃən/", pos: "n.", meanings: ["재분배"], example: "Progressive taxation and welfare spending achieve the redistribution of wealth from higher to lower income groups.", exampleKr: "누진세와 복지 지출은 고소득 계층에서 저소득 계층으로의 부의 재분배를 달성한다." },
      { word: "public procurement", pron: "/pʌblɪk prəkjʊərmənt/", pos: "n.", meanings: ["공공 조달"], example: "Transparent public procurement processes prevent corruption and ensure value for money in government contracting.", exampleKr: "투명한 공공 조달 프로세스는 부패를 방지하고 정부 계약에서 가격 대비 가치를 보장한다." },
      { word: "green paper", pron: "/ɡriːn peɪpər/", pos: "n.", meanings: ["녹서", "정책 토론서"], example: "A green paper invites public and stakeholder feedback on a policy proposal before the government commits to legislation.", exampleKr: "녹서는 정부가 입법을 결정하기 전에 정책 제안에 대한 공중과 이해관계자의 피드백을 구한다." }
    ]
  },
  138: {
    theme: "노동고용 어휘",
    words: [
      { word: "redundancy", pron: "/rɪdʌndənsi/", pos: "n.", meanings: ["정리해고", "인원 과잉"], example: "The company announced two hundred redundancies as it sought to cut costs and remain competitive.", exampleKr: "회사는 비용을 절감하고 경쟁력을 유지하기 위해 200명의 정리해고를 발표했다." },
      { word: "collective bargaining", pron: "/kəlektɪv bɑːrɡɪnɪŋ/", pos: "n.", meanings: ["단체 교섭"], example: "Collective bargaining allows workers, through their union, to negotiate wages and conditions with employers collectively.", exampleKr: "단체 교섭은 노동자들이 노동조합을 통해 사용자와 집단적으로 임금과 근무 조건을 협상할 수 있게 한다." },
      { word: "trade union", pron: "/treɪd juːnjən/", pos: "n.", meanings: ["노동조합"], example: "The trade union called a strike after management refused to improve working conditions in the factory.", exampleKr: "경영진이 공장 근무 조건 개선을 거부한 후 노동조합이 파업을 선언했다." },
      { word: "underemployment", pron: "/ʌndərɪmplɔɪmənt/", pos: "n.", meanings: ["불완전 고용", "불충분 취업"], example: "Graduate underemployment, where highly qualified people work in low-skilled jobs, is a growing concern.", exampleKr: "고학력자가 저숙련 직업에 종사하는 대졸자 불완전 고용은 점점 더 큰 문제가 되고 있다." },
      { word: "occupational hazard", pron: "/ɒkjʊpeɪʃənəl hæzərd/", pos: "n.", meanings: ["직업적 위험", "직업병 위험"], example: "Back injuries are a common occupational hazard for workers whose jobs require heavy lifting or repetitive movement.", exampleKr: "허리 부상은 무거운 물건 들기나 반복적인 움직임이 필요한 직업을 가진 근로자들의 일반적인 직업적 위험이다." },
      { word: "severance pay", pron: "/sevərəns peɪ/", pos: "n.", meanings: ["퇴직금", "해고 보상금"], example: "The employment contract specified that employees would receive three months' severance pay if made redundant.", exampleKr: "고용 계약서는 직원들이 해고될 경우 3개월 치 퇴직금을 받게 된다고 명시했다." },
      { word: "strike", pron: "/straɪk/", pos: "n./v.", meanings: ["파업", "파업하다"], example: "Thousands of workers went on strike demanding a pay rise that kept pace with the rising cost of living.", exampleKr: "수천 명의 노동자들이 생활비 상승에 맞는 임금 인상을 요구하며 파업에 들어갔다." },
      { word: "gig economy", pron: "/ɡɪɡ ɪkɒnəmi/", pos: "n.", meanings: ["긱 이코노미", "임시 고용 경제"], example: "The gig economy offers flexibility but leaves workers without the job security or benefits of traditional employment.", exampleKr: "긱 이코노미는 유연성을 제공하지만 근로자들에게 전통적인 고용의 고용 안정성이나 혜택 없이 남겨둔다." },
      { word: "telecommuting", pron: "/telikɒmjuːtɪŋ/", pos: "n.", meanings: ["재택 근무", "원격 근무"], example: "The pandemic accelerated the adoption of telecommuting, with millions working from home who had never done so before.", exampleKr: "팬데믹은 재택 근무 도입을 가속화하여 이전에는 하지 못했던 수백만 명이 집에서 일하게 했다." },
      { word: "minimum wage", pron: "/mɪnɪməm weɪdʒ/", pos: "n.", meanings: ["최저 임금"], example: "Raising the minimum wage helps reduce poverty among low-paid workers but may also reduce employment in some sectors.", exampleKr: "최저 임금 인상은 저임금 근로자의 빈곤 감소에 도움이 되지만 일부 부문에서 고용을 감소시킬 수도 있다." },
      { word: "overtime", pron: "/əʊvətaɪm/", pos: "n.", meanings: ["초과 근무", "연장 근무"], example: "Employees who work overtime are generally entitled to additional pay at a premium rate.", exampleKr: "초과 근무를 하는 직원들은 일반적으로 할증률의 추가 급여를 받을 권리가 있다." },
      { word: "maternity leave", pron: "/mətɜːrnɪti liːv/", pos: "n.", meanings: ["출산 휴가"], example: "Generous maternity leave policies help retain female talent and improve gender equality in the workplace.", exampleKr: "넉넉한 출산 휴가 정책은 여성 인재를 유지하고 직장 내 성 평등을 향상시키는 데 도움이 된다." },
      { word: "apprenticeship", pron: "/əprentɪʃɪp/", pos: "n.", meanings: ["도제 제도", "실습 과정"], example: "Apprenticeships combine on-the-job training with formal study, providing young people with practical skills.", exampleKr: "도제 제도는 직무 중 훈련과 공식적인 학습을 결합하여 젊은 사람들에게 실용적인 기술을 제공한다." },
      { word: "outsourcing", pron: "/aʊtsɔːrsɪŋ/", pos: "n.", meanings: ["아웃소싱", "외주"], example: "Many firms outsource non-core functions such as payroll and IT support to reduce costs and access expertise.", exampleKr: "많은 기업들이 비용을 절감하고 전문성을 활용하기 위해 급여 및 IT 지원과 같은 비핵심 기능을 외주화한다." },
      { word: "discrimination", pron: "/dɪskrɪmɪneɪʃən/", pos: "n.", meanings: ["차별", "부당 대우"], example: "Employment discrimination based on gender, race, or disability is prohibited by law in most developed countries.", exampleKr: "성별, 인종, 장애를 이유로 한 고용 차별은 대부분의 선진국에서 법으로 금지되어 있다." },
      { word: "harassment", pron: "/həræsmənt/", pos: "n.", meanings: ["괴롭힘", "희롱"], example: "Workplace harassment policies must be enforced consistently to create a safe and inclusive environment for all staff.", exampleKr: "직장 내 괴롭힘 정책은 모든 직원을 위한 안전하고 포용적인 환경을 만들기 위해 일관되게 시행되어야 한다." },
      { word: "workforce", pron: "/wɜːrkfɔːrs/", pos: "n.", meanings: ["노동력", "인력"], example: "An ageing workforce is one of the most significant demographic challenges facing many developed economies.", exampleKr: "고령화 노동력은 많은 선진국 경제가 직면한 가장 중요한 인구 통계학적 과제 중 하나이다." },
      { word: "employee retention", pron: "/ɪmplɔɪiː rɪtenʃən/", pos: "n.", meanings: ["직원 유지", "인재 유지"], example: "High employee retention rates reflect workplace satisfaction and reduce the costly process of recruiting replacements.", exampleKr: "높은 직원 유지율은 직장 만족도를 반영하며 대체 인원 채용의 비용이 많이 드는 과정을 줄인다." },
      { word: "paternity leave", pron: "/pətɜːrnɪti liːv/", pos: "n.", meanings: ["배우자 출산 휴가", "육아 휴가"], example: "Paid paternity leave encourages fathers to take an active role in early childcare and supports gender equality.", exampleKr: "유급 배우자 출산 휴가는 아버지가 초기 육아에 적극적인 역할을 하도록 장려하고 성 평등을 지원한다." },
      { word: "benchmark", pron: "/bentʃmɑːrk/", pos: "n./v.", meanings: ["기준", "벤치마크"], example: "Companies benchmark their salaries against industry standards to remain competitive in attracting talent.", exampleKr: "기업들은 인재 유치에 경쟁력을 유지하기 위해 업계 기준에 맞춰 급여를 벤치마크한다." }
    ]
  },
  139: {
    theme: "세계종교신화 어휘",
    words: [
      { word: "monotheism", pron: "/mɒnəʊθiɪzəm/", pos: "n.", meanings: ["일신론", "유일신 신앙"], example: "Monotheism, the belief in a single all-powerful God, characterises the major Abrahamic faiths.", exampleKr: "하나의 전능한 신에 대한 믿음인 일신론은 주요 아브라함 종교들의 특징이다." },
      { word: "polytheism", pron: "/pɒliθiɪzəm/", pos: "n.", meanings: ["다신론", "다신 신앙"], example: "Ancient Greek and Roman religion were forms of polytheism, worshipping a pantheon of distinct divine beings.", exampleKr: "고대 그리스와 로마 종교는 서로 다른 신적 존재들로 이루어진 만신전을 숭배하는 다신론의 형태였다." },
      { word: "pantheon", pron: "/pænθiɒn/", pos: "n.", meanings: ["모든 신들", "만신전"], example: "The Greek pantheon included gods overseeing all aspects of life, from love and wisdom to war and the sea.", exampleKr: "그리스 만신전은 사랑과 지혜에서 전쟁과 바다까지 삶의 모든 면을 관장하는 신들을 포함했다." },
      { word: "scripture", pron: "/skrɪptʃər/", pos: "n.", meanings: ["성전", "경전"], example: "Sacred scriptures such as the Bible, Quran, and Torah are foundational texts for their respective traditions.", exampleKr: "성경, 쿠란, 토라와 같은 성전들은 각 종교 전통의 기본 텍스트이다." },
      { word: "theology", pron: "/θiɒlədʒi/", pos: "n.", meanings: ["신학"], example: "Theology examines the nature of God, divine relationships, and religious belief through systematic philosophical inquiry.", exampleKr: "신학은 체계적인 철학적 탐구를 통해 신의 본성, 신성한 관계, 종교적 믿음을 검토한다." },
      { word: "pilgrimage", pron: "/pɪlɡrɪmɪdʒ/", pos: "n.", meanings: ["순례", "성지 순례"], example: "The Hajj, the annual pilgrimage to Mecca, is one of the five pillars of Islam and is obligatory for all able Muslims.", exampleKr: "메카로의 연례 순례인 하지는 이슬람의 다섯 기둥 중 하나로, 능력 있는 모든 이슬람 교인에게 의무이다." },
      { word: "ritual", pron: "/rɪtʃʊəl/", pos: "n./adj.", meanings: ["의식", "의례적인"], example: "Religious rituals create shared meaning, reinforce community bonds, and connect the present to sacred traditions.", exampleKr: "종교 의식은 공유된 의미를 만들고, 공동체 유대를 강화하며, 현재를 신성한 전통과 연결한다." },
      { word: "doctrine", pron: "/dɒktrɪn/", pos: "n.", meanings: ["교리", "독트린"], example: "Catholic doctrine on the Eucharist holds that the bread and wine are transformed into the body and blood of Christ.", exampleKr: "성찬식에 관한 가톨릭 교리는 빵과 포도주가 그리스도의 몸과 피로 변화한다고 주장한다." },
      { word: "clergy", pron: "/klɜːrdʒi/", pos: "n.", meanings: ["성직자", "사제단"], example: "The clergy play a central role in conducting religious services, offering pastoral care, and interpreting sacred texts.", exampleKr: "성직자들은 종교 예배를 이끌고, 목회 돌봄을 제공하며, 성전을 해석하는 데 중심적인 역할을 한다." },
      { word: "secular", pron: "/sekjʊlər/", pos: "adj.", meanings: ["세속적인", "비종교적인"], example: "France operates under a secular constitution that strictly separates religion from the functions of the state.", exampleKr: "프랑스는 종교와 국가 기능을 엄격하게 분리하는 세속적인 헌법 아래에서 운영된다." },
      { word: "denomination", pron: "/dɪnɒmɪneɪʃən/", pos: "n.", meanings: ["교파", "종파"], example: "Christianity encompasses hundreds of denominations, from Roman Catholic to Baptist and Pentecostal.", exampleKr: "기독교는 로마 카톨릭에서 침례교, 오순절교까지 수백 개의 교파를 포함한다." },
      { word: "deity", pron: "/diːɪti/", pos: "n.", meanings: ["신", "신격"], example: "In Hindu belief, the supreme deity is worshipped in many different forms and names across the tradition.", exampleKr: "힌두 신앙에서 최고 신은 전통을 통해 많은 다양한 형태와 이름으로 숭배된다." },
      { word: "mysticism", pron: "/mɪstɪsɪzəm/", pos: "n.", meanings: ["신비주의"], example: "Mysticism seeks direct personal experience of the divine, transcending formal doctrine and institutional religion.", exampleKr: "신비주의는 공식적인 교리와 제도적 종교를 초월하여 신성과의 직접적인 개인적 경험을 추구한다." },
      { word: "heresy", pron: "/herəsi/", pos: "n.", meanings: ["이단", "이설"], example: "In medieval Europe, accusations of heresy could result in severe punishment, including torture and execution.", exampleKr: "중세 유럽에서 이단 혐의는 고문과 처형을 포함한 심각한 처벌로 이어질 수 있었다." },
      { word: "incarnation", pron: "/ɪnkɑːrneɪʃən/", pos: "n.", meanings: ["화신", "육신화"], example: "The Christian doctrine of Incarnation holds that the divine became fully human in the person of Jesus Christ.", exampleKr: "기독교의 성육신 교리는 신성이 예수 그리스도의 몸으로 완전한 인간이 되었다고 주장한다." },
      { word: "karma", pron: "/kɑːrmə/", pos: "n.", meanings: ["업", "카르마"], example: "In Hindu and Buddhist thought, karma refers to the law of cause and effect governing action and its consequences.", exampleKr: "힌두교와 불교 사상에서 카르마는 행동과 그 결과를 지배하는 인과의 법칙을 말한다." },
      { word: "nirvana", pron: "/nɪrvɑːnə/", pos: "n.", meanings: ["열반", "해탈"], example: "In Buddhism, nirvana is the ultimate liberation from suffering achieved by extinguishing desire and ignorance.", exampleKr: "불교에서 열반은 욕망과 무지를 소멸시켜 달성하는 고통으로부터의 궁극적인 해방이다." },
      { word: "parable", pron: "/pærəbəl/", pos: "n.", meanings: ["비유", "우화"], example: "Jesus taught moral lessons through parables, using simple, relatable stories to illustrate deeper truths.", exampleKr: "예수님은 더 깊은 진리를 설명하기 위해 단순하고 공감할 수 있는 이야기를 사용하는 비유를 통해 도덕적 교훈을 가르쳤다." },
      { word: "apostle", pron: "/əpɒsəl/", pos: "n.", meanings: ["사도", "전도자"], example: "The Twelve Apostles were chosen by Jesus to be his closest followers and to spread his teachings after his death.", exampleKr: "열두 사도는 예수님의 가장 가까운 추종자가 되어 그의 사후에 그의 가르침을 전파하도록 예수님에 의해 선택되었다." },
      { word: "mythological", pron: "/mɪθəlɒdʒɪkəl/", pos: "adj.", meanings: ["신화의", "신화적인"], example: "Mythological stories from ancient Greece continue to inspire literature, film, and art around the world today.", exampleKr: "고대 그리스의 신화적 이야기들은 오늘날 전 세계의 문학, 영화, 예술에 계속 영감을 주고 있다." }
    ]
  },
  140: {
    theme: "논리학수사학 어휘",
    words: [
      { word: "syllogism", pron: "/sɪlədʒɪzəm/", pos: "n.", meanings: ["삼단논법"], example: "A syllogism draws a conclusion from two premises; if both are true and the logic valid, the conclusion must follow.", exampleKr: "삼단논법은 두 전제로부터 결론을 도출한다. 둘 다 참이고 논리가 유효하면 결론이 따라야 한다." },
      { word: "premise", pron: "/premɪs/", pos: "n.", meanings: ["전제", "가정"], example: "The entire argument rests on a faulty premise that assumes all wealthy people are inherently dishonest.", exampleKr: "전체 논거는 모든 부유한 사람들이 본질적으로 부정직하다고 가정하는 잘못된 전제에 의존한다." },
      { word: "inference", pron: "/ɪnfərəns/", pos: "n.", meanings: ["추론", "결론"], example: "Drawing valid inferences from limited data requires careful reasoning and awareness of potential biases.", exampleKr: "제한적인 데이터에서 유효한 추론을 도출하려면 신중한 추론과 잠재적 편향에 대한 인식이 필요하다." },
      { word: "fallacy", pron: "/fæləsi/", pos: "n.", meanings: ["오류", "궤변"], example: "The ad hominem fallacy attacks a person's character rather than addressing the substance of their argument.", exampleKr: "인신공격 오류는 논거의 본질을 다루는 대신 사람의 성격을 공격한다." },
      { word: "deductive reasoning", pron: "/dɪdʌktɪv riːzənɪŋ/", pos: "n.", meanings: ["연역적 추론"], example: "Deductive reasoning moves from general principles to specific conclusions, guaranteeing valid conclusions if premises are true.", exampleKr: "연역적 추론은 일반 원칙에서 특정 결론으로 나아가며, 전제가 참이면 유효한 결론을 보장한다." },
      { word: "inductive reasoning", pron: "/ɪndʌktɪv riːzənɪŋ/", pos: "n.", meanings: ["귀납적 추론"], example: "Inductive reasoning builds general conclusions from specific observations and is fundamental to scientific inquiry.", exampleKr: "귀납적 추론은 특정 관찰에서 일반적인 결론을 구축하며 과학적 탐구의 근본이다." },
      { word: "rhetoric", pron: "/retərɪk/", pos: "n.", meanings: ["수사학", "수사"], example: "Skilled use of rhetoric can make a weak argument sound convincing to an uncritical audience.", exampleKr: "능숙한 수사학의 사용은 약한 논거를 비판적이지 않은 청중에게 설득력 있게 들리게 할 수 있다." },
      { word: "paradox", pron: "/pærədɒks/", pos: "n.", meanings: ["역설", "모순"], example: "The paradox of heaps asks at what point, adding one grain at a time, a pile becomes a heap.", exampleKr: "소리데스 역설은 한 번에 한 알씩 추가할 때 어느 지점에서 더미가 되는지를 묻는다." },
      { word: "analogy", pron: "/ənælədʒi/", pos: "n.", meanings: ["유추", "비유"], example: "Drawing an analogy between the brain and a computer helps non-specialists understand cognitive neuroscience.", exampleKr: "뇌와 컴퓨터 사이의 유추는 비전문가가 인지 신경과학을 이해하는 데 도움이 된다." },
      { word: "dichotomy", pron: "/daɪkɒtəmi/", pos: "n.", meanings: ["이분법", "양분"], example: "The false dichotomy fallacy presents only two options when in reality there are several viable alternatives.", exampleKr: "거짓 이분법 오류는 실제로는 여러 실행 가능한 대안이 있음에도 두 가지 선택지만 제시한다." },
      { word: "tautology", pron: "/tɔːtɒlədʒi/", pos: "n.", meanings: ["동어반복", "항진명제"], example: "Saying 'a circle is round' is a tautology because roundness is already part of the definition of a circle.", exampleKr: "'원은 둥글다'고 말하는 것은 동어반복인데, 둥근 것이 이미 원의 정의의 일부이기 때문이다." },
      { word: "sophistry", pron: "/sɒfɪstri/", pos: "n.", meanings: ["궤변", "교묘한 논리"], example: "The lawyer's sophistry confused the jury by presenting technically true statements in a deeply misleading context.", exampleKr: "변호사의 궤변은 기술적으로 참인 진술을 매우 오해의 소지가 있는 맥락에서 제시함으로써 배심원을 혼란스럽게 했다." },
      { word: "dialectic", pron: "/daɪəlektɪk/", pos: "n./adj.", meanings: ["변증법", "변증법적인"], example: "Hegel's dialectic describes how thesis and antithesis clash to produce a higher synthesis.", exampleKr: "헤겔의 변증법은 어떻게 정(테제)과 반(안티테제)이 충돌하여 더 높은 합(진테제)을 생성하는지 설명한다." },
      { word: "straw man", pron: "/strɔː mæn/", pos: "n.", meanings: ["허수아비 논증", "거짓 반론"], example: "Creating a straw man involves misrepresenting an opponent's position to make it easier to refute.", exampleKr: "허수아비 논증을 만드는 것은 상대방의 입장을 오해하여 반박하기 더 쉽게 만드는 것을 포함한다." },
      { word: "ad hominem", pron: "/æd hɒmɪnem/", pos: "adj./adv.", meanings: ["인신공격의", "인신공격적으로"], example: "Resorting to ad hominem attacks signals the debater has run out of rational arguments to make.", exampleKr: "인신공격에 의존하는 것은 토론자가 제기할 합리적인 논거가 없어졌다는 신호이다." },
      { word: "ethos", pron: "/iːθɒs/", pos: "n.", meanings: ["에토스", "성격 호소"], example: "In Aristotelian rhetoric, ethos refers to the speaker's credibility and moral character as a persuasive tool.", exampleKr: "아리스토텔레스의 수사학에서 에토스는 설득 도구로서 연사의 신뢰성과 도덕적 성격을 말한다." },
      { word: "pathos", pron: "/peɪθɒs/", pos: "n.", meanings: ["파토스", "감정 호소"], example: "Effective fundraising appeals use pathos by sharing real stories of individuals affected by hardship.", exampleKr: "효과적인 모금 호소는 어려움을 겪는 개인의 실제 이야기를 공유하여 파토스를 사용한다." },
      { word: "logos", pron: "/lɒɡɒs/", pos: "n.", meanings: ["로고스", "논리 호소"], example: "A logos-based argument relies on evidence, data, and logical reasoning rather than emotional appeal.", exampleKr: "로고스 기반 논거는 감정적 호소보다는 증거, 데이터, 논리적 추론에 의존한다." },
      { word: "empirical", pron: "/ɪmpɪrɪkəl/", pos: "adj.", meanings: ["경험적인", "실증적인"], example: "Empirical evidence gathered through observation and experiment forms the basis of scientific knowledge.", exampleKr: "관찰과 실험을 통해 수집된 경험적 증거는 과학적 지식의 기반을 형성한다." },
      { word: "reductio ad absurdum", pron: "/rɪdʌktioʊ æd əbsɜːrdəm/", pos: "n.", meanings: ["귀류법", "부당한 결론 도출"], example: "Reductio ad absurdum disproves a proposition by showing that accepting it leads to an absurd conclusion.", exampleKr: "귀류법은 명제를 받아들이면 불합리한 결론으로 이어진다는 것을 보여줌으로써 명제를 반증한다." }
    ]
  }
});
