/**
 * examples2.js — 두 번째 예문 데이터
 * key 형식: "day_wordIndex"
 * Day 1~10 (200단어 × 2번째 예문)
 */
const EXAMPLES2 = {
  // ── Day 1 핵심 동사 I ──
  '1_0':  { example2: "He finally achieved his dream of running a marathon.", example2Kr: "그는 마침내 마라톤 완주라는 꿈을 이루었다." },
  '1_1':  { example2: "Organisms must adapt to survive in changing environments.", example2Kr: "생물은 변화하는 환경에서 생존하기 위해 적응해야 한다." },
  '1_2':  { example2: "We need to advance our knowledge in this field.", example2Kr: "우리는 이 분야에서 지식을 발전시켜야 한다." },
  '1_3':  { example2: "Time should be allocated wisely each day.", example2Kr: "매일 시간을 현명하게 배분해야 한다." },
  '1_4':  { example2: "The doctor analyzed the test results carefully.", example2Kr: "의사가 검사 결과를 신중하게 분석했다." },
  '1_5':  { example2: "We anticipated delays due to the storm.", example2Kr: "우리는 폭풍으로 인한 지연을 예상했다." },
  '1_6':  { example2: "The same principles apply in both cases.", example2Kr: "동일한 원칙이 두 경우 모두에 적용된다." },
  '1_7':  { example2: "It is difficult to assess the full impact of the decision.", example2Kr: "그 결정의 전체 영향을 평가하기는 어렵다." },
  '1_8':  { example2: "Never assume you know everything.", example2Kr: "모든 것을 안다고 절대 가정하지 마라." },
  '1_9':  { example2: "Honey attracts bees and other insects.", example2Kr: "꿀은 벌과 다른 곤충들을 끌어들인다." },
  '1_10': { example2: "Higher education benefits society as a whole.", example2Kr: "고등 교육은 사회 전체에 이익을 준다." },
  '1_11': { example2: "The coach challenged the team to improve their performance.", example2Kr: "코치는 팀에게 성적 향상에 도전하라고 했다." },
  '1_12': { example2: "Animals communicate in various ways.", example2Kr: "동물들은 다양한 방법으로 의사소통한다." },
  '1_13': { example2: "Many companies are competing for the same customers.", example2Kr: "많은 회사들이 같은 고객들을 두고 경쟁하고 있다." },
  '1_14': { example2: "He concentrated all his energy on the final project.", example2Kr: "그는 모든 에너지를 마지막 프로젝트에 집중했다." },
  '1_15': { example2: "Can you confirm that the meeting is at 3 PM?", example2Kr: "회의가 오후 3시인 것을 확인해 줄 수 있나요?" },
  '1_16': { example2: "Have you considered the risks involved?", example2Kr: "관련된 위험들을 고려해 보셨나요?" },
  '1_17': { example2: "Many factors contribute to climate change.", example2Kr: "많은 요인들이 기후 변화에 기여한다." },
  '1_18': { example2: "Music has the power to create strong emotions.", example2Kr: "음악은 강한 감정을 만들어내는 힘이 있다." },
  '1_19': { example2: "Success is defined differently by different people.", example2Kr: "성공은 사람마다 다르게 정의된다." },

  // ── Day 2 핵심 동사 II ──
  '2_0':  { example2: "The student demonstrated excellent problem-solving skills.", example2Kr: "그 학생은 뛰어난 문제 해결 능력을 보여주었다." },
  '2_1':  { example2: "Children develop language skills at different rates.", example2Kr: "아이들은 서로 다른 속도로 언어 능력을 발전시킨다." },
  '2_2':  { example2: "I discovered a great coffee shop near my office.", example2Kr: "나는 사무실 근처에서 좋은 커피숍을 발견했다." },
  '2_3':  { example2: "We discussed the issue for over an hour.", example2Kr: "우리는 한 시간 넘게 그 문제를 논의했다." },
  '2_4':  { example2: "She displayed great courage under pressure.", example2Kr: "그녀는 압박감 속에서도 대단한 용기를 보여주었다." },
  '2_5':  { example2: "A good education enables people to pursue better careers.", example2Kr: "좋은 교육은 사람들이 더 나은 직업을 추구할 수 있게 한다." },
  '2_6':  { example2: "The manager encouraged her team through difficult times.", example2Kr: "매니저는 힘든 시기를 헤쳐나가도록 팀을 격려했다." },
  '2_7':  { example2: "She established herself as a leading expert in the field.", example2Kr: "그녀는 그 분야의 선도적인 전문가로 자리를 확립했다." },
  '2_8':  { example2: "Students should evaluate their own work regularly.", example2Kr: "학생들은 자신의 작업을 정기적으로 평가해야 한다." },
  '2_9':  { example2: "The company expanded its product line to attract new customers.", example2Kr: "회사는 새 고객을 유치하기 위해 제품 라인을 확장했다." },
  '2_10': { example2: "Children love to explore new places.", example2Kr: "아이들은 새로운 장소를 탐험하는 것을 좋아한다." },
  '2_11': { example2: "Art is a way to express ideas beyond words.", example2Kr: "예술은 말을 넘어 생각을 표현하는 방법이다." },
  '2_12': { example2: "The report focuses on environmental issues.", example2Kr: "그 보고서는 환경 문제에 초점을 맞추고 있다." },
  '2_13': { example2: "The new policy generated a lot of debate.", example2Kr: "새 정책은 많은 토론을 불러일으켰다." },
  '2_14': { example2: "Police identified the suspect through CCTV footage.", example2Kr: "경찰은 CCTV 영상을 통해 용의자를 확인했다." },
  '2_15': { example2: "It's not easy to implement change in large organizations.", example2Kr: "대형 조직에서 변화를 실행하는 것은 쉽지 않다." },
  '2_16': { example2: "The city has improved its public transportation system.", example2Kr: "그 도시는 대중교통 시스템을 개선했다." },
  '2_17': { example2: "His expression indicated that he was unhappy.", example2Kr: "그의 표정이 그가 기분이 좋지 않음을 나타냈다." },
  '2_18': { example2: "Parenting style influences a child's development.", example2Kr: "양육 방식은 아이의 발달에 영향을 미친다." },
  '2_19': { example2: "The rescue operation involved hundreds of volunteers.", example2Kr: "구조 작전에는 수백 명의 자원봉사자가 참여했다." },

  // ── Day 3 핵심 형용사 I ──
  '3_0':  { example2: "Her thesis was too abstract to be easily understood.", example2Kr: "그녀의 논문은 너무 추상적이어서 이해하기 어려웠다." },
  '3_1':  { example2: "It's important to keep accurate records.", example2Kr: "정확한 기록을 유지하는 것이 중요하다." },
  '3_2':  { example2: "The facilities were adequate but not exceptional.", example2Kr: "시설은 충분하지만 특별하지는 않았다." },
  '3_3':  { example2: "A dog may become aggressive if it feels threatened.", example2Kr: "개는 위협을 느끼면 공격적이 될 수 있다." },
  '3_4':  { example2: "His ambitious plan impressed everyone at the meeting.", example2Kr: "그의 야심찬 계획이 회의에 참석한 모든 사람을 감동시켰다." },
  '3_5':  { example2: "She was anxious about speaking in front of a large crowd.", example2Kr: "그녀는 많은 사람들 앞에서 말하는 것에 대해 불안했다." },
  '3_6':  { example2: "It's not appropriate to use your phone during class.", example2Kr: "수업 중에 휴대폰을 사용하는 것은 적절하지 않다." },
  '3_7':  { example2: "There are still a few tickets available for tonight's show.", example2Kr: "오늘 밤 공연의 표가 아직 몇 장 남아 있다." },
  '3_8':  { example2: "Reading is beneficial for improving vocabulary.", example2Kr: "독서는 어휘력 향상에 이롭다." },
  '3_9':  { example2: "The team is capable of achieving great results.", example2Kr: "그 팀은 훌륭한 결과를 달성할 능력이 있다." },
  '3_10': { example2: "There are certain rules you must follow.", example2Kr: "반드시 따라야 하는 특정 규칙들이 있다." },
  '3_11': { example2: "He wrote a comprehensive guide to healthy eating.", example2Kr: "그는 건강한 식습관에 관한 종합적인 가이드를 썼다." },
  '3_12': { example2: "She is very conscious of her posture while working.", example2Kr: "그녀는 일하는 동안 자신의 자세를 매우 의식한다." },
  '3_13': { example2: "A consistent sleep schedule improves overall health.", example2Kr: "일관된 수면 일정은 전반적인 건강을 향상시킨다." },
  '3_14': { example2: "It's very convenient to live near a subway station.", example2Kr: "지하철역 근처에 사는 것은 매우 편리하다." },
  '3_15': { example2: "The children surprised everyone with their creative artwork.", example2Kr: "아이들은 창의적인 작품으로 모든 사람을 놀라게 했다." },
  '3_16': { example2: "Water is critical to the survival of all living things.", example2Kr: "물은 모든 생물의 생존에 매우 중요하다." },
  '3_17': { example2: "The curious student asked many thoughtful questions.", example2Kr: "호기심 많은 학생이 많은 사려 깊은 질문을 했다." },
  '3_18': { example2: "He is dedicated to making a positive difference in the community.", example2Kr: "그는 지역 사회에 긍정적인 변화를 만들기 위해 전념하고 있다." },
  '3_19': { example2: "Our team has diverse skills and backgrounds.", example2Kr: "우리 팀은 다양한 기술과 배경을 가지고 있다." },

  // ── Day 4 핵심 형용사 II ──
  '4_0':  { example2: "The new CEO brought a dynamic energy to the company.", example2Kr: "새 CEO는 회사에 역동적인 에너지를 가져왔다." },
  '4_1':  { example2: "She found a more efficient way to complete the task.", example2Kr: "그녀는 그 과제를 완수하는 더 효율적인 방법을 찾았다." },
  '4_2':  { example2: "Good communication skills are essential in any career.", example2Kr: "좋은 의사소통 기술은 어떤 직업에서도 필수적이다." },
  '4_3':  { example2: "The effects of stress were evident on his face.", example2Kr: "스트레스의 영향이 그의 얼굴에 분명히 나타났다." },
  '4_4':  { example2: "Only members have exclusive access to the lounge.", example2Kr: "회원만이 라운지에 독점적으로 접근할 수 있다." },
  '4_5':  { example2: "A flexible schedule allows employees to maintain work-life balance.", example2Kr: "유연한 일정은 직원들이 일과 삶의 균형을 유지할 수 있게 한다." },
  '4_6':  { example2: "Honesty is fundamental to any lasting friendship.", example2Kr: "정직은 지속되는 모든 우정의 근본이다." },
  '4_7':  { example2: "She showed genuine interest in learning about other cultures.", example2Kr: "그녀는 다른 문화에 대해 배우는 데 진정한 관심을 보였다." },
  '4_8':  { example2: "Social media has made communication a global phenomenon.", example2Kr: "소셜 미디어는 의사소통을 세계적인 현상으로 만들었다." },
  '4_9':  { example2: "The gradual rise in temperature is a sign of climate change.", example2Kr: "온도의 점진적인 상승은 기후 변화의 신호이다." },
  '4_10': { example2: "The mountains are the ideal place for a peaceful retreat.", example2Kr: "산은 평화로운 휴식을 위한 이상적인 장소이다." },
  '4_11': { example2: "The government took immediate action to control the spread of disease.", example2Kr: "정부는 질병 확산을 막기 위해 즉각적인 조치를 취했다." },
  '4_12': { example2: "The report was conducted by an independent research team.", example2Kr: "그 보고서는 독립적인 연구팀에 의해 수행되었다." },
  '4_13': { example2: "Conflict is an inevitable part of working in teams.", example2Kr: "갈등은 팀에서 일하는 불가피한 부분이다." },
  '4_14': { example2: "Innovative thinking can solve problems others think are impossible.", example2Kr: "혁신적인 사고는 다른 사람들이 불가능하다고 생각하는 문제를 해결할 수 있다." },
  '4_15': { example2: "The intense heat made it difficult to work outside.", example2Kr: "강렬한 더위로 인해 밖에서 일하기가 어려웠다." },
  '4_16': { example2: "The most logical solution is to cut unnecessary expenses.", example2Kr: "가장 논리적인 해결책은 불필요한 지출을 줄이는 것이다." },
  '4_17': { example2: "Motivated employees tend to be more productive.", example2Kr: "의욕 있는 직원들은 더 생산적인 경향이 있다." },
  '4_18': { example2: "Switzerland is known for its neutral foreign policy.", example2Kr: "스위스는 중립적인 외교 정책으로 알려져 있다." },
  '4_19': { example2: "It was obvious from her tone that she was disappointed.", example2Kr: "그녀의 어조에서 실망했다는 것이 분명했다." },

  // ── Day 5 핵심 명사 I ──
  '5_0':  { example2: "Learning to speak another language is a remarkable achievement.", example2Kr: "다른 언어를 말하는 것을 배우는 것은 놀라운 성취이다." },
  '5_1':  { example2: "Starting early gives you a significant advantage.", example2Kr: "일찍 시작하는 것은 상당한 이점을 준다." },
  '5_2':  { example2: "The teacher used a hands-on approach to teaching science.", example2Kr: "선생님은 과학 수업에 실습 접근법을 사용했다." },
  '5_3':  { example2: "Time management is an important aspect of productivity.", example2Kr: "시간 관리는 생산성의 중요한 측면이다." },
  '5_4':  { example2: "There was a tense atmosphere in the meeting room.", example2Kr: "회의실에 긴장된 분위기가 감돌았다." },
  '5_5':  { example2: "His attitude toward learning improved after the workshop.", example2Kr: "그의 학습에 대한 태도는 워크숍 후에 개선되었다." },
  '5_6':  { example2: "The police have the authority to enforce the law.", example2Kr: "경찰은 법을 집행할 권한이 있다." },
  '5_7':  { example2: "The teacher addressed the disruptive behavior immediately.", example2Kr: "선생님은 방해가 되는 행동을 즉시 처리했다." },
  '5_8':  { example2: "One benefit of remote work is the ability to set your own schedule.", example2Kr: "재택근무의 한 가지 혜택은 자신만의 일정을 정할 수 있다는 것이다." },
  '5_9':  { example2: "He decided to change his career from finance to education.", example2Kr: "그는 금융에서 교육으로 직업을 바꾸기로 결정했다." },
  '5_10': { example2: "The investigation revealed unusual circumstances surrounding the incident.", example2Kr: "조사를 통해 사건 주변의 특이한 상황이 밝혀졌다." },
  '5_11': { example2: "Nonverbal communication can be just as powerful as words.", example2Kr: "비언어적 의사소통은 말만큼 강력할 수 있다." },
  '5_12': { example2: "Local businesses play a vital role in the community.", example2Kr: "지역 사업체는 지역 사회에서 중요한 역할을 한다." },
  '5_13': { example2: "Healthy competition motivates people to do their best.", example2Kr: "건전한 경쟁은 사람들이 최선을 다하도록 동기를 부여한다." },
  '5_14': { example2: "She explained the concept clearly with simple examples.", example2Kr: "그녀는 간단한 예시로 개념을 명확하게 설명했다." },
  '5_15': { example2: "Workers demanded better pay and working conditions.", example2Kr: "근로자들은 더 나은 급여와 근무 조건을 요구했다." },
  '5_16': { example2: "A good mentor helps you build confidence in your abilities.", example2Kr: "좋은 멘토는 자신의 능력에 대한 자신감을 키우는 데 도움이 된다." },
  '5_17': { example2: "Learning to manage conflict is an essential life skill.", example2Kr: "갈등을 관리하는 법을 배우는 것은 필수적인 생활 기술이다." },
  '5_18': { example2: "Climate change has serious consequences for the planet.", example2Kr: "기후 변화는 지구에 심각한 결과를 초래한다." },
  '5_19': { example2: "It's essential to consider the historical context of events.", example2Kr: "사건의 역사적 맥락을 고려하는 것이 필수적이다." },

  // ── Day 6 핵심 명사 II ──
  '6_0':  { example2: "Volunteering is a meaningful contribution to society.", example2Kr: "자원봉사는 사회에 의미 있는 기여이다." },
  '6_1':  { example2: "The film sparked controversy over its historical accuracy.", example2Kr: "그 영화는 역사적 정확성에 대한 논란을 불러일으켰다." },
  '6_2':  { example2: "Boredom can sometimes spark creativity.", example2Kr: "지루함이 때로는 창의력을 자극할 수 있다." },
  '6_3':  { example2: "Food is an important part of Korean culture.", example2Kr: "음식은 한국 문화의 중요한 부분이다." },
  '6_4':  { example2: "It was a difficult decision, but she chose to move abroad.", example2Kr: "어려운 결정이었지만 그녀는 해외로 이사하기로 선택했다." },
  '6_5':  { example2: "The demand for electric vehicles is increasing rapidly.", example2Kr: "전기 자동차에 대한 수요가 빠르게 증가하고 있다." },
  '6_6':  { example2: "Sustainable development balances economic growth with environmental care.", example2Kr: "지속 가능한 발전은 경제 성장과 환경 보호의 균형을 맞춘다." },
  '6_7':  { example2: "The school celebrates diversity through cultural events.", example2Kr: "학교는 문화 행사를 통해 다양성을 축하한다." },
  '6_8':  { example2: "A growing economy creates more job opportunities.", example2Kr: "성장하는 경제는 더 많은 일자리 기회를 창출한다." },
  '6_9':  { example2: "The importance of early childhood education cannot be overstated.", example2Kr: "유아 교육의 중요성은 아무리 강조해도 지나치지 않다." },
  '6_10': { example2: "A clean environment is essential for physical and mental health.", example2Kr: "깨끗한 환경은 신체적·정신적 건강에 필수적이다." },
  '6_11': { example2: "Archaeologists found evidence of an ancient civilization.", example2Kr: "고고학자들은 고대 문명의 증거를 발견했다." },
  '6_12': { example2: "Traveling gives you experience no classroom can provide.", example2Kr: "여행은 어떤 교실도 제공할 수 없는 경험을 준다." },
  '6_13': { example2: "Location is a major factor when choosing a school.", example2Kr: "위치는 학교를 선택할 때 주요한 요인이다." },
  '6_14': { example2: "Many successful entrepreneurs experienced failure before succeeding.", example2Kr: "많은 성공한 기업가들은 성공하기 전에 실패를 경험했다." },
  '6_15': { example2: "The new car model features an advanced safety system.", example2Kr: "새 자동차 모델은 고급 안전 시스템을 특징으로 한다." },
  '6_16': { example2: "Early childhood experiences form the foundation of personality.", example2Kr: "유아기의 경험이 개성의 토대를 형성한다." },
  '6_17': { example2: "He fought for the freedom to choose his own path.", example2Kr: "그는 자신만의 길을 선택할 자유를 위해 싸웠다." },
  '6_18': { example2: "Sleep has the vital function of restoring the body.", example2Kr: "수면은 신체를 회복시키는 중요한 기능을 한다." },
  '6_19': { example2: "She set a goal to read 12 books this year.", example2Kr: "그녀는 올해 12권의 책을 읽겠다는 목표를 세웠다." },

  // ── Day 7 일상생활 표현 I ──
  '7_0':  { example2: "The company acknowledged the problem and offered a refund.", example2Kr: "회사는 문제를 인정하고 환불을 제공했다." },
  '7_1':  { example2: "Study abroad is something not everyone can afford.", example2Kr: "해외 유학은 모든 사람이 여유가 있는 것은 아니다." },
  '7_2':  { example2: "We agreed to meet at the café at noon.", example2Kr: "우리는 정오에 카페에서 만나기로 합의했다." },
  '7_3':  { example2: "He called to apologize for missing the meeting.", example2Kr: "그는 회의에 불참한 것을 사과하기 위해 전화했다." },
  '7_4':  { example2: "A new message appeared on the screen.", example2Kr: "화면에 새 메시지가 나타났다." },
  '7_5':  { example2: "His mother arranged all the books neatly on the shelf.", example2Kr: "그의 어머니는 책장에 모든 책을 깔끔하게 정리했다." },
  '7_6':  { example2: "He avoided the topic whenever it came up.", example2Kr: "그 화제가 나올 때마다 그는 피했다." },
  '7_7':  { example2: "The residents complained about the construction noise.", example2Kr: "주민들은 공사 소음에 대해 불평했다." },
  '7_8':  { example2: "She uses meditation to cope with anxiety.", example2Kr: "그녀는 불안감에 대처하기 위해 명상을 사용한다." },
  '7_9':  { example2: "They decided to postpone the trip due to bad weather.", example2Kr: "그들은 나쁜 날씨로 인해 여행을 연기하기로 결정했다." },
  '7_10': { example2: "You can't always depend on others to solve your problems.", example2Kr: "항상 다른 사람들이 네 문제를 해결해 줄 것이라고 의존할 수는 없다." },
  '7_11': { example2: "Every child deserves a safe and loving home.", example2Kr: "모든 아이는 안전하고 사랑스러운 가정을 받을 자격이 있다." },
  '7_12': { example2: "They disagreed on the best way to solve the problem.", example2Kr: "그들은 문제를 해결하는 최선의 방법에 대해 의견이 달랐다." },
  '7_13': { example2: "You can earn extra income by freelancing on weekends.", example2Kr: "주말에 프리랜서 업무를 통해 추가 수입을 벌 수 있다." },
  '7_14': { example2: "The professor expects students to submit work on time.", example2Kr: "교수는 학생들이 제때 과제를 제출하기를 기대한다." },
  '7_15': { example2: "She patiently explained the instructions step by step.", example2Kr: "그녀는 지침을 단계별로 차분하게 설명했다." },
  '7_16': { example2: "The power grid failed during the storm.", example2Kr: "폭풍 동안 전력망이 고장났다." },
  '7_17': { example2: "Children need to learn how to handle disappointment.", example2Kr: "아이들은 실망감을 처리하는 방법을 배울 필요가 있다." },
  '7_18': { example2: "She hesitated to accept the job offer without more details.", example2Kr: "그녀는 더 많은 세부 사항 없이 취업 제안을 수락하는 것을 주저했다." },
  '7_19': { example2: "He managed to finish the report despite the tight deadline.", example2Kr: "그는 촉박한 마감에도 불구하고 어떻게든 보고서를 완성했다." },

  // ── Day 8 일상생활 표현 II ──
  '8_0':  { example2: "He briefly mentioned his plans for the weekend.", example2Kr: "그는 주말 계획을 간략히 언급했다." },
  '8_1':  { example2: "I notice you've changed your hairstyle.", example2Kr: "헤어스타일을 바꾼 것을 알아챘어요." },
  '8_2':  { example2: "With persistence, you can overcome any obstacle.", example2Kr: "인내심으로 어떤 장애물도 극복할 수 있다." },
  '8_3':  { example2: "Students who participate actively tend to learn more.", example2Kr: "적극적으로 참여하는 학생들은 더 많이 배우는 경향이 있다." },
  '8_4':  { example2: "The salesperson persuaded me to buy the extended warranty.", example2Kr: "판매원이 나에게 연장 보증을 구매하도록 설득했다." },
  '8_5':  { example2: "The government provides free healthcare to all citizens.", example2Kr: "정부는 모든 시민에게 무료 의료를 제공한다." },
  '8_6':  { example2: "She realized the importance of sleep after falling ill.", example2Kr: "그녀는 병이 난 후 수면의 중요성을 깨달았다." },
  '8_7':  { example2: "The doctor recommended regular exercise for heart health.", example2Kr: "의사는 심장 건강을 위해 규칙적인 운동을 권고했다." },
  '8_8':  { example2: "He refused the offer because the salary was too low.", example2Kr: "그는 급여가 너무 낮아서 제안을 거절했다." },
  '8_9':  { example2: "This song always reminds me of my childhood.", example2Kr: "이 노래는 항상 내 어린 시절을 생각나게 한다." },
  '8_10': { example2: "Digital photos have replaced traditional film cameras.", example2Kr: "디지털 사진이 전통적인 필름 카메라를 대체했다." },
  '8_11': { example2: "Becoming a doctor requires years of dedicated study.", example2Kr: "의사가 되기 위해서는 수년간의 헌신적인 공부가 필요하다." },
  '8_12': { example2: "Students learn to respect both their teachers and peers.", example2Kr: "학생들은 교사와 동료 모두를 존중하는 것을 배운다." },
  '8_13': { example2: "The company responded to customer complaints within 24 hours.", example2Kr: "회사는 24시간 이내에 고객 불만에 응답했다." },
  '8_14': { example2: "She shared her personal story to inspire others.", example2Kr: "그녀는 다른 사람들에게 영감을 주기 위해 자신의 개인 이야기를 나눴다." },
  '8_15': { example2: "Teamwork is often the best way to solve complex problems.", example2Kr: "팀워크는 복잡한 문제를 해결하는 가장 좋은 방법인 경우가 많다." },
  '8_16': { example2: "She succeeded in passing the difficult certification exam.", example2Kr: "그녀는 어려운 자격증 시험을 통과하는 데 성공했다." },
  '8_17': { example2: "The HR manager suggested hiring more part-time staff.", example2Kr: "인사 매니저는 더 많은 파트타임 직원을 채용할 것을 제안했다." },
  '8_18': { example2: "Never share your password with someone you don't trust.", example2Kr: "신뢰하지 않는 사람과 비밀번호를 공유하지 마라." },
  '8_19': { example2: "I often wonder about the meaning of life.", example2Kr: "나는 종종 삶의 의미에 대해 궁금해한다." },

  // ── Day 9 학문 & 직업 어휘 ──
  '9_0':  { example2: "Please submit a 200-word abstract with your research paper.", example2Kr: "연구 논문과 함께 200단어 요약을 제출해 주세요." },
  '9_1':  { example2: "He decided to pursue an academic career rather than work in industry.", example2Kr: "그는 산업 분야보다 학문적 경력을 쌓기로 결정했다." },
  '9_2':  { example2: "The company acquired three smaller businesses last year.", example2Kr: "회사는 작년에 세 곳의 소규모 기업을 인수했다." },
  '9_3':  { example2: "The new hospital administration introduced stricter visiting hours.", example2Kr: "새 병원 행정부는 더 엄격한 면회 시간을 도입했다." },
  '9_4':  { example2: "He spent hours preparing his university application.", example2Kr: "그는 대학 지원서를 준비하는 데 몇 시간을 보냈다." },
  '9_5':  { example2: "The group assignment required collaboration among all members.", example2Kr: "그룹 과제는 모든 구성원 간의 협력이 필요했다." },
  '9_6':  { example2: "The interview panel selected the most qualified candidate.", example2Kr: "면접 위원회는 가장 자격을 갖춘 지원자를 선발했다." },
  '9_7':  { example2: "She received a certificate of completion at the workshop.", example2Kr: "그녀는 워크숍에서 수료증을 받았다." },
  '9_8':  { example2: "I had lunch with my colleagues to celebrate a project success.", example2Kr: "나는 프로젝트 성공을 축하하기 위해 동료들과 점심을 먹었다." },
  '9_9':  { example2: "The curriculum was revised to include more practical skills.", example2Kr: "교육과정이 더 많은 실용적인 기술을 포함하도록 개정되었다." },
  '9_10': { example2: "She stayed up all night to meet the assignment deadline.", example2Kr: "그녀는 과제 마감을 지키기 위해 밤새 공부했다." },
  '9_11': { example2: "He earned his master's degree in two years.", example2Kr: "그는 2년 만에 석사 학위를 취득했다." },
  '9_12': { example2: "The marketing department launched a new campaign.", example2Kr: "마케팅 부서가 새 캠페인을 시작했다." },
  '9_13': { example2: "The executive team approved the annual budget.", example2Kr: "임원진이 연간 예산을 승인했다." },
  '9_14': { example2: "The project required expertise in both design and engineering.", example2Kr: "그 프로젝트는 디자인과 공학 양쪽의 전문성이 필요했다." },
  '9_15': { example2: "She graduated with honors from a top university.", example2Kr: "그녀는 최우수 성적으로 명문 대학을 졸업했다." },
  '9_16': { example2: "She applied for a summer internship at a publishing company.", example2Kr: "그녀는 출판사에서 여름 인턴십에 지원했다." },
  '9_17': { example2: "He practiced his presentation in front of the mirror.", example2Kr: "그는 거울 앞에서 발표 연습을 했다." },
  '9_18': { example2: "You need the right qualifications to apply for this position.", example2Kr: "이 직위에 지원하려면 적합한 자격이 필요하다." },
  '9_19': { example2: "The professor hosted a weekly seminar for graduate students.", example2Kr: "교수는 대학원생을 위한 주간 세미나를 주최했다." },

  // ── Day 10 사회 & 시사 어휘 ──
  '10_0':  { example2: "His advocacy for environmental protection earned international recognition.", example2Kr: "환경 보호를 위한 그의 옹호 활동은 국제적인 인정을 받았다." },
  '10_1':  { example2: "Journalists should report news without political bias.", example2Kr: "기자들은 정치적 편견 없이 뉴스를 보도해야 한다." },
  '10_2':  { example2: "As a responsible citizen, you should vote in elections.", example2Kr: "책임 있는 시민으로서 선거에서 투표해야 한다." },
  '10_3':  { example2: "Corruption in the justice system is a serious problem.", example2Kr: "사법 시스템의 부패는 심각한 문제이다." },
  '10_4':  { example2: "A healthy democracy requires free and fair elections.", example2Kr: "건강한 민주주의는 자유롭고 공정한 선거를 필요로 한다." },
  '10_5':  { example2: "Laws exist to protect people from racial discrimination.", example2Kr: "인종 차별로부터 사람들을 보호하기 위한 법률이 있다." },
  '10_6':  { example2: "The movement fought for equality in the workplace.", example2Kr: "그 운동은 직장 내 평등을 위해 싸웠다." },
  '10_7':  { example2: "Globalization has made it easier to trade across borders.", example2Kr: "세계화로 인해 국경을 넘는 무역이 더 쉬워졌다." },
  '10_8':  { example2: "The country introduced new policies to control immigration.", example2Kr: "그 나라는 이민을 통제하기 위한 새 정책을 도입했다." },
  '10_9':  { example2: "Access to quality education is affected by economic inequality.", example2Kr: "양질의 교육에 대한 접근성은 경제적 불평등에 영향을 받는다." },
  '10_10': { example2: "Good infrastructure attracts foreign investment.", example2Kr: "좋은 사회 기반 시설은 외국인 투자를 유치한다." },
  '10_11': { example2: "New environmental legislation limits industrial pollution.", example2Kr: "새로운 환경 법률이 산업 오염을 제한한다." },
  '10_12': { example2: "Social media has changed the way we receive news.", example2Kr: "소셜 미디어는 우리가 뉴스를 받는 방식을 바꾸었다." },
  '10_13': { example2: "Government policy plays a key role in shaping society.", example2Kr: "정부 정책은 사회를 형성하는 데 핵심적인 역할을 한다." },
  '10_14': { example2: "Global efforts to end poverty have made significant progress.", example2Kr: "빈곤을 없애기 위한 세계적인 노력이 상당한 진전을 이루었다." },
  '10_15': { example2: "Overcoming prejudice requires education and open-mindedness.", example2Kr: "편견을 극복하기 위해서는 교육과 열린 마음이 필요하다." },
  '10_16': { example2: "Workers organized a protest against the unfair layoffs.", example2Kr: "근로자들은 부당한 해고에 반대하는 시위를 조직했다." },
  '10_17': { example2: "Tax reform is essential to address economic inequality.", example2Kr: "세금 개혁은 경제적 불평등을 해결하기 위해 필수적이다." },
  '10_18': { example2: "Companies are increasingly adopting sustainability practices.", example2Kr: "기업들은 점점 더 지속 가능성 관행을 채택하고 있다." },
  '10_19': { example2: "Child welfare organizations provide support to vulnerable families.", example2Kr: "아동 복지 기관은 취약한 가정에 지원을 제공한다." },
};
