/**
 * examples2_3.js - Day 51~80 예문 데이터
 * examples2_2.js 이후에 로드해야 합니다
 */
Object.assign(EXAMPLES2, {
  // ── Day 51 TOEIC 빈출 어휘 I ──
  '51_0':  { example2: "The hotel accommodated all the conference delegates despite the last-minute booking.", example2Kr: "호텔은 막판 예약에도 불구하고 모든 학회 대표단을 수용했다." },
  '51_1':  { example2: "The meeting agenda was distributed to all participants the evening before.", example2Kr: "회의 의제는 전날 저녁에 모든 참가자들에게 배포되었다." },
  '51_2':  { example2: "Only senior managers are authorized to approve large expenditures.", example2Kr: "대규모 지출 승인은 고위 관리자만 할 수 있다." },
  '51_3':  { example2: "The bulk of the research was completed before the funding ran out.", example2Kr: "연구의 대부분은 자금이 바닥나기 전에 완료되었다." },
  '51_4':  { example2: "The supplier failed to comply with delivery deadlines stated in the agreement.", example2Kr: "공급업체가 계약서에 명시된 납기 기한을 준수하지 못했다." },
  '51_5':  { example2: "The software recorded five consecutive system errors within one hour.", example2Kr: "소프트웨어가 한 시간 내에 연속 5건의 시스템 오류를 기록했다." },
  '51_6':  { example2: "The new park area was officially designated as a UNESCO World Heritage site.", example2Kr: "새 공원 지역이 공식적으로 유네스코 세계 문화유산으로 지정되었다." },
  '51_7':  { example2: "Staff were informed of the expected duration of the system maintenance period.", example2Kr: "직원들은 예상되는 시스템 유지보수 기간을 통보받았다." },
  '51_8':  { example2: "Only residents who have lived in the district for over a year are eligible to vote.", example2Kr: "1년 이상 해당 구에 거주한 주민만 투표할 자격이 있다." },
  '51_9':  { example2: "The digital platform facilitates direct communication between doctors and patients.", example2Kr: "디지털 플랫폼이 의사와 환자 간의 직접 소통을 용이하게 한다." },
  '51_10': { example2: "The city council voted to implement stricter noise control ordinances.", example2Kr: "시의회는 더 엄격한 소음 규제 조례를 시행하기로 표결했다." },
  '51_11': { example2: "The nonprofit launched a new initiative to provide free meals to schoolchildren.", example2Kr: "비영리 단체는 학생들에게 무료 급식을 제공하는 새로운 계획을 시작했다." },
  '51_12': { example2: "The freelancer sent an invoice listing every hour worked on the project.", example2Kr: "프리랜서는 프로젝트에 투입된 모든 작업 시간을 나열한 청구서를 보냈다." },
  '51_13': { example2: "The central bank announced a new monetary policy to control rising prices.", example2Kr: "중앙은행은 물가 상승을 통제하기 위한 새로운 통화 정책을 발표했다." },
  '51_14': { example2: "The union successfully negotiated a 10% pay increase for all workers.", example2Kr: "노조는 모든 근로자를 위한 10% 임금 인상을 성공적으로 협상했다." },
  '51_15': { example2: "Residents were notified of the road closure two weeks in advance.", example2Kr: "주민들은 2주 전에 도로 폐쇄 사실을 통보받았다." },
  '51_16': { example2: "Due to a simple oversight, the wrong date was printed on the event flyers.", example2Kr: "단순한 실수로 이벤트 전단지에 잘못된 날짜가 인쇄되었다." },
  '51_17': { example2: "He became proficient in Japanese through years of daily practice and immersion.", example2Kr: "그는 매일 꾸준한 연습과 몰입을 통해 일본어에 능숙해졌다." },
  '51_18': { example2: "Employees who use personal vehicles for work are reimbursed at a standard mileage rate.", example2Kr: "업무에 개인 차량을 사용하는 직원들은 표준 요율로 환불받는다." },
  '51_19': { example2: "The tax authority investigated the company's revenue figures for the past three years.", example2Kr: "세무 당국은 지난 3년간 회사의 수익 수치를 조사했다." },

  // ── Day 52 TOEIC 빈출 어휘 II ──
  '52_0':  { example2: "An independent audit confirmed that all funds had been properly accounted for.", example2Kr: "독립 감사를 통해 모든 자금이 적절히 처리되었음을 확인했다." },
  '52_1':  { example2: "The settlement included full compensation for medical bills and lost wages.", example2Kr: "합의에는 의료비와 lost wages에 대한 전액 보상이 포함되었다." },
  '52_2':  { example2: "The terms of the acquisition deal remained confidential for several weeks.", example2Kr: "인수 계약의 조건은 몇 주간 기밀로 유지되었다." },
  '52_3':  { example2: "Charitable donations of up to $500 can be deducted from annual tax returns.", example2Kr: "500달러까지의 자선 기부금을 연간 세금 신고에서 공제할 수 있다." },
  '52_4':  { example2: "The director delegated responsibility for social media to the marketing team.", example2Kr: "이사는 소셜 미디어에 대한 책임을 마케팅 팀에 위임했다." },
  '52_5':  { example2: "The sports brand endorsed by the champion saw a dramatic rise in sales.", example2Kr: "그 챔피언이 지지하는 스포츠 브랜드는 판매량이 급격히 증가했다." },
  '52_6':  { example2: "The government's fiscal policy aimed to cut the national deficit within three years.", example2Kr: "정부의 재정 정책은 3년 내에 국가 적자를 줄이는 것을 목표로 했다." },
  '52_7':  { example2: "The store was shut down after health inspectors found serious inventory discrepancies.", example2Kr: "보건 검사관이 심각한 재고 불일치를 발견한 후 가게가 폐쇄되었다." },
  '52_8':  { example2: "Regulators scrutinized the proposed merger for potential anti-competitive effects.", example2Kr: "규제 당국은 잠재적인 반경쟁 효과를 위해 제안된 합병을 면밀히 검토했다." },
  '52_9':  { example2: "The historic theater was renovated and reopened to great public enthusiasm.", example2Kr: "역사적인 극장이 개조되어 대중의 열렬한 환영 속에 재개관했다." },
  '52_10': { example2: "The two neighbors agreed to resolve their boundary dispute with a surveyor's help.", example2Kr: "두 이웃은 측량사의 도움으로 경계 분쟁을 해결하기로 합의했다." },
  '52_11': { example2: "The authors revised their model after new data challenged key assumptions.", example2Kr: "저자들은 새 데이터가 핵심 가정에 의문을 제기하자 모델을 수정했다." },
  '52_12': { example2: "Candidates are required to submit a resume and two letters of recommendation.", example2Kr: "지원자들은 이력서와 추천서 2부를 제출해야 한다." },
  '52_13': { example2: "The clinic offers supplemental therapy sessions alongside standard treatment.", example2Kr: "클리닉은 표준 치료와 함께 보충 치료 세션을 제공한다." },
  '52_14': { example2: "Power to the building was terminated after the company defaulted on utility payments.", example2Kr: "회사가 공과금을 연체하자 건물 전원이 차단되었다." },
  '52_15': { example2: "Efficient procurement practices helped the hospital manage its limited budget.", example2Kr: "효율적인 조달 관행이 병원이 한정된 예산을 관리하는 데 도움이 되었다." },
  '52_16': { example2: "The warranty on the laptop expired just days before the screen broke.", example2Kr: "노트북 보증이 화면이 고장 나기 불과 며칠 전에 만료되었다." },
  '52_17': { example2: "The company denied any liability for the injuries suffered by the contractor.", example2Kr: "회사는 하청업체가 입은 부상에 대한 법적 책임을 부인했다." },
  '52_18': { example2: "The franchise model allowed the brand to expand rapidly without heavy investment.", example2Kr: "프랜차이즈 모델은 브랜드가 대규모 투자 없이 빠르게 확장할 수 있게 했다." },
  '52_19': { example2: "The incumbent prime minister was widely expected to win the upcoming election.", example2Kr: "현직 총리는 다가오는 선거에서 당선될 것이 널리 예상되었다." },

  // ── Day 53 TOEFL 필수 어휘 I ──
  '53_0':  { example2: "The convention voted overwhelmingly to abolish mandatory retirement at age 65.", example2Kr: "대회는 65세 의무 퇴직을 폐지하기 위해 압도적으로 투표했다." },
  '53_1':  { example2: "Warm baths and herbal tea can help alleviate mild symptoms of insomnia.", example2Kr: "따뜻한 목욕과 허브차는 불면증의 가벼운 증상을 완화하는 데 도움이 될 수 있다." },
  '53_2':  { example2: "The politician alluded to budget cuts without specifying which programs would be affected.", example2Kr: "그 정치인은 어떤 프로그램이 영향을 받을지 명시하지 않고 예산 삭감을 암시했다." },
  '53_3':  { example2: "Despite no personal benefit, he made an altruistic decision to donate his bone marrow.", example2Kr: "개인적인 이익 없이도 그는 골수를 기증하는 이타적인 결정을 내렸다." },
  '53_4':  { example2: "The new policy was designed to ameliorate the housing shortage in the city center.", example2Kr: "새 정책은 도심 주택 부족 문제를 개선하기 위해 설계되었다." },
  '53_5':  { example2: "The doctor identified an anomaly in the scan that suggested a minor infection.", example2Kr: "의사는 가벼운 감염을 나타내는 스캔의 이상 현상을 발견했다." },
  '53_6':  { example2: "The students felt apprehensive about the outcome of their high-stakes standardized test.", example2Kr: "학생들은 중요한 표준화 시험 결과에 대해 불안함을 느꼈다." },
  '53_7':  { example2: "The articulate journalist explained the complex policy in plain language.", example2Kr: "그 표현력 있는 기자는 복잡한 정책을 평이한 언어로 설명했다." },
  '53_8':  { example2: "Her astute reading of the political landscape helped the party win the election.", example2Kr: "정치 지형에 대한 그녀의 예리한 분석이 당의 선거 승리를 도왔다." },
  '53_9':  { example2: "The military augmented its border presence in response to rising regional tensions.", example2Kr: "군은 지역 긴장 고조에 대응해 국경 경계를 강화했다." },
  '53_10': { example2: "She overcame her deep aversion to hospitals when her child fell seriously ill.", example2Kr: "그녀는 아이가 심각하게 아팠을 때 병원에 대한 깊은 혐오감을 극복했다." },
  '53_11': { example2: "The sheer scale of the archaeological site baffled even seasoned historians.", example2Kr: "고고학 유적지의 방대한 규모가 노련한 역사학자들도 어리둥절하게 했다." },
  '53_12': { example2: "The follow-up scan confirmed that the cyst was benign and posed no health risk.", example2Kr: "추적 스캔으로 낭종이 양성이며 건강에 위험이 없음을 확인했다." },
  '53_13': { example2: "Community support helped bolster the confidence of the grieving family.", example2Kr: "지역사회의 지지가 슬픔에 빠진 가족의 자신감을 높이는 데 도움이 되었다." },
  '53_14': { example2: "The professor valued brevity and penalized students for unnecessarily long answers.", example2Kr: "교수는 간결함을 중시하여 불필요하게 긴 답변에 대해 감점했다." },
  '53_15': { example2: "The documentary featured a candid interview with the former government official.", example2Kr: "다큐멘터리에는 전직 정부 관계자와의 솔직한 인터뷰가 담겼다." },
  '53_16': { example2: "The board formally censured the chairman for misusing company funds.", example2Kr: "이사회는 회사 자금을 남용한 회장을 공식적으로 비난했다." },
  '53_17': { example2: "He struggled with chronic back pain that prevented him from sitting for long periods.", example2Kr: "그는 오래 앉아 있는 것을 방해하는 만성 요통으로 고생했다." },
  '53_18': { example2: "The loophole allowed wealthy individuals to circumvent income tax obligations.", example2Kr: "허점을 통해 부유층이 소득세 의무를 우회할 수 있었다." },
  '53_19': { example2: "The workers alleged that managers had coerced them into falsifying safety reports.", example2Kr: "근로자들은 관리자들이 안전 보고서를 조작하도록 강요했다고 주장했다." },

  // ── Day 54 TOEFL 필수 어휘 II ──
  '54_0':  { example2: "The policy statement was so coherent that it won praise from all political parties.", example2Kr: "그 정책 성명은 너무 일관성이 있어 모든 정당의 찬사를 받았다." },
  '54_1':  { example2: "The colloquial phrase 'burning the midnight oil' means working very late into the night.", example2Kr: "'burning the midnight oil'이라는 구어 표현은 밤늦게까지 일한다는 뜻이다." },
  '54_2':  { example2: "Legal proceedings against the former executive will commence next Monday.", example2Kr: "전 임원에 대한 법적 절차가 다음 주 월요일부터 시작된다." },
  '54_3':  { example2: "A society that condones cheating will ultimately undermine its institutions.", example2Kr: "부정행위를 묵인하는 사회는 궁극적으로 그 자체의 제도를 훼손할 것이다." },
  '54_4':  { example2: "His theory about the asteroid impact was widely dismissed as mere conjecture.", example2Kr: "소행성 충돌에 대한 그의 이론은 단순한 추측으로 널리 무시되었다." },
  '54_5':  { example2: "The contentious bill on immigration reform was rejected after hours of heated debate.", example2Kr: "논란이 많은 이민 개혁 법안이 격렬한 토론 끝에 부결되었다." },
  '54_6':  { example2: "His claim that poverty is declining around the world contradicts recent UN data.", example2Kr: "전 세계 빈곤이 감소하고 있다는 그의 주장은 최근 유엔 데이터와 모순된다." },
  '54_7':  { example2: "Body language often conveys a person's true emotions more clearly than words.", example2Kr: "몸짓 언어는 종종 말보다 더 명확하게 사람의 진짜 감정을 전달한다." },
  '54_8':  { example2: "Security camera footage corroborated the eyewitness accounts of the theft.", example2Kr: "보안 카메라 영상이 절도에 대한 목격자 진술을 확증했다." },
  '54_9':  { example2: "Years of overfishing have depleted the salmon stocks in the river system.", example2Kr: "수년간의 남획으로 강 유역의 연어 개체 수가 고갈되었다." },
  '54_10': { example2: "The English word 'salary' is derived from the Latin word for salt.", example2Kr: "영어 단어 'salary'는 소금을 뜻하는 라틴어에서 유래했다." },
  '54_11': { example2: "It is difficult for younger children to discern the difference between fantasy and reality.", example2Kr: "어린 아이들은 환상과 현실의 차이를 구별하기 어렵다." },
  '54_12': { example2: "The CEO held a press conference to dispel rumors that the company was facing bankruptcy.", example2Kr: "CEO는 회사가 파산에 직면해 있다는 루머를 불식시키기 위해 기자 회견을 열었다." },
  '54_13': { example2: "The investigation diverged from its original scope when new evidence emerged.", example2Kr: "새로운 증거가 나타나면서 조사가 원래 범위에서 벗어났다." },
  '54_14': { example2: "The detective used leading questions to elicit a confession from the suspect.", example2Kr: "형사는 용의자로부터 자백을 이끌어내기 위해 유도 심문을 사용했다." },
  '54_15': { example2: "The restored temple was said to embody centuries of cultural and spiritual tradition.", example2Kr: "복원된 사원은 수백 년의 문화적·정신적 전통을 구현한다고 했다." },
  '54_16': { example2: "The researchers relied on empirical data collected over ten years of field observations.", example2Kr: "연구자들은 10년 동안의 현장 관찰로 수집된 실증 데이터에 의존했다." },
  '54_17': { example2: "The refugees had to endure a dangerous sea crossing before reaching safe shores.", example2Kr: "난민들은 안전한 해안에 도착하기 전에 위험한 바다 건너기를 견뎌야 했다." },
  '54_18': { example2: "The health official enumerated the side effects patients might experience.", example2Kr: "보건 공무원은 환자들이 겪을 수 있는 부작용들을 열거했다." },
  '54_19': { example2: "The seminar on epistemology challenged students to question the basis of their beliefs.", example2Kr: "인식론 세미나는 학생들이 자신의 믿음의 근거에 의문을 품도록 했다." },

  // ── Day 55 고급 형용사 I ──
  '55_0':  { example2: "The witness gave an ambiguous answer that satisfied neither the prosecution nor the defense.", example2Kr: "증인은 검찰도 변호인도 만족시키지 못하는 모호한 대답을 했다." },
  '55_1':  { example2: "He was one of the most prominent scientists of his generation in molecular biology.", example2Kr: "그는 자신의 세대에서 분자 생물학 분야의 가장 저명한 과학자 중 하나였다." },
  '55_2':  { example2: "Creativity is an inherent part of human nature that should be nurtured from childhood.", example2Kr: "창의성은 어린 시절부터 길러야 할 인간 본성의 본질적인 부분이다." },
  '55_3':  { example2: "Without significant structural reforms, economic decline seems inevitable.", example2Kr: "대대적인 구조 개혁 없이는 경제 쇠퇴가 불가피해 보인다." },
  '55_4':  { example2: "The earthquake caused substantial damage to buildings throughout the city.", example2Kr: "지진은 도시 전역의 건물에 상당한 피해를 입혔다." },
  '55_5':  { example2: "The school prides itself on having a diverse student body from over 40 countries.", example2Kr: "학교는 40개국 이상에서 온 다양한 학생 구성을 자랑스럽게 여긴다." },
  '55_6':  { example2: "The safety manual includes explicit instructions for evacuating the building.", example2Kr: "안전 매뉴얼에는 건물 대피에 관한 명시적인 지침이 포함되어 있다." },
  '55_7':  { example2: "There was always an implicit expectation that children would follow family traditions.", example2Kr: "아이들이 가족 전통을 따를 것이라는 암묵적인 기대가 항상 있었다." },
  '55_8':  { example2: "The selection process seemed arbitrary and failed to account for individual merit.", example2Kr: "선발 과정은 임의적으로 보였으며 개인의 능력을 고려하지 않았다." },
  '55_9':  { example2: "The documentary had a profound impact on how audiences viewed climate change.", example2Kr: "그 다큐멘터리는 관객들이 기후 변화를 바라보는 방식에 심대한 영향을 주었다." },
  '55_10': { example2: "Children from low-income households are particularly vulnerable to food insecurity.", example2Kr: "저소득층 가정의 아이들은 특히 식량 불안에 취약하다." },
  '55_11': { example2: "Mental health disorders are more prevalent among university students than commonly believed.", example2Kr: "정신 건강 장애는 일반적으로 생각하는 것보다 대학생들 사이에 더 만연해 있다." },
  '55_12': { example2: "The emergency shelters provided adequate protection against the freezing temperatures.", example2Kr: "비상 대피소는 영하의 기온에 충분한 보호를 제공했다." },
  '55_13': { example2: "The defendant's alibi was plausible but could not be independently verified.", example2Kr: "피고의 알리바이는 그럴듯했지만 독립적으로 검증될 수 없었다." },
  '55_14': { example2: "The committee published a comprehensive review of road safety laws across all provinces.", example2Kr: "위원회는 모든 주의 도로 안전법에 대한 포괄적인 검토 보고서를 발표했다." },
  '55_15': { example2: "The restoration team was meticulous in recreating the original colors of the ancient mural.", example2Kr: "복원팀은 고대 벽화의 원래 색상을 재현하는 데 꼼꼼했다." },
  '55_16': { example2: "The barrister delivered an eloquent defense that swayed the jury in her client's favor.", example2Kr: "그 변호사는 배심원단을 의뢰인에게 유리하게 설득한 웅변적인 변론을 펼쳤다." },
  '55_17': { example2: "The small startup faced a formidable challenge: competing against industry giants.", example2Kr: "그 소규모 스타트업은 만만치 않은 도전에 직면했다: 대형 업체들과 경쟁하는 것." },
  '55_18': { example2: "The diligent researcher spent years verifying each source before publishing her findings.", example2Kr: "그 근면한 연구자는 연구 결과를 발표하기 전에 각 자료를 확인하는 데 수년을 보냈다." },
  '55_19': { example2: "Her lucid explanation of quantum mechanics impressed even the senior physicists present.", example2Kr: "양자역학에 대한 그녀의 명쾌한 설명은 그 자리에 참석한 선임 물리학자들도 감동시켰다." },

  // ── Day 56 고급 형용사 II ──
  '56_0':  { example2: "The mayor remained ambivalent about approving the controversial new development plan.", example2Kr: "시장은 논란이 많은 새 개발 계획 승인에 대해 양가적인 태도를 유지했다." },
  '56_1':  { example2: "The team grew complacent after winning the championship and failed to train as hard.", example2Kr: "팀은 우승 후 안주하여 예전만큼 열심히 훈련하지 않았다." },
  '56_2':  { example2: "Scientists confirmed that the chemical was detrimental to marine ecosystems.", example2Kr: "과학자들은 그 화학물질이 해양 생태계에 유해하다는 것을 확인했다." },
  '56_3':  { example2: "The enigmatic philosopher rarely answered questions directly.", example2Kr: "그 불가사의한 철학자는 거의 질문에 직접적으로 답하지 않았다." },
  '56_4':  { example2: "The court ruled the lawsuit frivolous and ordered the plaintiff to pay legal costs.", example2Kr: "법원은 소송이 경솔하다고 판결하고 원고에게 소송 비용을 지불하도록 명령했다." },
  '56_5':  { example2: "With an imminent deadline, the team stayed overnight to complete the deliverable.", example2Kr: "마감이 임박하자 팀은 과제를 완료하기 위해 밤샘 작업을 했다." },
  '56_6':  { example2: "Reliable electricity supply is indispensable for modern industrial production.", example2Kr: "신뢰할 수 있는 전력 공급은 현대 산업 생산에 없어서는 안 된다." },
  '56_7':  { example2: "The insightful remarks of the keynote speaker sparked a lively debate.", example2Kr: "기조 연설자의 통찰력 있는 발언이 활발한 토론을 불러일으켰다." },
  '56_8':  { example2: "Many traditional crafts have become obsolete as factories replaced handmade goods.", example2Kr: "공장이 수제품을 대체하면서 많은 전통 공예가 구식이 되었다." },
  '56_9':  { example2: "Transparency and accountability are of paramount importance in public governance.", example2Kr: "투명성과 책임감은 공공 거버넌스에서 가장 중요하다." },
  '56_10': { example2: "There was something peculiar about the way he always avoided eye contact.", example2Kr: "그가 항상 눈을 맞추지 않는 방식에는 뭔가 특이한 점이 있었다." },
  '56_11': { example2: "A pervasive sense of inequality has fueled social unrest in many parts of the world.", example2Kr: "불평등에 대한 만연한 감각이 세계 많은 지역에서 사회 불안을 부채질했다." },
  '56_12': { example2: "Her pragmatic leadership style focused on achievable goals rather than idealistic visions.", example2Kr: "그녀의 실용적인 리더십 스타일은 이상적인 비전보다 달성 가능한 목표에 초점을 맞췄다." },
  '56_13': { example2: "Stringent visa requirements have made it harder for students to study abroad.", example2Kr: "엄격한 비자 요건이 학생들이 해외에서 공부하기 더 어렵게 만들었다." },
  '56_14': { example2: "The tenacious defense team refused to give up, even when the odds were against them.", example2Kr: "끈질긴 수비팀은 불리한 상황에서도 포기하지 않았다." },
  '56_15': { example2: "A versatile musician, she plays guitar, piano, and violin professionally.", example2Kr: "다재다능한 음악가인 그녀는 기타, 피아노, 바이올린을 전문적으로 연주한다." },
  '56_16': { example2: "The company's stock price has been volatile due to ongoing supply chain disruptions.", example2Kr: "회사 주가는 지속적인 공급망 혼란으로 인해 불안정했다." },
  '56_17': { example2: "Investors are wary of committing funds to emerging markets amid global instability.", example2Kr: "투자자들은 전 세계 불안정성 속에서 신흥 시장에 자금을 투입하는 것을 조심스러워한다." },
  '56_18': { example2: "Animal poaching remains rampant in several regions despite conservation efforts.", example2Kr: "보전 노력에도 불구하고 동물 밀렵이 여러 지역에서 여전히 만연하다." },
  '56_19': { example2: "The judge was known for taking a lenient approach with first-time offenders.", example2Kr: "판사는 초범에게 관대한 접근 방식을 취하는 것으로 알려져 있었다." },

  // ── Day 57 고급 명사 I ──
  '57_0':  { example2: "The legal document was drafted with deliberate ambiguity to allow for flexibility.", example2Kr: "그 법률 문서는 유연성을 허용하기 위해 의도적인 모호함으로 작성되었다." },
  '57_1':  { example2: "The regions were promised greater local autonomy as part of the peace agreement.", example2Kr: "지역들은 평화 협정의 일환으로 더 큰 지역 자율성을 약속받았다." },
  '57_2':  { example2: "Unconscious bias in hiring can prevent talented candidates from getting jobs.", example2Kr: "채용 과정의 무의식적 편견이 재능 있는 지원자들이 취업하는 것을 방해할 수 있다." },
  '57_3':  { example2: "Scientific consensus on climate change is supported by thousands of studies.", example2Kr: "기후 변화에 관한 과학적 합의는 수천 개의 연구에 의해 지지된다." },
  '57_4':  { example2: "The contradiction in the witness's story raised doubts about the entire account.", example2Kr: "증인의 이야기에서의 모순이 전체 진술에 대한 의심을 불러일으켰다." },
  '57_5':  { example2: "Her conviction that justice would prevail kept her going through years of legal battles.", example2Kr: "정의가 승리할 것이라는 그녀의 확신이 수년간의 법적 싸움을 버티게 해주었다." },
  '57_6':  { example2: "The discrepancy between the official data and fieldwork findings puzzled researchers.", example2Kr: "공식 데이터와 현장 연구 결과 사이의 불일치가 연구자들을 당혹스럽게 했다." },
  '57_7':  { example2: "Companies face a dilemma: cut jobs to reduce costs, or maintain staff and risk bankruptcy.", example2Kr: "기업들은 딜레마에 처해 있다: 비용 절감을 위해 일자리를 줄이거나 직원을 유지하며 파산 위험을 감수하거나." },
  '57_8':  { example2: "Voluntary work is a worthwhile endeavor that benefits both the giver and the community.", example2Kr: "자원봉사는 봉사자와 지역 사회 모두에게 이익을 주는 가치 있는 노력이다." },
  '57_9':  { example2: "The argument that 'natural' equals 'safe' is a popular but dangerous fallacy.", example2Kr: "'자연적인 것'이 '안전한 것'과 같다는 주장은 인기 있지만 위험한 오류이다." },
  '57_10': { example2: "Flatter organisational hierarchies tend to encourage more creativity and collaboration.", example2Kr: "더 평평한 조직 위계 구조는 더 많은 창의성과 협업을 장려하는 경향이 있다." },
  '57_11': { example2: "Her professional integrity was never questioned throughout her thirty-year career.", example2Kr: "그녀의 직업적 청렴함은 30년 경력 내내 의문시된 적이 없었다." },
  '57_12': { example2: "The notion of universal basic income is gaining traction among economists.", example2Kr: "보편적 기본소득의 개념이 경제학자들 사이에서 주목받고 있다." },
  '57_13': { example2: "Listening to diverse perspectives is essential for making well-informed decisions.", example2Kr: "다양한 관점을 듣는 것이 충분한 정보를 갖춘 결정을 내리는 데 필수적이다." },
  '57_14': { example2: "Access to higher education must not be seen as a privilege of the wealthy few.", example2Kr: "고등교육에 대한 접근이 소수 부유층의 특권으로 여겨져서는 안 된다." },
  '57_15': { example2: "His speech was praised for avoiding empty rhetoric and focusing on concrete solutions.", example2Kr: "그의 연설은 공허한 미사여구를 피하고 구체적인 해결책에 집중한다는 점에서 칭찬받았다." },
  '57_16': { example2: "Public skepticism about the safety of vaccines led to a drop in immunization rates.", example2Kr: "백신 안전성에 대한 대중의 회의론이 예방 접종률 감소로 이어졌다." },
  '57_17': { example2: "Trade unions organized a massive march to demonstrate solidarity with striking workers.", example2Kr: "노동조합은 파업 노동자들과의 연대를 보여주기 위해 대규모 행진을 조직했다." },
  '57_18': { example2: "The referendum was seen as undermining the country's long-held state sovereignty.", example2Kr: "국민투표는 국가의 오랜 주권을 훼손하는 것으로 여겨졌다." },
  '57_19': { example2: "Managing the transition from fossil fuels to renewables requires careful planning.", example2Kr: "화석연료에서 재생에너지로의 전환을 관리하려면 신중한 계획이 필요하다." },

  // ── Day 58 고급 명사 II ──
  '58_0':  { example2: "A lack of accountability within institutions often leads to corruption and mismanagement.", example2Kr: "기관 내 책임감 부재는 종종 부패와 비리로 이어진다." },
  '58_1':  { example2: "His political affiliation became an issue during the background check for the position.", example2Kr: "그의 정치적 소속이 직위에 대한 신원 조사 중 문제가 되었다." },
  '58_2':  { example2: "The circumstances surrounding the accident have not yet been fully explained.", example2Kr: "사고를 둘러싼 상황들이 아직 완전히 설명되지 않았다." },
  '58_3':  { example2: "The award-winning film was the result of close collaboration between the director and the cast.", example2Kr: "그 수상 영화는 감독과 배우 간의 긴밀한 협력의 결과였다." },
  '58_4':  { example2: "The complexity of urban planning requires expertise across multiple disciplines.", example2Kr: "도시 계획의 복잡성은 여러 분야의 전문 지식을 필요로 한다." },
  '58_5':  { example2: "Fake news can erode the media's credibility in the eyes of the public.", example2Kr: "가짜 뉴스는 대중의 눈에 미디어의 신뢰성을 훼손할 수 있다." },
  '58_6':  { example2: "The study explored the temporal dimension of leadership effectiveness.", example2Kr: "연구는 리더십 효과성의 시간적 차원을 탐구했다." },
  '58_7':  { example2: "Seasonal fluctuations in demand can make supply chain management very challenging.", example2Kr: "계절적 수요 변동이 공급망 관리를 매우 어렵게 만들 수 있다." },
  '58_8':  { example2: "The implications of artificial intelligence for employment are still being debated.", example2Kr: "고용에 대한 인공지능의 함의는 아직 논의 중이다." },
  '58_9':  { example2: "Our inference that the fire was deliberate was supported by the forensic report.", example2Kr: "화재가 의도적이었다는 우리의 추론은 포렌식 보고서로 뒷받침되었다." },
  '58_10': { example2: "Citizens questioned the legitimacy of a government that had never been elected.", example2Kr: "시민들은 한 번도 선출된 적 없는 정부의 합법성에 의문을 품었다." },
  '58_11': { example2: "Their marketing campaign gained momentum when a famous influencer shared it.", example2Kr: "유명 인플루언서가 공유하면서 그들의 마케팅 캠페인이 탄력을 얻었다." },
  '58_12': { example2: "Students have a social obligation to engage with issues affecting their communities.", example2Kr: "학생들은 자신의 지역 사회에 영향을 미치는 문제에 참여해야 할 사회적 의무가 있다." },
  '58_13': { example2: "The rapid spread of the virus was described as an unprecedented global phenomenon.", example2Kr: "바이러스의 빠른 확산은 전례 없는 세계적 현상으로 묘사되었다." },
  '58_14': { example2: "A solid grasp of algebra is a prerequisite for studying advanced mathematics.", example2Kr: "대수학에 대한 탄탄한 이해는 고급 수학을 공부하기 위한 전제조건이다." },
  '58_15': { example2: "The community showed incredible resilience, rebuilding within months of the flood.", example2Kr: "지역 사회는 홍수 후 몇 달 만에 재건하며 놀라운 회복력을 보여줬다." },
  '58_16': { example2: "Major corporations are increasingly judged on their commitment to sustainability.", example2Kr: "대기업들은 지속가능성에 대한 헌신으로 점점 더 평가받고 있다." },
  '58_17': { example2: "The unemployment rate crossed the critical threshold of 10% for the first time.", example2Kr: "실업률이 처음으로 10%의 핵심 임계점을 넘어섰다." },
  '58_18': { example2: "The athlete's trajectory from unknown rookie to world champion was extraordinary.", example2Kr: "그 운동선수의 무명 신인에서 세계 챔피언까지의 궤적은 놀라웠다." },
  '58_19': { example2: "The geopolitical vulnerability of small island nations is often overlooked.", example2Kr: "소규모 도서 국가의 지정학적 취약성은 종종 간과된다." },

  // ── Day 59 숙어 표현 I ──
  '59_0':  { example2: "The startup broke new ground by combining AI with traditional healthcare diagnostics.", example2Kr: "그 스타트업은 AI와 전통적인 의료 진단을 결합시키며 새로운 길을 개척했다." },
  '59_1':  { example2: "The engineering team burned the midnight oil to meet the product launch deadline.", example2Kr: "엔지니어링 팀은 제품 출시 마감일을 맞추기 위해 밤새워 일했다." },
  '59_2':  { example2: "We'll have to bite the bullet and cut 15% of our operational budget.", example2Kr: "우리는 참고 운영 예산의 15%를 삭감해야 할 것이다." },
  '59_3':  { example2: "Please stop beating around the bush and explain the actual problem.", example2Kr: "돌려서 말하지 말고 실제 문제를 설명해주세요." },
  '59_4':  { example2: "The chairperson got the ball rolling by introducing the main agenda item.", example2Kr: "의장은 주요 의제 항목을 소개하면서 일을 시작했다." },
  '59_5':  { example2: "The auditor hit the nail on the head when he pointed out the accounting irregularities.", example2Kr: "감사관이 회계 불규칙성을 지적하며 핵심을 정확히 찔렀다." },
  '59_6':  { example2: "The inspection revealed that the builders had cut corners on structural safety.", example2Kr: "검사에서 건설업자들이 구조 안전에 대해 편법을 쓴 것이 밝혀졌다." },
  '59_7':  { example2: "Having embezzled funds for years, the executive finally faced the music in court.", example2Kr: "수년간 자금을 횡령한 임원은 마침내 법정에서 결과에 책임져야 했다." },
  '59_8':  { example2: "I'll give the new system the benefit of the doubt for a few more weeks before judging.", example2Kr: "판단하기 전에 몇 주 더 새 시스템을 일단 믿어줄게요." },
  '59_9':  { example2: "She went out on a limb to defend her colleague against the unfair dismissal.", example2Kr: "그녀는 위험을 감수하며 동료의 부당 해고에 맞서 변호했다." },
  '59_10': { example2: "The company hit rock bottom during the financial crisis but recovered within two years.", example2Kr: "그 회사는 금융 위기 동안 최저점을 쳤지만 2년 내에 회복했다." },
  '59_11': { example2: "The disgraced CEO tried to keep a low profile while the investigation was ongoing.", example2Kr: "망신당한 CEO는 조사가 진행되는 동안 눈에 띄지 않게 지내려 했다." },
  '59_12': { example2: "Defense lawyers left no stone unturned to find evidence that might clear their client.", example2Kr: "변호인은 의뢰인의 무죄를 입증할 증거를 찾기 위해 모든 수단을 동원했다." },
  '59_13': { example2: "The aide accidentally let the cat out of the bag about the prime minister's resignation.", example2Kr: "보좌관이 실수로 총리의 사임에 대한 비밀을 발설했다." },
  '59_14': { example2: "Early investors missed the boat when they sold shares before the tech boom.", example2Kr: "초기 투자자들은 기술 붐 전에 주식을 팔며 기회를 놓쳤다." },
  '59_15': { example2: "A skilled diplomat must read between the lines of foreign policy statements.", example2Kr: "숙련된 외교관은 외교 정책 성명의 행간을 읽을 수 있어야 한다." },
  '59_16': { example2: "When reading product reviews online, it's wise to take them with a grain of salt.", example2Kr: "온라인 제품 리뷰를 읽을 때는 비판적으로 받아들이는 것이 현명하다." },
  '59_17': { example2: "Analysts were still on the fence about whether the economy would enter recession.", example2Kr: "분석가들은 경제가 침체에 들어갈지에 대해 아직 결론을 내리지 못하고 있었다." },
  '59_18': { example2: "He was accused of pulling strings to secure a government tender for his firm.", example2Kr: "그는 자신의 회사를 위해 정부 입찰을 따내기 위해 인맥을 이용했다는 비난을 받았다." },
  '59_19': { example2: "After years of reckless behavior, the young actor seemed to have turned over a new leaf.", example2Kr: "수년간의 무모한 행동 끝에 그 젊은 배우는 새 출발을 한 것 같았다." },

  // ── Day 60 구동사 I ──
  '60_0':  { example2: "Software bugs accounted for nearly half of all service outages last year.", example2Kr: "소프트웨어 버그가 작년 모든 서비스 중단의 거의 절반을 차지했다." },
  '60_1':  { example2: "The conference hoped to bring about closer ties between the two rival nations.", example2Kr: "회의는 두 경쟁국 간의 더 긴밀한 관계를 이끌어내기를 희망했다." },
  '60_2':  { example2: "The launch was called off after engineers discovered a critical fuel leak.", example2Kr: "엔지니어들이 심각한 연료 누출을 발견한 후 발사가 취소되었다." },
  '60_3':  { example2: "The research team carried out extensive tests before releasing the findings.", example2Kr: "연구팀은 결과를 발표하기 전에 광범위한 테스트를 수행했다." },
  '60_4':  { example2: "While sorting old files, she came across a letter she had written decades ago.", example2Kr: "오래된 파일을 정리하다가 그녀는 수십 년 전에 쓴 편지를 우연히 발견했다." },
  '60_5':  { example2: "Schools must deal with online bullying as seriously as physical bullying.", example2Kr: "학교는 사이버 폭력을 신체 폭력만큼 진지하게 다뤄야 한다." },
  '60_6':  { example2: "The speech writer drew on historical speeches to craft a powerful address.", example2Kr: "연설문 작성자는 강력한 연설을 만들기 위해 역사적 연설을 활용했다." },
  '60_7':  { example2: "Without external support, the fragile coalition government could easily fall apart.", example2Kr: "외부 지원 없이는 취약한 연립 정부가 쉽게 무너질 수 있다." },
  '60_8':  { example2: "Psychologists are still trying to figure out what drives human altruism.", example2Kr: "심리학자들은 여전히 인간의 이타주의를 이끄는 것이 무엇인지 알아내려 하고 있다." },
  '60_9':  { example2: "The government refused to give in to hackers' ransom demands.", example2Kr: "정부는 해커들의 몸값 요구에 굴복하기를 거부했다." },
  '60_10': { example2: "Budget cuts are holding back critical improvements to the healthcare system.", example2Kr: "예산 삭감이 의료 시스템의 중요한 개선을 가로막고 있다." },
  '60_11': { example2: "Parliament is looking into allegations of financial misconduct within the ministry.", example2Kr: "의회는 부처 내 재정 비위 혐의를 조사하고 있다." },
  '60_12': { example2: "Overtime pay was offered to make up for the weekend shifts imposed at short notice.", example2Kr: "급하게 부과된 주말 교대 근무에 대한 보상으로 초과 근무 수당이 제공되었다." },
  '60_13': { example2: "The selection committee narrowed down the applications to fifteen finalists.", example2Kr: "선발 위원회는 지원서를 15명의 최종 후보로 압축했다." },
  '60_14': { example2: "An increasing number of homebuyers are opting for solar-powered properties.", example2Kr: "점점 더 많은 주택 구매자들이 태양광 발전 주택을 선택하고 있다." },
  '60_15': { example2: "The whistleblower pointed out systematic fraud in the company's accounting records.", example2Kr: "내부 고발자는 회사의 회계 기록에서 체계적인 사기를 지적했다." },
  '60_16': { example2: "Police initially listed the death as accidental but later ruled out natural causes.", example2Kr: "경찰은 처음에 사망을 사고로 분류했지만 나중에 자연사를 배제했다." },
  '60_17': { example2: "The action plan sets out a series of milestones over the next five years.", example2Kr: "행동 계획은 향후 5년간의 일련의 이정표를 제시한다." },
  '60_18': { example2: "The young chef stood out at the competition with his creative use of local ingredients.", example2Kr: "그 젊은 요리사는 지역 재료를 창의적으로 활용해 대회에서 두드러졌다." },
  '60_19': { example2: "The new CEO took on the challenges of restructuring the company with confidence.", example2Kr: "새 CEO는 자신감 있게 회사 구조조정의 어려움을 맡았다." },

  // ── Day 61 구동사 II ──
  '61_0':  { example2: "Always back up important files to cloud storage to prevent data loss.", example2Kr: "데이터 손실을 방지하기 위해 중요한 파일을 항상 클라우드 스토리지에 백업하세요." },
  '61_1':  { example2: "The old bridge broke down under the weight of heavy trucks.", example2Kr: "오래된 다리가 무거운 트럭의 무게를 버티지 못하고 무너졌다." },
  '61_2':  { example2: "Check out the latest research findings published in the journal.", example2Kr: "학술지에 발표된 최신 연구 결과를 확인해보세요." },
  '61_3':  { example2: "The marketing team came up with a brilliant campaign idea overnight.", example2Kr: "마케팅팀이 하룻밤 사이에 훌륭한 캠페인 아이디어를 생각해냈다." },
  '61_4':  { example2: "Businesses are cutting down on energy use to reduce carbon emissions.", example2Kr: "기업들은 탄소 배출량을 줄이기 위해 에너지 사용을 줄이고 있다." },
  '61_5':  { example2: "Attendance dropped off sharply after the first few lectures.", example2Kr: "첫 몇 개의 강의 이후 출석률이 급격히 감소했다." },
  '61_6':  { example2: "The manager asked everyone to follow up on the action items from yesterday's meeting.", example2Kr: "매니저는 어제 회의의 실행 항목들에 대해 후속 조치를 해달라고 부탁했다." },
  '61_7':  { example2: "It was difficult to get the abstract concept across to the general public.", example2Kr: "추상적인 개념을 일반 대중에게 이해시키기 어려웠다." },
  '61_8':  { example2: "The prime minister handed over power to the newly elected successor.", example2Kr: "총리는 새로 선출된 후계자에게 권력을 넘겨주었다." },
  '61_9':  { example2: "The professor brought up an interesting theory that challenged existing assumptions.", example2Kr: "교수는 기존 가정에 도전하는 흥미로운 이론을 언급했다." },
  '61_10': { example2: "The factory laid off half its workforce due to the economic downturn.", example2Kr: "공장은 경제 침체로 인해 노동력의 절반을 해고했다." },
  '61_11': { example2: "The product's quality failed to live up to the reputation of the brand.", example2Kr: "제품의 품질이 브랜드 명성에 걸맞지 않았다." },
  '61_12': { example2: "She could barely make out the signature at the bottom of the page.", example2Kr: "그녀는 페이지 하단의 서명을 겨우 알아볼 수 있었다." },
  '61_13': { example2: "Cultural values are passed on through language, art, and tradition.", example2Kr: "문화적 가치관은 언어, 예술, 전통을 통해 전해진다." },
  '61_14': { example2: "The ceremony was put off due to unexpected technical difficulties.", example2Kr: "예상치 못한 기술적 어려움으로 행사가 연기되었다." },
  '61_15': { example2: "We ran out of time before we could address all the agenda items.", example2Kr: "모든 안건을 다루기 전에 시간이 다 됐다." },
  '61_16': { example2: "The HR department sorted out the payroll errors within a day.", example2Kr: "인사부서는 하루 만에 급여 오류를 해결했다." },
  '61_17': { example2: "The applicant turned down the offer, hoping for a better opportunity.", example2Kr: "지원자는 더 나은 기회를 기대하며 제안을 거절했다." },
  '61_18': { example2: "Continuous overtime wore out the employees and reduced their productivity.", example2Kr: "지속적인 야근이 직원들을 지치게 하고 생산성을 떨어뜨렸다." },
  '61_19': { example2: "The project worked out better than anyone had initially expected.", example2Kr: "프로젝트는 처음에 누구도 예상했던 것보다 더 잘 해결되었다." },

  // ── Day 62 구동사 III ──
  '62_0':  { example2: "Researchers finally broke through a major barrier in quantum computing.", example2Kr: "연구자들은 마침내 양자 컴퓨팅의 주요 장벽을 돌파했다." },
  '62_1':  { example2: "Regular practice helps build up the skills needed for academic success.", example2Kr: "규칙적인 연습이 학업 성공에 필요한 기술을 쌓는 데 도움이 된다." },
  '62_2':  { example2: "Developing nations are working hard to catch up with industrialized economies.", example2Kr: "개발도상국들은 산업화된 경제를 따라잡기 위해 열심히 노력하고 있다." },
  '62_3':  { example2: "The report cleared up lingering doubts about the safety of the product.", example2Kr: "보고서는 제품 안전성에 대한 남아있는 의심을 해소했다." },
  '62_4':  { example2: "The project came up against numerous bureaucratic obstacles.", example2Kr: "프로젝트는 수많은 관료적 장애물에 직면했다." },
  '62_5':  { example2: "Raising visa fees might drive away talented students from overseas.", example2Kr: "비자 수수료 인상이 해외의 우수한 학생들을 쫓아낼 수 있다." },
  '62_6':  { example2: "Applicants must fill in the form completely or their application will be rejected.", example2Kr: "지원자는 양식을 완전히 기입해야 하며 그렇지 않으면 지원이 거부된다." },
  '62_7':  { example2: "It took considerable time for the economy to get over the financial crisis.", example2Kr: "경제가 금융 위기를 극복하는 데 상당한 시간이 걸렸다." },
  '62_8':  { example2: "She decided not to give up on learning the language despite the difficulties.", example2Kr: "그녀는 어려움에도 불구하고 언어 학습을 포기하지 않기로 결심했다." },
  '62_9':  { example2: "The minority members refused to go along with the majority's decision.", example2Kr: "소수 구성원들은 다수의 결정을 따르기를 거부했다." },
  '62_10': { example2: "Hold on to your principles even when you are under pressure to compromise.", example2Kr: "타협하라는 압박을 받을 때도 자신의 원칙을 고수하세요." },
  '62_11': { example2: "Small companies find it difficult to keep up with industry regulations.", example2Kr: "중소기업들은 업계 규정을 따라가기가 어렵다." },
  '62_12': { example2: "We look forward to receiving your formal response by the end of the week.", example2Kr: "이번 주 말까지 공식 답변을 받기를 기대합니다." },
  '62_13': { example2: "Children pick up new languages much more easily than adults.", example2Kr: "아이들은 어른들보다 훨씬 쉽게 새로운 언어를 배운다." },
  '62_14': { example2: "Several experts put forward alternative approaches to tackle climate change.", example2Kr: "여러 전문가들이 기후 변화를 해결하기 위한 대안적 접근법을 제안했다." },
  '62_15': { example2: "The tech company plans to scale up its operations in Southeast Asia.", example2Kr: "기술 회사는 동남아시아에서의 운영을 확장할 계획이다." },
  '62_16': { example2: "The government stepped up monitoring of financial institutions after the scandal.", example2Kr: "정부는 스캔들 이후 금융 기관 감시를 강화했다." },
  '62_17': { example2: "Increasing numbers of consumers are turning to sustainable alternatives.", example2Kr: "점점 더 많은 소비자들이 지속 가능한 대안으로 눈을 돌리고 있다." },
  '62_18': { example2: "A single storm wiped out months of careful conservation work.", example2Kr: "단 한 번의 폭풍이 수개월에 걸친 세심한 보전 작업을 없애버렸다." },
  '62_19': { example2: "The audit team zeroed in on discrepancies in the quarterly financial report.", example2Kr: "감사팀은 분기별 재무 보고서의 불일치에 집중했다." },

  // ── Day 63 비즈니스 어휘 I ──
  '63_0':  { example2: "The hostile acquisition attempt was blocked by the board of directors.", example2Kr: "적대적 인수 시도는 이사회에 의해 차단되었다." },
  '63_1':  { example2: "Customer satisfaction scores serve as a key benchmark for service quality.", example2Kr: "고객 만족도 점수는 서비스 품질의 핵심 기준으로 작용한다." },
  '63_2':  { example2: "Strong brand equity allows companies to charge premium prices.", example2Kr: "강력한 브랜드 자산은 회사들이 프리미엄 가격을 책정할 수 있게 해준다." },
  '63_3':  { example2: "Startups often struggle with cash flow in their first few years of operation.", example2Kr: "스타트업들은 종종 운영 첫 몇 년간 현금 흐름에 어려움을 겪는다." },
  '63_4':  { example2: "A unique product design can provide a lasting competitive advantage.", example2Kr: "독특한 제품 디자인은 지속적인 경쟁 우위를 제공할 수 있다." },
  '63_5':  { example2: "The country suffered a period of deflation after the collapse of the property market.", example2Kr: "그 나라는 부동산 시장 붕괴 이후 디플레이션 시기를 겪었다." },
  '63_6':  { example2: "Companies must diversify their income streams to remain resilient.", example2Kr: "회사들은 탄력성을 유지하기 위해 수입원을 다각화해야 한다." },
  '63_7':  { example2: "Investors conduct due diligence to assess potential risks and liabilities.", example2Kr: "투자자들은 잠재적 위험과 부채를 평가하기 위해 실사를 수행한다." },
  '63_8':  { example2: "Successful entrepreneurs are known for their resilience and adaptability.", example2Kr: "성공한 기업가들은 탄력성과 적응력으로 유명하다." },
  '63_9':  { example2: "The strong gross profit enabled the company to reinvest in R&D.", example2Kr: "높은 매출 총이익이 회사가 연구개발에 재투자할 수 있게 해주었다." },
  '63_10': { example2: "Performance incentives help motivate employees to exceed their targets.", example2Kr: "성과 인센티브는 직원들이 목표를 초과 달성하도록 동기를 부여한다." },
  '63_11': { example2: "The startup leveraged social media to grow its customer base rapidly.", example2Kr: "스타트업은 소셜 미디어를 활용해 고객 기반을 빠르게 성장시켰다." },
  '63_12': { example2: "The company's market share declined following the product recall.", example2Kr: "제품 리콜 이후 회사의 시장 점유율이 감소했다." },
  '63_13': { example2: "Cutting costs increased the net profit without raising product prices.", example2Kr: "비용 절감이 제품 가격 인상 없이 순이익을 증가시켰다." },
  '63_14': { example2: "The company decided to outsource IT support to a specialist firm.", example2Kr: "회사는 IT 지원을 전문 업체에 외주화하기로 결정했다." },
  '63_15': { example2: "Renting a co-working space helped reduce monthly overhead considerably.", example2Kr: "공유 오피스를 임대하는 것이 월간 간접비를 상당히 줄이는 데 도움이 되었다." },
  '63_16': { example2: "His sales pitch convinced the investors to fund the new concept.", example2Kr: "그의 판매 제안이 투자자들이 새로운 개념에 자금을 지원하도록 설득했다." },
  '63_17': { example2: "Thin profit margins mean that even small cost increases threaten viability.", example2Kr: "낮은 이익률은 작은 비용 증가만으로도 생존 가능성이 위협받는다는 것을 의미한다." },
  '63_18': { example2: "The CEO reassured all stakeholders that the company's fundamentals remain strong.", example2Kr: "CEO는 모든 이해관계자에게 회사의 기본 여건이 여전히 건전하다고 확신시켰다." },
  '63_19': { example2: "High employee turnover often signals problems with company culture.", example2Kr: "높은 직원 이직률은 종종 기업 문화의 문제를 나타낸다." },

  // ── Day 64 비즈니스 어휘 II ──
  '64_0':  { example2: "The political agenda behind the policy reform was widely debated.", example2Kr: "정책 개혁 뒤에 있는 정치적 의도가 광범위하게 논의되었다." },
  '64_1':  { example2: "The fund exclusively invests in blue-chip companies with solid track records.", example2Kr: "그 펀드는 탄탄한 실적을 가진 우량 기업에만 투자한다." },
  '64_2':  { example2: "The bottom line is that we cannot continue operating at a loss.", example2Kr: "핵심은 우리가 적자 운영을 계속할 수 없다는 것이다." },
  '64_3':  { example2: "The hospital has limited capacity and cannot take any more patients.", example2Kr: "병원은 수용 능력이 제한되어 더 이상 환자를 받을 수 없다." },
  '64_4':  { example2: "An international consortium was formed to develop the new space telescope.", example2Kr: "새로운 우주 망원경을 개발하기 위해 국제 컨소시엄이 결성되었다." },
  '64_5':  { example2: "The airline was forced to downsize its fleet during the travel industry crisis.", example2Kr: "항공사는 여행 산업 위기 동안 함대 규모를 줄여야 했다." },
  '64_6':  { example2: "Early investors received equity in exchange for their financial support.", example2Kr: "초기 투자자들은 재정적 지원의 대가로 지분을 받았다." },
  '64_7':  { example2: "The central bank's latest forecast points to slower growth in the coming months.", example2Kr: "중앙은행의 최신 예측은 앞으로 몇 달 동안 성장 둔화를 가리킨다." },
  '64_8':  { example2: "The firm headhunted a renowned expert from a leading research institute.", example2Kr: "그 회사는 유명 연구 기관에서 저명한 전문가를 스카우트했다." },
  '64_9':  { example2: "Improving digital infrastructure is vital for economic development.", example2Kr: "디지털 인프라 개선은 경제 발전에 필수적이다." },
  '64_10': { example2: "The joint venture gave both companies access to new technology and markets.", example2Kr: "합작 투자는 두 회사 모두에게 새로운 기술과 시장에 대한 접근권을 주었다." },
  '64_11': { example2: "The firm's strong liquidity position helped it weather the financial storm.", example2Kr: "회사의 탄탄한 유동성 상태가 금융 위기를 견뎌내는 데 도움이 됐다." },
  '64_12': { example2: "The business identified a niche in the market for premium pet care products.", example2Kr: "사업체는 고급 반려동물 케어 제품에 대한 틈새시장을 찾아냈다." },
  '64_13': { example2: "Her online portfolio showcased her diverse range of creative projects.", example2Kr: "그녀의 온라인 포트폴리오는 다양한 창의적 프로젝트들을 보여주었다." },
  '64_14': { example2: "The company restructured its debt to avoid filing for bankruptcy.", example2Kr: "회사는 파산 신청을 피하기 위해 부채를 구조조정했다." },
  '64_15': { example2: "Cloud-based solutions are more scalable than traditional on-premises systems.", example2Kr: "클라우드 기반 솔루션은 기존 온프레미스 시스템보다 더 확장 가능하다." },
  '64_16': { example2: "The pandemic exposed vulnerabilities in just-in-time supply chains.", example2Kr: "팬데믹은 적시 공급망의 취약점을 드러냈다." },
  '64_17': { example2: "The merger failed to deliver the promised synergy between the two firms.", example2Kr: "합병은 두 회사 간에 약속된 시너지를 제공하지 못했다." },
  '64_18': { example2: "Advertisers invest heavily to reach their precise target market effectively.", example2Kr: "광고주들은 자신의 목표 시장에 효과적으로 도달하기 위해 많은 투자를 한다." },
  '64_19': { example2: "The startup raised venture capital by pitching to Silicon Valley investors.", example2Kr: "스타트업은 실리콘밸리 투자자들에게 발표해 벤처 자본을 조달했다." },

  // ── Day 65 법률 어휘 ──
  '65_0':  { example2: "The court acquitted all three suspects due to insufficient evidence.", example2Kr: "법원은 증거 불충분으로 세 명의 용의자 모두에게 무죄를 선고했다." },
  '65_1':  { example2: "The journalist provided an affidavit confirming the source of the leaked documents.", example2Kr: "기자는 유출된 문서의 출처를 확인하는 선서 진술서를 제출했다." },
  '65_2':  { example2: "The appeal court upheld the original ruling, dismissing the challenge.", example2Kr: "항소 법원은 원래 판결을 지지하며 이의 신청을 기각했다." },
  '65_3':  { example2: "International trade disputes are often settled through binding arbitration.", example2Kr: "국제 무역 분쟁은 종종 구속력 있는 중재를 통해 해결된다." },
  '65_4':  { example2: "A breach of privacy law can result in significant financial penalties.", example2Kr: "개인정보보호법 위반은 상당한 금전적 처벌을 초래할 수 있다." },
  '65_5':  { example2: "The confidentiality clause prevented either party from disclosing the settlement terms.", example2Kr: "기밀 유지 조항이 어느 당사자도 합의 조건을 공개하지 못하게 했다." },
  '65_6':  { example2: "The defendant's lawyer presented a compelling alibi to the court.", example2Kr: "피고인의 변호사는 법원에 설득력 있는 알리바이를 제시했다." },
  '65_7':  { example2: "Several corporate executives were indicted for insider trading.", example2Kr: "여러 기업 임원들이 내부자 거래로 기소되었다." },
  '65_8':  { example2: "The environmental group won an injunction preventing the logging operation.", example2Kr: "환경 단체는 벌목 작업을 막는 금지 명령을 얻어냈다." },
  '65_9':  { example2: "The crime was committed outside of the court's jurisdiction.", example2Kr: "그 범죄는 법원의 관할권 밖에서 저질러졌다." },
  '65_10': { example2: "The consumer protection lawsuit resulted in a $50 million settlement.", example2Kr: "소비자 보호 소송은 5천만 달러 합의로 이어졌다." },
  '65_11': { example2: "Protracted litigation drained the company's financial reserves significantly.", example2Kr: "장기적 소송이 회사의 재무 준비금을 상당히 소모시켰다." },
  '65_12': { example2: "The new regulation mandates annual safety inspections for all commercial vehicles.", example2Kr: "새 규정은 모든 상업용 차량에 대한 연간 안전 검사를 의무화한다." },
  '65_13': { example2: "The construction firm was found guilty of negligence following the building collapse.", example2Kr: "건설 회사는 건물 붕괴 사고 이후 과실 혐의로 유죄 판결을 받았다." },
  '65_14': { example2: "As the plaintiff, she had the burden of proving that harm had occurred.", example2Kr: "원고로서 그녀는 피해가 발생했음을 증명할 책임이 있었다." },
  '65_15': { example2: "The suspect entered a not-guilty plea despite the overwhelming evidence.", example2Kr: "용의자는 압도적인 증거에도 불구하고 무죄를 주장했다." },
  '65_16': { example2: "This ruling will set a precedent for how similar cases are handled in the future.", example2Kr: "이 판결은 미래에 유사한 사건들을 처리하는 방식에 대한 선례를 세울 것이다." },
  '65_17': { example2: "A new statute was introduced to regulate the use of artificial intelligence.", example2Kr: "인공지능 사용을 규제하기 위한 새로운 법규가 도입되었다." },
  '65_18': { example2: "Her expert testimony helped the jury understand the complex technical evidence.", example2Kr: "그녀의 전문가 증언이 배심원단이 복잡한 기술적 증거를 이해하는 데 도움이 됐다." },
  '65_19': { example2: "The verdict shocked the nation and sparked widespread protests across the country.", example2Kr: "그 평결은 국가를 충격에 빠뜨리고 전국에 걸쳐 광범위한 시위를 촉발시켰다." },

  // ── Day 66 의학·건강 어휘 ──
  '66_0':  { example2: "The patient was transferred to intensive care following an acute cardiac event.", example2Kr: "환자는 급성 심장 사건 이후 집중 치료실로 이송되었다." },
  '66_1':  { example2: "Managing chronic conditions requires consistent medication and lifestyle adjustments.", example2Kr: "만성 질환을 관리하려면 지속적인 약물 복용과 생활 방식 조정이 필요하다." },
  '66_2':  { example2: "Early screening programmes help doctors diagnose cancer at a treatable stage.", example2Kr: "조기 검진 프로그램은 의사들이 치료 가능한 단계에서 암을 진단하도록 돕는다." },
  '66_3':  { example2: "The measles epidemic spread quickly due to low vaccination rates in the region.", example2Kr: "낮은 예방 접종률로 인해 그 지역에서 홍역이 빠르게 퍼졌다." },
  '66_4':  { example2: "Mental fatigue from overwork is just as debilitating as physical exhaustion.", example2Kr: "과로로 인한 정신적 피로는 신체적 탈진만큼이나 쇠약하게 만든다." },
  '66_5':  { example2: "Newborns rely entirely on maternal antibodies while their own immune systems mature.", example2Kr: "신생아는 자신의 면역 체계가 성숙할 동안 전적으로 모체 항체에 의존한다." },
  '66_6':  { example2: "Anti-inflammatory drugs are often prescribed to reduce swelling and relieve pain.", example2Kr: "소염제는 붓기를 줄이고 통증을 완화하기 위해 자주 처방된다." },
  '66_7':  { example2: "The patient was referred to an oncologist after a malignant growth was detected.", example2Kr: "악성 종양이 발견된 후 환자는 종양 전문의에게 의뢰되었다." },
  '66_8':  { example2: "A sluggish metabolism can contribute to weight gain even with a healthy diet.", example2Kr: "건강한 식단에도 불구하고 느린 신진대사가 체중 증가에 기여할 수 있다." },
  '66_9':  { example2: "The global pandemic highlighted the need for stronger international health cooperation.", example2Kr: "세계적인 팬데믹은 더 강력한 국제 보건 협력의 필요성을 부각시켰다." },
  '66_10': { example2: "Health authorities traced the outbreak back to a single airborne pathogen.", example2Kr: "보건 당국은 발병의 원인을 단일 공기 전파 병원체로 추적했다." },
  '66_11': { example2: "The placebo effect demonstrates the powerful connection between mind and body.", example2Kr: "플라시보 효과는 마음과 몸 사이의 강력한 연결을 보여준다." },
  '66_12': { example2: "The pharmacist checked the prescription carefully before dispensing the medication.", example2Kr: "약사는 약을 조제하기 전에 처방전을 주의 깊게 확인했다." },
  '66_13': { example2: "The doctor gave a cautious prognosis, urging the family not to raise false hopes.", example2Kr: "의사는 가족에게 헛된 희망을 갖지 말라고 당부하며 신중한 예후를 전달했다." },
  '66_14': { example2: "Speech and language rehabilitation helped him regain communication skills after the stroke.", example2Kr: "언어 재활이 뇌졸중 이후 그가 의사소통 능력을 회복하도록 도왔다." },
  '66_15': { example2: "The patient experienced a relapse just three months after completing the treatment course.", example2Kr: "환자는 치료 과정을 마친 지 불과 3개월 만에 재발을 경험했다." },
  '66_16': { example2: "The dentist used a mild sedative to help the anxious child relax before the procedure.", example2Kr: "치과 의사는 불안해하는 아이가 시술 전에 진정하도록 가벼운 진정제를 사용했다." },
  '66_17': { example2: "Recognising the early symptoms of a stroke can dramatically improve survival rates.", example2Kr: "뇌졸중의 초기 증상을 인식하면 생존율을 극적으로 향상시킬 수 있다." },
  '66_18': { example2: "Occupational therapy helps patients regain independence in daily activities.", example2Kr: "작업 치료는 환자들이 일상 활동에서 독립성을 회복하도록 돕는다." },
  '66_19': { example2: "Routine childhood vaccination has dramatically reduced the incidence of polio worldwide.", example2Kr: "일상적인 소아 예방 접종이 전 세계 소아마비 발생률을 극적으로 줄였다." },

  // ── Day 67 환경·생태 어휘 ──
  '67_0':  { example2: "Scientists are still cataloguing species as biodiversity loss accelerates globally.", example2Kr: "과학자들은 생물 다양성 손실이 전 세계적으로 가속화되는 가운데 여전히 종을 목록화하고 있다." },
  '67_1':  { example2: "Switching to renewable energy is one of the most effective ways to cut your carbon footprint.", example2Kr: "재생 에너지로 전환하는 것은 탄소 발자국을 줄이는 가장 효과적인 방법 중 하나다." },
  '67_2':  { example2: "Rampant deforestation has left vast areas of Southeast Asia vulnerable to flooding.", example2Kr: "무분별한 삼림 벌채로 동남아시아의 넓은 지역이 홍수에 취약해졌다." },
  '67_3':  { example2: "The introduction of invasive species can completely destabilise a local ecosystem.", example2Kr: "침입 외래종의 유입은 지역 생태계를 완전히 불안정하게 만들 수 있다." },
  '67_4':  { example2: "Carbon emissions from aviation remain one of the hardest sectors to decarbonise.", example2Kr: "항공 분야의 탄소 배출은 탈탄소화하기 가장 어려운 분야 중 하나로 남아 있다." },
  '67_5':  { example2: "Aggressive land clearing has accelerated severe soil erosion across the highlands.", example2Kr: "무분별한 토지 개간이 고지대 전역에서 심각한 토양 침식을 가속화했다." },
  '67_6':  { example2: "The extinction of pollinators such as bees would threaten global food security.", example2Kr: "벌과 같은 수분 매개체의 멸종은 전 세계 식량 안보를 위협할 것이다." },
  '67_7':  { example2: "The world must rapidly phase out fossil fuels to meet its climate targets.", example2Kr: "세계는 기후 목표를 달성하기 위해 화석 연료를 빠르게 단계적으로 폐지해야 한다." },
  '67_8':  { example2: "The enhanced greenhouse effect is causing polar ice caps to melt at an alarming rate.", example2Kr: "강화된 온실 효과가 극지방 빙하를 놀라운 속도로 녹이고 있다." },
  '67_9':  { example2: "Conservation programmes aim to protect remaining wildlife habitat from further encroachment.", example2Kr: "보존 프로그램들은 남아있는 야생 동물 서식지를 추가적인 침범으로부터 보호하겠다다." },
  '67_10': { example2: "Reducing landfill use requires both better recycling and less packaging in the first place.", example2Kr: "매립지 사용을 줄이려면 더 나은 재활용과 근본적으로 더 적은 포장이 필요하다." },
  '67_11': { example2: "The Montreal Protocol succeeded in halting the erosion of the ozone layer.", example2Kr: "몬트리올 의정서는 오존층 침식을 막는 데 성공했다." },
  '67_12': { example2: "Air quality monitors detected dangerously high levels of particulate pollutants in the city.", example2Kr: "대기 질 모니터들이 도시에서 위험할 정도로 높은 수준의 미립자 오염 물질을 감지했다." },
  '67_13': { example2: "Affordable renewable energy is now a reality in many parts of the developing world.", example2Kr: "저렴한 재생 에너지는 이제 개발도상국의 많은 지역에서 현실이 됐다." },
  '67_14': { example2: "Community-led reforestation projects are helping to restore degraded upland areas.", example2Kr: "지역 사회 주도 재조림 프로젝트들이 황폐화된 고지대를 복원하는 데 도움을 주고 있다." },
  '67_15': { example2: "Corporate sustainability reports are now scrutinised by investors and regulators alike.", example2Kr: "기업 지속 가능성 보고서들은 이제 투자자와 규제 기관 모두에게 면밀히 검토된다." },
  '67_16': { example2: "Communities near the plant suffered health effects from toxic waste dumped illegally.", example2Kr: "공장 주변 지역 사회는 불법으로 투기된 독성 폐기물로 인한 건강 피해를 입었다." },
  '67_17': { example2: "The flooding of the lowlands was a watershed event that changed flood management policy.", example2Kr: "저지대 침수는 홍수 관리 정책을 바꾼 분수령이 되는 사건이었다." },
  '67_18': { example2: "Wetland drainage for agriculture has eliminated habitats for countless water birds.", example2Kr: "농업을 위한 습지 배수가 수많은 물새의 서식지를 없애버렸다." },
  '67_19': { example2: "Several major cities have introduced zero-emission bus fleets on their busiest routes.", example2Kr: "여러 주요 도시들이 가장 바쁜 노선에 무배출 버스 대열을 도입했다." },

  // ── Day 68 사회·정치 어휘 ──
  '68_0':  { example2: "Citizens demand greater accountability from elected officials over public spending.", example2Kr: "시민들은 공공 지출에 대해 선출된 공직자들로부터 더 큰 책임을 요구한다." },
  '68_1':  { example2: "The constitutional amendment was ratified after a decade of parliamentary debate.", example2Kr: "헌법 수정 조항은 10년간의 의회 토론 끝에 비준되었다." },
  '68_2':  { example2: "Human rights organisations condemned the authoritarian government's crackdown on protests.", example2Kr: "인권 단체들은 시위에 대한 권위주의 정부의 탄압을 비난했다." },
  '68_3':  { example2: "Investors cited excessive bureaucracy as a deterrent to doing business in the country.", example2Kr: "투자자들은 과도한 관료주의를 그 나라에서 사업하는 것을 방해하는 요인으로 꼽았다." },
  '68_4':  { example2: "Online censorship has made it increasingly difficult to access independent news sources.", example2Kr: "온라인 검열이 독립적인 뉴스 출처에 접근하는 것을 점점 더 어렵게 만들었다." },
  '68_5':  { example2: "NGOs form an important part of a healthy and engaged civil society.", example2Kr: "비정부기구들은 건강하고 참여적인 시민 사회의 중요한 부분을 구성한다." },
  '68_6':  { example2: "The candidate toured her constituency to listen to residents' concerns firsthand.", example2Kr: "후보자는 주민들의 우려를 직접 듣기 위해 선거구를 순회했다." },
  '68_7':  { example2: "Anti-corruption legislation has helped reduce bribery in the public sector.", example2Kr: "반부패 법안이 공공 부문의 뇌물 공여를 줄이는 데 도움이 되었다." },
  '68_8':  { example2: "Demographic shifts in the electorate are reshaping the political landscape.", example2Kr: "선거인단의 인구 통계학적 변화가 정치 지형을 재편하고 있다." },
  '68_9':  { example2: "Experienced diplomats were dispatched to prevent the dispute from escalating.", example2Kr: "분쟁이 확대되는 것을 막기 위해 숙련된 외교관들이 파견되었다." },
  '68_10': { example2: "The legislation aimed to enfranchise citizens who had been denied the right to vote.", example2Kr: "그 법안은 투표권이 거부됐던 시민들에게 선거권을 부여하는 것을 목표로 했다." },
  '68_11': { example2: "The conflict had deep geopolitical implications that extended far beyond the region.", example2Kr: "그 분쟁은 지역을 훨씬 넘어서는 깊은 지정학적 함의를 가지고 있었다." },
  '68_12': { example2: "The two candidates held fundamentally different ideologies on taxation and welfare.", example2Kr: "두 후보자는 세금과 복지에 대해 근본적으로 다른 이데올로기를 가지고 있었다." },
  '68_13': { example2: "The independence referendum was closely watched by governments around the world.", example2Kr: "독립 국민 투표는 전 세계 정부들의 주목을 받았다." },
  '68_14': { example2: "The UN Security Council imposed new sanctions on the country following the attack.", example2Kr: "유엔 안전보장이사회는 공격 이후 그 나라에 새로운 제재를 부과했다." },
  '68_15': { example2: "Small nations sometimes find it difficult to assert their sovereignty against powerful neighbours.", example2Kr: "작은 나라들은 때때로 강력한 이웃 나라들에 맞서 주권을 주장하기 어려움을 느낀다." },
  '68_16': { example2: "Agricultural subsidies are a major point of contention in international trade negotiations.", example2Kr: "농업 보조금은 국제 무역 협상에서 주요 쟁점이다." },
  '68_17': { example2: "The campaign for universal suffrage galvanised ordinary citizens across class boundaries.", example2Kr: "보통 선거권을 위한 운동이 계층의 경계를 넘어 일반 시민들을 결집시켰다." },
  '68_18': { example2: "Public trust in institutions declines when transparency is lacking.", example2Kr: "투명성이 부족할 때 기관에 대한 대중의 신뢰가 감소한다." },
  '68_19': { example2: "The chairman used his casting veto to halt the merger proposal.", example2Kr: "의장은 자신의 결정권 있는 거부권을 사용해 합병 제안을 중단시켰다." },

  // ── Day 69 심리학·감정 어휘 ──
  '69_0':  { example2: "Crowding and lack of personal space are known triggers for aggression.", example2Kr: "밀집과 개인 공간의 부족은 공격성을 유발하는 것으로 알려져 있다." },
  '69_1':  { example2: "His ambivalence about the promotion left him unable to make a clear decision.", example2Kr: "승진에 대한 그의 양가감정이 그를 명확한 결정을 내리지 못하게 했다." },
  '69_2':  { example2: "Breathing exercises are a simple but effective tool for managing anxiety.", example2Kr: "호흡 운동은 불안을 관리하기 위한 간단하지만 효과적인 도구이다." },
  '69_3':  { example2: "Political apathy among young voters is a challenge for democratic engagement.", example2Kr: "젊은 유권자들 사이의 정치적 무관심은 민주주의적 참여에 대한 도전이다." },
  '69_4':  { example2: "Crying at a sad film can serve as a form of emotional catharsis.", example2Kr: "슬픈 영화를 보며 우는 것은 감정적 카타르시스의 한 형태로 작용할 수 있다." },
  '69_5':  { example2: "Higher-order cognition such as reasoning distinguishes humans from other animals.", example2Kr: "추론과 같은 고차원적 인지는 인간을 다른 동물과 구별 짓는다." },
  '69_6':  { example2: "Structured training helps professionals recognise and counteract their cognitive biases.", example2Kr: "구조화된 훈련은 전문가들이 인지 편향을 인식하고 대응하도록 돕는다." },
  '69_7':  { example2: "The nurse's compassion toward her patients was evident in her daily interactions.", example2Kr: "환자들에 대한 간호사의 연민은 일상적인 상호작용에서 명백히 드러났다." },
  '69_8':  { example2: "Acknowledging depression as an illness rather than weakness is vital for recovery.", example2Kr: "우울증을 나약함이 아닌 질병으로 인정하는 것이 회복에 중요하다." },
  '69_9':  { example2: "Empathy allows us to connect with others and respond to their needs more effectively.", example2Kr: "공감은 우리가 다른 사람들과 연결되고 그들의 필요에 더 효과적으로 반응하게 한다." },
  '69_10': { example2: "Winning the championship filled the athletes with a sense of pure euphoria.", example2Kr: "우승은 선수들을 순수한 행복감으로 가득 채웠다." },
  '69_11': { example2: "Stage fright is a well-known form of inhibition that affects many performers.", example2Kr: "무대 공포증은 많은 공연자들에게 영향을 미치는 잘 알려진 억제의 형태이다." },
  '69_12': { example2: "Through introspection, she identified the root causes of her recurring stress.", example2Kr: "자기 성찰을 통해 그녀는 반복적인 스트레스의 근본 원인을 파악했다." },
  '69_13': { example2: "Setting small achievable goals is a practical strategy for sustaining motivation.", example2Kr: "작고 달성 가능한 목표를 설정하는 것은 동기를 유지하기 위한 실용적인 전략이다." },
  '69_14': { example2: "Our perception of risk is influenced by personal experience and media coverage.", example2Kr: "위험에 대한 우리의 인식은 개인적인 경험과 미디어 보도에 의해 영향을 받는다." },
  '69_15': { example2: "Teaching resilience skills in schools can help children cope with adversity later in life.", example2Kr: "학교에서 회복력 기술을 가르치면 아이들이 나중에 삶의 역경에 대처하는 데 도움이 될 수 있다." },
  '69_16': { example2: "Athletes with high self-efficacy recover more quickly from poor performance.", example2Kr: "자기 효능감이 높은 운동선수들은 저조한 성과로부터 더 빠르게 회복한다." },
  '69_17': { example2: "The visual stimulus triggered an immediate emotional response in the test subjects.", example2Kr: "시각적 자극이 피험자들에게 즉각적인 감정적 반응을 촉발했다." },
  '69_18': { example2: "Many war veterans suffer from post-traumatic stress disorder long after returning home.", example2Kr: "많은 참전용사들이 귀국 후 오랫동안 외상 후 스트레스 장애로 고통받는다." },
  '69_19': { example2: "Organisations that invest in employee wellbeing see lower absenteeism and higher output.", example2Kr: "직원 웰빙에 투자하는 조직들은 낮은 결근율과 높은 생산성을 보인다." },

  // ── Day 70 학술 어휘 I ──
  '70_0':  { example2: "A clear and concise abstract is crucial for attracting readers to a research paper.", example2Kr: "명확하고 간결한 초록은 연구 논문에 독자를 끌어들이는 데 매우 중요하다." },
  '70_1':  { example2: "The professor asked students to annotate the primary sources before the seminar.", example2Kr: "교수는 학생들에게 세미나 전에 1차 자료에 주석을 달도록 요청했다." },
  '70_2':  { example2: "Improper citation of sources in academic work can constitute plagiarism.", example2Kr: "학술 연구에서 출처를 불충분하게 인용하면 표절에 해당할 수 있다." },
  '70_3':  { example2: "The origins of language remain a matter of scientific conjecture.", example2Kr: "언어의 기원은 여전히 과학적 추측의 문제로 남아 있다." },
  '70_4':  { example2: "The study established a clear correlation between hours of revision and exam performance.", example2Kr: "연구는 복습 시간과 시험 성적 사이의 명확한 상관관계를 확립했다." },
  '70_5':  { example2: "The committee published a thorough critique of the government's education reform.", example2Kr: "위원회는 정부의 교육 개혁에 대한 철저한 비평을 발표했다." },
  '70_6':  { example2: "Public discourse on immigration has become more polarised in recent years.", example2Kr: "이민에 관한 공론이 최근 몇 년간 더욱 양극화됐다." },
  '70_7':  { example2: "The clinical trial produced empirical evidence that the drug reduces relapse rates.", example2Kr: "임상 시험은 그 약이 재발률을 낮춘다는 실증적 증거를 도출했다." },
  '70_8':  { example2: "Philosophy of science courses often begin with the foundations of epistemology.", example2Kr: "과학 철학 과목들은 종종 인식론의 기초로 시작한다." },
  '70_9':  { example2: "It would be dangerous to extrapolate the pilot study's results to the general population.", example2Kr: "파일럿 연구의 결과를 일반 인구에게 외삽하는 것은 위험할 것이다." },
  '70_10': { example2: "The research team formulated a testable hypothesis before designing the experiment.", example2Kr: "연구팀은 실험을 설계하기 전에 검증 가능한 가설을 수립했다." },
  '70_11': { example2: "From the pattern of injuries, investigators inferred that the accident occurred at high speed.", example2Kr: "부상 패턴으로부터 수사관들은 사고가 고속에서 발생했다고 추론했다." },
  '70_12': { example2: "A mixed methods methodology allowed the researchers to capture both depth and breadth of data.", example2Kr: "혼합 방법 방법론은 연구자들이 데이터의 깊이와 폭을 모두 포착할 수 있게 해주었다." },
  '70_13': { example2: "The internet created a paradigm shift in how information is produced and distributed.", example2Kr: "인터넷은 정보가 생산되고 배포되는 방식에 패러다임의 전환을 일으켰다." },
  '70_14': { example2: "The findings were credible because they survived a rigorous peer review process.", example2Kr: "그 발견은 엄격한 동료 검토 과정을 통과했기 때문에 신뢰할 수 있었다." },
  '70_15': { example2: "Newton postulated the universal law of gravitation based on his observations of falling objects.", example2Kr: "뉴턴은 낙하하는 물체에 대한 관찰을 바탕으로 만유인력의 법칙을 가정했다." },
  '70_16': { example2: "The report combined both quantitative data and qualitative interviews for a fuller picture.", example2Kr: "보고서는 더 완전한 그림을 위해 양적 데이터와 질적 인터뷰를 결합했다." },
  '70_17': { example2: "The introduction should clearly state the rationale for conducting the study.", example2Kr: "서론은 연구를 수행하는 이론적 근거를 명확하게 기술해야 한다." },
  '70_18': { example2: "The literature review synthesises decades of research into a coherent overview.", example2Kr: "문헌 고찰은 수십 년간의 연구를 일관된 개요로 종합한다." },
  '70_19': { example2: "The independent variable was altered systematically while all other variables were held constant.", example2Kr: "독립 변수가 체계적으로 변경되는 동안 다른 모든 변수는 일정하게 유지되었다." },

  // ── Day 71 학술 어휘 II ──
  '71_0':  { example2: "The report's ambiguous conclusions left policymakers uncertain about next steps.", example2Kr: "보고서의 모호한 결론이 정책 입안자들을 다음 단계에 대해 불확실하게 만들었다." },
  '71_1':  { example2: "It is an axiom in science that theories must be falsifiable to be taken seriously.", example2Kr: "과학에서 이론이 진지하게 받아들여지려면 반증 가능해야 한다는 것은 공리이다." },
  '71_2':  { example2: "Researchers must acknowledge potential sources of bias when reporting their findings.", example2Kr: "연구자들은 결과를 보고할 때 잠재적인 편향의 출처를 인정해야 한다." },
  '71_3':  { example2: "Establishing causality between two variables requires careful experimental design.", example2Kr: "두 변수 사이의 인과관계를 확립하려면 신중한 실험 설계가 필요하다." },
  '71_4':  { example2: "Deductive reasoning proceeds from established premises to reach a logical conclusion.", example2Kr: "연역적 추론은 확립된 전제로부터 논리적 결론에 도달하기 위해 진행된다." },
  '71_5':  { example2: "Completing the dissertation was the most demanding intellectual challenge of her career.", example2Kr: "논문을 완성하는 것이 그녀의 경력에서 가장 힘든 지적 도전이었다." },
  '71_6':  { example2: "The study raised epistemological questions about whether objective truth is obtainable.", example2Kr: "그 연구는 객관적 진리가 달성 가능한지에 대한 인식론적 질문들을 제기했다." },
  '71_7':  { example2: "Identifying the naturalistic fallacy helps students reason more carefully about ethical claims.", example2Kr: "자연주의적 오류를 파악하면 학생들이 윤리적 주장에 대해 더 신중하게 추론하는 데 도움이 된다." },
  '71_8':  { example2: "The paper's implications for policy were discussed in the conclusion.", example2Kr: "논문의 정책적 함의는 결론에서 논의되었다." },
  '71_9':  { example2: "Inductive thinking allows scientists to generate hypotheses from patterns in observed data.", example2Kr: "귀납적 사고는 과학자들이 관찰된 데이터의 패턴에서 가설을 생성할 수 있게 한다." },
  '71_10': { example2: "A skilled translator must capture the nuance of the original text.", example2Kr: "숙련된 번역가는 원문의 뉘앙스를 포착해야 한다." },
  '71_11': { example2: "Scientific objectivity requires that researchers separate their personal values from their findings.", example2Kr: "과학적 객관성은 연구자들이 개인적인 가치관을 연구 결과와 분리할 것을 요구한다." },
  '71_12': { example2: "The university dismissed the student after clear evidence of plagiarism was discovered.", example2Kr: "명백한 표절 증거가 발견된 후 대학은 학생을 퇴학 처분했다." },
  '71_13': { example2: "The opening proposition of the argument must be clearly defined and testable.", example2Kr: "논증의 도입부 명제는 명확하게 정의되고 검증 가능해야 한다." },
  '71_14': { example2: "Qualitative interviews gave voice to experiences that statistics alone could not capture.", example2Kr: "질적 인터뷰는 통계만으로는 포착할 수 없는 경험들에 목소리를 부여했다." },
  '71_15': { example2: "The failure to achieve replication cast doubt on the original study's conclusions.", example2Kr: "재현 실패가 원래 연구의 결론에 의심을 제기했다." },
  '71_16': { example2: "The seminal paper laid the theoretical foundations for an entire new discipline.", example2Kr: "그 획기적인 논문은 완전히 새로운 학문 분야의 이론적 토대를 마련했다." },
  '71_17': { example2: "His master's thesis examined the long-term effects of bilingual education.", example2Kr: "그의 석사 논문은 이중 언어 교육의 장기적 효과를 검토했다." },
  '71_18': { example2: "The internal validity of the study was strengthened by its controlled experimental design.", example2Kr: "연구의 내적 타당성은 통제된 실험 설계에 의해 강화되었다." },
  '71_19': { example2: "The transcript was reproduced verbatim in the appendix for full transparency.", example2Kr: "완전한 투명성을 위해 녹취록은 부록에 그대로 재현되었다." },

  // ── Day 72 기술·IT 어휘 ──
  '72_0':  { example2: "A flawed algorithm can amplify social biases in automated decision-making systems.", example2Kr: "결함 있는 알고리즘은 자동화된 의사 결정 시스템에서 사회적 편견을 증폭시킬 수 있다." },
  '72_1':  { example2: "Advances in artificial intelligence are raising urgent questions about the future of work.", example2Kr: "인공지능의 발전이 미래 직업의 미래에 대한 시급한 질문들을 제기하고 있다." },
  '72_2':  { example2: "Remote teams need sufficient bandwidth to participate in high-quality video calls.", example2Kr: "원격 팀들은 고화질 화상 통화에 참여하기 위해 충분한 대역폭이 필요하다." },
  '72_3':  { example2: "Blockchain technology is increasingly being explored for use in supply chain transparency.", example2Kr: "블록체인 기술이 공급망 투명성에 사용하기 위해 점점 더 많이 탐색되고 있다." },
  '72_4':  { example2: "Cloud computing has enabled small businesses to access enterprise-level tools affordably.", example2Kr: "클라우드 컴퓨팅이 중소기업들이 기업 수준의 도구에 저렴하게 접근할 수 있게 해주었다." },
  '72_5':  { example2: "Cybersecurity threats are evolving faster than organisations can develop defences.", example2Kr: "사이버 보안 위협이 조직들이 방어책을 개발할 수 있는 것보다 빠르게 진화하고 있다." },
  '72_6':  { example2: "The company's reputation was damaged severely after the data breach became public.", example2Kr: "데이터 침해가 공개된 후 회사의 명성이 심각하게 훼손되었다." },
  '72_7':  { example2: "Strong encryption protects financial transactions from interception by cybercriminals.", example2Kr: "강력한 암호화가 금융 거래를 사이버 범죄자들의 가로챔으로부터 보호한다." },
  '72_8':  { example2: "A clean and consistent interface improves user productivity and reduces errors.", example2Kr: "깔끔하고 일관된 인터페이스는 사용자 생산성을 향상시키고 오류를 줄인다." },
  '72_9':  { example2: "Self-driving vehicles require ultra-low latency networks to respond safely in real time.", example2Kr: "자율 주행 차량은 실시간으로 안전하게 반응하기 위해 초저 지연 네트워크가 필요하다." },
  '72_10': { example2: "Machine learning is being used to detect fraudulent transactions in banking systems.", example2Kr: "머신 러닝이 은행 시스템에서 사기 거래를 탐지하기 위해 사용되고 있다." },
  '72_11': { example2: "Open source communities collaborate globally to improve and maintain shared software.", example2Kr: "오픈 소스 커뮤니티들이 공유 소프트웨어를 개선하고 유지하기 위해 전 세계적으로 협력한다." },
  '72_12': { example2: "Employees must be vigilant about phishing attacks disguised as internal communications.", example2Kr: "직원들은 내부 커뮤니케이션으로 위장한 피싱 공격에 대해 경계해야 한다." },
  '72_13': { example2: "The prototype was tested by focus groups before mass production was approved.", example2Kr: "프로토타입은 대량 생산이 승인되기 전에 포커스 그룹에 의해 테스트되었다." },
  '72_14': { example2: "The server farm consumes enormous amounts of electricity to keep cool and operational.", example2Kr: "서버 팜은 냉각 상태를 유지하고 운영되기 위해 엄청난 양의 전기를 소비한다." },
  '72_15': { example2: "Outdated software is one of the biggest vulnerabilities in any organisation's IT infrastructure.", example2Kr: "오래된 소프트웨어는 모든 조직의 IT 인프라에서 가장 큰 취약점 중 하나이다." },
  '72_16': { example2: "The rise of streaming platforms has disrupted the traditional broadcasting industry.", example2Kr: "스트리밍 플랫폼의 부상이 전통적인 방송 산업을 붕괴시켰다." },
  '72_17': { example2: "Virtual reality therapy is showing promising results for treating phobias and PTSD.", example2Kr: "가상 현실 치료가 공포증과 PTSD 치료에 유망한 결과를 보여주고 있다." },
  '72_18': { example2: "Patching software vulnerabilities promptly is a basic yet essential security practice.", example2Kr: "소프트웨어 취약점을 신속하게 패치하는 것은 기본적이지만 필수적인 보안 관행이다." },
  '72_19': { example2: "Wireless connectivity has fundamentally changed how and where people choose to work.", example2Kr: "무선 연결성이 사람들이 일하는 방식과 장소를 근본적으로 바꿔놓았다." },

  // ── Day 73 예술·문화 어휘 ──
  '73_0':  { example2: "The aesthetic of the new gallery collection contrasts sharply with traditional design.", example2Kr: "새 갤러리 컬렉션의 미학은 전통적인 디자인과 뚜렷하게 대조된다." },
  '73_1':  { example2: "The film functions as an allegory for the dangers of unchecked political ambition.", example2Kr: "그 영화는 제어되지 않는 정치적 야망의 위험에 대한 우화로 기능한다." },
  '73_2':  { example2: "The avant-garde artwork divided critics, with some calling it genius and others nonsense.", example2Kr: "그 아방가르드 작품은 비평가들을 나누었는데, 일부는 천재적이라 하고 다른 일부는 터무니없다고 했다." },
  '73_3':  { example2: "Scholars debate whether the literary canon should be expanded to include more diverse voices.", example2Kr: "학자들은 문학 정전이 더 다양한 목소리를 포함하도록 확장되어야 하는지를 논의한다." },
  '73_4':  { example2: "The museum curator organised the retrospective chronologically to show the artist's development.", example2Kr: "박물관 큐레이터는 작가의 발전을 보여주기 위해 회고전을 연대순으로 구성했다." },
  '73_5':  { example2: "The novel defies easy categorisation, borrowing from multiple literary genres.", example2Kr: "그 소설은 여러 문학 장르를 차용하며 쉬운 분류에 저항한다." },
  '73_6':  { example2: "The UNESCO list helps to safeguard intangible cultural heritage for future generations.", example2Kr: "유네스코 목록은 미래 세대를 위해 무형 문화유산을 보호하는 데 도움이 된다." },
  '73_7':  { example2: "The iconoclast filmmaker rejected studio conventions and financed her own independent work.", example2Kr: "우상 파괴적인 영화감독은 스튜디오 관행을 거부하고 자신의 독립 작품에 스스로 자금을 대었다." },
  '73_8':  { example2: "The comedian's improvisation brought the audience to tears with laughter.", example2Kr: "코미디언의 즉흥 연기는 관객들을 웃음의 눈물로 이끌었다." },
  '73_9':  { example2: "The film celebrates indigenous storytelling traditions that have survived colonisation.", example2Kr: "그 영화는 식민지화에서 살아남은 토착 이야기 전통을 축하한다." },
  '73_10': { example2: "The serpent motif appears throughout the artist's work as a symbol of transformation.", example2Kr: "뱀의 모티프는 변화의 상징으로 작가의 작품 전반에 걸쳐 나타난다." },
  '73_11': { example2: "The film's powerful narrative kept audiences on the edges of their seats throughout.", example2Kr: "영화의 강렬한 서사는 내내 관객들을 자리 끝에 긴장하게 만들었다." },
  '73_12': { example2: "The arts have historically depended heavily on royal and aristocratic patronage.", example2Kr: "예술은 역사적으로 왕실과 귀족의 후원에 크게 의존해 왔다." },
  '73_13': { example2: "The prolific composer wrote over 600 pieces before his untimely death at 35.", example2Kr: "그 다작의 작곡가는 35세에 요절하기 전에 600개 이상의 작품을 작곡했다." },
  '73_14': { example2: "The neighbourhood is undergoing a creative renaissance, attracting artists from across the country.", example2Kr: "그 동네는 전국에서 예술가들을 끌어들이며 창의적인 르네상스를 경험하고 있다." },
  '73_15': { example2: "Political satire was banned under the authoritarian regime, which feared public ridicule.", example2Kr: "정치 풍자는 대중의 조롱을 두려워한 권위주의 정권 아래 금지되었다." },
  '73_16': { example2: "The surrealism of the painting unsettled viewers with its dreamlike distortions of reality.", example2Kr: "그 그림의 초현실주의는 현실의 꿈같은 왜곡으로 관람객들을 불안하게 만들었다." },
  '73_17': { example2: "Writing in the vernacular made literature accessible to people who could not read Latin.", example2Kr: "일상 언어로 쓰는 것이 라틴어를 읽지 못하는 사람들에게 문학을 접근 가능하게 만들었다." },
  '73_18': { example2: "The virtuoso violinist brought the entire audience to a standing ovation.", example2Kr: "거장 바이올리니스트는 전체 관객을 기립 박수로 이끌었다." },
  '73_19': { example2: "The exhibition captured the restless zeitgeist of a generation shaped by rapid digital change.", example2Kr: "전시회는 빠른 디지털 변화에 의해 형성된 세대의 불안한 시대정신을 포착했다." },

  // ── Day 74 경제·금융 어휘 ──
  '74_0':  { example2: "The government's austerity programme sparked protests from public sector workers.", example2Kr: "정부의 긴축 프로그램이 공공 부문 근로자들의 시위를 촉발했다." },
  '74_1':  { example2: "Investors bought government bonds as a hedge against equity market volatility.", example2Kr: "투자자들은 주식 시장 변동성에 대한 헤지로 국채를 매입했다." },
  '74_2':  { example2: "Agricultural commodities such as wheat and corn saw sharp price rises due to the drought.", example2Kr: "가뭄으로 인해 밀과 옥수수 같은 농산물 상품 가격이 급격히 올랐다." },
  '74_3':  { example2: "Starting to save early maximises the benefits of compound interest over time.", example2Kr: "일찍 저축을 시작하면 시간이 지남에 따라 복리의 혜택을 극대화한다." },
  '74_4':  { example2: "Currency depreciation can make exports more competitive but fuels domestic inflation.", example2Kr: "통화 절하는 수출을 더 경쟁력 있게 만들 수 있지만 국내 인플레이션을 부채질한다." },
  '74_5':  { example2: "The country's trade deficit widened significantly due to rising import costs.", example2Kr: "수입 비용 상승으로 인해 국가의 무역 적자가 크게 확대되었다." },
  '74_6':  { example2: "The record dividend payment rewarded long-term shareholders for their patience.", example2Kr: "사상 최대 배당금 지급이 장기 주주들의 인내에 보상했다." },
  '74_7':  { example2: "The government's fiscal stimulus helped offset the impact of the global slowdown.", example2Kr: "정부의 재정 부양책이 세계 경기 둔화의 영향을 상쇄하는 데 도움이 되었다." },
  '74_8':  { example2: "Several hedge funds bet against the housing market ahead of the 2008 financial crisis.", example2Kr: "여러 헤지 펀드들이 2008년 금융 위기 전에 주택 시장을 역베팅했다." },
  '74_9':  { example2: "Central banks tightened monetary policy aggressively to bring inflation under control.", example2Kr: "중앙은행들은 인플레이션을 통제하에 두기 위해 공격적으로 통화 정책을 긴축했다." },
  '74_10': { example2: "Higher interest rates tend to cool consumer spending and slow economic growth.", example2Kr: "높은 금리는 소비자 지출을 식히고 경제 성장을 둔화시키는 경향이 있다." },
  '74_11': { example2: "Unconventional monetary policy tools such as quantitative easing became widely used after 2008.", example2Kr: "양적 완화와 같은 비전통적 통화 정책 수단들이 2008년 이후 널리 사용되게 되었다." },
  '74_12': { example2: "The prolonged recession left a generation of young people struggling to find stable employment.", example2Kr: "장기간의 경기 침체가 한 세대의 젊은이들을 안정적인 고용을 찾기 위해 고군분투하게 만들었다." },
  '74_13': { example2: "Family remittances sent home account for a significant portion of some countries' GDP.", example2Kr: "가족에게 보내는 해외 송금이 일부 국가들의 GDP의 상당 부분을 차지한다." },
  '74_14': { example2: "The company's shares surged 20% on the day of its stock market listing.", example2Kr: "회사 주식이 주식 시장 상장 당일 20% 급등했다." },
  '74_15': { example2: "Excessive financial speculation with borrowed money amplified the severity of the crisis.", example2Kr: "차입금을 이용한 과도한 금융 투기가 위기의 심각성을 증폭시켰다." },
  '74_16': { example2: "The 1970s saw a damaging period of stagflation, combining high inflation and high unemployment.", example2Kr: "1970년대는 높은 인플레이션과 높은 실업률이 결합된 스태그플레이션의 해로운 시기를 보았다." },
  '74_17': { example2: "Retaliatory tariffs escalated the trade dispute into a damaging international trade war.", example2Kr: "보복 관세가 무역 분쟁을 파괴적인 국제 무역 전쟁으로 확대시켰다." },
  '74_18': { example2: "The persistent trade surplus reflects the country's strong export competitiveness.", example2Kr: "지속적인 무역 흑자는 국가의 강한 수출 경쟁력을 반영한다." },
  '74_19': { example2: "Falling bond yields signal that investors expect slower economic growth ahead.", example2Kr: "하락하는 채권 수익률은 투자자들이 앞으로 느린 경제 성장을 기대한다는 신호다." },

  // ── Day 75 철학·윤리 어휘 ──
  '75_0':  { example2: "Her altruism led her to donate her entire estate to educational charities.", example2Kr: "그녀의 이타심은 그녀가 전 재산을 교육 자선 단체에 기부하게 했다." },
  '75_1':  { example2: "Medical professionals must balance patient autonomy with duties of care.", example2Kr: "의료 전문가들은 환자의 자율성과 돌봄의 의무를 균형 있게 조율해야 한다." },
  '75_2':  { example2: "Kant's categorical imperative asks whether an action could be willed as a universal law.", example2Kr: "칸트의 정언 명령은 행동이 보편적인 법칙으로 의지될 수 있는지를 묻는다." },
  '75_3':  { example2: "From a consequentialist perspective, lying may be justified if it prevents serious harm.", example2Kr: "결과주의적 관점에서 거짓말은 심각한 해를 방지한다면 정당화될 수 있다." },
  '75_4':  { example2: "Determinism challenges the common assumption that humans possess genuine free will.", example2Kr: "결정론은 인간이 진정한 자유 의지를 가지고 있다는 일반적인 가정에 도전한다." },
  '75_5':  { example2: "Marx used the Hegelian dialectic to develop his materialist theory of history.", example2Kr: "마르크스는 역사의 유물론적 이론을 발전시키기 위해 헤겔의 변증법을 사용했다." },
  '75_6':  { example2: "Empiricism underpins the scientific method, prioritising evidence over speculation.", example2Kr: "경험주의는 추측보다 증거를 우선시하며 과학적 방법을 뒷받침한다." },
  '75_7':  { example2: "Existentialism became highly influential in post-war Europe as people sought new meaning.", example2Kr: "사람들이 새로운 의미를 찾으면서 실존주의가 전후 유럽에서 매우 영향력 있게 되었다." },
  '75_8':  { example2: "Some critics argue that modern consumer culture promotes hedonism at the expense of deeper values.", example2Kr: "일부 비평가들은 현대 소비자 문화가 더 깊은 가치들을 희생시키며 쾌락주의를 촉진한다고 주장한다." },
  '75_9':  { example2: "Her integrity in the face of pressure to compromise was widely admired.", example2Kr: "타협하라는 압박에도 불구하고 그녀의 청렴함은 널리 존경받았다." },
  '75_10': { example2: "Moral relativism makes it difficult to condemn practices that violate universal human rights.", example2Kr: "도덕 상대주의는 보편적 인권을 침해하는 관행을 비난하기 어렵게 만든다." },
  '75_11': { example2: "Nietzsche saw nihilism as a crisis that demanded a radical revaluation of all values.", example2Kr: "니체는 허무주의를 모든 가치의 급진적인 재평가를 요구하는 위기로 보았다." },
  '75_12': { example2: "Ontology explores whether abstract concepts like numbers and justice truly exist.", example2Kr: "존재론은 숫자와 정의와 같은 추상적 개념들이 진정으로 존재하는지를 탐구한다." },
  '75_13': { example2: "A pragmatist approach focuses on what works in practice, not theoretical ideals.", example2Kr: "실용주의적 접근법은 이론적 이상이 아닌 실제로 효과가 있는 것에 초점을 맞춘다." },
  '75_14': { example2: "Descartes is considered the father of modern rationalism for his famous 'I think, therefore I am'.", example2Kr: "데카르트는 유명한 '나는 생각한다, 고로 나는 존재한다'로 현대 합리주의의 아버지로 여겨진다." },
  '75_15': { example2: "Critics of cultural relativism argue that it can be used to excuse serious human rights abuses.", example2Kr: "문화 상대주의 비평가들은 그것이 심각한 인권 침해를 용인하는 데 사용될 수 있다고 주장한다." },
  '75_16': { example2: "Stoicism remains popular today as a framework for coping with adversity and anxiety.", example2Kr: "스토아철학은 역경과 불안에 대처하기 위한 틀로 오늘날에도 여전히 인기가 있다." },
  '75_17': { example2: "The historian acknowledged the subjectivity of her own perspective in the introduction.", example2Kr: "역사학자는 서론에서 자신의 관점의 주관성을 인정했다." },
  '75_18': { example2: "Utilitarianism underpinned many 19th-century social reforms aimed at maximising public welfare.", example2Kr: "공리주의는 공공 복지를 극대화하려는 19세기 많은 사회 개혁의 기반이 되었다." },
  '75_19': { example2: "Virtue ethics asks not what you should do but what kind of person you should strive to be.", example2Kr: "덕 윤리학은 무엇을 해야 하는지가 아니라 어떤 사람이 되기 위해 노력해야 하는지를 묻는다." },

  // ── Day 76 언어·언어학 어휘 ──
  '76_0':  { example2: "She quickly learned to adapt her accent to be better understood in her new country.", example2Kr: "그녀는 새로운 나라에서 더 잘 이해되기 위해 빠르게 억양을 적응시키는 법을 배웠다." },
  '76_1':  { example2: "Being bilingual opens doors to wider cultural understanding and professional opportunities.", example2Kr: "이중 언어 구사 능력은 더 넓은 문화적 이해와 직업적 기회로 가는 문을 열어준다." },
  '76_2':  { example2: "Recognising cognates across languages can accelerate vocabulary acquisition significantly.", example2Kr: "언어들 사이에서 동계어를 인식하면 어휘 습득을 크게 가속화할 수 있다." },
  '76_3':  { example2: "Writers choose words carefully, aware of the different connotations each carries.", example2Kr: "작가들은 각 단어가 가진 다른 함축을 인식하며 신중하게 단어를 선택한다." },
  '76_4':  { example2: "The author's precise diction demonstrated a deep command of the English language.", example2Kr: "저자의 정확한 어법은 영어에 대한 깊은 이해를 보여주었다." },
  '76_5':  { example2: "The researcher recorded hours of natural dialect speech for phonological analysis.", example2Kr: "연구자는 음운론적 분석을 위해 수 시간의 자연 방언 발화를 녹음했다." },
  '76_6':  { example2: "Understanding the etymology of a word often illuminates its current meaning.", example2Kr: "단어의 어원을 이해하면 종종 현재의 의미를 밝혀준다." },
  '76_7':  { example2: "The phrase 'it's raining cats and dogs' is an example of figurative language.", example2Kr: "'고양이와 개가 비처럼 쏟아진다'는 표현은 비유적 언어의 예이다." },
  '76_8':  { example2: "The teacher emphasised that good grammar supports clarity and credibility in writing.", example2Kr: "선생님은 좋은 문법이 글쓰기의 명확성과 신뢰성을 지지한다고 강조했다." },
  '76_9':  { example2: "He struggled to understand the idioms that native speakers used so naturally.", example2Kr: "그는 원어민들이 너무나 자연스럽게 사용하는 관용어를 이해하는 데 어려움을 겪었다." },
  '76_10': { example2: "The linguistics department offers courses in phonology, syntax, and discourse analysis.", example2Kr: "언어학과는 음운론, 통사론, 담화 분석 과목들을 제공한다." },
  '76_11': { example2: "The morphology of English verbs is simpler than that of many other European languages.", example2Kr: "영어 동사의 형태론은 다른 많은 유럽 언어들보다 더 단순하다." },
  '76_12': { example2: "The phonetics course trained students to produce and distinguish sounds of unfamiliar languages.", example2Kr: "음성학 과목은 학생들이 낯선 언어의 소리를 산출하고 구별하도록 훈련시켰다." },
  '76_13': { example2: "Pragmatics explains how the phrase 'Can you pass the salt?' functions as a request.", example2Kr: "화용론은 '소금 건네줄 수 있어?'라는 문장이 어떻게 요청으로 기능하는지를 설명한다." },
  '76_14': { example2: "The politician's rhetoric was powerful but lacked substance and specific policy proposals.", example2Kr: "정치인의 수사학은 강력했지만 내용과 구체적인 정책 제안이 부족했다." },
  '76_15': { example2: "Even small changes in wording can shift the entire semantics of a legal clause.", example2Kr: "표현의 작은 변화도 법적 조항의 전체적인 의미를 바꿀 수 있다." },
  '76_16': { example2: "The syntax of Japanese differs markedly from that of English in word order.", example2Kr: "일본어의 통사는 어순에서 영어와 현저하게 다르다." },
  '76_17': { example2: "Literary translation demands not just linguistic skill but deep cultural knowledge.", example2Kr: "문학 번역은 단순한 언어 능력만이 아니라 깊은 문화적 지식을 요구한다." },
  '76_18': { example2: "The court interpreter transcribed every utterance of the witness without omission.", example2Kr: "법정 통역사는 증인의 모든 발언을 빠짐없이 기록했다." },
  '76_19': { example2: "A rich vocabulary allows writers to express subtle differences in meaning with precision.", example2Kr: "풍부한 어휘력은 작가들이 의미의 미묘한 차이를 정확하게 표현할 수 있게 한다." },

  // ── Day 77 교육·사회과학 어휘 ──
  '77_0':  { example2: "International accreditation ensures that a degree is recognised by employers worldwide.", example2Kr: "국제 인증은 학위가 전 세계 고용주들에게 인정받도록 보장한다." },
  '77_1':  { example2: "Immigration policy must balance cultural assimilation with respect for diversity.", example2Kr: "이민 정책은 문화적 동화와 다양성에 대한 존중 사이에서 균형을 잡아야 한다." },
  '77_2':  { example2: "Strong social cohesion helped the community recover quickly after the natural disaster.", example2Kr: "강한 사회 결속력이 자연재해 이후 지역 사회가 빠르게 회복하는 데 도움이 되었다." },
  '77_3':  { example2: "The curriculum was overhauled to better prepare students for the demands of the 21st century.", example2Kr: "교육과정은 21세기의 요구에 학생들을 더 잘 대비시키기 위해 전면 개편되었다." },
  '77_4':  { example2: "Research consistently highlights the disparity in achievement between advantaged and disadvantaged pupils.", example2Kr: "연구는 지속적으로 유리한 학생과 불리한 학생 사이의 성취 격차를 부각시킨다." },
  '77_5':  { example2: "Anti-discrimination laws aim to protect workers from unfair treatment in the workplace.", example2Kr: "반차별 법은 직장에서 불공정한 대우로부터 근로자들을 보호하는 것을 목표로 한다." },
  '77_6':  { example2: "The egalitarian school model places equal value on academic and vocational learning.", example2Kr: "평등주의적 학교 모델은 학문적 학습과 직업적 학습에 동등한 가치를 부여한다." },
  '77_7':  { example2: "Women's empowerment through education has strong links to reducing child mortality rates.", example2Kr: "교육을 통한 여성의 역량 강화는 영아 사망률 감소와 강한 연관성이 있다." },
  '77_8':  { example2: "The ethnography immersed the researcher in the daily routines of a nomadic community.", example2Kr: "민족지학 연구가 연구자를 유목 공동체의 일상 속에 완전히 몰입시켰다." },
  '77_9':  { example2: "Globalisation has accelerated the spread of English as the dominant language of trade.", example2Kr: "세계화가 무역의 지배적 언어로서 영어의 확산을 가속화했다." },
  '77_10': { example2: "Hypothesis testing allows social scientists to draw statistically valid conclusions from data.", example2Kr: "가설 검증은 사회과학자들이 데이터로부터 통계적으로 유효한 결론을 도출할 수 있게 한다." },
  '77_11': { example2: "Rising inequality undermines social trust and increases political polarisation.", example2Kr: "증가하는 불평등은 사회적 신뢰를 약화시키고 정치적 양극화를 심화시킨다." },
  '77_12': { example2: "Successful integration requires adequate support services for newcomer communities.", example2Kr: "성공적인 통합을 위해서는 신규 이주민 공동체를 위한 충분한 지원 서비스가 필요하다." },
  '77_13': { example2: "Financial literacy should be taught in schools to prepare young people for adult life.", example2Kr: "금융 리터러시는 청소년들이 성인 생활을 준비할 수 있도록 학교에서 가르쳐야 한다." },
  '77_14': { example2: "Breaking social norms can signal creativity but may also invite disapproval or exclusion.", example2Kr: "사회 규범을 어기는 것은 창의성을 나타낼 수 있지만 불승인이나 배제를 초래할 수도 있다." },
  '77_15': { example2: "Modern pedagogy encourages students to question ideas rather than passively accept them.", example2Kr: "현대 교수법은 학생들이 수동적으로 받아들이기보다 아이디어에 의문을 제기하도록 장려한다." },
  '77_16': { example2: "Early socialisation in the family and school shapes lifelong attitudes and behaviours.", example2Kr: "가족과 학교에서의 초기 사회화는 평생의 태도와 행동을 형성한다." },
  '77_17': { example2: "Education programmes can challenge stereotypes by exposing students to diverse perspectives.", example2Kr: "교육 프로그램은 학생들에게 다양한 관점을 접하게 함으로써 고정관념에 도전할 수 있다." },
  '77_18': { example2: "Social stratification based on birth remains entrenched in many parts of the world.", example2Kr: "출생에 기반한 사회 계층화는 세계 많은 지역에서 여전히 뿌리 깊게 남아 있다." },
  '77_19': { example2: "The welfare system was reformed to better support those most in need.", example2Kr: "복지 시스템은 가장 도움이 필요한 사람들을 더 잘 지원하기 위해 개혁되었다." },

  // ── Day 78 역사·문명 어휘 ──
  '78_0':  { example2: "Philosophers of antiquity grappled with questions that are still debated today.", example2Kr: "고대의 철학자들은 오늘날에도 여전히 논의되는 질문들과 씨름했다." },
  '78_1':  { example2: "Underwater archaeology has uncovered ancient trade routes lost for thousands of years.", example2Kr: "수중 고고학이 수천 년간 잊혀진 고대 무역로를 발굴했다." },
  '78_2':  { example2: "The court chronicle described the king's military campaigns in painstaking detail.", example2Kr: "궁중 연대기는 왕의 군사 작전을 세세하게 묘사했다." },
  '78_3':  { example2: "The collapse of the Roman civilisation had profound consequences for Europe for centuries.", example2Kr: "로마 문명의 붕괴는 수 세기 동안 유럽에 심오한 영향을 미쳤다." },
  '78_4':  { example2: "Scholars debate the long-term economic consequences of British colonialism in Asia.", example2Kr: "학자들은 아시아에서의 영국 식민주의의 장기적인 경제적 결과를 논의한다." },
  '78_5':  { example2: "Alexander the Great's conquest spread Hellenistic culture across the ancient world.", example2Kr: "알렉산더 대왕의 정복은 고대 세계에 헬레니즘 문화를 퍼뜨렸다." },
  '78_6':  { example2: "The Tang Dynasty is celebrated for its cultural openness and cosmopolitan character.", example2Kr: "당나라는 문화적 개방성과 세계시민적 특성으로 유명하다." },
  '78_7':  { example2: "At its peak, the Roman Empire controlled territories from Britain to Mesopotamia.", example2Kr: "전성기에 로마 제국은 영국에서 메소포타미아까지 영토를 지배했다." },
  '78_8':  { example2: "The decline of feudalism paved the way for a more mobile and commercially active society.", example2Kr: "봉건제의 쇠퇴는 더 이동성 있고 상업적으로 활발한 사회를 위한 길을 열었다." },
  '78_9':  { example2: "European imperialism in the 19th century caused widespread suffering across Africa and Asia.", example2Kr: "19세기 유럽 제국주의는 아프리카와 아시아 전역에서 광범위한 고통을 야기했다." },
  '78_10': { example2: "Every great civilisation leaves a legacy that future generations must interpret and learn from.", example2Kr: "모든 위대한 문명은 미래 세대가 해석하고 배워야 할 유산을 남긴다." },
  '78_11': { example2: "Medieval trade networks connected Europe, the Middle East, and Asia in a web of commerce.", example2Kr: "중세 무역망은 유럽, 중동, 아시아를 상업의 그물망으로 연결했다." },
  '78_12': { example2: "The constitutional monarchy evolved gradually from centuries of conflict between crown and parliament.", example2Kr: "입헌군주제는 수 세기에 걸친 왕권과 의회의 갈등에서 점진적으로 발전했다." },
  '78_13': { example2: "Nationalist movements in the 20th century led to the creation of numerous new states.", example2Kr: "20세기 민족주의 운동들이 수많은 새로운 국가들의 탄생으로 이어졌다." },
  '78_14': { example2: "The Protestant Reformation shattered the religious unity of medieval Europe.", example2Kr: "프로테스탄트 종교개혁은 중세 유럽의 종교적 단일성을 산산조각 냈다." },
  '78_15': { example2: "The Italian Renaissance produced an extraordinary flowering of art, science, and literature.", example2Kr: "이탈리아 르네상스는 예술, 과학, 문학의 놀라운 꽃을 피웠다." },
  '78_16': { example2: "The Industrial Revolution was a economic revolution that reshaped human labour and society.", example2Kr: "산업혁명은 인간의 노동과 사회를 재편한 경제 혁명이었다." },
  '78_17': { example2: "After independence, the new nation asserted its sovereignty with a new flag and constitution.", example2Kr: "독립 이후 새로운 나라는 새로운 국기와 헌법으로 주권을 선언했다." },
  '78_18': { example2: "The 1648 Peace of Westphalia treaty established the foundations of modern international law.", example2Kr: "1648년 베스트팔렌 평화 조약이 현대 국제법의 토대를 확립했다." },
  '78_19': { example2: "The popular uprising was sparked by decades of political repression and economic misery.", example2Kr: "민중 봉기는 수십 년간의 정치적 억압과 경제적 고통에 의해 촉발됐다." },

  // ── Day 79 과학·자연 어휘 ──
  '79_0':  { example2: "Atoms are extraordinarily small; a single grain of sand contains billions of them.", example2Kr: "원자는 엄청나게 작다; 모래 한 알에도 수십억 개가 들어 있다." },
  '79_1':  { example2: "The discovery served as a catalyst for rapid advances in renewable energy technology.", example2Kr: "그 발견은 재생 에너지 기술의 빠른 발전에 촉매 역할을 했다." },
  '79_2':  { example2: "Errors in chromosome replication during cell division can lead to genetic disorders.", example2Kr: "세포 분열 중 염색체 복제 오류는 유전 질환으로 이어질 수 있다." },
  '79_3':  { example2: "Combustion of fossil fuels releases carbon dioxide, contributing to the greenhouse effect.", example2Kr: "화석 연료의 연소는 이산화탄소를 방출하여 온실 효과에 기여한다." },
  '79_4':  { example2: "Condensation in the water cycle returns water vapour from clouds to the earth's surface.", example2Kr: "물의 순환에서 응결은 구름에서 수증기를 지구 표면으로 되돌린다." },
  '79_5':  { example2: "Maxwell's equations describe how electromagnetism governs the behaviour of electric and magnetic fields.", example2Kr: "맥스웰 방정식은 전자기가 전기장과 자기장의 행동을 어떻게 지배하는지를 설명한다." },
  '79_6':  { example2: "Enzymes are vital biological catalysts that drive nearly every chemical reaction in living cells.", example2Kr: "효소는 살아있는 세포에서 거의 모든 화학 반응을 이끄는 중요한 생물학적 촉매이다." },
  '79_7':  { example2: "The fossil record provides compelling evidence for the theory of evolution.", exampleKr: "화석 기록은 진화론에 대한 설득력 있는 증거를 제공한다." },
  '79_8':  { example2: "Nuclear fission powers both atomic bombs and commercial nuclear power stations.", example2Kr: "핵분열은 핵폭탄과 상업용 원자력 발전소 모두에 동력을 공급한다." },
  '79_9':  { example2: "Gene therapy is emerging as a treatment for diseases caused by faulty genetic sequences.", example2Kr: "유전자 치료가 결함 있는 유전자 서열로 인한 질환의 치료법으로 부상하고 있다." },
  '79_10': { example2: "Without gravity, the moon would drift away from Earth into deep space.", example2Kr: "중력이 없으면 달은 지구를 떠나 우주 공간으로 표류할 것이다." },
  '79_11': { example2: "Water molecules are polar, which gives water its unique solvent properties.", example2Kr: "물 분자는 극성을 띠어 물에 독특한 용매 특성을 부여한다." },
  '79_12': { example2: "A mutation in the BRCA gene significantly increases the risk of breast and ovarian cancer.", example2Kr: "BRCA 유전자의 돌연변이는 유방암과 난소암의 위험을 크게 높인다." },
  '79_13': { example2: "Without photosynthesis, the oxygen in Earth's atmosphere would not exist.", example2Kr: "광합성이 없다면 지구 대기의 산소는 존재하지 않을 것이다." },
  '79_14': { example2: "Quantum entanglement allows particles to influence each other instantly across any distance.", example2Kr: "양자 얽힘은 입자들이 어떤 거리에서도 즉각적으로 서로에게 영향을 미칠 수 있게 한다." },
  '79_15': { example2: "Radiation therapy targets cancer cells while minimising damage to surrounding healthy tissue.", example2Kr: "방사선 치료는 주변 건강한 조직에 대한 손상을 최소화하면서 암세포를 표적으로 한다." },
  '79_16': { example2: "Scientists have estimated that up to 8.7 million species inhabit our planet.", example2Kr: "과학자들은 최대 870만 종이 우리 지구에 서식하고 있다고 추정한다." },
  '79_17': { example2: "Thermal insulation in buildings reduces energy loss and lowers heating costs.", example2Kr: "건물의 열 단열은 에너지 손실을 줄이고 난방 비용을 낮춘다." },
  '79_18': { example2: "The satellite's velocity must be precisely calibrated to maintain a stable orbit.", example2Kr: "위성의 속도는 안정적인 궤도를 유지하기 위해 정확하게 보정되어야 한다." },
  '79_19': { example2: "Infrared light has a longer wavelength than visible light and is invisible to the human eye.", example2Kr: "적외선은 가시광선보다 파장이 길며 인간의 눈에 보이지 않는다." },

  // ── Day 80 스포츠·신체 어휘 ──
  '80_0':  { example2: "The defender's agility allowed her to outmanoeuvre her opponents consistently.", example2Kr: "수비수의 민첩성이 그녀가 지속적으로 상대방을 능가하게 해주었다." },
  '80_1':  { example2: "Aerobic fitness significantly reduces the risk of developing cardiovascular disease.", example2Kr: "유산소 체력은 심혈관 질환 발병 위험을 크게 줄인다." },
  '80_2':  { example2: "Sports biomechanics has helped swimmers refine their stroke technique for maximum efficiency.", example2Kr: "스포츠 생체역학은 수영 선수들이 최대 효율을 위해 수영 동작을 개선하는 데 도움이 됐다." },
  '80_3':  { example2: "The patient's cardiovascular function improved dramatically after six months of rehabilitation.", example2Kr: "환자의 심혈관 기능은 6개월의 재활 이후 극적으로 향상되었다." },
  '80_4':  { example2: "Strict protocols now govern how concussion is managed in professional sport.", example2Kr: "엄격한 프로토콜이 이제 프로 스포츠에서 뇌진탕이 어떻게 관리되는지를 규정한다." },
  '80_5':  { example2: "The anti-doping agency conducted surprise tests at the national athletics championships.", example2Kr: "반도핑 기관은 전국 육상 선수권 대회에서 불시 검사를 실시했다." },
  '80_6':  { example2: "Elite cyclists develop outstanding endurance through years of structured training.", example2Kr: "엘리트 사이클리스트들은 수년간의 체계적인 훈련을 통해 뛰어난 지구력을 개발한다." },
  '80_7':  { example2: "Flexibility declines with age, making stretching an increasingly important habit.", example2Kr: "유연성은 나이가 들면서 감소하여 스트레칭이 점점 더 중요한 습관이 된다." },
  '80_8':  { example2: "Athletes competing in hot climates must prioritise hydration to avoid heat exhaustion.", example2Kr: "더운 기후에서 경쟁하는 선수들은 열 탈진을 피하기 위해 수분 공급을 우선시해야 한다." },
  '80_9':  { example2: "The training programme varied in intensity to allow adequate recovery between sessions.", example2Kr: "훈련 프로그램은 세션 사이에 적절한 회복을 허용하기 위해 강도를 다양하게 했다." },
  '80_10': { example2: "Ligament damage often requires surgery and months of physiotherapy to fully recover.", example2Kr: "인대 손상은 종종 완전히 회복하는 데 수술과 수개월의 물리 치료가 필요하다." },
  '80_11': { example2: "A higher resting metabolism means the body burns more calories even while at rest.", example2Kr: "더 높은 안정 시 신진대사는 신체가 휴식 중에도 더 많은 칼로리를 태운다는 것을 의미한다." },
  '80_12': { example2: "Muscular imbalance between opposing muscle groups is a common cause of overuse injuries.", example2Kr: "대립하는 근육 그룹 사이의 근육 불균형은 과사용 부상의 흔한 원인이다." },
  '80_13': { example2: "The team dietitian designed a nutrition plan tailored to each player's training load.", example2Kr: "팀 영양사는 각 선수의 훈련 부하에 맞춘 영양 계획을 설계했다." },
  '80_14': { example2: "Sports physiology explains why altitude training improves endurance performance at sea level.", example2Kr: "스포츠 생리학은 왜 고도 훈련이 해수면에서 지구력 수행을 향상시키는지를 설명한다." },
  '80_15': { example2: "Correcting poor posture early can prevent chronic pain and injury in later life.", example2Kr: "나쁜 자세를 일찍 교정하면 나중에 만성 통증과 부상을 예방할 수 있다." },
  '80_16': { example2: "Her quick reflex action prevented what could have been a serious accident.", example2Kr: "그녀의 빠른 반사 행동이 심각한 사고가 될 수 있었던 일을 막았다." },
  '80_17': { example2: "Building stamina requires patience and a gradual increase in training load over time.", example2Kr: "스태미나를 기르려면 인내심과 시간이 지남에 따라 훈련 부하의 점진적인 증가가 필요하다." },
  '80_18': { example2: "Inflammation of the patellar tendon is a common complaint among cyclists and runners.", example2Kr: "슬개건의 염증은 사이클리스트와 달리기 선수들 사이에서 흔한 불편 사항이다." },
  '80_19': { example2: "A proper warm-up raises muscle temperature and significantly reduces injury risk.", example2Kr: "적절한 준비 운동은 근육 온도를 높이고 부상 위험을 크게 줄인다." },
});
