/**
 * examples2_1.js - Day 1~20
*/
const EXAMPLES2 = {
  // ── Day 1 핵심 동사 I ──
  '1_0':  { example2: "He finally achieved his dream of running a marathon.", example2Kr: "그는 마침내 마라톤 완주라는 꿈을 이루었다." },
  '1_1':  { example2: "Organisms must adapt to survive in changing environments.", example2Kr: "생물은 변화하는 환경에서 생존하기 위해 적응해야 한다." },
  '1_2':  { example2: "We need to advance our knowledge in this field.", example2Kr: "우리는 이 분야에서 지식을 발전시켜야 한다." },
  '1_3':  { example2: "Time should be allocated wisely each day.", example2Kr: "매일 시간을 현명하게 배분해야 한다." },
  '1_4':  { example2: "The doctor analyzed the test results carefully.", example2Kr: "의사가 검사 결과를 신중하게 분석했다." },
  '1_5':  { example2: "We anticipated delays due to the storm.", example2Kr: "우리는 폭풍으로 인한 지연을 예상했다." },
  '1_6':  { example2: "The same principles apply in both cases.", example2Kr: "동일한 원칙이 두 경우 모두에 적용된다." },
  '1_7':  { example2: "It is difficult to assess the full impact of the decision.", example2Kr: "그 결정의 전체 영향을 평가하기는 어렵다." },
  '1_8':  { example2: "Never assume you know everything.", example2Kr: "모든 것을 안다고 절대 가정하지 마라." },
  '1_9':  { example2: "Honey attracts bees and other insects.", example2Kr: "꿀은 벌과 다른 곤충들을 끌어들인다." },
  '1_10': { example2: "Higher education benefits society as a whole.", example2Kr: "고등 교육은 사회 전체에 이익을 준다." },
  '1_11': { example2: "The coach challenged the team to improve their performance.", example2Kr: "코치는 팀에게 성적 향상에 도전하라고 했다." },
  '1_12': { example2: "Animals communicate in various ways.", example2Kr: "동물들은 다양한 방법으로 의사소통한다." },
  '1_13': { example2: "Many companies are competing for the same customers.", example2Kr: "많은 회사들이 같은 고객들을 두고 경쟁하고 있다." },
  '1_14': { example2: "He concentrated all his energy on the final project.", example2Kr: "그는 모든 에너지를 마지막 프로젝트에 집중했다." },
  '1_15': { example2: "Can you confirm that the meeting is at 3 PM?", example2Kr: "회의가 오후 3시인 것을 확인해 줄 수 있나요?" },
  '1_16': { example2: "Have you considered the risks involved?", example2Kr: "관련된 위험들을 고려해 보셨나요?" },
  '1_17': { example2: "Many factors contribute to climate change.", example2Kr: "많은 요인들이 기후 변화에 기여한다." },
  '1_18': { example2: "Music has the power to create strong emotions.", example2Kr: "음악은 강한 감정을 만들어내는 힘이 있다." },
  '1_19': { example2: "Success is defined differently by different people.", example2Kr: "성공은 사람마다 다르게 정의된다." },

  // ── Day 2 핵심 동사 II ──
  '2_0':  { example2: "The student demonstrated excellent problem-solving skills.", example2Kr: "그 학생은 뛰어난 문제 해결 능력을 보여주었다." },
  '2_1':  { example2: "Children develop language skills at different rates.", example2Kr: "아이들은 서로 다른 속도로 언어 능력을 발전시킨다." },
  '2_2':  { example2: "I discovered a great coffee shop near my office.", example2Kr: "나는 사무실 근처에서 좋은 커피숍을 발견했다." },
  '2_3':  { example2: "We discussed the issue for over an hour.", example2Kr: "우리는 한 시간 넘게 그 문제를 논의했다." },
  '2_4':  { example2: "She displayed great courage under pressure.", example2Kr: "그녀는 압박감 속에서도 대단한 용기를 보여주었다." },
  '2_5':  { example2: "A good education enables people to pursue better careers.", example2Kr: "좋은 교육은 사람들이 더 나은 직업을 추구할 수 있게 한다." },
  '2_6':  { example2: "The manager encouraged her team through difficult times.", example2Kr: "매니저는 힘든 시기를 헤쳐나가도록 팀을 격려했다." },
  '2_7':  { example2: "She established herself as a leading expert in the field.", example2Kr: "그녀는 그 분야의 선도적인 전문가로 자리를 확립했다." },
  '2_8':  { example2: "Students should evaluate their own work regularly.", example2Kr: "학생들은 자신의 작업을 정기적으로 평가해야 한다." },
  '2_9':  { example2: "The company expanded its product line to attract new customers.", example2Kr: "회사는 새 고객을 유치하기 위해 제품 라인을 확장했다." },
  '2_10': { example2: "Children love to explore new places.", example2Kr: "아이들은 새로운 장소를 탐험하는 것을 좋아한다." },
  '2_11': { example2: "Art is a way to express ideas beyond words.", example2Kr: "예술은 말을 넘어 생각을 표현하는 방법이다." },
  '2_12': { example2: "The report focuses on environmental issues.", example2Kr: "그 보고서는 환경 문제에 초점을 맞추고 있다." },
  '2_13': { example2: "The new policy generated a lot of debate.", example2Kr: "새 정책은 많은 토론을 불러일으켰다." },
  '2_14': { example2: "Police identified the suspect through CCTV footage.", example2Kr: "경찰은 CCTV 영상을 통해 용의자를 확인했다." },
  '2_15': { example2: "It's not easy to implement change in large organizations.", example2Kr: "대형 조직에서 변화를 실행하는 것은 쉽지 않다." },
  '2_16': { example2: "The city has improved its public transportation system.", example2Kr: "그 도시는 대중교통 시스템을 개선했다." },
  '2_17': { example2: "His expression indicated that he was unhappy.", example2Kr: "그의 표정이 그가 기분이 좋지 않음을 나타냈다." },
  '2_18': { example2: "Parenting style influences a child's development.", example2Kr: "양육 방식은 아이의 발달에 영향을 미친다." },
  '2_19': { example2: "The rescue operation involved hundreds of volunteers.", example2Kr: "구조 작전에는 수백 명의 자원봉사자가 참여했다." },

  // ── Day 3 핵심 형용사 I ──
  '3_0':  { example2: "Her thesis was too abstract to be easily understood.", example2Kr: "그녀의 논문은 너무 추상적이어서 이해하기 어려웠다." },
  '3_1':  { example2: "It's important to keep accurate records.", example2Kr: "정확한 기록을 유지하는 것이 중요하다." },
  '3_2':  { example2: "The facilities were adequate but not exceptional.", example2Kr: "시설은 충분하지만 특별하지는 않았다." },
  '3_3':  { example2: "A dog may become aggressive if it feels threatened.", example2Kr: "개는 위협을 느끼면 공격적이 될 수 있다." },
  '3_4':  { example2: "His ambitious plan impressed everyone at the meeting.", example2Kr: "그의 야심찬 계획이 회의에 참석한 모든 사람을 감동시켰다." },
  '3_5':  { example2: "She was anxious about speaking in front of a large crowd.", example2Kr: "그녀는 많은 사람들 앞에서 말하는 것에 대해 불안했다." },
  '3_6':  { example2: "It's not appropriate to use your phone during class.", example2Kr: "수업 중에 휴대폰을 사용하는 것은 적절하지 않다." },
  '3_7':  { example2: "There are still a few tickets available for tonight's show.", example2Kr: "오늘 밤 공연의 표가 아직 몇 장 남아 있다." },
  '3_8':  { example2: "Reading is beneficial for improving vocabulary.", example2Kr: "독서는 어휘력 향상에 이롭다." },
  '3_9':  { example2: "The team is capable of achieving great results.", example2Kr: "그 팀은 훌륭한 결과를 달성할 능력이 있다." },
  '3_10': { example2: "There are certain rules you must follow.", example2Kr: "반드시 따라야 하는 특정 규칙들이 있다." },
  '3_11': { example2: "He wrote a comprehensive guide to healthy eating.", example2Kr: "그는 건강한 식습관에 관한 종합적인 가이드를 썼다." },
  '3_12': { example2: "She is very conscious of her posture while working.", example2Kr: "그녀는 일하는 동안 자신의 자세를 매우 의식한다." },
  '3_13': { example2: "A consistent sleep schedule improves overall health.", example2Kr: "일관된 수면 일정은 전반적인 건강을 향상시킨다." },
  '3_14': { example2: "It's very convenient to live near a subway station.", example2Kr: "지하철역 근처에 사는 것은 매우 편리하다." },
  '3_15': { example2: "The children surprised everyone with their creative artwork.", example2Kr: "아이들은 창의적인 작품으로 모든 사람을 놀라게 했다." },
  '3_16': { example2: "Water is critical to the survival of all living things.", example2Kr: "물은 모든 생물의 생존에 매우 중요하다." },
  '3_17': { example2: "The curious student asked many thoughtful questions.", example2Kr: "호기심 많은 학생이 많은 사려 깊은 질문을 했다." },
  '3_18': { example2: "He is dedicated to making a positive difference in the community.", example2Kr: "그는 지역 사회에 긍정적인 변화를 만들기 위해 전념하고 있다." },
  '3_19': { example2: "Our team has diverse skills and backgrounds.", example2Kr: "우리 팀은 다양한 기술과 배경을 가지고 있다." },

  // ── Day 4 핵심 형용사 II ──
  '4_0':  { example2: "The new CEO brought a dynamic energy to the company.", example2Kr: "새 CEO는 회사에 역동적인 에너지를 가져왔다." },
  '4_1':  { example2: "She found a more efficient way to complete the task.", example2Kr: "그녀는 그 과제를 완수하는 더 효율적인 방법을 찾았다." },
  '4_2':  { example2: "Good communication skills are essential in any career.", example2Kr: "좋은 의사소통 기술은 어떤 직업에서도 필수적이다." },
  '4_3':  { example2: "The effects of stress were evident on his face.", example2Kr: "스트레스의 영향이 그의 얼굴에 분명히 나타났다." },
  '4_4':  { example2: "Only members have exclusive access to the lounge.", example2Kr: "회원만이 라운지에 독점적으로 접근할 수 있다." },
  '4_5':  { example2: "A flexible schedule allows employees to maintain work-life balance.", example2Kr: "유연한 일정은 직원들이 일과 삶의 균형을 유지할 수 있게 한다." },
  '4_6':  { example2: "Honesty is fundamental to any lasting friendship.", example2Kr: "정직은 지속되는 모든 우정의 근본이다." },
  '4_7':  { example2: "She showed genuine interest in learning about other cultures.", example2Kr: "그녀는 다른 문화에 대해 배우는 데 진정한 관심을 보였다." },
  '4_8':  { example2: "Social media has made communication a global phenomenon.", example2Kr: "소셜 미디어는 의사소통을 세계적인 현상으로 만들었다." },
  '4_9':  { example2: "The gradual rise in temperature is a sign of climate change.", example2Kr: "온도의 점진적인 상승은 기후 변화의 신호이다." },
  '4_10': { example2: "The mountains are the ideal place for a peaceful retreat.", example2Kr: "산은 평화로운 휴식을 위한 이상적인 장소이다." },
  '4_11': { example2: "The government took immediate action to control the spread of disease.", example2Kr: "정부는 질병 확산을 막기 위해 즉각적인 조치를 취했다." },
  '4_12': { example2: "The report was conducted by an independent research team.", example2Kr: "그 보고서는 독립적인 연구팀에 의해 수행되었다." },
  '4_13': { example2: "Conflict is an inevitable part of working in teams.", example2Kr: "갈등은 팀에서 일하는 불가피한 부분이다." },
  '4_14': { example2: "Innovative thinking can solve problems others think are impossible.", example2Kr: "혁신적인 사고는 다른 사람들이 불가능하다고 생각하는 문제를 해결할 수 있다." },
  '4_15': { example2: "The intense heat made it difficult to work outside.", example2Kr: "강렬한 더위로 인해 밖에서 일하기가 어려웠다." },
  '4_16': { example2: "The most logical solution is to cut unnecessary expenses.", example2Kr: "가장 논리적인 해결책은 불필요한 지출을 줄이는 것이다." },
  '4_17': { example2: "Motivated employees tend to be more productive.", example2Kr: "의욕 있는 직원들은 더 생산적인 경향이 있다." },
  '4_18': { example2: "Switzerland is known for its neutral foreign policy.", example2Kr: "스위스는 중립적인 외교 정책으로 알려져 있다." },
  '4_19': { example2: "It was obvious from her tone that she was disappointed.", example2Kr: "그녀의 어조에서 실망했다는 것이 분명했다." },

  // ── Day 5 핵심 명사 I ──
  '5_0':  { example2: "Learning to speak another language is a remarkable achievement.", example2Kr: "다른 언어를 말하는 것을 배우는 것은 놀라운 성취이다." },
  '5_1':  { example2: "Starting early gives you a significant advantage.", example2Kr: "일찍 시작하는 것은 상당한 이점을 준다." },
  '5_2':  { example2: "The teacher used a hands-on approach to teaching science.", example2Kr: "선생님은 과학 수업에 실습 접근법을 사용했다." },
  '5_3':  { example2: "Time management is an important aspect of productivity.", example2Kr: "시간 관리는 생산성의 중요한 측면이다." },
  '5_4':  { example2: "There was a tense atmosphere in the meeting room.", example2Kr: "회의실에 긴장된 분위기가 감돌았다." },
  '5_5':  { example2: "His attitude toward learning improved after the workshop.", example2Kr: "그의 학습에 대한 태도는 워크숍 후에 개선되었다." },
  '5_6':  { example2: "The police have the authority to enforce the law.", example2Kr: "경찰은 법을 집행할 권한이 있다." },
  '5_7':  { example2: "The teacher addressed the disruptive behavior immediately.", example2Kr: "선생님은 방해가 되는 행동을 즉시 처리했다." },
  '5_8':  { example2: "One benefit of remote work is the ability to set your own schedule.", example2Kr: "재택근무의 한 가지 혜택은 자신만의 일정을 정할 수 있다는 것이다." },
  '5_9':  { example2: "He decided to change his career from finance to education.", example2Kr: "그는 금융에서 교육으로 직업을 바꾸기로 결정했다." },
  '5_10': { example2: "The investigation revealed unusual circumstances surrounding the incident.", example2Kr: "조사를 통해 사건 주변의 특이한 상황이 밝혀졌다." },
  '5_11': { example2: "Nonverbal communication can be just as powerful as words.", example2Kr: "비언어적 의사소통은 말만큼 강력할 수 있다." },
  '5_12': { example2: "Local businesses play a vital role in the community.", example2Kr: "지역 사업체는 지역 사회에서 중요한 역할을 한다." },
  '5_13': { example2: "Healthy competition motivates people to do their best.", example2Kr: "건전한 경쟁은 사람들이 최선을 다하도록 동기를 부여한다." },
  '5_14': { example2: "She explained the concept clearly with simple examples.", example2Kr: "그녀는 간단한 예시로 개념을 명확하게 설명했다." },
  '5_15': { example2: "Workers demanded better pay and working conditions.", example2Kr: "근로자들은 더 나은 급여와 근무 조건을 요구했다." },
  '5_16': { example2: "A good mentor helps you build confidence in your abilities.", example2Kr: "좋은 멘토는 자신의 능력에 대한 자신감을 키우는 데 도움이 된다." },
  '5_17': { example2: "Learning to manage conflict is an essential life skill.", example2Kr: "갈등을 관리하는 법을 배우는 것은 필수적인 생활 기술이다." },
  '5_18': { example2: "Climate change has serious consequences for the planet.", example2Kr: "기후 변화는 지구에 심각한 결과를 초래한다." },
  '5_19': { example2: "It's essential to consider the historical context of events.", example2Kr: "사건의 역사적 맥락을 고려하는 것이 필수적이다." },

  // ── Day 6 핵심 명사 II ──
  '6_0':  { example2: "Volunteering is a meaningful contribution to society.", example2Kr: "자원봉사는 사회에 의미 있는 기여이다." },
  '6_1':  { example2: "The film sparked controversy over its historical accuracy.", example2Kr: "그 영화는 역사적 정확성에 대한 논란을 불러일으켰다." },
  '6_2':  { example2: "Boredom can sometimes spark creativity.", example2Kr: "지루함이 때로는 창의력을 자극할 수 있다." },
  '6_3':  { example2: "Food is an important part of Korean culture.", example2Kr: "음식은 한국 문화의 중요한 부분이다." },
  '6_4':  { example2: "It was a difficult decision, but she chose to move abroad.", example2Kr: "어려운 결정이었지만 그녀는 해외로 이사하기로 선택했다." },
  '6_5':  { example2: "The demand for electric vehicles is increasing rapidly.", example2Kr: "전기 자동차에 대한 수요가 빠르게 증가하고 있다." },
  '6_6':  { example2: "Sustainable development balances economic growth with environmental care.", example2Kr: "지속 가능한 발전은 경제 성장과 환경 보호의 균형을 맞춘다." },
  '6_7':  { example2: "The school celebrates diversity through cultural events.", example2Kr: "학교는 문화 행사를 통해 다양성을 축하한다." },
  '6_8':  { example2: "A growing economy creates more job opportunities.", example2Kr: "성장하는 경제는 더 많은 일자리 기회를 창출한다." },
  '6_9':  { example2: "The importance of early childhood education cannot be overstated.", example2Kr: "유아 교육의 중요성은 아무리 강조해도 지나치지 않다." },
  '6_10': { example2: "A clean environment is essential for physical and mental health.", example2Kr: "깨끗한 환경은 신체적·정신적 건강에 필수적이다." },
  '6_11': { example2: "Archaeologists found evidence of an ancient civilization.", example2Kr: "고고학자들은 고대 문명의 증거를 발견했다." },
  '6_12': { example2: "Traveling gives you experience no classroom can provide.", example2Kr: "여행은 어떤 교실도 제공할 수 없는 경험을 준다." },
  '6_13': { example2: "Location is a major factor when choosing a school.", example2Kr: "위치는 학교를 선택할 때 주요한 요인이다." },
  '6_14': { example2: "Many successful entrepreneurs experienced failure before succeeding.", example2Kr: "많은 성공한 기업가들은 성공하기 전에 실패를 경험했다." },
  '6_15': { example2: "The new car model features an advanced safety system.", example2Kr: "새 자동차 모델은 고급 안전 시스템을 특징으로 한다." },
  '6_16': { example2: "Early childhood experiences form the foundation of personality.", example2Kr: "유아기의 경험이 개성의 토대를 형성한다." },
  '6_17': { example2: "He fought for the freedom to choose his own path.", example2Kr: "그는 자신만의 길을 선택할 자유를 위해 싸웠다." },
  '6_18': { example2: "Sleep has the vital function of restoring the body.", example2Kr: "수면은 신체를 회복시키는 중요한 기능을 한다." },
  '6_19': { example2: "She set a goal to read 12 books this year.", example2Kr: "그녀는 올해 12권의 책을 읽겠다는 목표를 세웠다." },

  // ── Day 7 일상생활 표현 I ──
  '7_0':  { example2: "The company acknowledged the problem and offered a refund.", example2Kr: "회사는 문제를 인정하고 환불을 제공했다." },
  '7_1':  { example2: "Study abroad is something not everyone can afford.", example2Kr: "해외 유학은 모든 사람이 여유가 있는 것은 아니다." },
  '7_2':  { example2: "We agreed to meet at the café at noon.", example2Kr: "우리는 정오에 카페에서 만나기로 합의했다." },
  '7_3':  { example2: "He called to apologize for missing the meeting.", example2Kr: "그는 회의에 불참한 것을 사과하기 위해 전화했다." },
  '7_4':  { example2: "A new message appeared on the screen.", example2Kr: "화면에 새 메시지가 나타났다." },
  '7_5':  { example2: "His mother arranged all the books neatly on the shelf.", example2Kr: "그의 어머니는 책장에 모든 책을 깔끔하게 정리했다." },
  '7_6':  { example2: "He avoided the topic whenever it came up.", example2Kr: "그 화제가 나올 때마다 그는 피했다." },
  '7_7':  { example2: "The residents complained about the construction noise.", example2Kr: "주민들은 공사 소음에 대해 불평했다." },
  '7_8':  { example2: "She uses meditation to cope with anxiety.", example2Kr: "그녀는 불안감에 대처하기 위해 명상을 사용한다." },
  '7_9':  { example2: "They decided to postpone the trip due to bad weather.", example2Kr: "그들은 나쁜 날씨로 인해 여행을 연기하기로 결정했다." },
  '7_10': { example2: "You can't always depend on others to solve your problems.", example2Kr: "항상 다른 사람들이 네 문제를 해결해 줄 것이라고 의존할 수는 없다." },
  '7_11': { example2: "Every child deserves a safe and loving home.", example2Kr: "모든 아이는 안전하고 사랑스러운 가정을 받을 자격이 있다." },
  '7_12': { example2: "They disagreed on the best way to solve the problem.", example2Kr: "그들은 문제를 해결하는 최선의 방법에 대해 의견이 달랐다." },
  '7_13': { example2: "You can earn extra income by freelancing on weekends.", example2Kr: "주말에 프리랜서 업무를 통해 추가 수입을 벌 수 있다." },
  '7_14': { example2: "The professor expects students to submit work on time.", example2Kr: "교수는 학생들이 제때 과제를 제출하기를 기대한다." },
  '7_15': { example2: "She patiently explained the instructions step by step.", example2Kr: "그녀는 지침을 단계별로 차분하게 설명했다." },
  '7_16': { example2: "The power grid failed during the storm.", example2Kr: "폭풍 동안 전력망이 고장났다." },
  '7_17': { example2: "Children need to learn how to handle disappointment.", example2Kr: "아이들은 실망감을 처리하는 방법을 배울 필요가 있다." },
  '7_18': { example2: "She hesitated to accept the job offer without more details.", example2Kr: "그녀는 더 많은 세부 사항 없이 취업 제안을 수락하는 것을 주저했다." },
  '7_19': { example2: "He managed to finish the report despite the tight deadline.", example2Kr: "그는 촉박한 마감에도 불구하고 어떻게든 보고서를 완성했다." },

  // ── Day 8 일상생활 표현 II ──
  '8_0':  { example2: "He briefly mentioned his plans for the weekend.", example2Kr: "그는 주말 계획을 간략히 언급했다." },
  '8_1':  { example2: "I notice you've changed your hairstyle.", example2Kr: "헤어스타일을 바꾼 것을 알아챘어요." },
  '8_2':  { example2: "With persistence, you can overcome any obstacle.", example2Kr: "인내심으로 어떤 장애물도 극복할 수 있다." },
  '8_3':  { example2: "Students who participate actively tend to learn more.", example2Kr: "적극적으로 참여하는 학생들은 더 많이 배우는 경향이 있다." },
  '8_4':  { example2: "The salesperson persuaded me to buy the extended warranty.", example2Kr: "판매원이 나에게 연장 보증을 구매하도록 설득했다." },
  '8_5':  { example2: "The government provides free healthcare to all citizens.", example2Kr: "정부는 모든 시민에게 무료 의료를 제공한다." },
  '8_6':  { example2: "She realized the importance of sleep after falling ill.", example2Kr: "그녀는 병이 난 후 수면의 중요성을 깨달았다." },
  '8_7':  { example2: "The doctor recommended regular exercise for heart health.", example2Kr: "의사는 심장 건강을 위해 규칙적인 운동을 권고했다." },
  '8_8':  { example2: "He refused the offer because the salary was too low.", example2Kr: "그는 급여가 너무 낮아서 제안을 거절했다." },
  '8_9':  { example2: "This song always reminds me of my childhood.", example2Kr: "이 노래는 항상 내 어린 시절을 생각나게 한다." },
  '8_10': { example2: "Digital photos have replaced traditional film cameras.", example2Kr: "디지털 사진이 전통적인 필름 카메라를 대체했다." },
  '8_11': { example2: "Becoming a doctor requires years of dedicated study.", example2Kr: "의사가 되기 위해서는 수년간의 헌신적인 공부가 필요하다." },
  '8_12': { example2: "Students learn to respect both their teachers and peers.", example2Kr: "학생들은 교사와 동료 모두를 존중하는 것을 배운다." },
  '8_13': { example2: "The company responded to customer complaints within 24 hours.", example2Kr: "회사는 24시간 이내에 고객 불만에 응답했다." },
  '8_14': { example2: "She shared her personal story to inspire others.", example2Kr: "그녀는 다른 사람들에게 영감을 주기 위해 자신의 개인 이야기를 나눴다." },
  '8_15': { example2: "Teamwork is often the best way to solve complex problems.", example2Kr: "팀워크는 복잡한 문제를 해결하는 가장 좋은 방법인 경우가 많다." },
  '8_16': { example2: "She succeeded in passing the difficult certification exam.", example2Kr: "그녀는 어려운 자격증 시험을 통과하는 데 성공했다." },
  '8_17': { example2: "The HR manager suggested hiring more part-time staff.", example2Kr: "인사 매니저는 더 많은 파트타임 직원을 채용할 것을 제안했다." },
  '8_18': { example2: "Never share your password with someone you don't trust.", example2Kr: "신뢰하지 않는 사람과 비밀번호를 공유하지 마라." },
  '8_19': { example2: "I often wonder about the meaning of life.", example2Kr: "나는 종종 삶의 의미에 대해 궁금해한다." },

  // ── Day 9 학문 & 직업 어휘 ──
  '9_0':  { example2: "Please submit a 200-word abstract with your research paper.", example2Kr: "연구 논문과 함께 200단어 요약을 제출해 주세요." },
  '9_1':  { example2: "He decided to pursue an academic career rather than work in industry.", example2Kr: "그는 산업 분야보다 학문적 경력을 쌓기로 결정했다." },
  '9_2':  { example2: "The company acquired three smaller businesses last year.", example2Kr: "회사는 작년에 세 곳의 소규모 기업을 인수했다." },
  '9_3':  { example2: "The new hospital administration introduced stricter visiting hours.", example2Kr: "새 병원 행정부는 더 엄격한 면회 시간을 도입했다." },
  '9_4':  { example2: "He spent hours preparing his university application.", example2Kr: "그는 대학 지원서를 준비하는 데 몇 시간을 보냈다." },
  '9_5':  { example2: "The group assignment required collaboration among all members.", example2Kr: "그룹 과제는 모든 구성원 간의 협력이 필요했다." },
  '9_6':  { example2: "The interview panel selected the most qualified candidate.", example2Kr: "면접 위원회는 가장 자격을 갖춘 지원자를 선발했다." },
  '9_7':  { example2: "She received a certificate of completion at the workshop.", example2Kr: "그녀는 워크숍에서 수료증을 받았다." },
  '9_8':  { example2: "I had lunch with my colleagues to celebrate a project success.", example2Kr: "나는 프로젝트 성공을 축하하기 위해 동료들과 점심을 먹었다." },
  '9_9':  { example2: "The curriculum was revised to include more practical skills.", example2Kr: "교육과정이 더 많은 실용적인 기술을 포함하도록 개정되었다." },
  '9_10': { example2: "She stayed up all night to meet the assignment deadline.", example2Kr: "그녀는 과제 마감을 지키기 위해 밤새 공부했다." },
  '9_11': { example2: "He earned his master's degree in two years.", example2Kr: "그는 2년 만에 석사 학위를 취득했다." },
  '9_12': { example2: "The marketing department launched a new campaign.", example2Kr: "마케팅 부서가 새 캠페인을 시작했다." },
  '9_13': { example2: "The executive team approved the annual budget.", example2Kr: "임원진이 연간 예산을 승인했다." },
  '9_14': { example2: "The project required expertise in both design and engineering.", example2Kr: "그 프로젝트는 디자인과 공학 양쪽의 전문성이 필요했다." },
  '9_15': { example2: "She graduated with honors from a top university.", example2Kr: "그녀는 최우수 성적으로 명문 대학을 졸업했다." },
  '9_16': { example2: "She applied for a summer internship at a publishing company.", example2Kr: "그녀는 출판사에서 여름 인턴십에 지원했다." },
  '9_17': { example2: "He practiced his presentation in front of the mirror.", example2Kr: "그는 거울 앞에서 발표 연습을 했다." },
  '9_18': { example2: "You need the right qualifications to apply for this position.", example2Kr: "이 직위에 지원하려면 적합한 자격이 필요하다." },
  '9_19': { example2: "The professor hosted a weekly seminar for graduate students.", example2Kr: "교수는 대학원생을 위한 주간 세미나를 주최했다." },

  // ── Day 10 사회 & 시사 어휘 ──
  '10_0':  { example2: "His advocacy for environmental protection earned international recognition.", example2Kr: "환경 보호를 위한 그의 옹호 활동은 국제적인 인정을 받았다." },
  '10_1':  { example2: "Journalists should report news without political bias.", example2Kr: "기자들은 정치적 편견 없이 뉴스를 보도해야 한다." },
  '10_2':  { example2: "As a responsible citizen, you should vote in elections.", example2Kr: "책임 있는 시민으로서 선거에서 투표해야 한다." },
  '10_3':  { example2: "Corruption in the justice system is a serious problem.", example2Kr: "사법 시스템의 부패는 심각한 문제이다." },
  '10_4':  { example2: "A healthy democracy requires free and fair elections.", example2Kr: "건강한 민주주의는 자유롭고 공정한 선거를 필요로 한다." },
  '10_5':  { example2: "Laws exist to protect people from racial discrimination.", example2Kr: "인종 차별로부터 사람들을 보호하기 위한 법률이 있다." },
  '10_6':  { example2: "The movement fought for equality in the workplace.", example2Kr: "그 운동은 직장 내 평등을 위해 싸웠다." },
  '10_7':  { example2: "Globalization has made it easier to trade across borders.", example2Kr: "세계화로 인해 국경을 넘는 무역이 더 쉬워졌다." },
  '10_8':  { example2: "The country introduced new policies to control immigration.", example2Kr: "그 나라는 이민을 통제하기 위한 새 정책을 도입했다." },
  '10_9':  { example2: "Access to quality education is affected by economic inequality.", example2Kr: "양질의 교육에 대한 접근성은 경제적 불평등에 영향을 받는다." },
  '10_10': { example2: "Good infrastructure attracts foreign investment.", example2Kr: "좋은 사회 기반 시설은 외국인 투자를 유치한다." },
  '10_11': { example2: "New environmental legislation limits industrial pollution.", example2Kr: "새로운 환경 법률이 산업 오염을 제한한다." },
  '10_12': { example2: "Social media has changed the way we receive news.", example2Kr: "소셜 미디어는 우리가 뉴스를 받는 방식을 바꾸었다." },
  '10_13': { example2: "Government policy plays a key role in shaping society.", example2Kr: "정부 정책은 사회를 형성하는 데 핵심적인 역할을 한다." },
  '10_14': { example2: "Global efforts to end poverty have made significant progress.", example2Kr: "빈곤을 없애기 위한 세계적인 노력이 상당한 진전을 이루었다." },
  '10_15': { example2: "Overcoming prejudice requires education and open-mindedness.", example2Kr: "편견을 극복하기 위해서는 교육과 열린 마음이 필요하다." },
  '10_16': { example2: "Workers organized a protest against the unfair layoffs.", example2Kr: "근로자들은 부당한 해고에 반대하는 시위를 조직했다." },
  '10_17': { example2: "Tax reform is essential to address economic inequality.", example2Kr: "세금 개혁은 경제적 불평등을 해결하기 위해 필수적이다." },
  '10_18': { example2: "Companies are increasingly adopting sustainability practices.", example2Kr: "기업들은 점점 더 지속 가능성 관행을 채택하고 있다." },
  '10_19': { example2: "Child welfare organizations provide support to vulnerable families.", example2Kr: "아동 복지 기관은 취약한 가정에 지원을 제공한다." },

  // ── Day 11 감정 & 심리 표현 ──
  '11_0':  { example2: "Anxiety disorders are among the most common mental health issues.", example2Kr: "불안 장애는 가장 흔한 정신 건강 문제 중 하나이다." },
  '11_1':  { example2: "Many people with depression find it hard to get out of bed.", example2Kr: "우울증을 앓는 많은 사람들은 침대에서 일어나기 힘들다고 느낀다." },
  '11_2':  { example2: "Empathy allows us to understand others' pain and joy.", example2Kr: "공감 능력은 타인의 고통과 기쁨을 이해하게 해준다." },
  '11_3':  { example2: "Her frustration grew as she couldn't find the answer.", example2Kr: "답을 찾지 못하자 그녀의 좌절감이 커졌다." },
  '11_4':  { example2: "Keeping a gratitude journal improves your overall happiness.", example2Kr: "감사 일기를 쓰는 것은 전반적인 행복감을 높여준다." },
  '11_5':  { example2: "The grief counselor helped the family cope with their loss.", example2Kr: "슬픔 상담사가 가족이 상실을 극복하도록 도왔다." },
  '11_6':  { example2: "Guilt over past mistakes can prevent people from moving forward.", example2Kr: "과거 실수에 대한 죄책감은 사람들이 앞으로 나아가는 것을 방해할 수 있다." },
  '11_7':  { example2: "She tried not to let jealousy affect her friendship.", example2Kr: "그녀는 질투가 우정에 영향을 미치지 않도록 노력했다." },
  '11_8':  { example2: "Technology can sometimes increase feelings of loneliness.", example2Kr: "기술은 때때로 외로움을 증가시킬 수 있다." },
  '11_9':  { example2: "The rainy autumn weather filled her with melancholy.", example2Kr: "비 오는 가을 날씨가 그녀를 우울하게 만들었다." },
  '11_10': { example2: "Optimism doesn't mean ignoring problems, but facing them positively.", example2Kr: "낙관주의는 문제를 무시하는 것이 아니라 긍정적으로 직면하는 것이다." },
  '11_11': { example2: "A panic attack can cause shortness of breath and dizziness.", example2Kr: "공황 발작은 호흡 곤란과 어지러움을 유발할 수 있다." },
  '11_12': { example2: "His passion for teaching inspired many of his students.", example2Kr: "교육에 대한 그의 열정은 많은 학생들에게 영감을 주었다." },
  '11_13': { example2: "Parents feel immense pride when their children succeed.", example2Kr: "부모는 자녀가 성공할 때 엄청난 자부심을 느낀다." },
  '11_14': { example2: "I regret not studying harder during my school years.", example2Kr: "나는 학창 시절에 더 열심히 공부하지 않은 것을 후회한다." },
  '11_15': { example2: "Years of resentment built up between the two brothers.", example2Kr: "두 형제 사이에 수년간 원망이 쌓였다." },
  '11_16': { example2: "The public shame of failing in front of everyone was hard to bear.", example2Kr: "모든 사람 앞에서 실패하는 공개적인 창피함은 견디기 힘들었다." },
  '11_17': { example2: "She couldn't hide the sorrow in her eyes.", example2Kr: "그녀는 눈의 슬픔을 숨길 수 없었다." },
  '11_18': { example2: "The community showed sympathy by donating to the victims.", example2Kr: "지역 사회는 피해자들에게 기부함으로써 동정심을 보였다." },
  '11_19': { example2: "Childhood trauma can have lasting effects on adult behavior.", example2Kr: "어린 시절의 트라우마는 성인의 행동에 지속적인 영향을 미칠 수 있다." },

  // ── Day 12 여행 & 교통 ──
  '12_0':  { example2: "The hotel couldn't provide accommodation for all the guests.", example2Kr: "호텔은 모든 손님을 위한 숙소를 제공할 수 없었다." },
  '12_1':  { example2: "Excess baggage fees at the airport can be very expensive.", example2Kr: "공항에서의 초과 수하물 요금은 매우 비쌀 수 있다." },
  '12_2':  { example2: "She found it exhausting to commute by train every day.", example2Kr: "그녀는 매일 기차로 통근하는 것이 지치는 일임을 알게 되었다." },
  '12_3':  { example2: "Some goods are prohibited from being brought through customs.", example2Kr: "일부 물품은 세관을 통해 반입이 금지되어 있다." },
  '12_4':  { example2: "Flight departure was delayed due to bad weather conditions.", example2Kr: "악천후로 인해 비행기 출발이 지연되었다." },
  '12_5':  { example2: "Their final destination was a small village in the mountains.", example2Kr: "그들의 최종 목적지는 산속의 작은 마을이었다." },
  '12_6':  { example2: "The detour added an extra 30 minutes to our journey.", example2Kr: "우회로로 인해 여행 시간이 30분 더 늘어났다." },
  '12_7':  { example2: "She dreamed of joining a scientific expedition to Antarctica.", example2Kr: "그녀는 남극 탐험에 참여하는 것을 꿈꿨다." },
  '12_8':  { example2: "The bus fare is free for children under five.", example2Kr: "버스 요금은 5세 미만 어린이에게 무료이다." },
  '12_9':  { example2: "The travel agency prepared a detailed itinerary for the group.", example2Kr: "여행사는 그룹을 위한 세부 일정을 준비했다." },
  '12_10': { example2: "She used the layover time to explore the transit city.", example2Kr: "그녀는 경유 시간을 이용해 환승 도시를 둘러봤다." },
  '12_11': { example2: "Using a map app makes it easier to navigate unfamiliar places.", example2Kr: "지도 앱을 사용하면 낯선 곳을 더 쉽게 찾아갈 수 있다." },
  '12_12': { example2: "She lost her passport and had to go to the embassy.", example2Kr: "그녀는 여권을 잃어버려 대사관에 가야 했다." },
  '12_13': { example2: "Canceling a reservation without notice may incur a fee.", example2Kr: "예고 없이 예약을 취소하면 수수료가 발생할 수 있다." },
  '12_14': { example2: "They followed the coastal route for the beautiful ocean views.", example2Kr: "그들은 아름다운 바다 경치를 위해 해안 경로를 따라갔다." },
  '12_15': { example2: "The bus terminal was crowded with passengers during the holidays.", example2Kr: "버스 터미널은 휴일 동안 승객들로 붐볐다." },
  '12_16': { example2: "Many international travelers use Seoul as a transit hub.", example2Kr: "많은 국제 여행자들이 서울을 환승 허브로 이용한다." },
  '12_17': { example2: "The severe turbulence caused many passengers to feel sick.", example2Kr: "심한 난기류로 많은 승객들이 멀미를 했다." },
  '12_18': { example2: "He applied for a tourist visa to visit Japan.", example2Kr: "그는 일본을 방문하기 위해 관광 비자를 신청했다." },
  '12_19': { example2: "The voyage across the Pacific took nearly three weeks.", example2Kr: "태평양을 가로지르는 항해는 거의 3주가 걸렸다." },

  // ── Day 13 음식 & 건강 ──
  '13_0':  { example2: "Stress can suppress your appetite and lead to weight loss.", example2Kr: "스트레스는 식욕을 억제하고 체중 감소로 이어질 수 있다." },
  '13_1':  { example2: "Athletes carefully track their daily calorie intake.", example2Kr: "운동선수들은 하루 칼로리 섭취량을 꼼꼼히 추적한다." },
  '13_2':  { example2: "Eating less saturated fat helps lower your cholesterol levels.", example2Kr: "포화 지방 섭취를 줄이면 콜레스테롤 수치를 낮추는 데 도움이 된다." },
  '13_3':  { example2: "She took a culinary course to master French cuisine.", example2Kr: "그녀는 프랑스 요리를 마스터하기 위해 요리 과정을 수강했다." },
  '13_4':  { example2: "Vitamin D deficiency is common in countries with little sunshine.", example2Kr: "비타민 D 결핍은 햇빛이 적은 나라에서 흔하다." },
  '13_5':  { example2: "Type 2 diabetes is often linked to an unhealthy lifestyle.", example2Kr: "2형 당뇨병은 종종 건강하지 않은 생활 방식과 관련이 있다." },
  '13_6':  { example2: "Drinking water after meals helps your body digest food.", example2Kr: "식사 후 물을 마시면 몸이 음식을 소화하는 데 도움이 된다." },
  '13_7':  { example2: "Public health officials are working to contain the epidemic.", example2Kr: "공중 보건 당국은 전염병을 억제하기 위해 노력하고 있다." },
  '13_8':  { example2: "A healthy diet and exercise build long-term immunity.", example2Kr: "건강한 식단과 운동은 장기적인 면역력을 키워준다." },
  '13_9':  { example2: "Always check the ingredients list before buying packaged food.", example2Kr: "포장 식품을 구입하기 전에 항상 성분 목록을 확인해라." },
  '13_10': { example2: "Aid organizations work to address malnutrition in conflict zones.", example2Kr: "구호 단체들은 분쟁 지역의 영양 결핍 문제를 해결하기 위해 노력한다." },
  '13_11': { example2: "A fast metabolism means your body burns calories more quickly.", example2Kr: "빠른 신진대사는 몸이 칼로리를 더 빨리 소모한다는 것을 의미한다." },
  '13_12': { example2: "A nutritionist can help you plan a balanced diet based on nutrition.", example2Kr: "영양사는 영양을 기반으로 균형 잡힌 식단을 계획하는 데 도움을 줄 수 있다." },
  '13_13': { example2: "Obesity increases the risk of heart disease and diabetes.", example2Kr: "비만은 심장병과 당뇨병의 위험을 높인다." },
  '13_14': { example2: "The organic farm uses no chemical pesticides or fertilizers.", example2Kr: "그 유기농 농장은 화학 농약이나 비료를 사용하지 않는다." },
  '13_15': { example2: "The pharmacy required a valid prescription before dispensing the drug.", example2Kr: "약국은 약을 조제하기 전에 유효한 처방전을 요구했다." },
  '13_16': { example2: "Beans and lentils are excellent plant-based sources of protein.", example2Kr: "콩과 렌틸콩은 훌륭한 식물성 단백질 공급원이다." },
  '13_17': { example2: "Rest remains the best remedy for most minor illnesses.", example2Kr: "휴식은 대부분의 경미한 질병에 가장 좋은 치료제이다." },
  '13_18': { example2: "Some athletes use protein supplements to recover after training.", example2Kr: "일부 운동선수들은 훈련 후 회복을 위해 단백질 보충제를 사용한다." },
  '13_19': { example2: "Early symptoms of the disease are easy to overlook.", example2Kr: "그 질병의 초기 증상은 간과하기 쉽다." },

  // ── Day 14 환경 & 자연 ──
  '14_0':  { example2: "Scientists warn that biodiversity is declining at an alarming rate.", example2Kr: "과학자들은 생물 다양성이 놀라운 속도로 감소하고 있다고 경고한다." },
  '14_1':  { example2: "Global climate patterns are shifting due to human activity.", example2Kr: "인간 활동으로 인해 전 지구적 기후 패턴이 변화하고 있다." },
  '14_2':  { example2: "Energy conservation helps reduce pollution and saves money.", example2Kr: "에너지 보전은 오염을 줄이고 비용을 절약하는 데 도움이 된다." },
  '14_3':  { example2: "Illegal logging contributes to rapid deforestation in tropical regions.", example2Kr: "불법 벌목은 열대 지역의 급속한 삼림 벌채에 기여한다." },
  '14_4':  { example2: "The drought forced many farmers to abandon their fields.", example2Kr: "가뭄은 많은 농부들이 밭을 버리도록 강요했다." },
  '14_5':  { example2: "Introducing invasive species can disrupt the local ecosystem.", example2Kr: "외래 침입종을 도입하면 지역 생태계를 교란할 수 있다." },
  '14_6':  { example2: "Carbon emission caps are set by international agreements.", example2Kr: "탄소 배출 상한선은 국제 협약으로 설정된다." },
  '14_7':  { example2: "Erosion of coastlines is accelerated by rising sea levels.", example2Kr: "해안선 침식은 해수면 상승으로 인해 빨라지고 있다." },
  '14_8':  { example2: "The dodo is one of history's most famous examples of extinction.", example2Kr: "도도새는 역사상 가장 유명한 멸종 사례 중 하나이다." },
  '14_9':  { example2: "The Nile Delta has some of the most fertile land in the world.", example2Kr: "나일강 삼각주는 세계에서 가장 비옥한 토지 중 일부를 보유하고 있다." },
  '14_10': { example2: "Scientists drill into glaciers to study past climate conditions.", example2Kr: "과학자들은 과거의 기후 조건을 연구하기 위해 빙하를 시추한다." },
  '14_11': { example2: "Urban development is destroying the habitat of many bird species.", example2Kr: "도시 개발은 많은 조류 종의 서식지를 파괴하고 있다." },
  '14_12': { example2: "Residents were evacuated before the hurricane made landfall.", example2Kr: "주민들은 허리케인이 상륙하기 전에 대피했다." },
  '14_13': { example2: "Water pollution makes rivers and lakes unsafe for swimming.", example2Kr: "수질 오염은 강과 호수를 수영하기에 안전하지 않게 만든다." },
  '14_14': { example2: "The government is investing in renewable energy infrastructure.", example2Kr: "정부는 재생 가능 에너지 인프라에 투자하고 있다." },
  '14_15': { example2: "The coral reef is home to thousands of marine species.", example2Kr: "산호초는 수천 종의 해양 생물의 서식지이다." },
  '14_16': { example2: "Sustainable agriculture protects soil quality for future generations.", example2Kr: "지속 가능한 농업은 미래 세대를 위해 토양 품질을 보호한다." },
  '14_17': { example2: "Workers were exposed to toxic chemicals without proper protection.", example2Kr: "근로자들은 적절한 보호 없이 독성 화학물질에 노출되었다." },
  '14_18': { example2: "The fire destroyed vast areas of vegetation across the hillside.", example2Kr: "화재가 산비탈 전역의 광대한 식물 지역을 파괴했다." },
  '14_19': { example2: "Protecting wildlife corridors is essential for animal migration.", example2Kr: "야생 동물 통로 보호는 동물 이동에 필수적이다." },

  // ── Day 15 기술 & 미디어 ──
  '15_0':  { example2: "The recommendation algorithm suggests content based on your history.", example2Kr: "추천 알고리즘은 시청 기록을 기반으로 콘텐츠를 추천한다." },
  '15_1':  { example2: "Artificial intelligence can now write essays and generate images.", example2Kr: "인공지능은 이제 글을 쓰고 이미지를 생성할 수 있다." },
  '15_2':  { example2: "High bandwidth is required for smooth online gaming.", example2Kr: "원활한 온라인 게임을 위해서는 높은 대역폭이 필요하다." },
  '15_3':  { example2: "The championship match was broadcast to over 50 countries.", example2Kr: "챔피언십 경기는 50개국 이상에 방송되었다." },
  '15_4':  { example2: "Good cybersecurity practices include regular password updates.", example2Kr: "좋은 사이버 보안 관행에는 정기적인 비밀번호 업데이트가 포함된다." },
  '15_5':  { example2: "The research database contains millions of academic papers.", example2Kr: "연구 데이터베이스에는 수백만 건의 학술 논문이 포함되어 있다." },
  '15_6':  { example2: "Digital literacy is now considered an essential life skill.", example2Kr: "디지털 리터러시는 이제 필수적인 생활 기술로 여겨진다." },
  '15_7':  { example2: "End-to-end encryption ensures private communications stay secure.", example2Kr: "종단간 암호화는 개인 통신이 안전하게 유지되도록 보장한다." },
  '15_8':  { example2: "Continuous innovation keeps technology companies competitive.", example2Kr: "지속적인 혁신은 기술 기업들이 경쟁력을 유지하게 한다." },
  '15_9':  { example2: "A well-designed interface improves user experience significantly.", example2Kr: "잘 설계된 인터페이스는 사용자 경험을 크게 향상시킨다." },
  '15_10': { example2: "Antivirus software helps detect and remove malware from your device.", example2Kr: "바이러스 백신 소프트웨어는 기기에서 악성 코드를 탐지하고 제거하는 데 도움을 준다." },
  '15_11': { example2: "The museum created a multimedia exhibit to attract younger visitors.", example2Kr: "박물관은 젊은 방문객을 유치하기 위해 멀티미디어 전시물을 만들었다." },
  '15_12': { example2: "A reliable network is essential for remote workers and students.", example2Kr: "신뢰할 수 있는 네트워크는 원격 근무자와 학생들에게 필수적이다." },
  '15_13': { example2: "New content creators are building audiences on emerging platforms.", example2Kr: "새로운 콘텐츠 크리에이터들이 새로운 플랫폼에서 시청자를 확보하고 있다." },
  '15_14': { example2: "Social media companies face pressure to better protect user privacy.", example2Kr: "소셜 미디어 기업들은 사용자 개인 정보를 더 잘 보호하라는 압력을 받고 있다." },
  '15_15': { example2: "The prototype was tested thoroughly before mass production began.", example2Kr: "대량 생산이 시작되기 전에 시제품이 철저히 테스트되었다." },
  '15_16': { example2: "Open-source software allows developers to freely modify the code.", example2Kr: "오픈소스 소프트웨어는 개발자가 코드를 자유롭게 수정할 수 있게 한다." },
  '15_17': { example2: "Music streaming has largely replaced physical CD sales.", example2Kr: "음악 스트리밍은 물리적 CD 판매를 상당 부분 대체했다." },
  '15_18': { example2: "Virtual meetings have become the norm in many international companies.", example2Kr: "가상 회의는 많은 국제 기업에서 일상적인 것이 되었다." },
  '15_19': { example2: "Wireless charging technology is becoming standard in new smartphones.", example2Kr: "무선 충전 기술은 신형 스마트폰의 표준이 되어가고 있다." },

  // ── Day 16 비즈니스 표현 ──
  '16_0':  { example2: "The agenda for today's meeting has been sent to all staff.", example2Kr: "오늘 회의 의제가 모든 직원에게 발송되었다." },
  '16_1':  { example2: "They cut the budget by 15% to reduce operating costs.", example2Kr: "그들은 운영 비용을 줄이기 위해 예산을 15% 삭감했다." },
  '16_2':  { example2: "The two universities collaborated on cutting-edge cancer research.", example2Kr: "두 대학은 최첨단 암 연구에 공동으로 참여했다." },
  '16_3':  { example2: "He read the contract carefully before putting his signature on it.", example2Kr: "그는 서명하기 전에 계약서를 꼼꼼히 읽었다." },
  '16_4':  { example2: "The team worked through the night to meet the deadline.", example2Kr: "팀은 마감 기한을 맞추기 위해 밤새 작업했다." },
  '16_5':  { example2: "She delegated most of the administrative work to her assistant.", example2Kr: "그녀는 대부분의 행정 업무를 보조자에게 위임했다." },
  '16_6':  { example2: "Performance-based incentives motivate employees to work harder.", example2Kr: "성과 기반 인센티브는 직원들이 더 열심히 일하도록 동기를 부여한다." },
  '16_7':  { example2: "The invoice showed a total amount due of five hundred dollars.", example2Kr: "청구서에는 총 500달러의 지불 금액이 표시되어 있었다." },
  '16_8':  { example2: "The merger resulted in thousands of job losses across both companies.", example2Kr: "합병으로 두 회사에 걸쳐 수천 명의 일자리가 사라졌다." },
  '16_9':  { example2: "They negotiated a deal that satisfied both parties.", example2Kr: "그들은 양측이 만족하는 거래를 협상해 냈다." },
  '16_10': { example2: "The objective of the campaign was to raise brand awareness.", example2Kr: "캠페인의 목표는 브랜드 인지도를 높이는 것이었다." },
  '16_11': { example2: "Outsourcing customer service can save significant costs.", example2Kr: "고객 서비스를 아웃소싱하면 상당한 비용을 절감할 수 있다." },
  '16_12': { example2: "The startup's pitch convinced investors to fund the project.", example2Kr: "스타트업의 제안 발표가 투자자들의 투자 결정을 이끌어냈다." },
  '16_13': { example2: "Quarterly profit figures showed strong growth for the company.", example2Kr: "분기별 이익 수치는 회사의 강한 성장을 보여줬다." },
  '16_14': { example2: "The company's revenue doubled following the product launch.", example2Kr: "제품 출시 이후 회사의 수익이 두 배가 되었다." },
  '16_15': { example2: "Stakeholder feedback shaped the direction of the new policy.", example2Kr: "이해관계자 피드백이 새 정책의 방향을 형성했다." },
  '16_16': { example2: "The long-term strategy focuses on expanding into Asian markets.", example2Kr: "장기 전략은 아시아 시장 진출에 초점을 맞추고 있다." },
  '16_17': { example2: "Every transaction is encrypted to prevent unauthorized access.", example2Kr: "모든 거래는 무단 접근을 막기 위해 암호화된다." },
  '16_18': { example2: "The transparent pricing policy built customer trust.", example2Kr: "투명한 가격 정책이 고객의 신뢰를 쌓았다." },
  '16_19': { example2: "High turnover in sales teams often leads to revenue drops.", example2Kr: "영업팀의 높은 이직률은 종종 매출 감소로 이어진다." },

  // ── Day 17 학교 & 교육 ──
  '17_0':  { example2: "Low attendance often leads to poor academic performance.", example2Kr: "낮은 출석률은 종종 부진한 학업 성취로 이어진다." },
  '17_1':  { example2: "She struggled with reading comprehension in her second language.", example2Kr: "그녀는 제2외국어 독해에 어려움을 겪었다." },
  '17_2':  { example2: "Voting in national elections is compulsory in some countries.", example2Kr: "일부 국가에서는 국가 선거 투표가 의무이다." },
  '17_3':  { example2: "Her dissertation explored the effects of social media on teenagers.", example2Kr: "그녀의 논문은 청소년에 대한 소셜 미디어의 영향을 탐구했다." },
  '17_4':  { example2: "Online enrollment systems have simplified the registration process.", example2Kr: "온라인 등록 시스템이 등록 절차를 간소화했다." },
  '17_5':  { example2: "She joined the chess club as an extracurricular activity.", example2Kr: "그녀는 과외 활동으로 체스 클럽에 가입했다." },
  '17_6':  { example2: "The engineering faculty hosted an international research conference.", example2Kr: "공과대학 교수진이 국제 연구 컨퍼런스를 주최했다." },
  '17_7':  { example2: "Her fluency in Japanese helped her land a job in Tokyo.", example2Kr: "일본어 유창함이 그녀가 도쿄에서 직업을 얻는 데 도움이 되었다." },
  '17_8':  { example2: "The hypothesis was supported by the evidence gathered in the study.", example2Kr: "가설은 연구에서 수집된 증거에 의해 뒷받침되었다." },
  '17_9':  { example2: "Programs aimed at improving adult literacy have shown positive results.", example2Kr: "성인 문해율 향상을 목표로 한 프로그램들이 긍정적인 결과를 보이고 있다." },
  '17_10': { example2: "It is mandatory to wear helmets when riding a motorcycle.", example2Kr: "오토바이를 탈 때는 헬멧 착용이 의무이다." },
  '17_11': { example2: "The program pairs experienced professionals as mentors with junior workers.", example2Kr: "그 프로그램은 경험 많은 전문가를 멘토로 신입 직원과 짝지어 준다." },
  '17_12': { example2: "Her peers nominated her for the student government president position.", example2Kr: "그녀의 동료들이 그녀를 학생회장 후보로 추천했다." },
  '17_13': { example2: "You must complete Introduction to Statistics as a prerequisite.", example2Kr: "선수 과목으로 통계학 개론을 반드시 이수해야 한다." },
  '17_14': { example2: "He spent an hour proofreading his cover letter before submitting.", example2Kr: "그는 지원서를 제출하기 전에 1시간 동안 교정을 봤다." },
  '17_15': { example2: "The scholarship covers all tuition fees and living expenses.", example2Kr: "그 장학금은 모든 수업료와 생활비를 포함한다." },
  '17_16': { example2: "Students should read the syllabus carefully on the first day of class.", example2Kr: "학생들은 수업 첫날 강의 계획서를 꼼꼼히 읽어야 한다." },
  '17_17': { example2: "Her thesis on renewable energy won the department's annual prize.", example2Kr: "재생 에너지에 관한 그녀의 논문이 학과 연간 상을 받았다." },
  '17_18': { example2: "The online tutorial walked users through the software step by step.", example2Kr: "온라인 튜토리얼이 사용자들에게 소프트웨어를 단계별로 안내했다." },
  '17_19': { example2: "Vocational programmes give students practical, job-ready skills.", example2Kr: "직업 훈련 과정은 학생들에게 실용적이고 즉시 활용 가능한 기술을 제공한다." },

  // ── Day 18 스포츠 & 취미 ──
  '18_0':  { example2: "She turned her amateur passion for baking into a successful business.", example2Kr: "그녀는 제빵에 대한 아마추어적 열정을 성공적인 사업으로 전환했다." },
  '18_1':  { example2: "Winning the world championship was the proudest moment of her career.", example2Kr: "세계 선수권 대회 우승은 그녀의 경력에서 가장 자랑스러운 순간이었다." },
  '18_2':  { example2: "Yoga helps coordinate the breath and body movement together.", example2Kr: "요가는 호흡과 몸의 움직임을 함께 조율하는 데 도움이 된다." },
  '18_3':  { example2: "His dedication to the sport earned him a spot on the national team.", example2Kr: "그 스포츠에 대한 헌신이 그를 국가대표팀에 합류시켰다." },
  '18_4':  { example2: "She developed incredible endurance through daily long-distance swimming.", example2Kr: "그녀는 매일 장거리 수영을 통해 놀라운 지구력을 키웠다." },
  '18_5':  { example2: "The gallery will hold an exhibition of local artists' work next month.", example2Kr: "갤러리는 다음 달 지역 예술가들의 작품 전시회를 개최할 예정이다." },
  '18_6':  { example2: "He has a fossil collection from various geological periods.", example2Kr: "그는 다양한 지질 시대의 화석 컬렉션을 보유하고 있다." },
  '18_7':  { example2: "The new gymnasium was equipped with the latest fitness machines.", example2Kr: "새 체육관에는 최신 피트니스 기기들이 구비되었다." },
  '18_8':  { example2: "The local market is full of colourful handicrafts from the region.", example2Kr: "지역 시장은 지역에서 만든 형형색색의 공예품으로 가득하다." },
  '18_9':  { example2: "He uses his leisure time wisely to pursue his love of photography.", example2Kr: "그는 여가 시간을 사진에 대한 열정을 추구하는 데 현명하게 사용한다." },
  '18_10': { example2: "She shook hands with her opponent after winning the match.", example2Kr: "그녀는 경기를 이긴 후 상대방과 악수했다." },
  '18_11': { example2: "The match was decided by a penalty shootout after extra time.", example2Kr: "그 경기는 연장전 끝에 페널티 슛아웃으로 결정되었다." },
  '18_12': { example2: "Her perseverance paid off when she finally passed the black belt test.", example2Kr: "그녀의 끈기는 마침내 검은 띠 시험을 통과했을 때 결실을 맺었다." },
  '18_13': { example2: "The beach resort offers plenty of recreation facilities for families.", example2Kr: "그 해변 리조트는 가족을 위한 다양한 레크리에이션 시설을 제공한다." },
  '18_14': { example2: "The referee's controversial decision sparked protests from the crowd.", example2Kr: "심판의 논란 있는 판정이 관중의 항의를 불러일으켰다." },
  '18_15': { example2: "The fierce rival match drew television audiences of millions.", example2Kr: "치열한 라이벌전은 수백만 명의 TV 시청자를 끌어모았다." },
  '18_16': { example2: "Thousands of spectators cheered as the runners crossed the finish line.", example2Kr: "선수들이 결승선을 통과하자 수천 명의 관중이 환호했다." },
  '18_17': { example2: "He improved his stamina significantly by cycling every morning.", example2Kr: "그는 매일 아침 자전거를 타면서 체력을 크게 향상시켰다." },
  '18_18': { example2: "The dance instructor corrected her students' technique patiently.", example2Kr: "무용 강사는 학생들의 기술을 인내심 있게 교정했다." },
  '18_19': { example2: "The tennis tournament attracts top players from over 50 countries.", example2Kr: "그 테니스 토너먼트는 50개국 이상의 정상급 선수들을 유치한다." },

  // ── Day 19 가족 & 인간관계 ──
  '19_0':  { example2: "Children thrive when they receive consistent affection and attention.", example2Kr: "아이들은 지속적인 애정과 관심을 받을 때 잘 자란다." },
  '19_1':  { example2: "The bond between twins is often described as uniquely powerful.", example2Kr: "쌍둥이 사이의 유대감은 종종 독특하게 강하다고 표현된다." },
  '19_2':  { example2: "He still cherishes the letters his grandmother sent him as a child.", example2Kr: "그는 어린 시절 할머니가 보내준 편지들을 여전히 소중히 간직하고 있다." },
  '19_3':  { example2: "Finding a compromise was difficult but necessary for their friendship.", example2Kr: "타협점을 찾는 것은 어려웠지만 그들의 우정을 위해 필요했다." },
  '19_4':  { example2: "The parents were awarded sole custody after the long court battle.", example2Kr: "부모는 긴 법적 다툼 끝에 단독 양육권을 얻었다." },
  '19_5':  { example2: "Divorce rates have been rising steadily in many developed countries.", example2Kr: "이혼율은 많은 선진국에서 꾸준히 상승하고 있다." },
  '19_6':  { example2: "Government programmes support elderly citizens living alone.", example2Kr: "정부 프로그램은 혼자 사는 노인 시민들을 지원한다." },
  '19_7':  { example2: "His extended family gathers every year for the harvest festival.", example2Kr: "그의 대가족은 매년 추수 축제에 모인다." },
  '19_8':  { example2: "Practising forgiveness can improve your mental health and relationships.", example2Kr: "용서를 실천하면 정신 건강과 인간관계가 개선될 수 있다." },
  '19_9':  { example2: "The generation gap makes it hard for parents to understand teenagers.", example2Kr: "세대 차이는 부모가 십대를 이해하기 어렵게 만든다." },
  '19_10': { example2: "Hereditary conditions like diabetes require close family monitoring.", example2Kr: "당뇨병 같은 유전적 질환은 가족의 긴밀한 관리를 필요로 한다." },
  '19_11': { example2: "Disputes over inheritance have torn many families apart.", example2Kr: "유산을 둘러싼 분쟁이 많은 가정을 갈라놓았다." },
  '19_12': { example2: "She nurtured her son's interest in science from a very early age.", example2Kr: "그녀는 어릴 때부터 아들의 과학에 대한 관심을 키워주었다." },
  '19_13': { example2: "He felt a strong obligation to support his aging parents financially.", example2Kr: "그는 나이 드신 부모님을 경제적으로 부양해야 한다는 강한 의무감을 느꼈다." },
  '19_14': { example2: "The two old friends reconciled after a decade of silence.", example2Kr: "두 오랜 친구는 10년간의 침묵 끝에 화해했다." },
  '19_15': { example2: "Growing up with siblings teaches children how to share and negotiate.", example2Kr: "형제자매와 함께 자라면 아이들이 나누고 협상하는 법을 배운다." },
  '19_16': { example2: "Both the employee and his spouse attended the company dinner.", example2Kr: "직원과 그의 배우자가 회사 만찬에 참석했다." },
  '19_17': { example2: "Her upbringing in a multicultural household made her highly adaptable.", example2Kr: "다문화 가정에서의 성장 환경이 그녀를 매우 적응력 있게 만들었다." },
  '19_18': { example2: "The elderly and the poor are among the most vulnerable in society.", example2Kr: "노인과 빈곤층은 사회에서 가장 취약한 계층 중 하나이다." },
  '19_19': { example2: "The new law aims to promote the welfare of single-parent families.", example2Kr: "새 법은 한부모 가족의 복지 증진을 목표로 한다." },

  // ── Day 20 문화 & 예술 ──
  '20_0':  { example2: "The café's minimalist aesthetic appealed to young professionals.", example2Kr: "카페의 미니멀리스트 미학은 젊은 직장인들에게 매력적으로 다가왔다." },
  '20_1':  { example2: "Ancient trade routes connected civilisations across continents.", example2Kr: "고대 무역로는 대륙을 넘어 여러 문명을 연결했다." },
  '20_2':  { example2: "The city's architecture blends traditional and modern styles.", example2Kr: "그 도시의 건축은 전통적인 양식과 현대적인 양식을 혼합하고 있다." },
  '20_3':  { example2: "The stolen artifact was finally returned to its country of origin.", example2Kr: "도난당한 유물이 마침내 원산지 국가로 반환되었다." },
  '20_4':  { example2: "She stretched a fresh canvas and began sketching with charcoal.", example2Kr: "그녀는 새 캔버스를 팽팽하게 당기고 목탄으로 스케치를 시작했다." },
  '20_5':  { example2: "The collapse of the Roman Empire shaped the course of Western civilization.", example2Kr: "로마 제국의 붕괴는 서양 문명의 역사를 형성했다." },
  '20_6':  { example2: "Contemporary dance challenges traditional ideas about movement and expression.", example2Kr: "현대 무용은 움직임과 표현에 관한 전통적인 관념에 도전한다." },
  '20_7':  { example2: "The dialect spoken in this village has nearly disappeared.", example2Kr: "이 마을에서 사용되는 방언은 거의 사라졌다." },
  '20_8':  { example2: "Business etiquette varies greatly from country to country.", example2Kr: "비즈니스 예절은 나라마다 크게 다르다." },
  '20_9':  { example2: "The festival preserves centuries-old folklore dances and songs.", example2Kr: "그 축제는 수백 년 된 민속 춤과 노래를 보존한다." },
  '20_10': { example2: "Protecting cultural heritage is essential for future generations.", example2Kr: "문화유산 보호는 미래 세대를 위해 필수적이다." },
  '20_11': { example2: "The art programme supports indigenous artists in sharing their stories.", example2Kr: "그 예술 프로그램은 토착 예술가들이 자신들의 이야기를 나눌 수 있도록 지원한다." },
  '20_12': { example2: "The manuscript revealed details about daily life in medieval Europe.", example2Kr: "그 원고는 중세 유럽의 일상생활에 대한 세부 내용을 밝혀주었다." },
  '20_13': { example2: "Art critics called his final symphony a true masterpiece.", example2Kr: "예술 평론가들은 그의 마지막 교향곡을 진정한 걸작이라고 불렀다." },
  '20_14': { example2: "Norse mythology includes fascinating tales of gods and monsters.", example2Kr: "북유럽 신화에는 신들과 괴물들에 관한 흥미로운 이야기들이 담겨 있다." },
  '20_15': { example2: "The documentary follows the narrative of refugees rebuilding their lives.", example2Kr: "그 다큐멘터리는 삶을 재건하는 난민들의 이야기를 따라간다." },
  '20_16': { example2: "The arts centre is seeking a major patron to fund its new wing.", example2Kr: "예술 센터는 새 건물 동의 자금을 지원할 주요 후원자를 찾고 있다." },
  '20_17': { example2: "The community takes part in an annual harvest ritual each autumn.", example2Kr: "지역 사회는 매년 가을에 연례 추수 의식에 참여한다." },
  '20_18': { example2: "The sculpture garden features works by internationally renowned artists.", example2Kr: "조각 정원에는 국제적으로 유명한 예술가들의 작품이 전시되어 있다." },
  '20_19': { example2: "Many communities are working hard to keep their cultural traditions alive.", example2Kr: "많은 지역 사회가 문화적 전통을 살아있게 유지하기 위해 열심히 노력하고 있다." },
};