/**
 * examples2_2.js - Day 21~50 예문 데이터
 * examples2_1.js 이후에 로드해야 합니다
 */
Object.assign(EXAMPLES2, {
  // ── Day 21 경제 & 금융 ──
  '21_0':  { example2: "The airline declared bankruptcy and cancelled all remaining flights.", example2Kr: "그 항공사는 파산을 선언하고 남은 모든 항편을 취소했다." },
  '21_1':  { example2: "Sugar and coffee were once luxury commodities available only to the wealthy.", example2Kr: "설탕과 커피는 한때 부유층만 구할 수 있는 사치 상품이었다." },
  '21_2':  { example2: "The trade deficit widened as imports outpaced exports.", example2Kr: "수입이 수출을 앞지르면서 무역 적자가 확대되었다." },
  '21_3':  { example2: "Accountants must calculate the annual depreciation of company assets.", example2Kr: "회계사들은 회사 자산의 연간 감가상각을 계산해야 한다." },
  '21_4':  { example2: "The dividend payment was higher than analysts had predicted.", example2Kr: "배당금 지급액이 분석가들의 예측보다 높았다." },
  '21_5':  { example2: "Private equity firms often acquire struggling companies to restructure them.", example2Kr: "사모펀드 회사들은 종종 어려움에 처한 기업을 인수해 구조조정한다." },
  '21_6':  { example2: "The government announced a new fiscal stimulus package worth billions.", example2Kr: "정부는 수십억 달러 규모의 새 재정 부양책을 발표했다." },
  '21_7':  { example2: "Exchange rates fluctuate daily based on supply and demand.", example2Kr: "환율은 수요와 공급에 따라 매일 변동한다." },
  '21_8':  { example2: "A high GDP does not always reflect the wellbeing of all citizens.", example2Kr: "높은 GDP가 항상 모든 시민의 복지를 반영하는 것은 아니다." },
  '21_9':  { example2: "The central bank raised rates to reduce inflation caused by rising energy prices.", example2Kr: "중앙은행은 에너지 가격 상승으로 인한 인플레이션을 줄이기 위해 금리를 인상했다." },
  '21_10': { example2: "Higher interest rates make borrowing more expensive for businesses.", example2Kr: "금리가 높아지면 기업에게 차입 비용이 더 비싸진다." },
  '21_11': { example2: "Young people are encouraged to invest early for long-term financial security.", example2Kr: "젊은 사람들은 장기적인 재정 안정을 위해 일찍 투자하도록 장려된다." },
  '21_12': { example2: "The bank assessed the company's liabilities before approving the loan.", example2Kr: "은행은 대출을 승인하기 전에 회사의 부채를 평가했다." },
  '21_13': { example2: "The government broke up the monopoly to encourage competition.", example2Kr: "정부는 경쟁을 촉진하기 위해 독점 체제를 해체했다." },
  '21_14': { example2: "Rising house prices made it harder to obtain a mortgage.", example2Kr: "집값 상승으로 주택담보대출을 받기가 더 어려워졌다." },
  '21_15': { example2: "Her portfolio included stocks, bonds, and real estate investments.", example2Kr: "그녀의 포트폴리오에는 주식, 채권, 부동산 투자가 포함되어 있었다." },
  '21_16': { example2: "The economy entered a recession and unemployment rose sharply.", example2Kr: "경제가 침체에 빠지면서 실업률이 급격히 상승했다." },
  '21_17': { example2: "Reckless speculation in tech stocks caused the market crash.", example2Kr: "기술주에 대한 무모한 투기가 시장 붕괴를 초래했다." },
  '21_18': { example2: "The farm received a government subsidy to help cover rising fuel costs.", example2Kr: "농장은 오르는 연료비를 충당하기 위한 정부 보조금을 받았다." },
  '21_19': { example2: "The tariff dispute between the two countries disrupted global supply chains.", example2Kr: "두 나라 간의 관세 분쟁이 글로벌 공급망을 혼란에 빠뜨렸다." },

  // ── Day 22 의학 & 건강 ──
  '22_0':  { example2: "The athlete suffered an acute injury during the final match.", example2Kr: "그 운동선수는 결승전에서 급성 부상을 당했다." },
  '22_1':  { example2: "Some patients experience adverse reactions when switching medications.", example2Kr: "일부 환자들은 약물을 바꿀 때 부정적인 반응을 겪는다." },
  '22_2':  { example2: "Living with chronic pain can significantly reduce quality of life.", example2Kr: "만성 통증을 안고 살면 삶의 질이 크게 저하될 수 있다." },
  '22_3':  { example2: "He was diagnosed with high blood pressure during his annual check-up.", example2Kr: "그는 연례 건강 검진에서 고혈압으로 진단받았다." },
  '22_4':  { example2: "Authorities declared a state of emergency when the epidemic reached the capital.", example2Kr: "유행병이 수도에 이르자 당국은 비상사태를 선포했다." },
  '22_5':  { example2: "Pilots are grounded if they show signs of severe fatigue.", example2Kr: "심각한 피로 증상을 보이는 조종사들은 비행이 금지된다." },
  '22_6':  { example2: "Newborns receive vaccinations to build immune protection early in life.", example2Kr: "신생아들은 초기 면역 보호를 형성하기 위해 예방 접종을 받는다." },
  '22_7':  { example2: "Poor ventilation in buildings can accelerate the spread of airborne infections.", example2Kr: "건물 내 불량한 환기는 공기 중 감염의 확산을 가속화할 수 있다." },
  '22_8':  { example2: "Always read the label before taking any over-the-counter medication.", example2Kr: "일반의약품을 복용하기 전에 항상 라벨을 읽으시오." },
  '22_9':  { example2: "Childhood obesity has increased significantly over the past two decades.", example2Kr: "소아 비만이 지난 20년 동안 크게 증가했다." },
  '22_10': { example2: "Scientists are racing to identify the pathogen responsible for the outbreak.", example2Kr: "과학자들은 발병의 원인이 되는 병원체를 찾아내기 위해 경쟁하고 있다." },
  '22_11': { example2: "Her prescription ran out, so she made an appointment to see her doctor.", example2Kr: "처방전이 다 떨어져서 그녀는 의사 진료 예약을 잡았다." },
  '22_12': { example2: "Good nutrition is key to the prevention of many chronic diseases.", example2Kr: "좋은 영양 섭취는 많은 만성 질환 예방의 핵심이다." },
  '22_13': { example2: "Folk remedies are sometimes used alongside conventional medical treatment.", example2Kr: "민간 요법은 때로 기존 의학 치료와 병행하여 사용된다." },
  '22_14': { example2: "Access to clean water and proper sanitation saves millions of lives each year.", example2Kr: "깨끗한 물과 적절한 위생 시설 접근성은 매년 수백만 명의 생명을 구한다." },
  '22_15': { example2: "Fatigue and loss of appetite are early symptoms of the illness.", example2Kr: "피로와 식욕 부진은 그 질환의 초기 증상이다." },
  '22_16': { example2: "Physical therapy helped her recover full movement after the surgery.", example2Kr: "물리 치료가 수술 후 완전한 움직임을 회복하는 데 도움이 되었다." },
  '22_17': { example2: "The transplant surgery lasted twelve hours and required a specialist team.", example2Kr: "이식 수술은 12시간이 걸렸으며 전문가 팀을 필요로 했다." },
  '22_18': { example2: "Volunteers helped distribute the vaccine to remote rural communities.", example2Kr: "자원봉사자들이 외딴 농촌 지역 사회에 백신을 배포하는 것을 도왔다." },
  '22_19': { example2: "The computer virus encrypted all files and demanded a ransom payment.", example2Kr: "컴퓨터 바이러스가 모든 파일을 암호화하고 몸값 지불을 요구했다." },

  // ── Day 23 법률 & 정치 ──
  '23_0':  { example2: "Campaigners are calling for the practice to be abolished immediately.", example2Kr: "캠페인 활동가들은 그 관행을 즉시 폐지하라고 촉구하고 있다." },
  '23_1':  { example2: "The senator proposed an amendment to strengthen environmental regulations.", example2Kr: "그 상원의원은 환경 규제를 강화하기 위한 수정안을 제안했다." },
  '23_2':  { example2: "The board authorized the release of emergency funds to affected communities.", example2Kr: "이사회는 피해 지역 사회에 긴급 자금 방출을 승인했다." },
  '23_3':  { example2: "Media bias can influence public opinion on political issues.", example2Kr: "언론 편향은 정치 문제에 대한 여론에 영향을 미칠 수 있다." },
  '23_4':  { example2: "The leader was awarded the civil rights prize for his lifelong activism.", example2Kr: "그 지도자는 평생에 걸친 사회 운동으로 시민권 상을 받았다." },
  '23_5':  { example2: "The new constitution guaranteed equal rights for all citizens regardless of gender.", example2Kr: "새 헌법은 성별에 관계없이 모든 시민에게 평등권을 보장했다." },
  '23_6':  { example2: "The politician's conviction shocked the nation and led to widespread protests.", example2Kr: "그 정치인의 유죄 판결은 국민을 충격에 빠뜨리고 광범위한 시위로 이어졌다." },
  '23_7':  { example2: "The defendant's lawyer argued that the evidence was obtained illegally.", example2Kr: "피고인의 변호사는 증거가 불법으로 수집되었다고 주장했다." },
  '23_8':  { example2: "A healthy democracy requires an informed and engaged citizenry.", example2Kr: "건강한 민주주의는 정보를 갖춘 시민 참여를 필요로 한다." },
  '23_9':  { example2: "Stricter penalties were introduced to better enforce traffic laws.", example2Kr: "교통법규를 더 잘 시행하기 위해 더 엄격한 처벌이 도입되었다." },
  '23_10': { example2: "The whistleblower was granted immunity in exchange for his testimony.", example2Kr: "내부고발자는 증언의 대가로 면제권을 부여받았다." },
  '23_11': { example2: "The regional court challenged the federal government's jurisdiction.", example2Kr: "지방 법원이 연방 정부의 관할권에 이의를 제기했다." },
  '23_12': { example2: "The legislation was introduced after years of lobbying by consumer groups.", example2Kr: "그 법률은 소비자 단체들의 수년간 로비 활동 끝에 도입되었다." },
  '23_13': { example2: "Thousands signed the online petition demanding the minister's resignation.", example2Kr: "수천 명이 장관의 사임을 요구하는 온라인 청원서에 서명했다." },
  '23_14': { example2: "The plaintiff was awarded substantial damages by the court.", example2Kr: "원고는 법원으로부터 상당한 손해 배상금을 받았다." },
  '23_15': { example2: "The landmark ruling set a precedent for future human rights cases.", example2Kr: "획기적인 판결이 향후 인권 사건에 대한 선례를 세웠다." },
  '23_16': { example2: "The prosecution failed to prove the case beyond a reasonable doubt.", example2Kr: "검찰은 합리적인 의심의 여지없이 사건을 입증하는 데 실패했다." },
  '23_17': { example2: "The small island nation fiercely defended its maritime sovereignty.", example2Kr: "그 작은 섬나라는 자국의 해양 주권을 맹렬히 수호했다." },
  '23_18': { example2: "The court found the witness's testimony to be inconsistent.", example2Kr: "법원은 증인의 증언이 일관성이 없다고 판단했다." },
  '23_19': { example2: "The verdict was delivered after three days of deliberation by the jury.", example2Kr: "평결은 배심원단의 3일간의 심의 끝에 내려졌다." },

  // ── Day 24 과학 & 기술 ──
  '24_0':  { example2: "The new algorithm processes data far more efficiently than previous versions.", example2Kr: "새 알고리즘은 이전 버전보다 훨씬 효율적으로 데이터를 처리한다." },
  '24_1':  { example2: "Artificial intelligence can now generate realistic images from text prompts.", example2Kr: "인공지능은 이제 텍스트 프롬프트에서 사실적인 이미지를 생성할 수 있다." },
  '24_2':  { example2: "Factory automation has greatly reduced production costs over the past decade.", example2Kr: "공장 자동화가 지난 10년에 걸쳐 생산 비용을 크게 줄였다." },
  '24_3':  { example2: "The coral reef is a hotspot for biodiversity, home to thousands of species.", example2Kr: "산호초는 수천 종의 서식지인 생물 다양성의 핫스팟이다." },
  '24_4':  { example2: "Switching to public transport significantly reduces your carbon footprint.", example2Kr: "대중교통으로 전환하면 탄소 발자국이 크게 줄어든다." },
  '24_5':  { example2: "The discovery of penicillin acted as a catalyst for modern medicine.", example2Kr: "페니실린의 발견은 현대 의학의 촉매제 역할을 했다." },
  '24_6':  { example2: "Governments are increasing investment in cybersecurity to protect critical infrastructure.", example2Kr: "정부들은 핵심 인프라를 보호하기 위해 사이버 보안 투자를 늘리고 있다." },
  '24_7':  { example2: "The researchers published their raw data so other scientists could verify the results.", example2Kr: "연구자들은 다른 과학자들이 결과를 검증할 수 있도록 원시 데이터를 공개했다." },
  '24_8':  { example2: "The evolution of communication technology has transformed how we interact.", example2Kr: "통신 기술의 진화는 우리가 상호 작용하는 방식을 변화시켰다." },
  '24_9':  { example2: "The world must shift away from fossil fuels to address climate change.", example2Kr: "기후 변화에 대처하기 위해 세계는 화석 연료에서 벗어나야 한다." },
  '24_10': { example2: "On the Moon, the reduced gravity makes carrying heavy objects easier.", example2Kr: "달에서는 중력이 약해 무거운 물건을 운반하기 더 쉽다." },
  '24_11': { example2: "Scientists tested the hypothesis by running a series of controlled experiments.", example2Kr: "과학자들은 일련의 통제된 실험을 실시해 가설을 검증했다." },
  '24_12': { example2: "Open-source innovation is accelerating progress in software development.", example2Kr: "오픈 소스 혁신이 소프트웨어 개발의 진전을 가속화하고 있다." },
  '24_13': { example2: "A molecule of DNA contains all the genetic information needed to build an organism.", example2Kr: "DNA 분자 하나는 유기체를 만드는 데 필요한 모든 유전 정보를 담고 있다." },
  '24_14': { example2: "Nanotechnology is being applied to create stronger and lighter materials.", example2Kr: "나노 기술이 더 강하고 가벼운 소재를 만드는 데 적용되고 있다." },
  '24_15': { example2: "The space probe entered orbit around Mars after a seven-month journey.", example2Kr: "우주 탐사선은 7개월의 여정 끝에 화성 궤도에 진입했다." },
  '24_16': { example2: "Workers in the nuclear plant were regularly tested for radiation exposure.", example2Kr: "원자력 발전소 직원들은 방사선 노출 여부를 정기적으로 검사받았다." },
  '24_17': { example2: "Renewable energy sources now account for over 30% of global electricity.", example2Kr: "재생 가능 에너지원이 이제 전 세계 전기의 30% 이상을 차지한다." },
  '24_18': { example2: "Engineers simulated the earthquake to test the building's resistance.", example2Kr: "엔지니어들은 건물의 내진성을 테스트하기 위해 지진을 시뮬레이션했다." },
  '24_19': { example2: "The general theory of relativity is one of the pillars of modern physics.", example2Kr: "일반 상대성 이론은 현대 물리학의 토대 중 하나이다." },

  // ── Day 25 영어 관용표현 I ──
  '25_0':  { example2: "She organised a team-building game to break the ice on the first day.", example2Kr: "그녀는 첫날 어색함을 풀기 위해 팀 빌딩 게임을 준비했다." },
  '25_1':  { example2: "I knew the exam would be hard, but I bit the bullet and revised all weekend.", example2Kr: "시험이 어려울 줄 알았지만 묵묵히 참고 주말 내내 복습했다." },
  '25_2':  { example2: "After putting in twelve hours, the team agreed it was time to call it a day.", example2Kr: "12시간을 일한 후 팀은 이제 마무리할 시간이라고 합의했다." },
  '25_3':  { example2: "They cut corners on safety checks, which led to a serious accident.", example2Kr: "그들은 안전 점검에서 편법을 써서 심각한 사고로 이어졌다." },
  '25_4':  { example2: "The CEO was surprisingly down to earth despite running a billion-dollar company.", example2Kr: "그 CEO는 수십억 달러 규모의 회사를 운영함에도 놀라울 정도로 소탈했다." },
  '25_5':  { example2: "You can't hide from your mistakes forever — eventually you'll have to face the music.", example2Kr: "실수를 영원히 숨길 수는 없어 — 결국에는 책임을 져야 한다." },
  '25_6':  { example2: "The chairperson asked someone to get the ball rolling with a brief introduction.", example2Kr: "의장은 누군가에게 간략한 소개로 논의를 시작해달라고 요청했다." },
  '25_7':  { example2: "The consultant's diagnosis hit the nail on the head — the issue was poor leadership.", example2Kr: "컨설턴트의 진단은 핵심을 정확히 짚었다 — 문제는 부실한 리더십이었다." },
  '25_8':  { example2: "Quitting smoking is hard, but the health benefits in the long run are enormous.", example2Kr: "금연은 어렵지만 장기적인 건강상 이점은 엄청나다." },
  '25_9':  { example2: "After the controversy, the politician chose to keep a low profile.", example2Kr: "논란 이후 그 정치인은 조용히 지내기로 선택했다." },
  '25_10': { example2: "Someone let the cat out of the bag and now everyone knows about the pay rise.", example2Kr: "누군가 비밀을 누설해서 이제 모두가 임금 인상에 대해 알고 있다." },
  '25_11': { example2: "She missed the boat on the early-bird discount by waiting too long.", example2Kr: "그녀는 너무 오래 기다리다가 조기 할인 기회를 놓쳤다." },
  '25_12': { example2: "He only visits his relatives in the countryside once in a blue moon.", example2Kr: "그는 시골에 있는 친척들을 아주 드물게만 방문한다." },
  '25_13': { example2: "The committee remained on the fence, unwilling to commit to either proposal.", example2Kr: "위원회는 어느 제안에도 동의하려 하지 않은 채 중립을 지켰다." },
  '25_14': { example2: "The department head kept passing the buck instead of making a decision.", example2Kr: "부서장은 결정을 내리지 않고 계속 책임을 떠넘겼다." },
  '25_15': { example2: "He was pulling your leg — there's no new policy about working on weekends.", example2Kr: "그가 너를 놀린 거야 — 주말 근무에 관한 새 정책은 없어." },
  '25_16': { example2: "The partners rarely see eye to eye on how best to expand the business.", example2Kr: "파트너들은 사업을 어떻게 가장 잘 확장할지에 대해 좀처럼 의견이 맞지 않는다." },
  '25_17': { example2: "He called in sick because he was feeling a bit under the weather.", example2Kr: "그는 몸 상태가 좋지 않아서 병가를 냈다." },
  '25_18': { example2: "Whether the summit will happen is still up in the air.", example2Kr: "정상회담이 열릴지는 아직 불확실하다." },
  '25_19': { example2: "It took me a while to wrap my head around the concept of quantum mechanics.", example2Kr: "양자역학 개념을 이해하는 데 시간이 좀 걸렸다." },

  // ── Day 26 환경 & 생태 ──
  '26_0':  { example2: "Biodegradable materials break down naturally and don't accumulate in landfill.", example2Kr: "생분해성 소재는 자연적으로 분해되어 매립지에 쌓이지 않는다." },
  '26_1':  { example2: "Airlines are investing in sustainable fuels to become carbon neutral.", example2Kr: "항공사들은 탄소 중립을 달성하기 위해 지속 가능한 연료에 투자하고 있다." },
  '26_2':  { example2: "Governments worldwide are struggling to respond to the effects of climate change.", example2Kr: "전 세계 정부들이 기후 변화의 영향에 대응하기 위해 분투하고 있다." },
  '26_3':  { example2: "Conservation charities rely heavily on public donations to fund their work.", example2Kr: "보존 단체들은 활동 자금을 위해 대중의 기부에 크게 의존한다." },
  '26_4':  { example2: "Chemical contamination in the river killed thousands of fish overnight.", example2Kr: "강의 화학 오염이 밤사이 수천 마리의 물고기를 죽였다." },
  '26_5':  { example2: "Large-scale deforestation is linked to increased flooding and soil erosion.", example2Kr: "대규모 삼림 벌채는 홍수 증가 및 토양 침식과 관련이 있다." },
  '26_6':  { example2: "Protecting the ocean ecosystem is vital for the health of the entire planet.", example2Kr: "해양 생태계를 보호하는 것은 지구 전체의 건강을 위해 매우 중요하다." },
  '26_7':  { example2: "Vehicle emissions are a major contributor to poor air quality in cities.", example2Kr: "차량 배기가스는 도시 대기 오염의 주요 원인이다." },
  '26_8':  { example2: "Soil erosion is threatening the productivity of farmland across the region.", example2Kr: "토양 침식이 지역 전반에 걸쳐 농지의 생산성을 위협하고 있다." },
  '26_9':  { example2: "The extinction of bees would have catastrophic effects on global food supplies.", example2Kr: "벌의 멸종은 세계 식량 공급에 재앙적인 영향을 미칠 것이다." },
  '26_10': { example2: "Reducing greenhouse gas emissions is central to fighting global warming.", example2Kr: "온실 가스 배출 감소는 지구 온난화 대응의 핵심이다." },
  '26_11': { example2: "The construction project was halted to protect a rare animal's habitat.", example2Kr: "희귀 동물의 서식지를 보호하기 위해 건설 프로젝트가 중단되었다." },
  '26_12': { example2: "The city introduced separate bins to keep recyclables out of landfill.", example2Kr: "시는 재활용품이 매립지로 가지 않도록 분리 수거통을 도입했다." },
  '26_13': { example2: "Scientists first detected the hole in the ozone layer in the 1980s.", example2Kr: "과학자들은 1980년대에 처음으로 오존층의 구멍을 발견했다." },
  '26_14': { example2: "Strict regulations have reduced the amount of pollutants released into rivers.", example2Kr: "엄격한 규정들이 강으로 방출되는 오염 물질의 양을 줄였다." },
  '26_15': { example2: "The city council introduced incentives to encourage residents to recycle more.", example2Kr: "시의회는 주민들이 더 많이 재활용하도록 장려하기 위해 인센티브를 도입했다." },
  '26_16': { example2: "Community reforestation drives have planted over a million trees this year.", example2Kr: "지역 사회 재조림 운동이 올해 100만 그루 이상의 나무를 심었다." },
  '26_17': { example2: "Businesses are being urged to adopt sustainability targets by 2030.", example2Kr: "기업들은 2030년까지 지속 가능성 목표를 채택하도록 촉구받고 있다." },
  '26_18': { example2: "Workers were evacuated after a toxic spill at the chemical plant.", example2Kr: "화학 공장에서 독성 물질이 유출되자 근로자들이 대피했다." },
  '26_19': { example2: "The charity works to rescue and rehabilitate injured wildlife.", example2Kr: "그 자선 단체는 부상당한 야생동물을 구조하고 재활시키기 위해 활동한다." },

  // ── Day 27 심리 & 철학 ──
  '27_0':  { example2: "He felt ambivalent about the promotion, excited but also anxious.", example2Kr: "그는 승진에 대해 설레기도 하고 불안하기도 한 양면적인 감정을 느꼈다." },
  '27_1':  { example2: "Breathing exercises are a proven technique for managing anxiety.", example2Kr: "호흡 운동은 불안을 관리하는 효과가 입증된 기법이다." },
  '27_2':  { example2: "Regular mental challenges can help maintain healthy cognition into old age.", example2Kr: "규칙적인 정신적 도전은 노년까지 건강한 인지 능력을 유지하는 데 도움이 될 수 있다." },
  '27_3':  { example2: "The relationship between the brain and consciousness remains deeply mysterious.", example2Kr: "뇌와 의식 사이의 관계는 여전히 매우 신비롭다." },
  '27_4':  { example2: "A process of careful deduction led the detective to the only possible suspect.", example2Kr: "신중한 연역 과정이 형사를 유일한 용의자로 인도했다." },
  '27_5':  { example2: "His belief that everyone was conspiring against him was a clear delusion.", example2Kr: "모든 사람이 자신을 모의하고 있다는 그의 믿음은 명백한 망상이었다." },
  '27_6':  { example2: "All theories must be supported by empirical evidence to be taken seriously.", example2Kr: "모든 이론은 진지하게 받아들여지기 위해 실증적 증거로 뒷받침되어야 한다." },
  '27_7':  { example2: "Business ethics courses teach students how to handle moral dilemmas at work.", example2Kr: "경영 윤리 과목은 학생들에게 직장에서의 도덕적 딜레마를 처리하는 방법을 가르친다." },
  '27_8':  { example2: "He relied on intuition rather than data when making the crucial decision.", example2Kr: "그는 중요한 결정을 내릴 때 데이터보다 직관에 의존했다." },
  '27_9':  { example2: "It seems irrational to fear spiders more than car accidents, which are far more deadly.", example2Kr: "훨씬 더 치명적인 자동차 사고보다 거미를 더 무서워하는 것은 비이성적으로 보인다." },
  '27_10': { example2: "Questions of morality are often more complex than they first appear.", example2Kr: "도덕성에 관한 문제는 처음 보이는 것보다 훨씬 복잡한 경우가 많다." },
  '27_11': { example2: "High motivation levels are strongly linked to better academic achievement.", example2Kr: "높은 동기 수준은 더 좋은 학업 성취와 강하게 연관된다." },
  '27_12': { example2: "A good scientist must remain objective even when the results are unexpected.", example2Kr: "좋은 과학자는 결과가 예상치 못한 경우에도 객관적이어야 한다." },
  '27_13': { example2: "The speed paradox shows that the faster you rush, the more mistakes you make.", example2Kr: "속도의 역설은 서두를수록 더 많은 실수를 한다는 것을 보여준다." },
  '27_14': { example2: "Our perception of colour can be influenced by surrounding light conditions.", example2Kr: "색에 대한 우리의 인식은 주변 조명 조건에 의해 영향받을 수 있다." },
  '27_15': { example2: "Positive psychology focuses on building strengths rather than fixing weaknesses.", example2Kr: "긍정 심리학은 약점 수정보다 강점 개발에 초점을 맞춘다." },
  '27_16': { example2: "Descartes is often seen as the father of modern Western rationalism.", example2Kr: "데카르트는 흔히 근대 서양 합리주의의 아버지로 여겨진다." },
  '27_17': { example2: "Our subconscious mind processes far more information than we are aware of.", example2Kr: "우리의 잠재의식은 우리가 인식하는 것보다 훨씬 더 많은 정보를 처리한다." },
  '27_18': { example2: "PTSD is a serious condition caused by exposure to severe trauma.", example2Kr: "PTSD는 심각한 트라우마에 노출되어 발생하는 중대한 상태이다." },
  '27_19': { example2: "The ancient Greeks believed that virtue was essential for a good society.", example2Kr: "고대 그리스인들은 덕목이 좋은 사회를 위해 필수적이라고 믿었다." },

  // ── Day 28 고급 동사 I ──
  '28_0':  { example2: "The company publicly acknowledged its mistakes and issued a formal apology.", example2Kr: "회사는 실수를 공개적으로 인정하고 공식 사과를 발표했다." },
  '28_1':  { example2: "The new drug was found to alleviate the pain of arthritis sufferers.", example2Kr: "새 약물이 관절염 환자들의 통증을 완화하는 것으로 나타났다." },
  '28_2':  { example2: "Scientists assert that the findings could change our understanding of the universe.", example2Kr: "과학자들은 그 발견이 우주에 대한 우리의 이해를 바꿀 수 있다고 주장한다." },
  '28_3':  { example2: "The two research teams collaborated to publish a co-authored study.", example2Kr: "두 연구팀은 공동 저자 연구를 발표하기 위해 협력했다." },
  '28_4':  { example2: "She took time to contemplate the ethical implications of her research.", example2Kr: "그녀는 자신의 연구의 윤리적 함의를 숙고하는 시간을 가졌다." },
  '28_5':  { example2: "Relations between the neighbours deteriorated after the border dispute.", example2Kr: "국경 분쟁 이후 두 이웃 나라 간의 관계가 악화되었다." },
  '28_6':  { example2: "His influence on the team began to diminish as younger talent emerged.", example2Kr: "젊은 인재가 등장하면서 팀에 대한 그의 영향력이 줄어들기 시작했다." },
  '28_7':  { example2: "The professor asked the student to elaborate on the argument in her essay.", example2Kr: "교수는 학생에게 에세이에서 주장을 더 자세히 설명해 달라고 요청했다." },
  '28_8':  { example2: "Better road layouts could facilitate the flow of traffic through the city centre.", example2Kr: "도로 구조 개선이 도심을 통과하는 교통 흐름을 용이하게 할 수 있다." },
  '28_9':  { example2: "The new law was implemented across all regions without exception.", example2Kr: "새로운 법이 예외 없이 모든 지역에 걸쳐 시행되었다." },
  '28_10': { example2: "Her reluctance to answer questions implied that she was hiding something.", example2Kr: "질문에 대답을 꺼리는 그녀의 태도는 뭔가 숨기고 있다는 것을 암시했다." },
  '28_11': { example2: "Cold weather can inhibit the growth of certain crops.", example2Kr: "추운 날씨는 특정 작물의 성장을 억제할 수 있다." },
  '28_12': { example2: "His talent began to manifest during his first performance on stage.", example2Kr: "그의 재능은 무대 위에서의 첫 공연 중에 나타나기 시작했다." },
  '28_13': { example2: "Urban green spaces help mitigate the urban heat island effect.", example2Kr: "도시 녹지 공간은 도시 열섬 현상을 완화하는 데 도움이 된다." },
  '28_14': { example2: "Union representatives will negotiate wages and working conditions next month.", example2Kr: "노조 대표들이 다음 달에 임금과 근무 조건을 협상할 예정이다." },
  '28_15': { example2: "Children often perceive the world very differently from adults.", example2Kr: "어린이들은 종종 어른들과 매우 다르게 세상을 인식한다." },
  '28_16': { example2: "She persisted with her research despite being told it was impossible.", example2Kr: "그녀는 불가능하다는 말을 들었음에도 불구하고 연구를 계속했다." },
  '28_17': { example2: "Repeating vocabulary in context reinforces memory far better than rote learning.", example2Kr: "문맥 속에서 어휘를 반복하는 것이 단순 암기보다 기억을 훨씬 잘 강화한다." },
  '28_18': { example2: "The committee scrutinised every line of the proposed budget.", example2Kr: "위원회는 제안된 예산의 모든 줄을 면밀히 검토했다." },
  '28_19': { example2: "Rumours and gossip can seriously undermine team morale and trust.", example2Kr: "루머와 험담은 팀의 사기와 신뢰를 심각하게 약화시킬 수 있다." },

  // ── Day 29 사회 & 국제관계 ──
  '29_0':  { example2: "She was granted asylum after proving that she faced persecution at home.", example2Kr: "그녀는 고국에서 박해를 받는다는 것을 입증한 후 망명을 허가받았다." },
  '29_1':  { example2: "The bilateral summit addressed issues including trade and climate policy.", example2Kr: "양자 정상회담은 무역과 기후 정책을 포함한 문제들을 다루었다." },
  '29_2':  { example2: "Both sides agreed to the cease-fire, halting three months of violence.", example2Kr: "양측은 3개월간의 폭력을 중단하는 휴전에 합의했다." },
  '29_3':  { example2: "Quiet diplomacy behind the scenes helped bring the parties to the table.", example2Kr: "뒤에서 이루어진 조용한 외교가 양측을 협상 테이블로 이끄는 데 도움이 되었다." },
  '29_4':  { example2: "He faced discrimination at work because of his religious beliefs.", example2Kr: "그는 종교적 신념 때문에 직장에서 차별을 받았다." },
  '29_5':  { example2: "The embargo has severely limited the country's ability to export goods.", example2Kr: "금수 조치는 그 나라의 상품 수출 능력을 심각하게 제한했다." },
  '29_6':  { example2: "Critics argue that globalisation has widened the gap between rich and poor.", example2Kr: "비평가들은 세계화가 부자와 빈자 사이의 격차를 넓혔다고 주장한다." },
  '29_7':  { example2: "Humanitarian organisations provided emergency food and shelter to displaced families.", example2Kr: "인도주의 단체들이 실향민 가족들에게 비상 식량과 피난처를 제공했다." },
  '29_8':  { example2: "Immigration has long been a deeply divisive issue in the national debate.", example2Kr: "이민은 오랫동안 국가 토론에서 깊이 분열적인 문제였다." },
  '29_9':  { example2: "Growing inequality in education opportunities is fuelling social unrest.", example2Kr: "교육 기회의 심화되는 불평등이 사회 불안을 조장하고 있다." },
  '29_10': { example2: "Third-party mediation helped the two companies reach a settlement.", example2Kr: "제3자 중재가 두 회사가 합의에 도달하는 데 도움이 되었다." },
  '29_11': { example2: "Economic migration is increasing, as people move for better opportunities.", example2Kr: "더 나은 기회를 위해 사람들이 이동하면서 경제적 이주가 증가하고 있다." },
  '29_12': { example2: "A multilateral response is needed to tackle terrorism effectively.", example2Kr: "테러리즘을 효과적으로 해결하기 위해서는 다자간 대응이 필요하다." },
  '29_13': { example2: "Generations of oppression had left deep scars on the community.", example2Kr: "여러 세대에 걸친 억압이 그 지역 사회에 깊은 상처를 남겼다." },
  '29_14': { example2: "State-controlled media was used to spread propaganda during the conflict.", example2Kr: "분쟁 중에 국가 통제 미디어가 선전을 퍼뜨리는 데 사용되었다." },
  '29_15': { example2: "The reconciliation commission heard testimony from victims on all sides.", example2Kr: "화해 위원회는 모든 측의 피해자들로부터 증언을 들었다." },
  '29_16': { example2: "Refugee camps struggle with overcrowding and a lack of clean water.", example2Kr: "난민 캠프는 과밀 상태와 깨끗한 물 부족으로 어려움을 겪고 있다." },
  '29_17': { example2: "Financial sanctions were imposed on individuals linked to the regime.", example2Kr: "정권과 연관된 개인들에게 금융 제재가 부과되었다." },
  '29_18': { example2: "The nuclear non-proliferation treaty was signed by over 190 nations.", example2Kr: "핵 비확산 조약은 190개국 이상이 서명했다." },
  '29_19': { example2: "The president threatened to use the veto if the bill was brought to a vote.", example2Kr: "대통령은 법안이 표결에 부쳐지면 거부권을 행사하겠다고 위협했다." },

  // ── Day 30 영어 관용표현 II ──
  '30_0':  { example2: "His sarcastic comment only added fuel to the fire during the argument.", example2Kr: "그의 빈정거리는 발언은 논쟁 중에 불에 기름을 붓는 꼴이 되었다." },
  '30_1':  { example2: "Just tell me the answer — there's no time to beat around the bush.", example2Kr: "그냥 답을 말해 줘 — 핵심을 피할 시간이 없어." },
  '30_2':  { example2: "He burned the midnight oil for weeks to prepare for his final exams.", example2Kr: "그는 최종 시험을 준비하기 위해 수 주 동안 밤새워 공부했다." },
  '30_3':  { example2: "We caught the last train by the skin of our teeth.", example2Kr: "우리는 아슬아슬하게 막차를 탔다." },
  '30_4':  { example2: "A good lawyer costs an arm and a leg, but it's worth it in court.", example2Kr: "좋은 변호사는 엄청나게 비싸지만 법정에서는 그만한 가치가 있다." },
  '30_5':  { example2: "She lost her job but found a better one — every cloud has a silver lining.", example2Kr: "그녀는 직장을 잃었지만 더 좋은 곳을 찾았다 — 고생 끝에 낙이 온다더니." },
  '30_6':  { example2: "I gave him the benefit of the doubt since it was his first offence.", example2Kr: "첫 번째 잘못이었기 때문에 선의로 해석해 주었다." },
  '30_7':  { example2: "After the merger collapsed, the team had to go back to square one.", example2Kr: "합병이 무산된 후 팀은 원점으로 돌아가야 했다." },
  '30_8':  { example2: "The training is tough, but hang in there — it gets easier.", example2Kr: "훈련이 힘들지만 버텨 — 점점 쉬워진다." },
  '30_9':  { example2: "With three projects at once, he definitely has a lot on his plate.", example2Kr: "동시에 세 가지 프로젝트가 있으니 그는 확실히 할 일이 너무 많다." },
  '30_10': { example2: "The new recruit hit the ground running and impressed everyone on day one.", example2Kr: "신입 직원은 첫날부터 즉시 활동을 시작해 모두를 감동시켰다." },
  '30_11': { example2: "By cycling to work and going to a gym nearby, she killed two birds with one stone.", example2Kr: "자전거로 출근하고 근처 헬스장에 가면서 그녀는 일석이조 효과를 거뒀다." },
  '30_12': { example2: "The security team left no stone unturned in their investigation of the breach.", example2Kr: "보안팀은 침해 사건 조사에서 온갖 수단을 다 동원했다." },
  '30_13': { example2: "I know the answer is on the tip of my tongue — give me a second.", example2Kr: "답이 혀끝에서 맴도는데 — 잠깐만 기다려 줘." },
  '30_14': { example2: "The tutor played devil's advocate to sharpen the students' critical thinking.", example2Kr: "강사는 학생들의 비판적 사고를 날카롭게 하기 위해 일부러 반론을 제기했다." },
  '30_15': { example2: "If you read between the lines, the memo implies staff cuts are coming.", example2Kr: "행간을 읽으면 그 메모는 직원 감축이 다가오고 있음을 암시한다." },
  '30_16': { example2: "The neutral mediator sat on the fence to keep both parties talking.", example2Kr: "중립적인 조정자는 양측이 계속 대화하도록 중립을 유지했다." },
  '30_17': { example2: "The way the audience went silent when she walked in spoke volumes.", example2Kr: "그녀가 들어왔을 때 청중이 조용해진 것이 많은 것을 말해 주었다." },
  '30_18': { example2: "Take online reviews with a grain of salt — some are fake.", example2Kr: "온라인 리뷰는 에누리해서 읽어라 — 일부는 가짜다." },
  '30_19': { example2: "I've explained my position clearly — the ball is in your court.", example2Kr: "제 입장을 명확히 설명했으니, 이제 결정은 당신 차례입니다." },

  // ── Day 31 TOEIC/TOEFL 빈출 고급 명사 ──
  '31_0':  { example2: "Legal ambiguity in the contract caused years of costly litigation.", example2Kr: "계약서의 법적 모호함이 수년간의 비용이 많이 드는 소송을 초래했다." },
  '31_1':  { example2: "His assertion that the company was profitable was later proven false.", example2Kr: "회사가 수익성이 있다는 그의 주장은 나중에 거짓으로 판명되었다." },
  '31_2':  { example2: "The lack of coherence in the report made it hard to understand.", example2Kr: "보고서의 일관성 부족이 이해하기 어렵게 만들었다." },
  '31_3':  { example2: "There was no consensus among the panel members on the best course of action.", example2Kr: "최선의 행동 방침에 대해 패널 구성원들 사이에 합의가 없었다." },
  '31_4':  { example2: "Studies show a strong correlation between poverty and poor health outcomes.", example2Kr: "연구들은 빈곤과 건강 불량 사이의 강한 상관관계를 보여준다." },
  '31_5':  { example2: "The discrepancy in the accounts suggested that someone had altered the records.", example2Kr: "회계 장부의 불일치는 누군가가 기록을 변조했다는 것을 시사했다." },
  '31_6':  { example2: "Machine learning has become a dominant force in the domain of data science.", example2Kr: "기계학습은 데이터 과학 분야에서 지배적인 힘이 되었다." },
  '31_7':  { example2: "Seasonal fluctuations in demand make staffing decisions very difficult.", example2Kr: "계절적 수요 변동이 인력 배치 결정을 매우 어렵게 만든다." },
  '31_8':  { example2: "The full implications of the ruling for future cases are still unclear.", example2Kr: "향후 사건에 대한 그 판결의 전체 함의는 아직 불분명하다." },
  '31_9':  { example2: "Financial incentives encourage people to install solar panels at home.", example2Kr: "금융 인센티브가 사람들이 집에 태양광 패널을 설치하도록 장려한다." },
  '31_10': { example2: "Centuries of neglect left the city's infrastructure in a poor state.", example2Kr: "수 세기에 걸친 방치로 도시의 인프라가 열악한 상태에 놓였다." },
  '31_11': { example2: "The school launched an initiative to improve digital literacy in the classroom.", example2Kr: "학교는 교실에서 디지털 리터러시를 향상시키기 위한 계획을 시작했다." },
  '31_12': { example2: "Researchers have not yet fully understood the mechanism behind the disease.", example2Kr: "연구자들은 아직 그 질병 뒤에 있는 메커니즘을 완전히 이해하지 못했다." },
  '31_13': { example2: "The economic downturn was a once-in-a-generation phenomenon.", example2Kr: "그 경제 침체는 한 세대에 한 번 있는 현상이었다." },
  '31_14': { example2: "The entire business model rested on the false premise that demand would grow.", example2Kr: "전체 비즈니스 모델은 수요가 성장할 것이라는 잘못된 전제에 기초했다." },
  '31_15': { example2: "The minister gave the rationale for the decision at a press conference.", example2Kr: "장관은 기자회견에서 결정의 근거를 설명했다." },
  '31_16': { example2: "The scope of the project expanded after the discovery of additional ruins.", example2Kr: "추가 유적지 발견 이후 프로젝트의 범위가 확대되었다." },
  '31_17': { example2: "The new guidelines lack specificity and are open to a range of interpretations.", example2Kr: "새 지침은 명확성이 부족해 다양한 해석의 여지가 있다." },
  '31_18': { example2: "Transparency in government spending builds public trust.", example2Kr: "정부 지출의 투명성이 국민의 신뢰를 구축한다." },
  '31_19': { example2: "Peer review is used to assess the validity of scientific findings.", example2Kr: "동료 심사는 과학적 발견의 타당성을 평가하는 데 사용된다." },

  // ── Day 32 학문 & 언어 ──
  '32_0':  { example2: "The concept of time is highly abstract and difficult to define precisely.", example2Kr: "시간의 개념은 매우 추상적이어서 정확하게 정의하기 어렵다." },
  '32_1':  { example2: "The report used ambiguous language that could be interpreted in different ways.", example2Kr: "그 보고서는 여러 방식으로 해석될 수 있는 모호한 언어를 사용했다." },
  '32_2':  { example2: "He used an analogy between the human body and a machine to explain the theory.", example2Kr: "그는 인체와 기계 사이의 비유를 사용해 이론을 설명했다." },
  '32_3':  { example2: "All citations in the paper must follow the APA referencing style.", example2Kr: "논문의 모든 인용은 APA 참조 스타일을 따라야 한다." },
  '32_4':  { example2: "The word 'home' carries powerful emotional connotations for most people.", example2Kr: "'home'이라는 단어는 대부분의 사람들에게 강력한 감정적 함축 의미를 지닌다." },
  '32_5':  { example2: "The book offers a sharp critique of modern consumer culture.", example2Kr: "그 책은 현대 소비 문화에 대한 날카로운 비평을 제공한다." },
  '32_6':  { example2: "The online forum became a space for open public discourse.", example2Kr: "그 온라인 포럼은 공개적인 공공 담론의 장이 되었다." },
  '32_7':  { example2: "The barrister was known for being both eloquent and persuasive in court.", example2Kr: "그 변호사는 법정에서 언변이 뛰어나고 설득력이 있는 것으로 알려졌다." },
  '32_8':  { example2: "The etymology of the word 'disaster' relates to the influence of stars.", example2Kr: "'disaster'라는 단어의 어원은 별의 영향과 관련이 있다." },
  '32_9':  { example2: "The idea that multitasking improves productivity is a common fallacy.", example2Kr: "멀티태스킹이 생산성을 향상시킨다는 생각은 흔한 오류이다." },
  '32_10': { example2: "Horror is one of the most commercially successful genres in cinema.", example2Kr: "공포는 영화에서 상업적으로 가장 성공적인 장르 중 하나이다." },
  '32_11': { example2: "The research team tested a new hypothesis about the origins of the universe.", example2Kr: "연구팀이 우주의 기원에 관한 새 가설을 검증했다." },
  '32_12': { example2: "From the available data, researchers drew the inference that the virus was airborne.", example2Kr: "이용 가능한 데이터에서 연구자들은 바이러스가 공기 중에 전파된다는 추론을 이끌어냈다." },
  '32_13': { example2: "The irony of the situation was that the doctor was the least healthy person in the room.", example2Kr: "그 상황의 아이러니는 의사가 방에서 가장 건강하지 않은 사람이었다는 것이었다." },
  '32_14': { example2: "She studied linguistics to better understand how children acquire language.", example2Kr: "그녀는 아이들이 어떻게 언어를 습득하는지 더 잘 이해하기 위해 언어학을 공부했다." },
  '32_15': { example2: "The author used the metaphor of a storm to describe the character's inner turmoil.", example2Kr: "작가는 주인공의 내면의 혼란을 묘사하기 위해 폭풍의 은유를 사용했다." },
  '32_16': { example2: "The politician's speech was dismissed as mere rhetoric with no substance.", example2Kr: "정치인의 연설은 실질적인 내용 없는 단순한 미사여구로 일축되었다." },
  '32_17': { example2: "Students learning a language must master syntax to form correct sentences.", example2Kr: "언어를 배우는 학생들은 올바른 문장을 형성하기 위해 구문론을 숙달해야 한다." },
  '32_18': { example2: "His thesis argued that globalisation had weakened national identity.", example2Kr: "그의 논문은 세계화가 국가 정체성을 약화시켰다고 주장했다." },
  '32_19': { example2: "The poem was composed in the local vernacular to reach a wider audience.", example2Kr: "그 시는 더 넓은 독자에게 다가가기 위해 지역 일상어로 작성되었다." },

  // ── Day 33 비즈니스 & 직장 ──
  '33_0':  { example2: "A culture of accountability helps organisations identify and correct mistakes.", example2Kr: "책임 문화는 조직이 실수를 파악하고 수정하는 데 도움이 된다." },
  '33_1':  { example2: "The acquisition was valued at over two billion dollars.", example2Kr: "그 인수의 가치는 20억 달러 이상으로 평가되었다." },
  '33_2':  { example2: "The team set new benchmarks for customer service excellence.", example2Kr: "팀은 고객 서비스 우수성에 대한 새로운 기준을 세웠다." },
  '33_3':  { example2: "Effective collaboration relies on clear communication and mutual respect.", example2Kr: "효과적인 협업은 명확한 의사소통과 상호 존중에 달려 있다." },
  '33_4':  { example2: "Missing the deadline damaged the team's reputation with the client.", example2Kr: "마감 기한을 놓친 것이 고객과의 팀 명성을 손상시켰다." },
  '33_5':  { example2: "She found it difficult to delegate responsibility to junior members of staff.", example2Kr: "그녀는 하위 직원들에게 책임을 위임하는 것이 어렵다는 것을 알았다." },
  '33_6':  { example2: "The young entrepreneur raised funding from angel investors to launch her app.", example2Kr: "젊은 기업가는 앱 출시를 위해 엔젤 투자자들로부터 자금을 조달했다." },
  '33_7':  { example2: "A feasibility study will determine whether the expansion plan is viable.", example2Kr: "타당성 조사가 확장 계획이 실행 가능한지 여부를 결정할 것이다." },
  '33_8':  { example2: "The rigid hierarchy stifled creativity and slowed decision-making.", example2Kr: "경직된 계층 구조가 창의성을 억누르고 의사결정을 더디게 했다." },
  '33_9':  { example2: "Following the merger, several senior executives chose to resign.", example2Kr: "합병 이후 몇몇 고위 임원들이 사임하기로 했다." },
  '33_10': { example2: "The company decided to outsource its payroll to save time and money.", example2Kr: "회사는 시간과 비용을 절약하기 위해 급여 관리를 외주로 처리하기로 했다." },
  '33_11': { example2: "The overhaul of the supply chain led to significant cost savings.", example2Kr: "공급망의 전면 개편이 상당한 비용 절감으로 이어졌다." },
  '33_12': { example2: "Flexible working hours have a notable positive effect on employee productivity.", example2Kr: "유연 근무 시간은 직원 생산성에 눈에 띄는 긍정적 영향을 미친다." },
  '33_13': { example2: "The engineers tested the prototype rigorously before going into mass production.", example2Kr: "엔지니어들은 대량 생산에 들어가기 전에 시제품을 엄격하게 테스트했다." },
  '33_14': { example2: "Subscription services now account for a growing share of the company's revenue.", example2Kr: "구독 서비스가 이제 회사 수익의 증가하는 비율을 차지하고 있다." },
  '33_15': { example2: "All major stakeholders were briefed on the risks before the launch.", example2Kr: "출시 전에 모든 주요 이해관계자들이 위험에 대해 브리핑을 받았다." },
  '33_16': { example2: "The company revised its strategy in response to changing consumer trends.", example2Kr: "회사는 변화하는 소비자 트렌드에 대응하여 전략을 수정했다." },
  '33_17': { example2: "The high turnover rate was identified as the firm's biggest challenge.", example2Kr: "높은 이직률이 회사의 가장 큰 과제로 확인되었다." },
  '33_18': { example2: "The joint venture allowed both companies to enter new international markets.", example2Kr: "합작 투자를 통해 두 회사 모두 새로운 국제 시장에 진출할 수 있었다." },
  '33_19': { example2: "Training the workforce in new technologies is essential to remain competitive.", example2Kr: "경쟁력을 유지하기 위해서는 새로운 기술로 인력을 교육하는 것이 필수적이다." },

  // ── Day 34 고급 형용사 ──
  '34_0':  { example2: "The wording in the original document was ambiguous and open to different readings.", example2Kr: "원본 문서의 문구는 모호하여 다양한 해석이 가능했다." },
  '34_1':  { example2: "Becoming a concert pianist requires years of arduous practice.", example2Kr: "연주회 피아니스트가 되기 위해서는 수년간의 고된 연습이 필요하다." },
  '34_2':  { example2: "A coherent narrative helps readers follow the story's logic easily.", example2Kr: "일관성 있는 서사는 독자들이 이야기의 논리를 쉽게 따라가도록 돕는다." },
  '34_3':  { example2: "The lawyer made a compelling argument that convinced the jury.", example2Kr: "변호사는 배심원단을 설득하는 설득력 있는 주장을 펼쳤다." },
  '34_4':  { example2: "She has a comprehensive knowledge of European history and culture.", example2Kr: "그녀는 유럽의 역사와 문화에 대한 포괄적인 지식을 가지고 있다." },
  '34_5':  { example2: "The decision to close the community centre was highly controversial.", example2Kr: "지역 사회 센터를 폐쇄하기로 한 결정은 매우 논란이 많았다." },
  '34_6':  { example2: "Eyewitness accounts are often considered less credible than forensic evidence.", example2Kr: "목격자 진술은 종종 법의학적 증거보다 신뢰성이 낮은 것으로 간주된다." },
  '34_7':  { example2: "Prolonged exposure to noise can be detrimental to your hearing.", example2Kr: "장기간 소음에 노출되는 것은 청력에 해로울 수 있다." },
  '34_8':  { example2: "Peace in the region has proved elusive despite years of negotiation.", example2Kr: "수년간의 협상에도 불구하고 그 지역의 평화는 여전히 파악하기 힘든 것으로 증명되었다." },
  '34_9':  { example2: "His erratic sleep schedule was affecting his performance at work.", example2Kr: "그의 불규칙한 수면 스케줄이 직장에서의 성과에 영향을 미치고 있었다." },
  '34_10': { example2: "It is now feasible to cross the country entirely using electric vehicles.", example2Kr: "이제 전기차만을 사용하여 나라를 횡단하는 것이 가능하다." },
  '34_11': { example2: "With storm clouds gathering, a decision to evacuate seemed imminent.", example2Kr: "먹구름이 몰려들면서 대피 결정이 임박한 것처럼 보였다." },
  '34_12': { example2: "There are inherent risks in publishing personal information online.", example2Kr: "온라인에 개인 정보를 게시하는 데에는 내재적인 위험이 있다." },
  '34_13': { example2: "The conservation team was meticulous in restoring every detail of the painting.", example2Kr: "보존팀은 그림의 모든 세부 사항을 복원하는 데 꼼꼼했다." },
  '34_14': { example2: "That corner of the city was notorious for late-night disturbances.", example2Kr: "도시의 그 구역은 늦은 밤 소동으로 악명이 높았다." },
  '34_15': { example2: "Many manual jobs are now obsolete thanks to advances in automation.", example2Kr: "자동화의 발전 덕분에 많은 육체 노동 직업들이 이제 구식이 되었다." },
  '34_16': { example2: "Providing clean water to all must be treated as a paramount priority.", example2Kr: "모든 사람에게 깨끗한 물을 공급하는 것은 최우선 과제로 다루어져야 한다." },
  '34_17': { example2: "Rather than idealistic goals, the board sought pragmatic solutions to immediate problems.", example2Kr: "이상적인 목표보다는 이사회가 당면한 문제에 대한 실용적인 해결책을 추구했다." },
  '34_18': { example2: "Meeting her mentor had a profound and lasting effect on her career.", example2Kr: "멘토를 만난 것이 그녀의 경력에 심오하고 지속적인 영향을 미쳤다." },
  '34_19': { example2: "The spontaneous applause from the crowd surprised even the performer.", example2Kr: "관중의 자발적인 박수갈채는 공연자 자신도 놀라게 했다." },

  // ── Day 35 구동사 & 관용표현 ──
  '35_0':  { example2: "She refused to back down from her position, even under intense scrutiny.", example2Kr: "그녀는 강도 높은 비판을 받으면서도 자신의 입장에서 물러서기를 거부했다." },
  '35_1':  { example2: "Bear in mind that prices are likely to rise before the holiday season.", example2Kr: "휴가 시즌 전에 가격이 오를 가능성이 있다는 것을 명심하세요." },
  '35_2':  { example2: "The press blew the celebrity's minor faux pas out of proportion.", example2Kr: "언론은 그 연예인의 사소한 실수를 침소봉대했다." },
  '35_3':  { example2: "The ceasefire broke down within 48 hours of being announced.", example2Kr: "휴전은 발표된 지 48시간 이내에 결렬되었다." },
  '35_4':  { example2: "The invention of the printing press brought about a revolution in education.", example2Kr: "인쇄기의 발명이 교육에 혁명을 초래했다." },
  '35_5':  { example2: "Think carefully before you quit — you don't want to burn your bridges.", example2Kr: "그만두기 전에 신중히 생각해라 — 퇴로를 끊고 싶지 않을 거야." },
  '35_6':  { example2: "The survey was carried out over a period of six months.", example2Kr: "설문조사는 6개월에 걸쳐 수행되었다." },
  '35_7':  { example2: "It took her a long time to come to terms with the end of her marriage.", example2Kr: "결혼 생활의 끝을 받아들이는 데 그녀에게 오랜 시간이 걸렸다." },
  '35_8':  { example2: "In her speech, she drew on personal experience to highlight the issue.", example2Kr: "연설에서 그녀는 문제를 부각시키기 위해 개인적인 경험을 활용했다." },
  '35_9':  { example2: "The planned renovation fell through after funding was withdrawn.", example2Kr: "계획된 리노베이션은 자금이 철회된 후 무산되었다." },
  '35_10': { example2: "Overcrowding in prisons gave rise to increasing tensions and violence.", example2Kr: "교도소의 과밀이 증가하는 긴장과 폭력을 유발했다." },
  '35_11': { example2: "Strikers held out for a 10% pay rise and a reduction in working hours.", example2Kr: "파업 노동자들은 10% 임금 인상과 근로 시간 단축을 끝까지 요구했다." },
  '35_12': { example2: "The committee will look into the allegations of misconduct next week.", example2Kr: "위원회는 다음 주에 비위 혐의를 조사할 것이다." },
  '35_13': { example2: "He worked weekends to make up for the days he had taken off sick.", example2Kr: "그는 병가를 낸 날들을 만회하기 위해 주말에 일했다." },
  '35_14': { example2: "Diet and lifestyle play a significant role in long-term wellbeing.", example2Kr: "식이요법과 생활 방식은 장기적인 건강에 중요한 역할을 한다." },
  '35_15': { example2: "The reviewer pointed out several inconsistencies in the research methods.", example2Kr: "검토자는 연구 방법의 몇 가지 불일치를 지적했다." },
  '35_16': { example2: "The car ran out of fuel on the motorway and had to be towed.", example2Kr: "고속도로에서 차가 연료가 다 떨어져 견인되어야 했다." },
  '35_17': { example2: "Set aside your differences and focus on what you have in common.", example2Kr: "차이점을 제쳐두고 공통점에 집중하세요." },
  '35_18': { example2: "We must take into account the environmental impact of any new development.", example2Kr: "우리는 새로운 개발이 환경에 미치는 영향을 고려해야 한다." },
  '35_19': { example2: "The experiment turned out to be far more significant than anyone had anticipated.", example2Kr: "실험은 누구도 예상했던 것보다 훨씬 더 중요한 것으로 판명되었다." },

  // Day 36 — 학술 어휘 I
  '36_0':  { example2: "An ambiguous question on the test confused many students.", example2Kr: "시험의 모호한 문제가 많은 학생들을 혼란스럽게 했다." },
  '36_1':  { example2: "He drew an analogy between the brain and a computer to explain memory.", example2Kr: "그는 기억을 설명하기 위해 뇌와 컴퓨터 사이의 유추를 사용했다." },
  '36_2':  { example2: "Setting an arbitrary deadline without consultation upset the entire team.", example2Kr: "협의 없이 자의적인 마감일을 설정한 것이 팀 전체를 화나게 했다." },
  '36_3':  { example2: "Her argument was so coherent that everyone in the room was convinced.", example2Kr: "그녀의 주장은 너무 논리적이어서 방에 있는 모든 사람이 납득했다." },
  '36_4':  { example2: "The university offers a comprehensive program covering all aspects of business.", example2Kr: "그 대학교는 비즈니스의 모든 측면을 다루는 종합 프로그램을 제공한다." },
  '36_5':  { example2: "The two experts gave contradictory advice, leaving the client confused.", example2Kr: "두 전문가가 모순된 조언을 내놓아 고객을 혼란스럽게 만들었다." },
  '36_6':  { example2: "The new drug was approved only after extensive empirical testing.", example2Kr: "새 약물은 광범위한 실증적 검사 후에야 승인되었다." },
  '36_7':  { example2: "The instructions were not explicit enough, leading to several mistakes.", example2Kr: "지시 사항이 충분히 명시적이지 않아 여러 실수로 이어졌다." },
  '36_8':  { example2: "There was an implicit rule that junior staff never questioned the director.", example2Kr: "하위 직원은 절대 디렉터에게 이의를 제기하지 않는다는 암묵적인 규칙이 있었다." },
  '36_9':  { example2: "Trust is inherent in any successful long-term relationship.", example2Kr: "신뢰는 성공적인 장기적 관계에서 본질적인 요소이다." },
  '36_10': { example2: "The apparent paradox was resolved once the full context was understood.", example2Kr: "전체 맥락이 이해되자 명백한 역설이 해소되었다." },
  '36_11': { example2: "The report lacked a clear rationale for the proposed budget cuts.", example2Kr: "보고서에는 제안된 예산 삭감에 대한 명확한 근거가 부족했다." },
  '36_12': { example2: "His inspiring rhetoric motivated volunteers to join the campaign.", example2Kr: "그의 감동적인 수사가 자원봉사자들이 캠페인에 합류하도록 동기를 부여했다." },
  '36_13': { example2: "The final chapter offered a synthesis of all the themes explored in the book.", example2Kr: "마지막 장은 책에서 탐구된 모든 주제의 종합을 제공했다." },
  '36_14': { example2: "The research team spent two years testing the hypothesis in the field.", example2Kr: "연구팀은 현장에서 가설을 검증하는 데 2년을 보냈다." },
  '36_15': { example2: "Honesty remains a cardinal virtue in any professional setting.", example2Kr: "정직함은 어떠한 전문적인 환경에서도 가장 중요한 덕목으로 남아 있다." },
  '36_16': { example2: "The sequel was considered derivative, merely recycling the original's plot.", example2Kr: "속편은 원작의 줄거리를 단순히 재활용한 파생적인 작품으로 여겨졌다." },
  '36_17': { example2: "Further research is needed to fully substantiate the initial findings.", example2Kr: "초기 결과를 완전히 입증하기 위해 추가 연구가 필요하다." },
  '36_18': { example2: "The abstract of the research paper captured the key findings in just 200 words.", example2Kr: "연구 논문의 초록은 핵심 결과를 단 200단어로 담아냈다." },
  '36_19': { example2: "The school ran three concurrent programs to address different learning needs.", example2Kr: "학교는 다양한 학습 요구를 해결하기 위해 세 가지 동시 프로그램을 운영했다." },

  // Day 37 — 정치 & 사회 고급 어휘
  '37_0':  { example2: "Citizens complained that the bureaucracy delayed vital services for months.", example2Kr: "시민들은 관료적 절차가 중요한 서비스를 수개월 지연시켰다고 불평했다." },
  '37_1':  { example2: "He toured his constituency to listen to the concerns of local residents.", example2Kr: "그는 지역 주민들의 우려를 듣기 위해 선거구를 돌아다녔다." },
  '37_2':  { example2: "Widespread corruption made it nearly impossible to do business fairly.", example2Kr: "만연한 부패로 인해 공정하게 사업을 하는 것이 거의 불가능했다." },
  '37_3':  { example2: "Historians warned that the charismatic leader was showing signs of becoming a demagogue.", example2Kr: "역사가들은 그 카리스마 있는 지도자가 선동가가 될 조짐을 보이고 있다고 경고했다." },
  '37_4':  { example2: "The egalitarian school system gave all children access to the same resources.", example2Kr: "평등주의적인 학교 시스템은 모든 아이들에게 동일한 자원에 대한 접근을 제공했다." },
  '37_5':  { example2: "Regional hegemony shifted as economic power moved from West to East.", example2Kr: "경제력이 서방에서 동방으로 이동하면서 지역 패권이 변화했다." },
  '37_6':  { example2: "The candidate's ideology appealed strongly to younger, more progressive voters.", example2Kr: "그 후보의 이념은 더 젊고 진보적인 유권자들에게 강하게 어필했다." },
  '37_7':  { example2: "The international court ruled that the case fell within its jurisdiction.", example2Kr: "국제 재판소는 그 사건이 자신의 관할권 내에 있다고 판결했다." },
  '37_8':  { example2: "The new legislation requires all employers to provide paid parental leave.", example2Kr: "새 법률은 모든 고용주가 유급 육아 휴가를 제공하도록 요구한다." },
  '37_9':  { example2: "The environmental group issued a manifesto demanding immediate government action.", example2Kr: "환경 단체는 즉각적인 정부 조치를 요구하는 선언문을 발표했다." },
  '37_10': { example2: "The museum exhibited powerful photographs documenting political oppression.", example2Kr: "그 박물관은 정치적 억압을 기록한 강렬한 사진들을 전시했다." },
  '37_11': { example2: "The highly partisan debate produced no useful consensus.", example2Kr: "매우 당파적인 토론은 유용한 합의를 도출하지 못했다." },
  '37_12': { example2: "Students were taught to critically evaluate propaganda and media bias.", example2Kr: "학생들은 선전과 미디어 편향을 비판적으로 평가하도록 교육받았다." },
  '37_13': { example2: "The small island nation fiercely defended its cultural sovereignty.", example2Kr: "그 작은 섬나라는 자국의 문화적 주권을 맹렬히 수호했다." },
  '37_14': { example2: "The suffrage movement paved the way for equal political participation.", example2Kr: "참정권 운동은 동등한 정치 참여의 길을 열었다." },
  '37_15': { example2: "Life in the totalitarian regime was characterized by fear and censorship.", example2Kr: "전체주의 체제에서의 삶은 공포와 검열로 특징지어졌다." },
  '37_16': { example2: "The prime minister threatened to use his veto if the reforms were rejected.", example2Kr: "총리는 개혁안이 거부되면 거부권을 행사하겠다고 위협했다." },
  '37_17': { example2: "The spy successfully infiltrated the foreign intelligence network.", example2Kr: "그 스파이는 외국 정보 네트워크에 성공적으로 잠입했다." },
  '37_18': { example2: "Activists protested laws that disenfranchised people with criminal records.", example2Kr: "활동가들은 전과 기록이 있는 사람들의 권리를 박탈하는 법률에 항의했다." },
  '37_19': { example2: "Understanding geopolitics is essential for anyone studying international relations.", example2Kr: "지정학을 이해하는 것은 국제 관계를 공부하는 사람에게 필수적이다." },

  // Day 38 — 경제 & 금융 고급 어휘 II
  '38_0':  { example2: "The years of austerity left public services severely underfunded.", example2Kr: "수년간의 긴축 재정으로 공공 서비스 자금이 심각하게 부족해졌다." },
  '38_1':  { example2: "Experts predict that several small retailers face bankruptcy this year.", example2Kr: "전문가들은 올해 여러 소규모 소매업체들이 파산에 직면할 것으로 예측한다." },
  '38_2':  { example2: "Gold has traditionally been seen as a safe commodity during economic uncertainty.", example2Kr: "금은 전통적으로 경제적 불확실성 시기에 안전한 원자재로 여겨져 왔다." },
  '38_3':  { example2: "Japan struggled with deflation for over a decade, hampering economic growth.", example2Kr: "일본은 10년 이상 디플레이션과 씨름하며 경제 성장을 저해했다." },
  '38_4':  { example2: "Critics argued that deregulation of the energy market harmed consumers.", example2Kr: "비평가들은 에너지 시장의 규제 완화가 소비자에게 해를 끼쳤다고 주장했다." },
  '38_5':  { example2: "The annual dividend rose by 15%, delighting long-term shareholders.", example2Kr: "연간 배당금이 15% 상승하여 장기 주주들을 기쁘게 했다." },
  '38_6':  { example2: "Successful entrepreneurs are not afraid of taking calculated risks.", example2Kr: "성공한 기업가들은 계산된 위험을 감수하는 것을 두려워하지 않는다." },
  '38_7':  { example2: "The government's fiscal responsibility attracted international investor confidence.", example2Kr: "정부의 재정 책임감이 국제 투자자들의 신뢰를 끌어들였다." },
  '38_8':  { example2: "Central banks raised interest rates aggressively to bring down inflation.", example2Kr: "중앙은행들은 인플레이션을 억제하기 위해 적극적으로 금리를 인상했다." },
  '38_9':  { example2: "Small businesses can leverage social media to reach a global audience.", example2Kr: "중소기업들은 소셜 미디어를 활용하여 전 세계 고객층에 도달할 수 있다." },
  '38_10': { example2: "The central bank injected funds into the system to improve liquidity.", example2Kr: "중앙은행은 유동성을 개선하기 위해 시스템에 자금을 투입했다." },
  '38_11': { example2: "The tech giant's monopoly over search engines drew regulatory scrutiny.", example2Kr: "그 기술 대기업의 검색 엔진 독점이 규제 당국의 감시를 끌어들였다." },
  '38_12': { example2: "A well-diversified portfolio reduces the impact of any single investment loss.", example2Kr: "잘 분산된 포트폴리오는 단일 투자 손실의 영향을 줄여준다." },
  '38_13': { example2: "The recession that followed the financial crisis lasted nearly three years.", example2Kr: "금융 위기 이후 이어진 경기 침체는 거의 3년간 지속되었다." },
  '38_14': { example2: "Reckless speculation in cryptocurrencies led to enormous financial losses.", example2Kr: "암호화폐에 대한 무모한 투기가 엄청난 재정적 손실로 이어졌다." },
  '38_15': { example2: "Agricultural subsidies were criticized for distorting global food markets.", example2Kr: "농업 보조금이 세계 식품 시장을 왜곡한다는 비판을 받았다." },
  '38_16': { example2: "New tariffs on imported steel threatened to raise construction costs.", example2Kr: "수입 철강에 대한 새로운 관세가 건설 비용을 높일 것이라는 우려가 나왔다." },
  '38_17': { example2: "The stock's high volatility discouraged many risk-averse investors.", example2Kr: "그 주식의 높은 변동성이 많은 위험 회피 투자자들을 저망하게 했다." },
  '38_18': { example2: "Remittances from overseas workers account for a large share of the country's GDP.", example2Kr: "해외 근로자들의 송금이 그 나라 GDP의 큰 비중을 차지한다." },
  '38_19': { example2: "The startup used its intellectual property as collateral to secure a loan.", example2Kr: "스타트업은 대출을 확보하기 위해 지적 재산을 담보로 사용했다." },

  // Day 39 — 고급 부사 & 연결어
  '39_0':  { example2: "The new law was welcomed, albeit long overdue in coming.", example2Kr: "새 법률은 비록 늦게나마 환영받았다." },
  '39_1':  { example2: "The factory closed down; consequently, hundreds of workers lost their jobs.", example2Kr: "공장이 문을 닫았다; 결과적으로, 수백 명의 노동자들이 일자리를 잃었다." },
  '39_2':  { example2: "Urban areas tend to have higher wages; conversely, rural regions often have lower costs of living.", example2Kr: "도시 지역은 임금이 더 높은 경향이 있다; 반대로, 농촌 지역은 종종 생활비가 더 낮다." },
  '39_3':  { example2: "The candidate was experienced; furthermore, she had the backing of key stakeholders.", example2Kr: "그 후보는 경험이 있었다; 더욱이, 그녀는 핵심 이해관계자들의 지지를 받고 있었다." },
  '39_4':  { example2: "Henceforth, any complaints must be submitted in writing to management.", example2Kr: "이후부터 모든 불만은 서면으로 경영진에 제출해야 한다." },
  '39_5':  { example2: "He inadvertently deleted the wrong file and lost a week's worth of work.", example2Kr: "그는 무심코 잘못된 파일을 삭제하여 일주일치의 작업을 잃었다." },
  '39_6':  { example2: "The second experiment yielded likewise disappointing results.", example2Kr: "두 번째 실험도 마찬가지로 실망스러운 결과를 낳았다." },
  '39_7':  { example2: "The new software is faster; moreover, it consumes far less memory than its predecessor.", example2Kr: "새 소프트웨어는 더 빠르다; 더욱이 이전 버전보다 훨씬 적은 메모리를 사용한다." },
  '39_8':  { example2: "The funding was cut; nevertheless, the research team continued their work.", example2Kr: "자금이 삭감되었다; 그럼에도 불구하고 연구팀은 작업을 계속했다." },
  '39_9':  { example2: "Notwithstanding their differences, the two teams cooperated effectively.", example2Kr: "그들의 차이점에도 불구하고 두 팀은 효과적으로 협력했다." },
  '39_10': { example2: "The report was ostensibly about safety, but it was really about cost-cutting.", example2Kr: "그 보고서는 표면상으로는 안전에 관한 것이었지만, 실제로는 비용 절감에 관한 것이었다." },
  '39_11': { example2: "Voters overwhelmingly rejected the proposed constitutional amendment.", example2Kr: "유권자들은 제안된 헌법 개정안을 압도적으로 거부했다." },
  '39_12': { example2: "Paradoxically, the wealthiest nation in the region had the lowest literacy rate.", example2Kr: "역설적으로, 그 지역에서 가장 부유한 나라가 가장 낮은 문해율을 기록했다." },
  '39_13': { example2: "The delay was presumably caused by the unexpected snowstorm overnight.", example2Kr: "지연은 아마도 밤새 예상치 못한 눈보라로 인해 발생했을 것이다." },
  '39_14': { example2: "The system processes thousands of transactions simultaneously without errors.", example2Kr: "그 시스템은 오류 없이 수천 건의 거래를 동시에 처리한다." },
  '39_15': { example2: "She completed her degree and subsequently won a national research award.", example2Kr: "그녀는 학위를 취득하고 이후 전국 연구상을 수상했다." },
  '39_16': { example2: "The budget was reduced, and all departments adjusted their spending accordingly.", example2Kr: "예산이 삭감되었고, 모든 부서는 그에 맞게 지출을 조정했다." },
  '39_17': { example2: "Incidentally, the study also revealed unexpected benefits for mental health.", example2Kr: "그런데, 연구는 정신 건강에 대한 예상치 못한 혜택도 밝혀냈다." },
  '39_18': { example2: "The region is predominantly agricultural, with few urban centers.", example2Kr: "그 지역은 도시 중심지가 거의 없는 주로 농업 지역이다." },
  '39_19': { example2: "They implemented a new system whereby employees could submit feedback anonymously.", example2Kr: "그들은 직원들이 익명으로 의견을 제출할 수 있는 새로운 시스템을 도입했다." },

  // Day 40 — 과학 & 기술 고급 어휘 II
  '40_0':  { example2: "Researchers are developing algorithms to detect early signs of Alzheimer's disease.", example2Kr: "연구자들은 알츠하이머병의 초기 징후를 감지하는 알고리즘을 개발하고 있다." },
  '40_1':  { example2: "The new policy acted as a catalyst for sweeping reforms in the education system.", example2Kr: "새 정책은 교육 시스템의 광범위한 개혁을 위한 촉매제 역할을 했다." },
  '40_2':  { example2: "An extra chromosome in cell 21 is the cause of Down syndrome.", example2Kr: "21번 세포의 추가 염색체가 다운 증후군의 원인이다." },
  '40_3':  { example2: "Protecting the local ecosystem requires a comprehensive conservation strategy.", example2Kr: "지역 생태계를 보호하려면 포괄적인 보전 전략이 필요하다." },
  '40_4':  { example2: "Scientists study entropy to understand why complex systems tend to break down.", example2Kr: "과학자들은 복잡한 시스템이 왜 붕괴되는 경향이 있는지 이해하기 위해 엔트로피를 연구한다." },
  '40_5':  { example2: "The genome of the new virus was sequenced within days of its discovery.", example2Kr: "발견된 지 며칠 만에 새 바이러스의 게놈이 해독되었다." },
  '40_6':  { example2: "Nanotechnology promises to revolutionize drug delivery directly to cancer cells.", example2Kr: "나노기술은 암세포에 직접 약물을 전달하는 방식을 혁신할 것으로 기대된다." },
  '40_7':  { example2: "The plant's roots absorb nutrients through osmosis from the surrounding soil.", example2Kr: "식물의 뿌리는 주변 토양으로부터 삼투를 통해 영양분을 흡수한다." },
  '40_8':  { example2: "The rise of artificial intelligence represents a paradigm shift in the job market.", example2Kr: "인공지능의 부상은 취업 시장의 패러다임 전환을 나타낸다." },
  '40_9':  { example2: "Without photosynthesis, life on Earth as we know it could not exist.", example2Kr: "광합성이 없다면 우리가 알고 있는 지구상의 생명체는 존재할 수 없을 것이다." },
  '40_10': { example2: "Quantum mechanics challenges our everyday intuitions about how matter behaves.", example2Kr: "양자 역학은 물질이 어떻게 행동하는지에 대한 우리의 일상적인 직관에 도전한다." },
  '40_11': { example2: "The radioactive contamination forced thousands of residents to evacuate permanently.", example2Kr: "방사성 오염으로 수천 명의 주민들이 영구적으로 대피해야 했다." },
  '40_12': { example2: "The spacecraft must reach escape velocity to break free from Earth's gravity.", example2Kr: "우주선은 지구 중력에서 벗어나기 위해 탈출 속도에 도달해야 한다." },
  '40_13': { example2: "Internet providers are upgrading infrastructure to offer greater bandwidth.", example2Kr: "인터넷 제공업체들은 더 큰 대역폭을 제공하기 위해 인프라를 업그레이드하고 있다." },
  '40_14': { example2: "The combustion of fossil fuels remains the primary source of greenhouse gas emissions.", example2Kr: "화석 연료의 연소는 온실 가스 배출의 주요 원인으로 남아 있다." },
  '40_15': { example2: "Breakthroughs in neuroscience have led to more effective treatments for depression.", example2Kr: "신경과학의 획기적인 발전이 우울증에 대한 보다 효과적인 치료법으로 이어졌다." },
  '40_16': { example2: "A computer simulation predicted the storm's path with remarkable accuracy.", example2Kr: "컴퓨터 시뮬레이션이 폭풍의 경로를 놀라운 정확도로 예측했다." },
  '40_17': { example2: "Biodiversity loss threatens the stability of ecosystems around the world.", example2Kr: "생물 다양성 손실이 전 세계 생태계의 안정성을 위협하고 있다." },
  '40_18': { example2: "A slow metabolism can contribute to weight gain if dietary habits don't change.", example2Kr: "식습관이 바뀌지 않으면 느린 신진대사가 체중 증가의 원인이 될 수 있다." },
  '40_19': { example2: "Thermodynamics plays a key role in the design of efficient engines.", example2Kr: "열역학은 효율적인 엔진 설계에 핵심적인 역할을 한다." },

  // Day 41 — 예술 & 문화 어휘
  '41_0':  { example2: "The architect paid careful attention to the aesthetics of the public space.", example2Kr: "건축가는 공공 공간의 미학에 세심한 주의를 기울였다." },
  '41_1':  { example2: "The play is a powerful allegory for the dangers of unchecked corporate greed.", example2Kr: "그 연극은 견제받지 않는 기업의 탐욕이 가진 위험성에 대한 강렬한 알레고리이다." },
  '41_2':  { example2: "The avant-garde composer was initially rejected but later celebrated worldwide.", example2Kr: "그 전위 작곡가는 처음에는 외면받았지만 나중에는 전 세계적으로 찬사를 받았다." },
  '41_3':  { example2: "The political cartoon's caricature was so exaggerated it became a national joke.", example2Kr: "그 정치 만화의 캐리커처는 너무 과장되어 국민적인 웃음거리가 되었다." },
  '41_4':  { example2: "The choreography blended traditional folk dance with contemporary hip-hop.", example2Kr: "그 안무는 전통 민속춤과 현대 힙합을 혼합했다." },
  '41_5':  { example2: "As a connoisseur of jazz, she could name every musician on the recording.", example2Kr: "재즈 감정가로서 그녀는 녹음에 참여한 모든 음악가의 이름을 댈 수 있었다." },
  '41_6':  { example2: "The lotus flower serves as a central motif in much of Eastern art and culture.", example2Kr: "연꽃은 동양의 예술과 문화에서 중심적인 모티프 역할을 한다." },
  '41_7':  { example2: "The film's characters spoke with nuance, revealing emotions through subtle gestures.", example2Kr: "영화의 등장인물들은 뉘앙스 있게 말하며 미묘한 제스처로 감정을 드러냈다." },
  '41_8':  { example2: "The gallery's generous patron donated a new wing to house the modern collection.", example2Kr: "갤러리의 관대한 후원자는 현대 컬렉션을 보관할 새 날개를 기증했다." },
  '41_9':  { example2: "The young swimmer was hailed as a prodigy after breaking three world records.", example2Kr: "그 어린 수영 선수는 세 개의 세계 기록을 깬 후 신동으로 환호받았다." },
  '41_10': { example2: "The pianist expanded his repertoire to include works by lesser-known composers.", example2Kr: "피아니스트는 덜 알려진 작곡가들의 작품을 포함하도록 레퍼토리를 확장했다." },
  '41_11': { example2: "The sketch show was sharp satire that exposed the absurdity of modern bureaucracy.", example2Kr: "그 스케치 쇼는 현대 관료주의의 부조리를 드러낸 날카로운 풍자였다." },
  '41_12': { example2: "The famous soliloquy in Act Two reveals the character's inner conflict.", example2Kr: "2막의 유명한 독백은 등장인물의 내면 갈등을 드러낸다." },
  '41_13': { example2: "Local writers were encouraged to write in the vernacular to connect with readers.", example2Kr: "지역 작가들은 독자들과 공감하기 위해 방언으로 쓰도록 장려받았다." },
  '41_14': { example2: "His stand-up comedy routine was a mix of scripted jokes and sharp improvisation.", example2Kr: "그의 스탠드업 코미디는 각본 있는 농담과 날카로운 즉흥 연기의 혼합이었다." },
  '41_15': { example2: "The neighborhood's artistic renaissance attracted tourists and new residents alike.", example2Kr: "그 동네의 예술적 부흥이 관광객과 신규 주민 모두를 끌어들였다." },
  '41_16': { example2: "Critics dismissed the novel as a clumsy pastiche of better-known works.", example2Kr: "비평가들은 그 소설을 더 잘 알려진 작품들의 어설픈 패스티시라고 일축했다." },
  '41_17': { example2: "The curator spent months negotiating to bring the rare sculptures to the gallery.", example2Kr: "큐레이터는 희귀한 조각품을 갤러리로 가져오기 위해 수개월간 협상했다." },
  '41_18': { example2: "The author crossed multiple genres, blending horror with dark comedy.", example2Kr: "그 작가는 공포와 다크 코미디를 혼합하며 여러 장르를 교차했다." },
  '41_19': { example2: "The cinematography used long, sweeping shots to convey the vastness of the landscape.", example2Kr: "그 영화 촬영법은 긴 스위핑 샷을 사용하여 경치의 광대함을 전달했다." },

  // Day 42 — 의학 & 심리 고급 어휘 II
  '42_0':  { example2: "The soldier returned from the front with partial amnesia, unable to recall key events.", example2Kr: "그 병사는 핵심 사건들을 기억하지 못하는 부분적 기억 상실증을 갖고 전선에서 돌아왔다." },
  '42_1':  { example2: "Local anesthetic was used so the patient remained awake during the procedure.", example2Kr: "환자가 시술 중에 깨어 있을 수 있도록 국소 마취제가 사용되었다." },
  '42_2':  { example2: "Managing bipolar disorder often requires a combination of medication and therapy.", example2Kr: "양극성 장애를 관리하려면 종종 약물과 치료의 병행이 필요하다." },
  '42_3':  { example2: "Playing brain training games can help slow the decline of cognition in aging adults.", example2Kr: "뇌 훈련 게임을 하면 노화하는 성인의 인지 기능 저하를 늦추는 데 도움이 될 수 있다." },
  '42_4':  { example2: "Patients recovering from surgery sometimes experience medication-induced hallucinations.", example2Kr: "수술에서 회복 중인 환자들은 때때로 약물로 인한 환각을 경험한다." },
  '42_5':  { example2: "Breast-feeding is known to boost a baby's immunity in the first months of life.", example2Kr: "모유 수유는 생후 첫 몇 달 동안 아기의 면역력을 강화하는 것으로 알려져 있다." },
  '42_6':  { example2: "The oncologist confirmed that the tumor was malignant and ordered surgery.", example2Kr: "종양 전문의는 종양이 악성임을 확인하고 수술을 지시했다." },
  '42_7':  { example2: "The neurological effects of the virus persisted long after the initial infection cleared.", example2Kr: "바이러스의 신경학적 영향은 초기 감염이 해소된 후에도 오랫동안 지속되었다." },
  '42_8':  { example2: "The study of pathology has helped scientists understand how cancers develop.", example2Kr: "병리학 연구는 과학자들이 암이 어떻게 발생하는지 이해하는 데 도움을 주었다." },
  '42_9':  { example2: "The placebo effect demonstrates the powerful connection between mind and body.", example2Kr: "플라시보 효과는 마음과 몸 사이의 강력한 연결을 보여준다." },
  '42_10': { example2: "With proper treatment, the doctor gave a favorable prognosis for a full recovery.", example2Kr: "적절한 치료를 받으면 의사는 완전한 회복에 대한 좋은 예후를 내렸다." },
  '42_11': { example2: "The new psychiatric clinic provides accessible mental health support to all residents.", example2Kr: "새 정신과 클리닉은 모든 주민에게 접근 가능한 정신 건강 지원을 제공한다." },
  '42_12': { example2: "Speech rehabilitation after a brain injury can take many months of hard work.", example2Kr: "뇌 손상 후 언어 재활은 수개월간의 노력이 필요할 수 있다." },
  '42_13': { example2: "Burnout syndrome is increasingly recognized as a serious occupational health issue.", example2Kr: "번아웃 증후군은 심각한 직업 건강 문제로 점점 더 인정받고 있다." },
  '42_14': { example2: "Children with chronic asthma may need to carry an inhaler at all times.", example2Kr: "만성 천식을 가진 어린이들은 항상 흡입기를 갖고 다녀야 할 수도 있다." },
  '42_15': { example2: "The diagnosis was delivered sensitively by the specialist to minimize patient distress.", example2Kr: "전문의는 환자의 고통을 최소화하기 위해 진단을 세심하게 전달했다." },
  '42_16': { example2: "Witnessing violence in childhood can result in lasting psychological trauma.", example2Kr: "어린 시절 폭력을 목격하는 것은 지속적인 심리적 트라우마를 초래할 수 있다." },
  '42_17': { example2: "The vaccination program successfully reduced the annual death toll from influenza.", example2Kr: "예방접종 프로그램은 인플루엔자로 인한 연간 사망자 수를 성공적으로 줄였다." },
  '42_18': { example2: "Health officials declared an epidemic after the disease spread to five cities.", example2Kr: "보건 당국은 질병이 다섯 개 도시로 확산된 후 전염병을 선포했다." },
  '42_19': { example2: "Addiction to prescription painkillers has become a growing public health crisis.", example2Kr: "처방 진통제 중독이 점점 커지는 공중 보건 위기가 되고 있다." },

  // Day 43 — 법률 & 국제관계 고급 어휘 II
  '43_0':  { example2: "The acquittal was appealed by prosecutors, who argued evidence had been overlooked.", example2Kr: "검사들은 증거가 간과되었다고 주장하며 무죄 판결에 항소했다." },
  '43_1':  { example2: "The company's CEO submitted an affidavit denying all knowledge of the fraud.", example2Kr: "회사 CEO는 사기에 대한 모든 사실을 부인하는 선서 진술서를 제출했다." },
  '43_2':  { example2: "Both parties agreed to submit the contract dispute to binding arbitration.", example2Kr: "양측은 계약 분쟁을 구속력 있는 중재에 제출하기로 합의했다." },
  '43_3':  { example2: "The bilateral summit aimed to strengthen economic and cultural ties between the nations.", example2Kr: "양자 정상회담은 두 나라 간의 경제적·문화적 유대를 강화하는 것을 목표로 했다." },
  '43_4':  { example2: "The judge showed clemency, reducing the sentence in light of the defendant's age.", example2Kr: "판사는 피고의 나이를 고려하여 관용을 베풀어 형량을 줄였다." },
  '43_5':  { example2: "She won significant damages in a defamation lawsuit against the tabloid newspaper.", example2Kr: "그녀는 타블로이드 신문을 상대로 한 명예훼손 소송에서 상당한 손해 배상을 받아냈다." },
  '43_6':  { example2: "The alliance relied on collective deterrence to keep potential aggressors at bay.", example2Kr: "그 동맹은 잠재적인 침략자들을 억제하기 위해 집단적 억지력에 의존했다." },
  '43_7':  { example2: "The extradition request was delayed by lengthy legal proceedings in both countries.", example2Kr: "범죄인 인도 요청이 양국에서 오랜 법적 절차로 인해 지연되었다." },
  '43_8':  { example2: "Under the settlement agreement, indemnity was paid to all affected employees.", example2Kr: "합의 계약에 따라 모든 피해 직원들에게 배상금이 지급되었다." },
  '43_9':  { example2: "The threat of litigation forced the manufacturer to recall the defective product.", example2Kr: "소송 위협으로 인해 제조업체는 결함 제품을 리콜하지 않을 수 없었다." },
  '43_10': { example2: "The multilateral peace talks involved representatives from twelve different nations.", example2Kr: "다자 평화 회담에는 12개 국가의 대표들이 참여했다." },
  '43_11': { example2: "He was convicted of perjury after his testimony was proved false by video evidence.", example2Kr: "그는 동영상 증거로 진술이 허위로 밝혀진 뒤 위증죄로 유죄 판결을 받았다." },
  '43_12': { example2: "The plaintiff sought compensation for both physical injury and loss of earnings.", example2Kr: "원고는 신체 상해와 소득 손실 모두에 대한 보상을 청구했다." },
  '43_13': { example2: "The landmark judgment set a precedent that protected whistleblowers from dismissal.", example2Kr: "획기적인 판결이 내부 고발자를 해고로부터 보호하는 선례를 설정했다." },
  '43_14': { example2: "Ratification of the peace treaty was delayed by disagreements in the upper house.", example2Kr: "평화 조약의 비준이 상원의 의견 불일치로 인해 지연되었다." },
  '43_15': { example2: "The government program provided restitution to communities affected by industrial pollution.", example2Kr: "정부 프로그램은 산업 오염으로 피해를 입은 지역 사회에 배상을 제공했다." },
  '43_16': { example2: "International sanctions cut off the regime's access to global financial markets.", example2Kr: "국제 제재가 그 정권의 글로벌 금융 시장 접근을 차단했다." },
  '43_17': { example2: "Key executives were issued subpoenas as part of the federal corruption investigation.", example2Kr: "주요 임원들이 연방 부패 수사의 일환으로 소환장을 받았다." },
  '43_18': { example2: "The statutory right to a fair trial is enshrined in the nation's constitution.", example2Kr: "공정한 재판을 받을 법정 권리는 그 나라의 헌법에 명시되어 있다." },
  '43_19': { example2: "Hundreds of dissidents fled the country and sought asylum abroad.", example2Kr: "수백 명의 반체제 인사들이 나라를 탈출하여 해외에서 망명을 신청했다." },

  // Day 44 — 구동사 & 관용표현 III
  '44_0':  { example2: "Renewable energy now accounts for nearly a third of the country's total electricity.", example2Kr: "재생에너지가 이제 국가 전체 전력의 거의 3분의 1을 차지하고 있다." },
  '44_1':  { example2: "The investment in new technology is beginning to bear fruit with record productivity.", example2Kr: "새로운 기술에 대한 투자가 기록적인 생산성으로 결실을 맺기 시작하고 있다." },
  '44_2':  { example2: "He stayed late every night to catch up with the backlog of unanswered emails.", example2Kr: "그는 답신하지 못한 이메일 적체를 해소하기 위해 매일 밤 늦게까지 남았다." },
  '44_3':  { example2: "Travelling abroad, she came across a hidden café that became her favorite.", example2Kr: "해외를 여행하던 중 그녀는 자신이 가장 좋아하는 숨겨진 카페를 우연히 발견했다." },
  '44_4':  { example2: "The building inspector found evidence that the developer had cut corners on insulation.", example2Kr: "건물 검사관은 개발업자가 단열재에 편법을 썼다는 증거를 발견했다." },
  '44_5':  { example2: "The company had to face up to the reality that the product was commercially unviable.", example2Kr: "회사는 제품이 상업적으로 사업성이 없다는 현실에 맞서야 했다." },
  '44_6':  { example2: "He didn't get away with the tax fraud — auditors caught the discrepancies.", example2Kr: "그는 세금 사기를 피할 수 없었다 — 감사관들이 불일치를 발견했다." },
  '44_7':  { example2: "Despite the recession, the small bookshop managed to hang on to its loyal customer base.", example2Kr: "경기 침체에도 불구하고 작은 서점은 충성스러운 고객층을 유지했다." },
  '44_8':  { example2: "In a nutshell, the project failed because of poor planning and lack of funding.", example2Kr: "한마디로, 그 프로젝트는 부실한 기획과 자금 부족으로 실패했다." },
  '44_9':  { example2: "The authorities kept tabs on the suspect's movements using CCTV footage.", example2Kr: "당국은 CCTV 영상을 이용하여 용의자의 동향을 감시했다." },
  '44_10': { example2: "Therapy helped him let go of the guilt he had carried since childhood.", example2Kr: "치료가 그가 어린 시절부터 가지고 있던 죄책감을 내려놓는 데 도움이 되었다." },
  '44_11': { example2: "Students on exchange programs should make the most of every cultural experience.", example2Kr: "교환 학생 프로그램에 참여한 학생들은 모든 문화적 경험을 최대한 활용해야 한다." },
  '44_12': { example2: "Many voters are on the fence and could swing the election either way.", example2Kr: "많은 유권자들이 부동층이어서 선거 결과를 어느 쪽으로든 결정할 수 있다." },
  '44_13': { example2: "Experienced nurses can quickly pick up on subtle changes in a patient's condition.", example2Kr: "경험 많은 간호사들은 환자 상태의 미묘한 변화를 빠르게 알아챌 수 있다." },
  '44_14': { example2: "She kept putting off the dentist appointment until the toothache became unbearable.", example2Kr: "그녀는 치통이 참을 수 없어질 때까지 치과 예약을 계속 미뤘다." },
  '44_15': { example2: "He saw through the flattery and recognized a hidden agenda behind the praise.", example2Kr: "그는 아첨을 꿰뚫어 보고 칭찬 뒤에 숨겨진 의도를 알아챘다." },
  '44_16': { example2: "The leaked documents threw light on the secret negotiations between the two governments.", example2Kr: "유출된 문서들이 두 정부 간의 비밀 협상을 밝혔다." },
  '44_17': { example2: "The counsellor helped the family deal with the breakdown in communication.", example2Kr: "상담사는 가족이 소통 단절 문제에 대처하도록 도왔다." },
  '44_18': { example2: "He started as a junior researcher but ended up leading the entire department.", example2Kr: "그는 주임 연구원으로 시작했지만 결국 부서 전체를 이끌게 되었다." },
  '44_19': { example2: "A senior colleague agreed to fill in for her while she was on maternity leave.", example2Kr: "선임 동료가 그녀의 육아 휴직 기간 동안 대신해 주기로 했다." },

  // Day 45 — TOEFL 빈출 고급 어휘
  '45_0':  { example2: "The psychiatrist noted several aberrant behaviors that warranted further assessment.", example2Kr: "정신과 의사는 추가 평가가 필요한 여러 비정상적인 행동에 주목했다." },
  '45_1':  { example2: "A responsible traveler must be cognizant of local customs and social norms.", example2Kr: "책임감 있는 여행자는 현지 관습과 사회적 규범을 인식하고 있어야 한다." },
  '45_2':  { example2: "The DNA evidence corroborated the alibi that the suspect had provided.", example2Kr: "DNA 증거가 용의자가 제공한 알리바이를 뒷받침했다." },
  '45_3':  { example2: "Years of public sector cuts have diminished the quality of essential services.", example2Kr: "수년간의 공공 부문 삭감이 필수 서비스의 질을 약화시켰다." },
  '45_4':  { example2: "Her eloquent defense of press freedom earned her widespread admiration.", example2Kr: "언론 자유에 대한 그녀의 설득력 있는 옹호가 광범위한 찬사를 받았다." },
  '45_5':  { example2: "Poverty has become endemic in parts of the city despite decades of regeneration efforts.", example2Kr: "수십 년간의 도시 재생 노력에도 불구하고 부패가 도시 일부 지역에서 고질적이 되었다." },
  '45_6':  { example2: "Online trends are ephemeral — what is viral today may be forgotten tomorrow.", example2Kr: "온라인 트렌드는 덧없다 — 오늘 바이럴되는 것이 내일은 잊혀질 수 있다." },
  '45_7':  { example2: "Cutting the mental health budget will only exacerbate the crisis in hospitals.", example2Kr: "정신 건강 예산을 삭감하면 병원의 위기를 악화시킬 뿐이다." },
  '45_8':  { example2: "Balancing academic study with a part-time job presents a formidable challenge.", example2Kr: "학업과 아르바이트를 병행하는 것은 어마어마한 도전을 제시한다." },
  '45_9':  { example2: "Her idiosyncratic use of color made her paintings instantly recognizable.", example2Kr: "색채에 대한 그녀의 독특한 사용법이 그녀의 그림을 즉시 알아볼 수 있게 했다." },
  '45_10': { example2: "The skyscraper's bold modern design looked incongruous among the historic buildings.", example2Kr: "고층 빌딩의 과감한 현대적 디자인은 역사적 건물들 사이에서 어울리지 않아 보였다." },
  '45_11': { example2: "Planting trees along streets can mitigate the urban heat island effect significantly.", example2Kr: "거리에 나무를 심으면 도시 열섬 효과를 크게 완화할 수 있다." },
  '45_12': { example2: "Physical maps became obsolete once digital navigation apps became widely available.", example2Kr: "디지털 내비게이션 앱이 널리 보급되자 지도책은 쓸모없게 되었다." },
  '45_13': { example2: "His refusal to accept orthodox explanations eventually led to a ground-breaking discovery.", example2Kr: "정통적인 설명을 받아들이기를 거부한 그의 태도가 결국 획기적인 발견으로 이어졌다." },
  '45_14': { example2: "The housing crisis is polarizing communities between wealthy homeowners and renters.", example2Kr: "주택 위기가 부유한 집주인과 세입자 간에 지역 사회를 양극화하고 있다." },
  '45_15': { example2: "Gig workers often live in precarious conditions with no job security or benefits.", example2Kr: "긱 경제 노동자들은 종종 고용 보장이나 복리 후생 없이 불안정한 상태로 생활한다." },
  '45_16': { example2: "Deep-sea plastic waste continues to proliferate despite international cleanup efforts.", example2Kr: "국제적인 정화 노력에도 불구하고 심해 플라스틱 쓰레기가 계속 확산되고 있다." },
  '45_17': { example2: "The editor cut all superfluous paragraphs to tighten the flow of the article.", example2Kr: "편집자는 기사의 흐름을 다듬기 위해 불필요한 단락을 모두 잘라냈다." },
  '45_18': { example2: "Even the most brilliant careers are transient against the backdrop of history.", example2Kr: "가장 빛나는 경력도 역사의 배경에 비추면 일시적이다." },
  '45_19': { example2: "The seminar examined the dialectical tension between freedom and social responsibility.", example2Kr: "세미나는 자유와 사회적 책임 사이의 변증법적 긴장을 검토했다." },

  // Day 46 — 환경 & 에너지 고급 어휘 II
  '46_0':  { example2: "The government invested heavily in renewable energy infrastructure to reduce coal dependency.", example2Kr: "정부는 석탄 의존도를 줄이기 위해 재생 에너지 인프라에 막대한 투자를 했다." },
  '46_1':  { example2: "The hotel chain adopted sustainable tourism practices to protect the local environment.", example2Kr: "호텔 체인은 지역 환경을 보호하기 위해 지속 가능한 관광 관행을 채택했다." },
  '46_2':  { example2: "Stopping deforestation is critical to preserving the Earth's oxygen supply.", example2Kr: "삼림 벌채를 막는 것은 지구의 산소 공급 보존에 매우 중요하다." },
  '46_3':  { example2: "New regulations require manufacturers to dramatically reduce factory emissions.", example2Kr: "새 규정은 제조업체들이 공장 배출량을 대폭 줄이도록 요구한다." },
  '46_4':  { example2: "A chemical spill contaminated the local water supply, causing public health concerns.", example2Kr: "화학물질 유출이 지역 수도를 오염시켜 공중 보건 우려를 일으켰다." },
  '46_5':  { example2: "Heavy rainfall accelerated the erosion of the hillside, endangering homes below.", example2Kr: "폭우가 언덕의 침식을 가속화해 아래의 주택들을 위험에 빠뜨렸다." },
  '46_6':  { example2: "The teacher showed students photographs of animals that became extinct in the last century.", example2Kr: "선생님은 지난 세기에 멸종된 동물들의 사진을 학생들에게 보여주었다." },
  '46_7':  { example2: "Environmental groups are fighting to protect the remaining habitat of the endangered tigers.", example2Kr: "환경 단체들이 멸종 위기의 호랑이들의 남은 서식지를 보호하기 위해 싸우고 있다." },
  '46_8':  { example2: "The drought forced farmers to abandon their fields and seek alternative income sources.", example2Kr: "가뭄으로 인해 농부들은 밭을 버리고 대안적인 수입원을 찾아야 했다." },
  '46_9':  { example2: "Scientists studying the glacier discovered it had retreated by five kilometers in just a decade.", example2Kr: "빙하를 연구하는 과학자들이 빙하가 불과 10년 만에 5킬로미터 후퇴했다는 사실을 발견했다." },
  '46_10': { example2: "The melting of permafrost in Siberia could release enough methane to accelerate global warming.", example2Kr: "시베리아의 영구 동토층 해빙이 지구 온난화를 가속화하기에 충분한 메탄을 방출할 수 있다." },
  '46_11': { example2: "The startup developed biodegradable cutlery to replace plastic utensils at outdoor events.", example2Kr: "그 스타트업은 야외 행사에서 플라스틱 식기를 대체하기 위한 생분해성 식기를 개발했다." },
  '46_12': { example2: "Reforestation projects are helping to restore ecosystems damaged by decades of logging.", example2Kr: "재조림 프로젝트가 수십 년간의 벌목으로 손상된 생태계를 복원하는 데 도움이 되고 있다." },
  '46_13': { example2: "Residents wore masks as thick smog reduced visibility to just a few meters.", example2Kr: "두꺼운 스모그가 가시거리를 불과 몇 미터로 줄이자 주민들이 마스크를 착용했다." },
  '46_14': { example2: "Engineers are exploring geothermal energy as a baseload power source in volcanic regions.", example2Kr: "엔지니어들이 화산 지역에서 기저 부하 전력원으로 지열 에너지를 탐색하고 있다." },
  '46_15': { example2: "Coastal regions increasingly rely on desalination as freshwater supplies diminish.", example2Kr: "담수 공급이 줄어들면서 해안 지역들이 점점 더 담수화에 의존하고 있다." },
  '46_16': { example2: "Pollution from agricultural runoff has contaminated the region's main aquifer.", example2Kr: "농업 유출수의 오염이 지역의 주 대수층을 오염시켰다." },
  '46_17': { example2: "Climate models predict that extreme events such as heavy precipitation will increase.", example2Kr: "기후 모델들은 폭우와 같은 극단적인 사건이 증가할 것으로 예측한다." },
  '46_18': { example2: "The policy supports soil carbon sequestration through changes in agricultural practices.", example2Kr: "그 정책은 농업 관행의 변화를 통한 토양 탄소 격리를 지원한다." },
  '46_19': { example2: "Critics question whether carbon capture technology can scale up quickly enough to matter.", example2Kr: "비평가들은 탄소 포집 기술이 충분히 빠르게 확장될 수 있는지에 의문을 제기한다." },

  // Day 47 — 역사 & 문명 어휘
  '47_0':  { example2: "The myths of antiquity still influence our understanding of heroism and morality.", example2Kr: "고대의 신화들이 여전히 영웅주의와 도덕성에 대한 우리의 이해에 영향을 미친다." },
  '47_1':  { example2: "Underwater archaeology has revealed entire cities swallowed by rising seas.", example2Kr: "수중 고고학이 상승하는 바다에 삼켜진 도시 전체를 밝혀냈다." },
  '47_2':  { example2: "The artifact was so delicate that it had to be examined under special lighting.", example2Kr: "그 유물은 너무 섬세하여 특수 조명 아래서 검사해야 했다." },
  '47_3':  { example2: "The BBC series chronicled the rise and fall of the British Empire over three centuries.", example2Kr: "BBC 시리즈는 3세기에 걸친 영국 제국의 흥망성쇠를 기록했다." },
  '47_4':  { example2: "The Joseon Dynasty ruled Korea for over five hundred years.", example2Kr: "조선 왕조는 500년 이상 한국을 통치했다." },
  '47_5':  { example2: "The British Empire once controlled nearly a quarter of the world's land surface.", example2Kr: "영국 제국은 한때 세계 육지 표면의 거의 4분의 1을 지배했다." },
  '47_6':  { example2: "The feudal lord demanded heavy taxes and military service from peasants on his land.", example2Kr: "봉건 영주는 자신의 땅에 있는 농민들에게 무거운 세금과 군역을 요구했다." },
  '47_7':  { example2: "The government issued an apology for historical injustices against indigenous communities.", example2Kr: "정부는 원주민 공동체에 대한 역사적 불의에 사과했다." },
  '47_8':  { example2: "The architectural legacy of ancient Rome can still be seen across Europe today.", example2Kr: "고대 로마의 건축 유산은 오늘날에도 유럽 전역에서 볼 수 있다." },
  '47_9':  { example2: "Medieval scholars preserved and translated many ancient Greek philosophical texts.", example2Kr: "중세 학자들은 많은 고대 그리스 철학 텍스트를 보존하고 번역했다." },
  '47_10': { example2: "The museum dedicated an entire wing to examining the violent history of colonialism.", example2Kr: "박물관은 식민주의의 폭력적인 역사를 검토하는 데 전체 날개를 할애했다." },
  '47_11': { example2: "A group of researchers studied the nomadic lifestyle of herders in Central Asia.", example2Kr: "연구자 그룹이 중앙아시아 목동들의 유목 생활 방식을 연구했다." },
  '47_12': { example2: "The play portrayed the king as a tyrant who sacrificed his people for personal glory.", example2Kr: "그 연극은 개인적인 영광을 위해 자신의 백성을 희생시킨 폭군으로 왕을 묘사했다." },
  '47_13': { example2: "The collapse of this civilization remains a mystery that historians are still debating.", example2Kr: "이 문명의 붕괴는 역사가들이 여전히 논쟁 중인 미스터리로 남아 있다." },
  '47_14': { example2: "The novel explores how imperialism destroyed traditional ways of life in West Africa.", example2Kr: "그 소설은 제국주의가 어떻게 서아프리카의 전통적인 삶의 방식을 파괴했는지를 탐구한다." },
  '47_15': { example2: "The census showed that the population had shifted dramatically toward urban centers.", example2Kr: "인구 조사는 인구가 도심 지역으로 급격히 이동했음을 보여주었다." },
  '47_16': { example2: "The religious schism divided the community and led to decades of sectarian conflict.", example2Kr: "종교적 분열이 지역 사회를 나누고 수십 년간의 종파 갈등으로 이어졌다." },
  '47_17': { example2: "The Reformation gave ordinary people access to the Bible in their own language for the first time.", example2Kr: "종교 개혁으로 일반인들이 처음으로 자신들의 언어로 성경에 접근할 수 있게 되었다." },
  '47_18': { example2: "The elderly patriarch gathered the entire extended family for an annual reunion.", example2Kr: "나이 든 족장은 연례 재회를 위해 온 대가족을 모았다." },
  '47_19': { example2: "The drought and war caused a massive exodus from rural villages to overcrowded cities.", example2Kr: "가뭄과 전쟁으로 인해 농촌 마을에서 과밀 도시로의 대규모 탈출이 발생했다." },

  // Day 48 — 언어 & 문학 고급 어휘
  '48_0':  { example2: "The advertising slogan used alliteration to make the brand name easier to remember.", example2Kr: "광고 슬로건은 브랜드 이름을 더 기억하기 쉽게 만들기 위해 두운법을 사용했다." },
  '48_1':  { example2: "The contract's ambiguity caused a legal dispute over the payment terms.", example2Kr: "계약의 모호함이 지불 조건에 관한 법적 분쟁을 야기했다." },
  '48_2':  { example2: "Reading about others' suffering can offer a form of emotional catharsis.", example2Kr: "타인의 고통에 대해 읽는 것이 일종의 감정적 카타르시스를 제공할 수 있다." },
  '48_3':  { example2: "The word 'home' carries warmer connotations than the word 'house'.", example2Kr: "'home'이라는 단어는 'house'라는 단어보다 더 따뜻한 함축을 담고 있다." },
  '48_4':  { example2: "The denouement was satisfying, tying together every loose thread in the story.", example2Kr: "대단원이 이야기의 모든 느슨한 실을 하나로 묶어 만족스러웠다." },
  '48_5':  { example2: "Some critics find children's literature too didactic, leaving no room for imagination.", example2Kr: "일부 비평가들은 아동 문학이 너무 교훈적이어서 상상의 여지를 남기지 않는다고 생각한다." },
  '48_6':  { example2: "The committee used various euphemisms to describe job losses without alarming employees.", example2Kr: "위원회는 직원들을 불안하게 하지 않고 일자리 손실을 묘사하기 위해 다양한 완곡어법을 사용했다." },
  '48_7':  { example2: "The opening scene of the film used rain and darkness as foreshadowing of the coming crisis.", example2Kr: "영화의 오프닝 장면은 다가올 위기의 복선으로 비와 어둠을 사용했다." },
  '48_8':  { example2: "The coach's hyperbole — 'You're the best team in history!' — motivated the players.", example2Kr: "코치의 과장법 — '너희는 역사상 최고의 팀이야!' — 이 선수들에게 동기를 부여했다." },
  '48_9':  { example2: "There is a deep irony in the fact that the peace advocate died in a violent conflict.", example2Kr: "평화 옹호자가 폭력적인 갈등으로 사망했다는 사실에는 깊은 아이러니가 있다." },
  '48_10': { example2: "The metaphor of light to represent knowledge appears throughout the philosopher's work.", example2Kr: "지식을 빛으로 나타내는 은유가 그 철학자의 작품 전반에 걸쳐 등장한다." },
  '48_11': { example2: "The politician tried to change the narrative around his administration's failures.", example2Kr: "그 정치인은 자신의 행정부의 실패에 대한 서사를 바꾸려 했다." },
  '48_12': { example2: "The children's book used onomatopoeia throughout to make the story come alive.", example2Kr: "그 어린이 책은 이야기에 생동감을 불어넣기 위해 전반에 걸쳐 의성어를 사용했다." },
  '48_13': { example2: "The poem's personification of death as a gentle traveler made mortality seem less frightening.", example2Kr: "죽음을 온화한 여행자로 의인화한 시가 죽음을 덜 무섭게 느끼게 했다." },
  '48_14': { example2: "The film's protagonist learns that revenge brings only more suffering.", example2Kr: "영화의 주인공은 복수가 더 많은 고통만 가져온다는 것을 배운다." },
  '48_15': { example2: "The writer described her grief 'like a stone weighing down her chest', a vivid simile.", example2Kr: "작가는 자신의 슬픔을 '가슴을 누르는 돌처럼'이라고 묘사했는데, 생생한 직유이다." },
  '48_16': { example2: "The green light in The Great Gatsby is full of symbolism, representing hope and desire.", example2Kr: "위대한 개츠비의 초록 불빛은 희망과 욕망을 나타내는 풍부한 상징으로 가득하다." },
  '48_17': { example2: "The student's writing improved significantly once she better understood sentence syntax.", example2Kr: "학생의 글쓰기는 그녀가 문장 구문을 더 잘 이해하게 되면서 크게 향상되었다." },
  '48_18': { example2: "The author brilliantly recreated the dialect of 19th-century rural England in the novel.", example2Kr: "작가는 소설에서 19세기 농촌 잉글랜드의 방언을 훌륭하게 재현했다." },
  '48_19': { example2: "Without understanding the biblical allusion, some readers miss the poem's full meaning.", example2Kr: "성경적 암시를 이해하지 못하면, 일부 독자들은 시의 완전한 의미를 놓친다." },

  // Day 49 — 심리 & 철학 고급 어휘 II
  '49_0':  { example2: "Critics debate whether true altruism exists or if all generosity has a selfish motive.", example2Kr: "비평가들은 진정한 이타주의가 존재하는지 아니면 모든 관대함에 이기적인 동기가 있는지를 논쟁한다." },
  '49_1':  { example2: "John Locke's empiricism influenced the founding principles of liberal democracy.", example2Kr: "존 로크의 경험주의가 자유민주주의의 건국 원칙에 영향을 미쳤다." },
  '49_2':  { example2: "The course introduced students to the long history of epistemology in Western philosophy.", example2Kr: "그 과정은 학생들에게 서양 철학에서 인식론의 긴 역사를 소개했다." },
  '49_3':  { example2: "Sartre's existentialism challenges us to create our own values in an indifferent universe.", example2Kr: "사르트르의 실존주의는 우리에게 무관심한 우주에서 스스로의 가치를 창조하도록 도전한다." },
  '49_4':  { example2: "His hedonism led him to prioritize immediate pleasure over long-term stability.", example2Kr: "그의 쾌락주의가 장기적인 안정보다 즉각적인 쾌락을 우선시하게 만들었다." },
  '49_5':  { example2: "There is tension between idealism and realism in discussions of international relations.", example2Kr: "국제 관계 논의에서 이상주의와 현실주의 사이에 갈등이 존재한다." },
  '49_6':  { example2: "Regular introspection allows leaders to identify their blind spots and weaknesses.", example2Kr: "정기적인 자기 성찰은 지도자들이 자신의 맹점과 약점을 파악할 수 있게 해준다." },
  '49_7':  { example2: "Nietzsche diagnosed nihilism as the greatest spiritual challenge of modern civilization.", example2Kr: "니체는 허무주의를 현대 문명의 가장 큰 정신적 도전으로 진단했다." },
  '49_8':  { example2: "Descartes used rationalism to argue that doubt itself proves the existence of the mind.", example2Kr: "데카르트는 합리주의를 사용하여 의심 자체가 마음의 존재를 증명한다고 주장했다." },
  '49_9':  { example2: "The philosopher's healthy skepticism prevented him from accepting untested assumptions.", example2Kr: "철학자의 건전한 회의주의가 그가 검증되지 않은 가정을 받아들이지 못하게 했다." },
  '49_10': { example2: "The philosopher argued that stoicism teaches us to focus only on what we can control.", example2Kr: "철학자는 스토아 철학이 우리가 통제할 수 있는 것에만 집중하도록 가르친다고 주장했다." },
  '49_11': { example2: "Utilitarianism would justify a harsh policy if it produced the greatest good for the greatest number.", example2Kr: "공리주의는 가장 많은 사람에게 최대의 선을 가져온다면 가혹한 정책도 정당화할 것이다." },
  '49_12': { example2: "She acted against her conscience when she chose profit over the safety of her customers.", example2Kr: "그녀는 고객의 안전보다 이익을 선택했을 때 양심에 어긋나게 행동했다." },
  '49_13': { example2: "Philosophers have long debated whether machines could ever achieve true consciousness.", example2Kr: "철학자들은 기계가 진정한 의식을 달성할 수 있는지를 오랫동안 논쟁해 왔다." },
  '49_14': { example2: "Our subconscious fears can surface unexpectedly in dreams or during moments of stress.", example2Kr: "우리의 잠재의식적 두려움은 꿈 속에서나 스트레스를 받는 순간에 예상치 못하게 표면에 드러날 수 있다." },
  '49_15': { example2: "The course explored how morality varies between cultures and across historical periods.", example2Kr: "그 과목은 도덕성이 문화 간, 역사적 시대에 따라 어떻게 다른지를 탐구했다." },
  '49_16': { example2: "A photogenic city can dramatically change visitors' perception of an entire country.", example2Kr: "사진이 잘 찍히는 도시가 방문객들의 국가 전체에 대한 인식을 크게 바꿀 수 있다." },
  '49_17': { example2: "Her business intuition proved accurate when the market moved exactly as she had predicted.", example2Kr: "시장이 그녀가 예측했던 대로 정확히 움직이자 그녀의 사업 직관이 정확한 것으로 증명되었다." },
  '49_18': { example2: "The ancient Greek philosophers devoted much of their thinking to defining virtue.", example2Kr: "고대 그리스 철학자들은 덕목을 정의하는 데 많은 사유를 바쳤다." },
  '49_19': { example2: "Her pragmatism was evident in how she resolved the conflict with minimal disruption.", example2Kr: "그녀의 실용주의는 최소한의 혼란으로 갈등을 해결한 방식에서 분명히 드러났다." },

  // Day 50 — 고급 동사 II
  '50_0':  { example2: "The dark border around the painting serves to accentuate its vivid central colors.", example2Kr: "그림 주위의 어두운 테두리가 생생한 중앙 색상을 두드러지게 하는 역할을 한다." },
  '50_1':  { example2: "Aid workers rushed supplies to the disaster zone to alleviate the suffering of survivors.", example2Kr: "구호 요원들은 생존자들의 고통을 완화하기 위해 재해 지역에 물자를 급히 보냈다." },
  '50_2':  { example2: "The government proposed amalgamating the two ministries to increase administrative efficiency.", example2Kr: "정부는 행정 효율성을 높이기 위해 두 부처를 합병하는 것을 제안했다." },
  '50_3':  { example2: "Few politicians can articulate complex policy issues as clearly as she does.", example2Kr: "그녀만큼 복잡한 정책 문제를 명확하게 표현할 수 있는 정치인은 거의 없다." },
  '50_4':  { example2: "Hackers found a way to circumvent the security system and access private data.", example2Kr: "해커들은 보안 시스템을 우회하고 개인 데이터에 접근하는 방법을 찾아냈다." },
  '50_5':  { example2: "The suspect claimed he had been coerced into signing a false confession.", example2Kr: "용의자는 허위 자백서에 서명하도록 강요받았다고 주장했다." },
  '50_6':  { example2: "The months of tension between the two countries finally culminated in open armed conflict.", example2Kr: "두 나라 간의 수개월간의 긴장이 마침내 공개적인 무력 충돌로 절정에 달했다." },
  '50_7':  { example2: "Universities have a responsibility to disseminate knowledge to the wider public.", example2Kr: "대학교는 더 넓은 대중에게 지식을 전파할 책임이 있다." },
  '50_8':  { example2: "The minister refused to elaborate on the details of the peace negotiations.", example2Kr: "장관은 평화 협상 세부 사항에 대해 더 자세히 설명하기를 거부했다." },
  '50_9':  { example2: "The defense attorney proved that the prosecution had fabricated key evidence.", example2Kr: "변호인은 검찰이 핵심 증거를 날조했다는 것을 입증했다." },
  '50_10': { example2: "The new bridge will facilitate the movement of goods between the two countries.", example2Kr: "새 다리가 두 나라 사이의 물자 이동을 용이하게 할 것이다." },
  '50_11': { example2: "From her tone, the class could infer that the teacher was unhappy with the results.", example2Kr: "그녀의 어조로부터, 학급은 선생님이 결과에 불만스럽다는 것을 추론할 수 있었다." },
  '50_12': { example2: "The exhibition juxtaposed ancient pottery with modern ceramics to show artistic evolution.", example2Kr: "전시는 고대 도자기와 현대 도자기를 나란히 배치해 예술적 발전을 보여주었다." },
  '50_13': { example2: "The documentary exposed how advertisers manipulate emotions to influence purchasing decisions.", example2Kr: "그 다큐멘터리는 광고주들이 구매 결정에 영향을 미치기 위해 어떻게 감정을 조종하는지를 폭로했다." },
  '50_14': { example2: "Ignoring the problem will only perpetuate the cycle of poverty and inequality.", example2Kr: "문제를 무시하면 빈곤과 불평등의 악순환만 지속될 것이다." },
  '50_15': { example2: "Efforts to reconcile the two feuding neighbors ultimately failed after months of mediation.", example2Kr: "두 불화하는 이웃을 화해시키려는 노력이 수개월간의 중재 끝에 결국 실패했다." },
  '50_16': { example2: "The media began to scrutinize the candidate's past business dealings.", example2Kr: "언론이 후보자의 과거 사업 거래를 면밀히 조사하기 시작했다." },
  '50_17': { example2: "The independent investigation vindicated the officer, finding no evidence of wrongdoing.", example2Kr: "독립 조사가 그 공무원에게 결백을 입증하며 비위 증거가 없다고 밝혔다." },
  '50_18': { example2: "The phrase 'trust, but verify' encapsulates the essence of diplomatic negotiation.", example2Kr: "'신뢰하되 검증하라'는 문구가 외교적 협상의 본질을 완전히 표현한다." },
  '50_19': { example2: "Determination and hard work propelled him from a small village to a top university.", example2Kr: "결단력과 노력이 그를 작은 마을에서 명문 대학교로 이끌었다." }
});